<table class="table table-bordered">
	<thead>
		<tr>
			<th>Finance Client</th>
			<th>Quota</th>
			<th>Quota Type</th>
			<th>Effective Date</th>
			<th>Effective Status</th>
			<th>Creation Time</th>
			<th>Review Status</th>
			<th>Review Date</th>
			<th>Last Modifier</th>
			<th>Modified Time</th>
			<th>Remarks</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>

		<?php if(isset($this->credit) && $this->credit) : ?>
			<?php foreach ($this->credit as $value) : ?>

				<?php 

					if($value['status'] == 1) { 
						$status = "<span style='color: blue'>Pending Review</span>"; 
					} elseif($value['status'] == 2) {
						$status = "<span style='color: green'>Approved</span>";
					} elseif($value['status'] == 3) {
						$status = "<span style='color: blue'>Re-review</span>";
					} else {
						$status = "<span style='color: orange'>Closed</span>";
					}

				?>

				<tr>
					<td><?php echo $value['finance_client_name'] ?></td>
					<td><?php echo number_format($value['quota']) ?></td>
					<td>
						<?php if($value['quota_type'] == 1) { echo "Finished Product Quota"; } ?>
					</td>
					<td><?php echo $value['start_date'] ?> - <?php echo $value['end_date'] ?></td>
					<td></td>
					<td><?php echo $value['created_at'] ?></td>
					<td><?php echo $status ?></td>
					<td><?php echo $value['review_date'] ?></td>
					<td><?php echo $this->staff[$value['updated_by']] ?></td>
					<td><?php echo $value['updated_at'] ?></td>
					<td><?php echo $value['remark'] ?></td>
					<td>
						<a href="<?php echo HOST ?>finance/add-credit-limit?id=<?php echo $value['id'] ?>&action_type=1"> Detail </a>

						<?php if(in_array($value['status'], array(1,3))) : ?>
						| <a href="<?php echo HOST ?>finance/add-credit-limit?id=<?php echo $value['id'] ?>&action_type=2"> Edit </a>
						<?php endif; ?>

						<?php if(in_array($value['status'], array(1,3))) : ?>
						| <a href="<?php echo HOST ?>finance/add-credit-limit?id=<?php echo $value['id'] ?>&action_type=3"> Approved </a>
						<?php endif; ?>

						<?php if(in_array($value['status'], array(2))) : ?>
						| <a href="<?php echo HOST ?>finance/approved-credit-limit?id=<?php echo $value['id'] ?>&action_type=4" style="color: orange;"> Re-review </a>
						<?php endif; ?>

						<?php if(in_array($value['status'], array(1,3))) : ?>
						| <a href="<?php echo HOST ?>finance/approved-credit-limit?id=<?php echo $value['id'] ?>&action_type=5" style="color: red"> Delete 
						<?php endif; ?>
					</td>
				</tr>
			<?php endforeach; ?>
		<?php endif; ?>
	</tbody>
</table>