<div class="page-header">
    <h1>Hub <small>list</small></h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="row">
    <div class="span12">
        <p class='pull-right'><a href="<?php echo HOST ?>hub/create" class="btn btn-success btn-mini"><span><i class="icon-plus"></i> Add New</span></a></p>
    </div>
</div>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('hub/partials/search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive" id="table">
    <?php
        echo $this->render('hub/partials/list.phtml');
    ?>
</div>

<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });
</script>