<style>
    .blockOverlay{
        z-index: 10000 !important;
    }
    .blockPage{
        z-index: 10001 !important;
    }
</style>

<div class="page-header">
    <h1>Borrowing Return</h1>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>

<div class="row">
    <div class="span12">

        <div class="span5">

            <!-- <div class="row">
                <div class="span6">
                    <label class="span2">Requert SN : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['sn'];?></strong></span>
                </div>
            </div> -->

            <div class="row">
                <div class="span6">
                    <label class="span2">Request Number : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['rq'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Product Grade : </label>
                    <span class="span3"><strong><?php
                    switch ($this->getDetailsReturn[0]['product_grade']) {
                        case '1':
                            echo 'A';
                            break;
                        case '2':
                            echo 'B';
                            break;
                        case '3':
                            echo 'Demo';
                            break;
                        case '4':
                            echo 'APK';
                            break;
                        case '5':
                            echo 'Prototype';
                            break;
                    }
                    ?></strong></span>
                </div>
            </div>

            <!-- <div class="row">
                <div class="span6">
                    <label class="span2">Borrow Type : </label>
                    <span class="span3"><strong><?php
                    // switch ($this->getDetailsReturn[0]['borrowing_type']) {
                    //     case '1':
                    //         // echo 'Demo for Event';
                    //         echo 'เบิกยืมพนักงาน';
                    //         break;
                    //     case '2':
                    //         // echo 'Complimentary';
                    //         echo 'อภินันทนาการ';
                    //         break;
                    //     case '3':
                    //         // echo 'Replace Customer Service';
                    //         echo 'เบิกเปลี่ยนเครื่องลูกค้า';
                    //         break;
                    //     case '4':
                    //         echo 'Prototype';
                    //         break;
                    // }
                    ?></strong></span>
                </div>
            </div> -->

            <div class="row">
                <div class="span6">
                    <label class="span2">Type : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['hrs_department_name'];?></strong></span>
                </div>
            </div>

            <div class="row <?php if(!$this->getDetailsReturn[0]['org_full_name']){echo 'hide';}?>">
                <div class="span6">
                    <label class="span2">ORG Full Name : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['org_full_name'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Event Program Name : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['event_program_name'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Event Program Start Period Date : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['event_program_start_period_date'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Event Program End Period Date : </label>
                    <span class="span3"><strong><?php 
                    // if($this->getDetailsReturn[0]['borrowing_type'] == 2){
                    //     echo 'No Return';
                    // }else{
                    //     echo $this->getDetailsReturn[0]['return_date'];
                    // }
                    if(!$this->getDetailsReturn[0]['return_date']){
                        echo 'No Return';
                    }else{
                        echo $this->getDetailsReturn[0]['return_date'];
                    }
                    ?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Remark : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['remark'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Address : </label>
                    <span class="span3"><strong><?php 
                    switch ($this->getDetailsReturn[0]['delivery']) {
                        case '1': ?>
                        คลังสินค้าเคอรี่ บางนา โลจิสติกส์ เซ็นเตอร์ <br/>เลขที่ 33/2 หมู่ 7 บางปลา บางพลี สมุทรปราการ 10540 ติดต่อคุณศริญญา เกตุเขียว 0657174931
                        <?php break;
                        case '2': ?>
                            บจก.ไทย ออปโป้ เลขที่230 ถ.บางขุนเทียน <br/>-ชายทะเล แขวงแสมดำ เขตบางขุนเทียน กรุงเทพฯ 10150 ติดต่อคุณหนึ่ง  0835527645 หรือ คุณเอ๋ 0958250441
                            <?php break;
                        case '3':
                            echo $this->getDetailsReturn[0]['address'];
                            break;
                        case '4': ?>
                            บริษัท ไทย ออปโป้ จำกัด <br/>อาคาร AIA Capital Center รัชดา เลขที่ 89 ชั้น 31 ห้อง 5-7 ถนน รัชดาภิเษก เขตดินแดง กทม. 10400 <br/>โทรศัพท์ : 02- 013-1810 แฟ็กซ์: 02-013–1820
                            <?php break;
                    }
                    ?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Product Type : </label>
                    <span class="span3"><strong><?php 
                    switch ($this->getDetailsReturn[0]['type']) {
                        case '1':
                            echo 'Normal';
                            break;
                        case '2':
                            echo 'Demo';
                            break;
                        case '5':
                            echo 'APK';
                            break;
                    }
                    ?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Old Warehouse : </label>
                    <span class="span3"><strong><?php echo $this->warehouse_cache[$this->getDetailsReturn[0]['old_id']];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Current Warehouse : </label>
                    <span class="span3"><strong><?php echo $this->warehouse_cache[$this->getDetailsReturn[0]['new_id']];?></strong></span>
                </div>
            </div>

        </div>

        <div class="span5">

            <div class="row">
                <div class="span7">
                    <label class="span3">Area : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['name'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span7">
                    <label class="span3">Request By : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['fullname'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span7">
                    <label class="span3">Position : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['position_name'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span7">
                    <label class="span3">Request Date : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['created_date'];?></strong></span>
                </div>
            </div>

            <div class="row <?php if(!$this->getDetailsReturn[0]['mg_fullname']){echo 'hide';}?>">
                <div class="span7">
                    <label class="span3">Manager Approved By : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['mg_fullname'];?></strong></span>
                </div>
            </div>

            <div class="row <?php if(!$this->getDetailsReturn[0]['manager_approved_date']){echo 'hide';}?>">
                <div class="span7">
                    <label class="span3">Manager Approved Date : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['manager_approved_date'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span7">
                    <label class="span3">Admin Approved By : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['admin_fullname'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span7">
                    <label class="span3">Admin Approved Date : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['admin_approved_date'];?></strong></span>
                </div>
            </div>

            <!-- <div class="row">
                <div class="span7">
                    <label class="span3">ASM Approved By : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['asm_fullname'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span7">
                    <label class="span3">ASM Approved Date : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['asm_approved_date'];?></strong></span>
                </div>
            </div> -->

            <div class="row <?php if(!$this->getDetailsReturn[0]['rm_fullname']){echo 'hide';}?>">
                <div class="span7">
                    <label class="span3">RD Approved By : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['rm_fullname'];?></strong></span>
                </div>
            </div>

            <div class="row <?php if(!$this->getDetailsReturn[0]['rm_approved_date']){echo 'hide';}?>">
                <div class="span7">
                    <label class="span3">RD Approved Date : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['rm_approved_date'];?></strong></span>
                </div>
            </div>

            <!-- <div class="row">
                <div class="span7">
                    <label class="span3">Area Director Approved By : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['area_fullname'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span7">
                    <label class="span3">Area Director Approved Date : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['area_director_approved_date'];?></strong></span>
                </div>
            </div> -->

            <div class="row">
                <div class="span7">
                    <label class="span3">Operation Director Approved By : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['op_fullname'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span7">
                    <label class="span3">Operation Director Approved Date : </label>
                    <span class="span3"><strong><?php echo $this->getDetailsReturn[0]['operation_director_approved_date'];?></strong></span>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="span12" style="margin-top: 30px;margin-bottom: 30px;">
                <table class="table table-bordered span12">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Products Code</th>
                            <th>Product Name</th>
                            <th>Color Name</th>
                            <th>Quantity</th>
                        </tr>
                    </thead>

                    <tbody>

                    <?php
                    $total = 0;
                    foreach ($this->getDetailsReturn as $key => $item):
                        $total += $item['total_qty'];
                    ?>

                        <tr>
                            <td><?php echo $key+1;?></td>
                            <td><?php echo $item['good_name'];?></td>
                            <td><?php echo $item['good_main_name'];?></td>
                            <td><?php echo $item['color_name'];?></td>
                            <td><?php echo $item['total_qty'];?></td>
                        </tr>

                    <?php endforeach;?>

                    </tbody>

                    <tfoot>
                        <tr>
                            <td colspan="4"><strong>SUMMARY</strong></td>
                            <td><strong><?php echo $total;?></strong></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        <form method="POST" action="<?=HOST."warehouse/borrowing-return-process"?>">

            <div style="margin-bottom: 30px;">

                <!-- <?php if ($this->getDetailsReturn[0]['product_grade'] == '1') { ?>
                    <span>Warehouse : </span>
                    <select class="" name="warehouse" style="width: 185px;" required>
                        <option value>----------</option>
                        <option value="5">WM03 - คลังโทรศัพท์เกรด B</option>
                        <option value="28">WMQT - คลังเครื่องทดสอบ</option>
                        <option value="36">WMKR - Kerry</option>
                        </select>
                <?php }else{ ?>
                <div style="margin-left: 30px;margin-bottom: 30px;">
                    <span>Warehouse : </span>
                    <select class="" name="warehouse" style="width: 185px;" required>
                        <option value>----------</option>
                        <option value="4">WM02 - คลังโทรศัพท์เสีย</option>
                        <option value="5">WM03 - คลังโทรศัพท์เกรด B</option>
                        <option value="28">WMQT - คลังเครื่องทดสอบ</option>
                    </select>
                </div>
                <?php } ?> -->

                <!-- WMCN - คลังรอเคลม -->
                <!-- <input type="hidden" name="warehouse" value="26"> -->

                <!-- Borrow Warehouse -->
                <input type="hidden" name="warehouse" value="142">

                <table class="<?php if(!$this->have_imei){echo 'hide';}?>" style="margin-top: 15px;margin-left: 30px;">
                    <tr>
                        <td style="vertical-align: text-top;color: red">
                            <div>
                                <input type="checkbox" id="checkbox_imei_missing" name="checkbox_imei_missing" value="0"> เครื่องศูนย์หาย
                                <input type="hidden" id="checkbox_imei_missing_submit" name="checkbox_imei_missing_submit" value="0">
                            </div>
                            <div class="div-imei-missing hide">
                                <span>Imei : </span>
                                <textarea name="imei_missing" id="imei_missing" cols="30" rows="10"></textarea>
                                <input type="hidden" id="imei_missing_submit" name="imei_missing_submit">
                            </div>
                        </td>
                        
                    </tr>
                    <tr>
                        <td style="vertical-align: text-top;">
                            <span>Imei : </span>
                            <textarea name="imei" id="imei" cols="30" rows="10"></textarea>
                            <input type="hidden" id="imei_submit" name="imei_submit">
                        </td>
                        <td style="vertical-align: text-top;">
                            <div style="margin-left: 30px;" class="display-check-imei" id="display-check-imei-missing"></div>
                        </td>
                        <td style="vertical-align: text-top;">
                            <div style="margin-left: 30px;" class="display-check-imei" id="display-check-imei-invalid"></div>
                        </td>
                    </tr>
                </table>
                <div style="margin-left: 40px;">
                    <span class="status-check-imei hide" id="status-check-imei-valid" style="color: green"><h3>Status : Valid (ผ่าน)</h3></span> 
                    <span class="status-check-imei hide" id="status-check-imei-invalid" style="color: red"><h3>Status : Invalid (ไม่ผ่าน)</h3></span> 
                </div>
                <br/>
                <!-- <input type="hidden" name="type" value="<?=$this->getDetailsReturn[0]['borrowing_type'];?>"> -->
                <button type="button" class="btn <?php if(!$this->have_imei){echo 'hide';}?>" id="btn-check-imei" style="margin-left: 66px;">Check Imei</button>
            </div>

            <div class="pull-right" style="margin-left: 30px; margin-top: 30px;margin-bottom: 30px;">
                <input type="hidden" name="have_imei" value="<?=$this->have_imei?>">
                <button type="submit" class="btn btn-primary" id="btn-submit" <?php if($this->have_imei){echo 'disabled';}?>>Confirm</button>
                <button type="button" class="btn btn-warning" onclick="window.location.href='<?=HOST."warehouse/borrowing-return-list"?>'">Back</button>
            </div>

            <input type="hidden" name="id" value="<?=$this->id?>">
            
        </form>

    </div>
</div>

<link href="../css/select2.css" rel="stylesheet"/>
<script src="../js/select2.js"></script>
<script src="/js/jquery.blockUI.js"></script>
<script>

    $(document).on("submit", "form", function(e){

        $.blockUI({ css: { 
            border: 'none', 
            padding: '15px', 
            backgroundColor: '#000', 
            '-webkit-border-radius': '10px', 
            '-moz-border-radius': '10px', 
            opacity: .5, 
            color: '#fff' 
        } });
    });

    $(document).ajaxStart(function(){
        $.blockUI({ css: { 
            border: 'none', 
            padding: '15px', 
            backgroundColor: '#000', 
            '-webkit-border-radius': '10px', 
            '-moz-border-radius': '10px', 
            opacity: .5, 
            color: '#fff' 
        } });
    });

    $(document).ajaxStop(function(){
        $.unblockUI();
    });

    $(document).ready(function () {
        $('.select2-warehouse').select2();

        $('#checkbox_imei_missing').change(function(event) {
            if(this.checked) {
                $('.div-imei-missing').removeClass('hide');
                $(this).val('1');
                $('#checkbox_imei_missing_submit').val('1');
            }else{
                $('.div-imei-missing').addClass('hide');
                $(this).val('0');
                $('#checkbox_imei_missing_submit').val('0');
            }
        });

        $('#btn-check-imei').click(function(event) {

            $('.display-check-imei').empty();
            $('.status-check-imei').addClass('hide');

            var checkbox_imei_missing = $('#checkbox_imei_missing').val();

            var imei = $('#imei').val();
            var imei_missing = $('#imei_missing').val();

            $.ajax({
                url: '<?php echo HOST.'warehouse/borrow-checking';?>',
                type: 'POST',
                // data: {'id':'<?=$this->id?>','checkbox_imei_missing' : checkbox_imei_missing,'imei' : imei,'imei_missing' : imei_missing,'type':'<?=$this->getDetailsReturn[0]['borrowing_type'];?>'},
                data: {'id':'<?=$this->id?>','checkbox_imei_missing' : checkbox_imei_missing,'imei' : imei,'imei_missing' : imei_missing},

                })
            .done(function(response) {
                var obj_response = jQuery.parseJSON(response);
                console.log("success");

                 switch(obj_response.status) {
                    case 200:

                        $('#imei_submit').val(imei);
                        $('#imei_missing_submit').val(imei_missing);

                        $('#checkbox_imei_missing').attr('disabled',true);

                        $('#imei').attr('disabled',true);
                        $('#imei_missing').attr('disabled',true);
                        $('#btn-check-imei').attr('disabled',true);
                        $('#btn-submit').removeAttr('disabled');

                        $('#status-check-imei-valid').removeClass('hide');

                        var add_append = '<span style="color: red">Missing (หายไป) : </span><textarea style="color: red" cols="30" rows="10" disabled>';
                        add_append += '</textarea>'

                        $('#display-check-imei-missing').append(add_append);

                        var add_append = '<span style="color: red">Invalid (ไม่ถูกต้อง) : </span><textarea style="color: red" cols="30" rows="10" disabled>';
                        add_append += '</textarea>'

                        $('#display-check-imei-invalid').append(add_append);
                        
                        break;
                    case 401:

                        $('#status-check-imei-invalid').removeClass('hide');

                        var add_append = '<span style="color: red">Missing : </span><textarea style="color: red" cols="30" rows="10" disabled>';
                        $.each( obj_response.diffSystem, function( key, value ) {
                            add_append += value+'\n';
                        });
                        add_append += '</textarea>'

                        $('#display-check-imei-missing').append(add_append);

                        var add_append = '<span style="color: red">Invalid : </span><textarea style="color: red" cols="30" rows="10" disabled>';
                        $.each( obj_response.diffImei, function( key, value ) {
                            add_append += value+'\n';
                        });
                        add_append += '</textarea>'

                        $('#display-check-imei-invalid').append(add_append);

                        break;
                    case 400:
                        alert(obj_response.message);
                        break;
                }
                    
            });
        });
    });
</script>