<link href="<?php echo HOST ?>css/jquery.tagit.css" rel="stylesheet" type="text/css">

<style>
    #imei_munti{
        width: 205px;
        background-color: #fff;
        border: 1px solid #ccc;
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
        display: inline-block;
        padding: 4px 6px;
        margin-bottom: 10px;
        color: #555;
        vertical-align: middle;
        border-radius: 4px;
        max-width: 100%;
        line-height: 22px;
        cursor: text;
    }
    #co_munti{
        width: 205px;
        background-color: #fff;
        border: 1px solid #ccc;
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
        display: inline-block;
        padding: 4px 6px;
        margin-bottom: 10px;
        color: #555;
        vertical-align: middle;
        border-radius: 4px;
        max-width: 100%;
        line-height: 22px;
        cursor: text;
    }
</style>

<div class="page-header">
    <h1>Borrowing Return Imei List</h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('warehouse/partials/search-borrowing-return-imei-list.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
    <?php
        echo $this->render('warehouse/partials/list-borrowing-return-imei-list.phtml');
    ?>
</div>

<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>

<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        $('#imei_munti').tagit({
            fieldName: 'imei_munti[]'
        });

        $('#co_munti').tagit({
            fieldName: 'co_munti[]'
        });

        $('.check_all').change(check_all);

        function check_all(e) {
            _self = $(e.target);
            $('.attach-id').prop('checked', _self.is(":checked"));
        }

        $('#attach-return').click(function(event) {

            if (!confirm('You confirm to return imei')) {
                return false;
            }

            $('#attach-return').attr("disabled","disabled");

            id = [];
            imei = [];
            $('.attach-id:checked').each(function(index, el) {
                id.push($(el).data('id'));
                imei.push($(el).data('imei'));
            });

            $.ajax({
                url: '<?php echo HOST.'warehouse/borrowing-return-imei';?>',
                type: 'POST',
                data: {id:id,imei:imei,btn:'return'},
            })
            .done(function(response) {
                var obj_response = jQuery.parseJSON(response);
                console.log("success");

                 switch(obj_response.status) {
                    case 200:
                        console.log('done');
                        location.reload();
                        break;
                    case 400:
                        alert(obj_response.message);
                        $('#attach-return').removeAttr("disabled");

                        break;
                    default:
                        location.reload();
                }
                
            });
            
            
        });

        $('#attach-so').click(function(event) {

            if (!confirm('You confirm to prepare create so')) {
                return false;
            }

            $('#attach-so').attr("disabled","disabled");

            id = [];
            imei = [];
            $('.attach-id:checked').each(function(index, el) {
                id.push($(el).data('id'));
                imei.push($(el).data('imei'));
            });

            $.ajax({
                url: '<?php echo HOST.'warehouse/borrowing-return-imei';?>',
                type: 'POST',
                data: {id:id,imei:imei,btn:'change_warehouse'},
            })
            .done(function(response) {
                var obj_response = jQuery.parseJSON(response);
                console.log("success");

                 switch(obj_response.status) {
                    case 200:
                        console.log('done');
                        location.reload();
                        break;
                    case 400:
                        alert(obj_response.message);
                        $('#attach-so').removeAttr("disabled");

                        break;
                    default:
                        location.reload();
                }
                
            });
            
        });

    });
</script>