<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Print</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
     <link rel="stylesheet" type="text/css" href="<?php echo HOST ?>css/thaiSalaban.css">
    <style type="text/css">
       @page{
        size: auto A4;
        margin: 5mm;
     }
      body{font-size:23px;font-family:"thaiSalaban"!important;}

        /*/Applications/XAMPP/xamppfiles/htdocs/wms_live/wms_live/public/img*/
        @media print{.print{width:20px !important;}.print{display:none!important}} }
          
          .top_page{margin-top: 67px;}
      .top{text-align:left;    margin-top: 63px;}
      .hid{display: none;  /*visibility:hidden;*/}
      .hid2{visibility:hidden;}
      .top p{height:24px;line-height:24px;margin:0}
      .textbox{width:600px;border:1px solid black;height:70px}
      .blank10{height:10px;clear:both}
      .blank75{height:149px;clear:both}

      .title_page_logo {font-weight:bold;}
      .title_page_logo_small{font-weight: normal;}
      .title_page{width: auto;text-align:center;font-size:15px;font-weight:bold;margin-top: 5px}
      .title_page_small_left{width: auto;text-align:left;height:12px;font-size:12px;line-height:12px;float:left;}
      .title_page_small_right{width: auto;text-align:right;height:12px;font-size:12px;line-height:12px;float:right;margin-top: -10px;}
      .title{width:600px;text-align:center;height:30px;font-size:15px;line-height:30px;background-color:#fabf8f;font-weight:bold}
      .title small {float: right;font-weight: normal;font-size: 8px;padding-right: 2em;}
      .tbl,
      .tbllist{width:90%;margin-top: 5px;}
      .tbllist_imei{margin-top: 30px;}
      .tbllist_height{height: 30mm;}height: 420px;
      .blog1{width:92%; border: 0px #ccc solid;margin-left: 30px;margin-top: -9px;}
      .blog2{height: 420px;}
      .tbl_col1_list{width:120px ;padding: 5px; float: left;    margin-top: -15px; border: 0px #ccc solid}
      .tbl_col2_list{width:280px;padding: 5px;float: left;    margin-top: -15px; border: 0px #ccc solid}
      .tbl_col3_list{width:30px;margin-left: 0px;text-align: left;padding: 5px;float: left;    margin-top: -15px; border: 0px #ccc solid}
      .tbl_col4_list{width:80px;margin-left: 0px;text-align: right;padding: 5px;float: left;    margin-top: -15px; border: 0px #ccc solid}
      .tbl_col5_list{width:100px;margin-left: 0px;text-align: right;padding: 5px;float: left;    margin-top: -15px; border: 0px #ccc solid}
      .tbl_col6_list{width:100px;margin-left: 0px;text-align: right;padding: 5px;float: left;    margin-top: -15px; border: 0px #ccc solid}
      .tbl_col7_list{width:97px;margin-left: 0px;text-align: right;padding: 5px;float: left;    margin-top: -15px; border: 0px #ccc solid}
      .tbl_col8_list{width:97px;margin-left: 0px;text-align: right;padding: 5px;float: left;    margin-top: -15px; border: 0px #ccc solid}
      .tbl_col9_list{width:97px;margin-left: 0px;text-align: right;padding: 5px;float: left;    margin-top: -15px; border: 0px #ccc solid}

      .tbl_col1_list_sum{width:230px;}
      .tbl_col2_list_sum{width:350px;}
      .tbl_tr_list_sum{margin-left: 410px;margin-top: -15px;position: absolute;width:750px;height: 30px;}
      .tbl_col3_list_sum{margin-left: 5px;text-align: center;position: absolute;}
      .tbl_col4_list_sum{margin-left: -50px;text-align: right;position: absolute;}
      .tbl_col5_list_sum{margin-left: 210px;text-align: right;position: absolute;}
      .tbl_col6_list_sum{margin-left: 330px;text-align: right;position: absolute;}
      .tbl_col7_list_sum{margin-left: 410px;text-align: right;position: absolute;}
      .tbl_col8_list_sum{margin-left: 520px;text-align: right;position: absolute;}
      .tbl_col9_list_sum{margin-left: 610px;text-align: right;position: absolute;}
      .single_record{page-break-after: always;}
      .tbl tr{margin:0}
      .tbl tr td,
      .tbllist tr td{background-color:#fff}.tbl .firsttd{width:145px}.tbl .secondtd{width:100px}.tbl .thirdtd{width:36px}.tbl .forthtd{width:65px}
      

         .note{border-bottom:1px dotted #ccc;width:300px;float:left;margin:9px 0 0 25px}.green{text-align:center}.green td{background-color:#ccffcc!important}#logo{
  float:left;
  display:block;
  left: 261px;
  top: 71px;
}#logo img{width:136px;margin-top:10px}
.trcenter{text-align:center}
.invoice{width:453px;display:block;clear:both;margin-left:119px}
.invoice-number{float:left;padding-left:37px}
.order-type{float:right;text-align:right}
         .right{text-align:right}
         .detail{width:400px;margin-left: 120px;}
         .title_page_col_left{float:left;width: 300px; }
         .title_page_col_right{float:right;width: 740px;height: 85px;}

         .below_page_col_left{float:left;width: 100px;}
         .below_page_col_right{float:right;width: 200px;margin-left: -300px;}
         .below_page_col_right_1{float:right;width: 400px;margin-left: -200px;}
         
         .below_detail .col1 span{width:300px;float:left;font-weight:bold;}
         .below_detail .col2 span{width:309px;float:left;font-weight:normal;}

         
         .below_detail_left{width:309px;float:left;font-weight:normal;}

         .assign{width: 200px;font-weight: bold;float: left;
         
         /* margin-top: 10px; */
         border-top: 1px dotted black;
         margin-left: 0px;
         margin-top: 40px;
         text-align: center;
         padding-top: 10px;}

         .signature_page_col_right{float:right;}

         .detail .col1{width:109px;float:left}
         .detail .col1 span{width:109px;float:left;font-weight:bold,margin-left: 110px;}
         .detail .col2{width:224px;float:left;margin-top: -10px;}
         .detail .col2_title{width:600px;float:left;margin-top: -10px;}
         .detail .col2 span{font-weight:bold}
         .detail .col3{width:100px;float:left}
         .detail .col3 span{font-weight:bold}
         .clear{clear:both}
         .colleft{float:left;width:300px}
         .colright{float:right;width:165px}
         .tablelist {font-size:10px;}
          tr td{height: 20mm;}

         .vat{width:435px!important;float:right!important}#vatnumber{clear:both}#vatnumber .sn{width:54px;border:1px solid black;height:14px;float:left}.marksn{float:left;border-left:1px solid black;font-weight:bold;padding-left:3px}.order{float:left;margin-left:10px}.order .sn{width:5px;height:10px;border:1px solid black;float:left;margin-left:5px}.order .alert{margin-left:16px;margin-bottom:4px}
         
        input[type="text"]
        {
            display: block;
            margin: 0px;
            font-family: time new roman;
            font-weight: bold;
            text-align: center;
            font-size: 10px;
            border: none;
        }
        .model
        {font-size: 8px !important;
            text-transform:uppercase;
        }
        .imgbutton{width:40px !important;cursor:pointer;position:  absolute;}
        
        .page-break  { display: block; page-break-before: always; }
        }
        
        .scroll{overflow:hidden;}
        .number{width:10px;}
        .signname{  width: 549px;margin: auto;padding-left: 70px;}
    </style>

    <script type="text/javascript">
        function Print()
        {
            //$( ".imgbutton" ).remove();
            window.print();
        }

    </script>
        <?php
            $item=$this->sales;
            //print_r($item);
            $item_total=count($item);
            $item_per_page=15;
            $item_imei_per_page=7;

            $max_show_imei=50;

            $row_product=0;$row_product_imei=0;
             /*
             echo "item_per_page>".($item_per_page); 
             echo "item_total>".($item_total); 
             echo ">".($item_total/$item_per_page); 
             echo ">round=". round($item_total/$item_per_page);
             echo ">ceil=". ceil($item_total/$item_per_page);

             echo ">mod=". ($item_total%$item_per_page);
           
           if($item_total<=$item_per_page){
              echo ">>round=".round($item_total/$item_per_page);
           }else{
              echo ">>ceil=".ceil($item_total/$item_per_page);
           }
           */
           $cat_id= $item[0]['cat_id'];
           
           if($cat_id==12){
                $pg_total= ceil($item_total/$item_per_page);
           }else{
             if(($item_total%$item_per_page)<=2){
                $pg_total= round($item_total/$item_per_page);
             }else{
                $pg_total= ceil($item_total/$item_per_page);
             }
           }
            
            if($pg_total<=0){
              $pg_total=1;
            }
           //$pg_total= ceil($item_total/$item_per_page);
           // $pg_total= round(($item_total/$item_per_page), 0, PHP_ROUND_HALF_DOWN);

            $g_total_num=0;
            $g_correct_amount=0;$g_difference_amount=0;
            $g_total_balance=0;$g_total_VAT=0;$g_total_amount=0;
            $g_total_price=0;$g_correct_bal_amount=0;

            $retailer_name="";$prepared_by_name="";
            //print_r($this->sales[0]);
            $retailer_name= $this->sales[0]['unames'];
            //$prepared_by_name= $this->sales[0]['prepared_by'];

            $add_tax = $this->sales[0]['add'];
            $distributor_tax = $this->sales[0]['mst_sn'];
            $cn_no= $this->sales[0]['creditnote_sn_view'];
            $create_date=$this->sales[0]['create_date_cn_view'];
            $create_date= date("d-m-Y", strtotime($create_date));
            
            $parent=$this->sales[0]['parent'];
            if($parent==0){
                $branch_name='สำนักงานใหญ่';
                $branch_no=$this->sales[0]['branch_no'];

            }else{
                $branch_name='สาขา';
                $branch_no=$this->sales[0]['branch_no'];
            }

        ?>
</head>
<body>
<div class="blog1" style=" border: 0px #ccc solid;margin-left: 20px;margin-top: -9px;">
<?php
  $top_page=76;
  for($pg=1;$pg<=$pg_total;$pg++)
  {
    if($cn_no=='CP590822-00008'){
      if($pg==1){
          $top_page=77;
      }
    }else{
      if($pg==1){
          $top_page=76;
      }else{
          if($cn_no=='CP590818-00001'){
              if($pg==4){
                $top_page+=4;
              }else{
                 $top_page+=6; 
              }
          }elseif ($pg==2) {
           $top_page = -31;
          }elseif ($pg==3) {
           $top_page = -186;
          }elseif ($pg==4) {
           $top_page = 62;
          }else{
            $top_page = 62; 
          }
            
      }  
    }

    

    $pg_number= $pg."/".$pg_total; 
?>
    <div class="nnnn" style="margin-top: <?=$top_page?>px;" ></div>
   

    <br>
    <div class="top ">

        <div style="float:right;" class="title_page_logo hid"><?php echo $pg_number;?></div>
        <div class="title_page_logo hid">บริษัท ไทย ออปโป้ จำกัด</div>
        <div class="title_page_logo hid">THAI OPPO CO., LTD</div></br>
        <div class="title_page_logo_small hid">สำนักงานใหญ่:  อาคาร เอไอเอ แคปปิตอล เซ็นเตอร์ ชั้น 31 ห้อง 5-7 เลขที่ 89 ถนนรัชดาภิเษก แขวงดินแดง เขตดินแดง กรุงเทพฯ 10400 โทร.02-013-1810 โทรสาร 02-013-1820</div>
        <div class="title_page_logo_small hid">Head Office: AIA Capital Center Building Fl 31 Unit 5-7  89 Ratchadaphisek Road, DinDaeng, DinDaeng, Bangkok 10400 Tel.02-013-1810 Fax: 02-013-1820</div>
    </div>
    <div style="float:right;margin-right: 140px;"><?php echo $pg_number;?></div>
    <div class="title_page hid">ต้นฉบับใบลดหนี้/ใบกำกับภาษี/ใบรับคืนสินค้า</div>
    <div class="title_page_small_left hid">เลขประจำตัวผู้เสียภาษี : <?=$distributor_tax?></div></br>
    <div class="title_page_small_right hid">(เอกสารออกเป็นชุด)</div></br>
    <div class="title_page_col_left">
        <div class="detail clear">
            <div class="col1 hid"><span>วันที่</span></div>  <div class="col2"><?=$create_date;?></div>
            <div class="col1 hid"><span>เลขที่ใบลดหนี้</span></div>  <div class="col2"><?=$cn_no?></div>
            <div class="col1 hid"><span>ชื่อสาขา</span></div>  <div class="col2"><?=$branch_name?></div>
            <div class="col1 hid"><span>สาขาที่</span></div>  <div class="col2"><?=$branch_no?></div>
        </div>
    </div>
    <div class="title_page_col_right">
        <div class="detail clear">
            <div class="col1 hid"><span>ชื่อลูกค้า</span></div>  <div class="col2_title"><?= $retailer_name?></div>
            <div class="col1 hid"><span>ที่อยู่</span></div>  
            <div class="col2_title" style="    margin-top: -28px;"><p style="line-height: 20px;"><?=$add_tax?></br> 
            เลขประจำตัวผู้เสียภาษี : <?=$distributor_tax?></p>
        </div>
        </div>
    </div>
    </br>
      <div class="blank10"></div>

<div class="blank75"></div>
<div class="blog2">

    <?php


        $total_num = $total_price = $total_total = 0;


        $correct_bal_amount=0;$difference_amount=0;
        
        //print_r($this->invoice_list);
        //echo count($this->invoice_list);

        $creditnote_type = substr($cn_no,0,2);
        $remark='';$margin_sum=8;$margin_imei=60;

        //print_r($item);
        for($i=0;$i<=$item_per_page;$i++):

            if($cat_id==12){
              $total_num = $item[$row_product]['qty'];
            }else{
              $total_num = $item[$row_product]['num'];
            }
            
            if($creditnote_type=='CP'){

                $invoice_price = $item[$row_product]['invoice_price'];
                $total_price = $item[$row_product]['total_price'];
                $price = $item[$row_product]['price'];

                $price_unit = round($item[$row_product]['out_price']/1.07,2);               
                $price = round($item[$row_product]['price']/1.07,2);
                $total_price = round($price_unit,2) * round($total_num,2);
                //$correct_bal_amount= round($total_price-(($price)*$total_num),2);

                $correct_bal_amount= round($total_price,2)-(round($price,2))*round($total_num,2);

                //$price_unit = $price_unit+$price;
            }else{
                $price_unit = round($item[$row_product]['price']/1.07,2);
                $total_price = $price_unit * $total_num;
                $correct_bal_amount= round($total_price,2)-(round($price_unit,2))*round($total_num,2);
            }
            //echo round($correct_bal_amount,2);
            $difference_amount=round($total_price,2)-round($correct_bal_amount,2);


            //$difference_amount=1440.00;
            $total_VAT = round(($difference_amount*1.07),2)-round($difference_amount,2);

            $total_amount=round($difference_amount,2)+round($total_VAT,2);
            if($cn_no=='CP591121-00006' || $cn_no=='CP591121-00007'){
             $total_amount +=0.01;
            }
            //------------------------//
            $g_total_num +=round($total_num,0);
            $g_total_price +=round($total_price,2);

            $g_correct_bal_amount +=round($correct_bal_amount,2); 
            $g_difference_amount +=round($difference_amount,2);
            $g_total_VAT +=round($total_VAT,2);



            $g_total_amount +=round($total_amount,2);

            $invoice_number=$item[$row_product]['invoice_number'];
            if($invoice_number !=''){
              //$margin_sum +=8;
              //$margin_imei -=8;
            }
    ?>
   
    <?php 
    $no = 1;
    if($item_total>$row_product){ 
       // print_r($item[$i]);
        
        if($invoice_number==''){
            $invoice_number=$item[$row_product]['invoice_number_bvg'];
        }

        //$remark.='['.$item[$i]['product_detail'].'] '.$item[$i]['text'];
        //$remark.=$item[$row_product]['remark'];
        $remark='['.$item[0]['product_detail'].'] '.$item[0]['remark'].'</br>';

        $product_detail_list = $item[$row_product]['product_detail'].' '.$item[$row_product]['color_name'];
        if($price_unit>0){
         /* $price_unit_show = My_Number::f($price_unit);
          $total_price_show = My_Number::f($total_price);
          $correct_bal_amount_show = My_Number::f($correct_bal_amount);
          $difference_amount_show = My_Number::f($difference_amount);

          $total_VAT_show = My_Number::f($total_VAT);
          $total_amount_show = My_Number::f($total_amount);
          */


		  $price_unit_show = round($price_unit,2);
          $total_price_show = round($total_price,2);
          $correct_bal_amount_show = round($correct_bal_amount,2);
          $difference_amount_show = round($difference_amount,2);

          $total_VAT_show = round($total_VAT,2);
          $total_amount_show = round($total_amount,2);
          
        }else{
          $price_unit_show='';$total_price_show='';$correct_bal_amount_show='';
          $difference_amount_show='';$total_VAT_show='';$total_amount_show='';
        }



    ?>
     
       
         
        <div class="tbl_col1_list"><?php echo $item_total.'>'.$row_product;;?></div>
        <div class="tbl_col2_list" style="text-align: left;"><?php echo $item[$row_product]['product_detail'];?></div>
        <div class="tbl_col3_list"><?php echo $total_num;?></div>
        <div class="tbl_col4_list"><?php echo My_Number::f($price_unit);?></div>
        <div class="tbl_col5_list"><?php echo My_Number::f($total_price);?></div>
        <div class="tbl_col6_list"><?php echo My_Number::f($correct_bal_amount);?></div>
        <div class="tbl_col7_list"><?php echo My_Number::f($difference_amount);?></div>
        <div class="tbl_col8_list"><?php echo My_Number::f($total_VAT);?></div>
        <div class="tbl_col9_list"><?php echo My_Number::f($total_amount);?> </div>
        
      <div style="clear:both"></div>
         
   
    <?php }else{ 

      $invoice_number = '';
      ?>
    
        <div class="tbl_col1_list"><span class=""><?php echo $item_total.'>'.$row_product;;?></span></div>
        <div class="tbl_col2_list" style="text-align: left;"><span class="hid2">text</span></div>
        <div class="tbl_col3_list"><span class="hid2">text</span></div>
        <div class="tbl_col4_list"><span class="hid2">text</span></div>
        <div class="tbl_col5_list"><span class="hid2">text</span></div>
        <div class="tbl_col6_list"><span class="hid2">text</span></div>
        <div class="tbl_col7_list"><span class="hid2">text</span></div>
        <div class="tbl_col8_list"><span class="hid2">text</span></div>
        <div class="tbl_col9_list"><span class="hid2">text</span></div>
      <div style="clear:both"></div>
         
   
    <?php } ?>
     
    <?php 
        

      $class_tr = "style='margin-left: 420px;margin-top: ".$margin_sum."px;position: absolute;width:750px;height: 30px;'"; 

      $tbllist_imei ="style='margin-top: ".$margin_imei."px;'";

        if($pg==$pg_total  && $item_per_page==$i)
        {

          /*
          if($cn_no='CP590823-00124')
          {
            $g_total_VAT = round($g_difference_amount *1.07,2)-$g_difference_amount;
            $g_total_amount = $g_difference_amount+$g_total_VAT;
          }
          */

          $g_total_VAT = round($g_difference_amount *1.07,2)-$g_difference_amount;
          $g_total_amount = $g_difference_amount+$g_total_VAT;
          if($cn_no=='CP591121-00006' || $cn_no=='CP591121-00007'){
             $g_total_amount +=0.01; 
            }
        ?>

    <div <?php echo $class_tr;?>>
        <div class="tbl_col1_list"></div>
        <div class="tbl_col2_list"></div>
        <div class="tbl_col3_list"><?php echo $g_total_num;?></div>
        <div class="tbl_col4_list"><span class="hid2">text</span></div>
        <div class="tbl_col5_list"><?php echo My_Number::f($g_total_price);?></div>
        <div class="tbl_col6_list"><?php echo My_Number::f($g_correct_bal_amount);?></div>
        <div class="tbl_col7_list"><?php echo My_Number::f($g_difference_amount);?></div>
        <div class="tbl_col8_list"><?php echo My_Number::f($g_total_VAT);?></div>
        <div class="tbl_col9_list"><?php echo My_Number::f($g_total_amount);?></div>
      </div>
    <?php }?>
     
    <?php 
    $row_product+=1;
    $n+=1;
    endfor;?>
   </div>   
</br>

<table <?php echo $tbllist_imei;?> cellspacing="0" cellpadding="1">
    <tr style="text-align: left;">
        <td class="hid">IMEI code: </td>
    </tr>

    <tr style="text-align: left; height: 200px;vertical-align:top;">
        <td >
                <?php
            $imei_sn_list='';
            $item_list=$this->imei_return_list;$show_item_product='';
            //print_r($item_list);
            //for($i=0;$i<count($item);$i++){
            if($max_show_imei>=count($item_list)){
            for($i=0;$i<=$item_imei_per_page;$i++){
              if($item[$row_product_imei]['cat_id']==11){
                $invoice_number=$item[$row_product_imei]['invoice_number'];
                if($invoice_number==''){
                    $invoice_number=$item[$row_product_imei]['invoice_number_bvg'];
                }

                //$invoice_number= $item[$i]['invoice_number'];
                $product_name= $item[$row_product_imei]['product_detail'].' '.$item[$row_product_imei]['color_name'];
                $product_detail= $product_name.' [';
                //print_r($item_list);
                $product_detail_imei ='';$imei_list='';$count_item=0;$row_imei=0;$count_row_imei=0;
                for($j=0;$j<count($item_list);$j++){
                    //$show_item_product=$item_list[$j]['product_detail'];
                    $show_item_product = $item_list[$j]['product_detail'].' '.$item_list[$j]['color_name'];
                    $show_invoice_number=$item_list[$j]['invoice_number_import'];

                    //echo $product_name;echo $show_item_product;
                    if($product_name==$show_item_product && $invoice_number==$show_invoice_number)
                    {     $count_item+=1;
                           
                        if($row_imei==0){
                          if($count_item==5){
                            $imei_list.=$item_list[$j]['imei_sn'].'</br>,';
                            $count_item=0;
                          }else{
                            $imei_list.=$item_list[$j]['imei_sn'].',';
                          }
                        }else{
                          if($count_item==8){
                            $imei_list.=$item_list[$j]['imei_sn'].'</br>,';
                            $count_item=0;
                          }else{
                            $imei_list.=$item_list[$j]['imei_sn'].',';
                          }
                        }
                        $row_imei+=1;                    
                    }  
                }
                if($g_total_num <=8){
              echo $product_detail_imei ='['.$invoice_number.']'.$product_detail.rtrim($imei_list,',').']</br>';
                }
              }
              $row_product_imei+=1;
            }
          }
        ?>
        </td>
    </tr>
</table>
</br>
<div class="below_page_col_left">
        <div class="below_detail clear">
        </br>
            <div class="col1" style="width: 500px;margin-top: 150px;">
            <?=$remark?>
            </div>
        </div>
    </div>
    <div class="below_page_col_right ">
        <div class="below_detail clear">
            <div class="col1 hid"><span>จัดทำโดย Prepared by</div>
            <div class="col1" style="margin-top: 190px;margin-left: -210px;"><?=$prepared_by_name?></div>
            <div class="col1 hid"><span>อนุมัติโดย Authorized by</span></div>
            <div class="assign hid">    ผู้มีอำนาจลงนาม  Authorized Signature     </div>
        </div>
        
    </div>
    </br>
    <div class="below_page_col_right_1 hid">
    <div class="below_detail clear">
        <div class="col1"><span>รับโดย Received by</span></div>
            <div class="assign">    ผู้รับลงนาม  Receive Bill Signature     </div>
        </div> 
    </div>
<div id="logo" style="position:  absolute;" >
    <img src="<?php echo HOST ?>img/print.png" class="imgbutton print"  onclick="Print()" id="print"  />
</div>
<div class="single_record"></div>
<?php } ?>
</div>
</body>
</html>

<?php
   function inc_vat($num){
           return number_format(round($num*1.07,2),2);
   }

?>