<style type="text/css">
    textarea {
        width: 100%;
        max-width: 100%;
        max-height: 100px;
    }

    .numbering {
        counter-reset: rowNumber;
    }

    .numbering .item {
        counter-increment: rowNumber;
        border-bottom: 1px solid #dadada;
        margin-bottom: 10px;
    }

    .numbering .item:nth-child(2n) {
        background: #fafafa;
    }

    .numbering .item .num:first-child::before {
        content: counter(rowNumber);
        min-width: 1em;
        margin-right: 0.5em;
        font-weight: bold;
    }
    .navbar , .subnavbar , .footer
    {
        display: none;
    }

</style>

<div class="row">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Invoice</a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Internal Transport</a></li>

    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">
            <?php echo $this->render('warehouse/partials/invoice/customer-invoice.phtml'); ?>
        </div>
        <div role="tabpanel" class="tab-pane" id="profile">
            <?php echo $this->render('warehouse/partials/invoice/customer-transport.phtml'); ?>
        </div>
    </div>
</div>
