<div class="page-header">
    <h1>List of Error IMEIs</h1>
</div>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('warehouse/partials/error-search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="table-responsive">
		    <?php
		        echo $this->render('warehouse/partials/not-scanned-list.phtml');
		    ?>
		</div>
	</div>	
<!-- 	<div class="span2">
		<label for="imei">IMEI list</label>
		<textarea name="imei" id="imei" cols="16" rows="20"><?php if (isset($this->imeis) && $this->imeis): ?><?php foreach ($this->imeis as $k => $v): ?><?php echo $v['imei_sn']."\n" ?><?php endforeach ?><?php endif ?></textarea>
	</div> -->
</div>
<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });
</script>