<style>
    .blockOverlay{
        z-index: 10000 !important;
    }
    .blockPage{
        z-index: 10001 !important;
    }

    hr{
        width: 220px;
    }
</style>

<div class="page-header">
    <h1>Input Money Service Factory Claim</h1>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>

<div class="row" style="margin-left: 30px;">
    <form action="factory-claim-input-money" method="post">

    <table class="table table-bordered" style="margin-top: 15px; margin-bottom: 30px;" border="1">
        <tr>
            <td>No.</td>
            <td>Imei</td>
            <td>Product Model</td>
            <td>Product Name</td>
            <td>Product Color</td>
            <td>Request By</td>
            <td>Request Date</td>
            <td>Approved By</td>
            <td>Approved Date</td>
            <td>Job Number</td>
            <td>Money <span style="color: red">*</span></td>
        </tr>
        <?php 
            foreach ($this->get_factory_claim_array as $key => $value) {
        ?>        

        <tr>
            <td><?=$key+1?></td>
            <td><?=$value['old_imei']?></td>
            <td><?=$value['old_good_model']?></td>
            <td><?=$value['old_good']?></td>
            <td><?=$value['old_good_color']?></td>
            <td><?=$value['fullname']?></td>
            <td><?=$value['created_date']?></td>
            <td><?=$value['fullname_approved']?></td>
            <td><?=$value['approved_date']?></td>
            <td><?=$value['job_number']?></td>
            <td>
                <input type="hidden" name="id[]" value="<?=$value['factory_claim_id']?>">
                <input type="text" name="money[]" value="<?=$value['old_good_price_import']?>" required>
            </td>
        </tr>

        <?php } ?>
    </table>

    <div class="" style="margin-bottom: 50px;">
        <input type="hidden" name="part_id" value="<?=$this->id;?>">
        <button style="margin-right: 15px;" type="button" class="btn btn-default" onclick="window.location.href='<?=HOST."warehouse/factory-claim-input-money-list"?>'">Back</button>
        <button type="submit" class="btn btn-primary" id="btn-submit">Confirm</button>

    </div>
        
    </form>
</div>

<script src="/js/jquery.blockUI.js"></script>
<script>

    $(document).on("submit", "form", function(e){

        $.blockUI({ css: { 
            border: 'none', 
            padding: '15px', 
            backgroundColor: '#000', 
            '-webkit-border-radius': '10px', 
            '-moz-border-radius': '10px', 
            opacity: .5, 
            color: '#fff' 
        } });
    });

    $(document).ready(function () {


    });
</script>