<table class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
					'#',
					'Changed SN',
					'SENT',
					'RECEIVED',
					'Old',
					'New',
					'Status',
					'Created by',
				    'created_at' => 'Created at',
                    'Action'
                ),
                $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php
        $statuses = unserialize(CHANGE_ORDER_STATUS);
        if (isset($this->change_sales) and $this->change_sales) :
            foreach ($this->change_sales as $k=>$m): ?>
                <tr>
                    <td>
                        <?php
                        echo $this->offset + $k + 1;
                        ?>
                    </td>
                    <td><?php echo $m['changed_sn'] ?></td>
                    <td><?php echo $m['total_qty_product'] ?></td>
                    <td><?php echo $m['total_qty_product_receive'] ?></td>
                    <td><?php echo ( $m['is_changed_wh']==1 ? ('WH: ' . ( isset( $this->warehouse_cached[$m['old_id']] ) ? $this->warehouse_cached[$m['old_id']] : '' ) ) : ( 'Retailer:' . ( isset( $this->distributor_cached[$m['old_id']] ) ? $this->distributor_cached[$m['old_id']] : '' ) ) ) ; ?></td>
                    <td><?php echo ( $m['is_changed_wh']==1 ? ('WH: ' . ( isset( $this->warehouse_cached[$m['new_id']] ) ? $this->warehouse_cached[$m['new_id']] : '' ) ) : ( 'Retailer:' . ( isset( $this->distributor_cached[$m['new_id']] ) ? $this->distributor_cached[$m['new_id']] : '' ) ) ) ; ?></td>


                    <td><?php echo ( isset($statuses[ $m['status'] ]) ? $statuses[ $m['status'] ] : '' ); ?></td>
                    <td><?php echo ( isset($this->staff_cached[ $m['created_by'] ]) ? $this->staff_cached[ $m['created_by'] ] : '' ); ?></td>
                    <td><?php echo $m['created_at']; ?></td>
                    <td class="">
                        <?php if ($this->access('warehouse', 'change-sales-view')) {?>
                            <a title="View" href="/warehouse/change-sales-view?id=<?php echo $m['id'];?>"> <i class="icon-eye-open"></i></a>
                        <?php } ?>

                        <?php if ($this->access('warehouse', 'change-sales-view')) {?>
                            <?php if ( in_array($m['status'], array(CHANGE_ORDER_STATUS_PENDING)) ):?>
                                <a title="Edit" href="/warehouse/change-sales?id=<?php echo $m['id'];?>"> <i class="icon-edit"></i></a>
                            <?php endif;?>
                        <?php } ?>

                        <?php if ($this->access('warehouse', 'change-sales-scan-out')) {?>
                            <?php if ( in_array($m['status'], array(CHANGE_ORDER_STATUS_PENDING)) ):?>
                                <a title="Scan OUT" href="/warehouse/change-sales-scan-out?id=<?php echo $m['id'];?>"> <i class="icon-tags"></i></a>
                            <?php endif;?>
                        <?php } ?>

                        <?php if ($this->access('warehouse', 'change-sales-confirm')) {?>
                            <?php if ( in_array($m['status'], array(CHANGE_ORDER_STATUS_SCANNED_OUT)) ):?>
                                <a title="Confirm OUT" href="/warehouse/change-sales-confirm?id=<?php echo $m['id'];?>"> <i class="icon-road"></i></a>
                            <?php endif;?>
                        <?php } ?>

                        <?php if ($this->access('warehouse', 'change-sales-receive')) {?>
                            <?php if ( in_array($m['status'], array(CHANGE_ORDER_STATUS_ON_CHANGE, CHANGE_ORDER_STATUS_SCANNED_IN , CHANGE_ORDER_STATUS_FULL_RECEIVED , CHANGE_ORDER_STATUS_PARTIALLY_RECEIVED)) ):?>
                                <a title="Scan IN" href="/warehouse/change-sales-receive?id=<?php echo $m['id'];?>"> <i class="icon-qrcode"></i></a>
                            <?php endif;?>
                        <?php } ?>

                        <?php if ($this->access('warehouse', 'change-sales-complete')) {?>
                            <?php if ( in_array($m['status'], array(CHANGE_ORDER_STATUS_SCANNED_IN , CHANGE_ORDER_STATUS_FULL_RECEIVED , CHANGE_ORDER_STATUS_PARTIALLY_RECEIVED )) ):?>
                                <a title="Complete IN" href="/warehouse/change-sales-complete?id=<?php echo $m['id'];?>"> <i class="icon-ok"></i></a>
                            <?php endif;?>
                        <?php } ?>

                    </td>
                </tr>
            <?php endforeach;?>
		<?php endif; ?>
    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>
