<div class="page-header">
    <h1>Confirm Purchase Order</h1>
</div>
<style>
    tr td:first-child {
        width: 20%;
    }
</style>
<?php
    if (isset($this->warning) and $this->warning)
        foreach ($this->warning as $message):
            echo '<div class="alert alert-block">'.$message.'</div>';
        endforeach;

    if (isset($this->error) and $this->error)
        foreach ($this->error as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="row">
    <div class="span12">
        <form role="form" id="form" action="<?php echo HOST.'warehouse/po-confirm';?>" method="post" class="form-horizontal">
	        <table class="table table-bordered">
	            <tbody>
                    <tr>
                        <td>Purchase order ID</td>
                        <td><strong><?php isset($this->PO) and $this->PO and printf($this->PO->id);?></strong></td>
                    </tr>

                    <tr>
                        <td>Purchase order number</td>
                        <td><strong><?php isset($this->PO) and $this->PO and printf($this->PO->sn_ref);?></strong></td>
                    </tr>

                    <tr>
                        <td>Purchase order Type</td>
                        <td><?php if (isset($this->PO['type'])) echo My_Po_Type::getLabel($this->PO['type']) ?></td>
                    </tr>

                    <tr>
                        <td>Purchase order Maker</td>
                        <td><?php printf($this->created_by_name);?></td>
                    </tr>

                    <tr>
                        <td>Purchase Model</td>
                        <td style="color:blue; font-size:16px; font-weight:bold;"><?php isset($this->good) and $this->good and printf($this->good);?></td>
                    </tr>

                    <tr>
                        <td>Purchase Color</td>
                        <td style="color:blue; font-size:16px; font-weight:bold;"><?php isset($this->good_color) and $this->good_color and printf($this->good_color);?></td>
                    </tr>

                    <tr>
                        <td>Purchase quantity</td>
                        <td style="color:blue; font-size:16px; font-weight:bold;"><?php isset($this->PO) and $this->PO and printf($this->PO->num);?></td>
                    </tr>

					<?php if ( in_array($this->PO->cat_id, array(PHONE_CAT_ID,IOT_CAT_ID, DIGITAL_CAT_ID, ILIKE_CAT_ID))): ?>
						<tr>
	                        <td>Number already in storage</td>
	                        <td style="color:red; font-size:16px; font-weight:bold;"><?php if (isset($this->num_scanned) and $this->num_scanned) echo $this->num_scanned; else echo "0";?></td>
	                    </tr>
					<?php endif ?>

                    <tr>
                        <td>Purchase price</td>
                        <td><?php isset($this->PO) and $this->PO and printf($this->PO->price);?></td>
                    </tr>

                    <tr>
                        <td>Purchase time</td>
                        <td><?php isset($this->PO) and $this->PO and printf($this->PO->created_at);?></td>
                    </tr>

                    <tr>
                        <td>Purchaser</td>
                        <td><?php isset($this->warehouse) and $this->warehouse and printf($this->warehouse);?></td>
                    </tr>

                    <tr>
                        <td>Purchase payment</td>
                        <td><?php if ($this->PO->flow):?><i class="icon-ok"></i><?php else:?><i class="icon-remove"></i><?php endif;?></td>
                    </tr>

                    <tr>
                        <td>Payer</td>
                        <td><?php echo $this->payer_name;?></td>
                    </tr>

                    <tr>
                        <td>Time of payment</td>
                        <td><?php if ($this->PO->flow):?><?php echo $this->PO->flow_time;?><?php else:?>-<?php endif;?></td>
                    </tr>

                    <!-- <tr>
                        <td>Whether to enter the warehouse</td>
                        <td><?php if ($this->PO->mysql_user):?><i class="icon-ok"></i><?php else:?><i class="icon-remove"></i><?php endif;?></td>
                    </tr>

                    <tr>
                        <td>Warehouse Man</td>
                        <td><?php echo $this->warehousing_name;?></td>
                    </tr>

                    <tr>
                        <td>Time input warehouse</td>
                        <td><?php if ($this->PO->mysql_time):?><?php echo $this->PO->mysql_time;?><?php else:?>-<?php endif;?></td>
                    </tr> -->

                    <tr>
                        <td>Purchase remark</td>
                        <td><strong><?php isset($this->PO) and $this->PO and printf($this->PO->text);?></strong></td>
                    </tr>

                    <tr>
                        <td>Payment Notes</td>
                        <td>
                            <?php isset($this->PO) and $this->PO and printf($this->PO->pay_user);?>
                        </td>
                    </tr>
	            </tbody>
	        </table>
	        <div class="row">
		        <div class="span4">
		            <input type="hidden" name="id" value="<?php isset($this->PO) and $this->PO and printf($this->PO->id);?>">
		            <input type="hidden" id="back_url" name="back_url" value="/warehouse/in">
		            <button type="submit" class="btn btn-primary">Submit</button>
		            <button type="button" class="btn btn-danger go-back">Go back</button>
		        </div>
	        </div>
        </form>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#form').submit(function (e){
            if (!confirm('This action can not be reversed, please exercise caution...'))
                return false;
        });
        $('.go-back').click(function(e){
            window.location.href = $('#back_url').val();
            return false;
        });
    });
</script>