<form class="form-search form-horizontal" method="get" action="/warehouse/product-out">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="sn" class="span2">Sales Order Number</label>
                <input id="sn" name="sn" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['sn']) and printf($this->params['sn']);?>">
            </div>

        </div>
        <div class="span5">
            <div class="control-group">
                <label for="warehouse_id" class="span2">Warehouse</label>
                <select id="warehouse_id" class="span3" name="warehouse_id">
                    <option value="">Choose</option>
                    <?php if ($this->warehouses): foreach ($this->warehouses as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['warehouse_id']) and $id==$this->params['warehouse_id']):?> selected<?php endif;?>><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="cat_id" class="span2">PRODUCT CATEGORY</label>
                <select id="cat_id" class="span3" name="cat_id">
                    <option value="">Choose</option>
                    <?php if ($this->good_categories): foreach ($this->good_categories as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['cat_id']) and $id==$this->params['cat_id']):?> selected<?php endif;?>><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">
                <label for="good_id" class="span2">Product</label>
                <select id="good_id" class="span3" name="good_id">
                    <option value="">Choose</option>
                    <?php if ($this->goods): foreach ($this->goods as $item):?>
                        <option value="<?php echo $item->id;?>" <?php if (isset($this->params['good_id']) and $item->id==$this->params['good_id']):?> selected<?php endif;?>><?php echo $item->name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">
                <label for="good_color" class="span2">Color</label>
                <select id="good_color" class="span3" name="good_color">
                    <option value="">Choose</option>
                    <?php if ($this->colors): foreach ($this->colors as $item):?>
                        <option value="<?php echo $item->id;?>" <?php if (isset($this->params['good_color']) and $item->id==$this->params['good_color']):?> selected<?php endif;?>><?php echo $item->name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>
            
            <div class="control-group">
                <label for="invoice_number" class="span2">Invoice Number</label>
                <input id="invoice_number" name="invoice_number" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['invoice_number']) and printf($this->params['invoice_number']);?>">
            
            </div>
           
            <div class="control-group">
                <label for="myTags" class="span2">Tags</label>
                <ul class="form-control span3" id="myTags"><?php
                    if (isset($this->params['tags']) and $this->params['tags']):
                        foreach ($this->params['tags'] as $ta)
                            echo '<li>'.$ta.'</li>';
                    endif;
                    ?></ul>
            </div>
        </div>

        <div class="span5">

            <div class="control-group">
                <label for="d_id" class="span2">Retailer Name</label>
                    <input type='text' class="span3" name='SearchBox' id="SearchBox" placeholder="Search" autocomplete="off" />
                    <select name="d_id" id="d_id" class="span3" size="5">
                        <option value="">Choose</option>
                        <?php if (isset($this->distributorsList) && $this->distributorsList): foreach ($this->distributorsList as $id=>$name):?>
                            <option value="<?php echo $id;?>" <?php if (isset($this->params['d_id']) and $id==$this->params['d_id']):?> selected="selected"<?php endif;?>><?php echo $name;?></option>
                        <?php endforeach; endif;?>
                    </select>
                
            </div>

            <div class="control-group">
                <label for="out_time_from" class="span2">OUT Time From</label>
                <input type="text" class="form-control search-query date" id="out_time_from" name="out_time_from" value="<?php isset($this->params['out_time_from']) and printf($this->params['out_time_from']);?>">
            </div>
            <div class="control-group">
                <label for="out_time_to" class="span2">OUT Time To</label>
                <input type="text" class="form-control search-query date" id="out_time_to" name="out_time_to" value="<?php isset($this->params['out_time_to']) and printf($this->params['out_time_to']);?>">
            </div>

            <div class="control-group">
                <label for="area_id" class="span2">Area</label>
                <select name="area_id" id="area" class="span3">
                    <option value="">Choose</option>
                    <?php if (isset($this->areas) && $this->areas): foreach ($this->areas as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['area_id']) and $id==$this->params['area_id']):?> selected="selected"<?php endif;?>><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">
                <label for="region" class="span2">Province</label>
                <select name="region_id" id="region" class="span3">
                    <option value="">Choose</option>
                    <?php if (isset($this->regions) && $this->regions): foreach ($this->regions as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['region_id']) and $id==$this->params['region_id']):?> selected="selected"<?php endif;?>><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">
                <label for="district" class="span2">District</label>
                <select name="district_id" id="district" class="span3">
                    <option value="">Choose</option>
                    <?php if (isset($this->districts) && $this->districts): foreach ($this->districts as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['district_id']) and $id==$this->params['district_id']):?> selected="selected"<?php endif;?>><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
    <button type="submit" name="export" value="1" class="btn btn-success">Export</button>
</form>

<script type="text/javascript" src="<?php echo HOST ?>js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" type="text/css" href="<?php echo HOST ?>css/jquery-ui-1.8.12.custom.css"/>
<link href="<?php echo HOST ?>css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="<?php echo HOST ?>css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">

<script>
    $(document).ready(function () {
        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('#cat_id, #good_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var cat_id = $('#cat_id').val();

            if (_self.attr('id')=='cat_id')
                $('#good_id').find('option:not(:first)').remove();

            var good_id = $('#good_id').val();

            $('#good_color').find('option:not(:first)').remove();

            $('#num, #price').val('');

            $.get("/get/load",
                {cat_id: cat_id, good_id: good_id}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    if (data.goods){
                        var obj = data.goods;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    if (data.colors){
                        var obj = data.colors;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    _self.nextAll('.loading').remove();
                });
        });

    	$('#area').change(function(){
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();

            $.get("<?php echo HOST ?>get/region",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#region').find('option:not(:first)').remove();
                    $('#district').find('option:not(:first)').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#region').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('.loading').remove();
                });
        });

        $('#region').change(function(){

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var region = _self.val();

            $('#district').find('option:not(:first)').remove();

            $.get("/get/district",
                {region: region}
                ,function(data,status){
                    var data = $.parseJSON( data );

                    for (var i = 0; i < data.length; i++) {
                        $('#district').append('<option value="'+data[i]['id']+'">'+data[i]['name']+'</option>');
                    }

                    _self.nextAll('.loading').remove();
                });
        });

        initTag();
        initSearchOptionDistributor('d_id', 'SearchBox');
	});

    function initTag(){

        $('#myTags').tagit({
            allowSpaces: true,
            fieldName: 'tags[]',
            autocomplete: {
                delay: 0,
                minLength: 2,
                source: "<?php echo HOST;?>get/get-tags"
            }
        });

    }
</script>
