<link rel="stylesheet" type="text/css" href="<?=HOST?>/datatable/media/css/jquery.dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="/datatable/extensions/buttons/css/buttons.dataTables.min.css"/>
<style type="text/css">
    a.dt-button.danger {
        background-image: linear-gradient(rgba(219, 51, 37, 0), rgba(1, 0, 0, 0.1));
        background-color: #db3325;
        border-color: rgba(0, 0, 0, 0.05) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.15);
        color: #fff;
        text-shadow: 1px 1px 0 rgba(0, 0, 0, 0.15);
    }

     a.dt-button.danger:hover {
        background-image: linear-gradient(rgba(219, 51, 37, 0), rgba(1, 0, 0, 0.1));
        background-color: #DB1204;
        border-color: rgba(0, 0, 0, 0.05) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.15);
        color: #fff !important;
        text-shadow: 1px 1px 0 rgba(0, 0, 0, 0.15);
    }
    table.dataTable thead th, table.dataTable thead td{
    border-bottom: 0 !important;
  }

  table.dataTable.no-footer {
       border-bottom:  0 !important;
  }

  .table-bordered, .table-bordered>thead>tr>th, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>tbody>tr>td, .table-bordered>tfoot>tr>td, .nav-tabs.nav-justified>.active>a, .nav-tabs.nav-justified>.active>a:hover, .nav-tabs.nav-justified>.active>a:focus, .nav-tabs-justified>.active>a, .nav-tabs-justified>.active>a:hover, .nav-tabs-justified>.active>a:focus {
    border: 1px solid #ddd;
  }


  .table-bordered th {
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FAFAFA), color-stop(100%,#E9E9E9)) !important;
   
    font-size: 10px;
    color: #19bc9c;
    text-transform: uppercase;
  }

  table.dataTable tbody tr{
    background-color: #f9f6f1 !important;
  }
    
</style>


<input type="hidden" name="filename_excel" id="filename_excel" value="<?php isset($this->filename_excel) and printf($this->filename_excel);?>">
<div class="page-header">
    <h1><?=$this->title;?></h1>
</div>

<div class="table-responsive">
 <!-- <div class="row">
            <div class="span4">                
                <button type="button" class="btn btn-danger go-back">Go back</button>
            </div>
          </div> -->
   <table id="imei_table" class="table table-bordered">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Imei id</th>
                    <th>Product</th>
                    <th>Color</th> 
                     <?php if($this->type == "po"){ ?>
                        <th>Imei Old</th> 
                        <th>CO SN</th> 
                     <?php } ?>
                </tr>
            </thead>
            <tbody>
            <?php for($i = 0;$i<$this->total;$i++){?>
              	<tr>
              		<td><?=($i+1)?></td>
              		<td><?=$this->imeiarr[$i]["imei_sn"];?></td>
              		<td><?=$this->imeiarr[$i]["good_name"];?>(<?=$this->imeiarr[$i]["desc"];?>)</td>
              		<td><?=$this->imeiarr[$i]["color_name"];?></td>
                  <?php if($this->type == "po"){ ?>
                      <td><?=$this->imeiarr[$i]["imei_old"];?></td>
                      <td><?=$this->imeiarr[$i]["co_sn"];?></td>
                  <?php } ?>
              	</tr>
            <?php } ?>
            </tbody>
        </table>
</div>




<script type="text/javascript" src="/datatable/media/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/datatable/extensions/buttons/js/dataTables.buttons.min.js"></script>

<script type="text/javascript" src="/datatable/extensions/buttons/js/buttons.flash.min.js"></script>




<!-- <script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script> -->
<!-- <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>-->
<!-- <script type="text/javascript" src="//cdn.datatables.net/buttons/1.3.1/js/buttons.flash.min.js"></script> -->

<!-- <script type="text/javascript" src="///cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script> -->

<!-- <script type="text/javascript" src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script> -->
<!-- <script type="text/javascript" src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script> -->
<!-- 
<script type="text/javascript" src="//cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/buttons/1.3.1/js/buttons.print.min.js"></script>
 -->

<script type="text/javascript" src="/datatable/extensions/jszip/jszip.min.js"></script>
<script type="text/javascript" src="/datatable/extensions/buttons/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="/datatable/extensions/buttons/js/buttons.print.min.js"></script>







<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });

    var d = new Date();
    var curr_date = d.getDate();
    var curr_month = d.getMonth() + 1; //Months are zero based
    var curr_year = d.getFullYear();
     $('#imei_table').DataTable( {
            "pageLength": 20,
            "lengthChange": false,
            "searching": false,
            dom: 'Bfrtip',
            buttons: [
               {
                  extend: 'excel',
                  filename: $("#filename_excel").val()
              },
              {
                  text: 'Go back',
                  className: 'danger',
                  action: function ( e, dt, node, config ) {
                      window.location.href = "/warehouse/product-warranty";
                  }
              }
            ]
            // "order": [[ 3, "desc" ]]
        } );
</script>
