<div class="page-header">
    <h1>Pickup ORDER - SCAN IN</h1>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<iframe name="iframe" id="iframe" width="100%" style="display:none;"></iframe>

<form role="form" id="form" method="post" target="iframe"  class="form-inline">

    <?php echo $this->render('warehouse/partials/requisition-sales-add-type.phtml');?>

    <?php echo $this->render('warehouse/partials/requisition-sales-add-form.phtml');?>

    <div class="row">
        <div class="span6">
            <div class="control-group">
                <div class="span4">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <input type="hidden" class="action_form" name="action_form" id="action_form" value="scan_in">
                    <input type="hidden" name="id" value="<?php if (isset($this->changeSalesOrder['id']) and $this->changeSalesOrder['id']) echo $this->changeSalesOrder['id'];?>" />
                    <input type="hidden" name="back_url" id="back_url" value="/warehouse/requisition-sales-list">
                    <button type="button" class="btn btn-danger go-back">Go back</button>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</form>

<?php echo $this->render('warehouse/partials/requisition-sales-add-script.phtml');?>