<div class="page-header">
    <h1>Requisition ORDER - VIEW</h1>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<form role="form" id="form" method="post" class="form-inline">

    <?php echo $this->render('warehouse/partials/requisition-sales-add-type.phtml');?>

    <?php echo $this->render('warehouse/partials/requisition-sales-add-form.phtml');?>

    <div class="row">
        <div class="span6">
            <div class="control-group">
                <div class="span4">
                    <input type="hidden" name="id" value="<?php if (isset($this->changeSalesOrder['id']) and $this->changeSalesOrder['id']) echo $this->changeSalesOrder['id'];?>" />
                    <input type="hidden" name="back_url" id="back_url" value="/warehouse/requisition-sales-list">
                    <button type="button" class="btn btn-danger go-back">Go back</button>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</form>

<?php echo $this->render('warehouse/partials/requisition-sales-add-script.phtml');?>