<div class="page-header">
    <h1>Transfer IMEI</h1>
</div>
<style>
    textarea {
        resize: none;
    }
</style>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">' . $message . '</div>';
    endforeach;
?>

<form role="form" id="transfer_form" action="" method="post"
      enctype="multipart/form-data" class="form-inline">
    <div class="row-fluid">
        <span class="span3">
            <p>Fill in IMEI, one per line.</p>
            <label for="" class="">IMEI Code: <span><strong id="num_imei"><?php echo (isset($this->params)) ? $this->params['total_imei'] : 0;?></strong> IMEI(s)</span></label>
        </span>
    </div>
    <div class="row-fluid">
        <div class="span3">
            <textarea name="imei" id="imei" cols="20" rows="20" required="required"><?php echo (isset($this->params)) ? $this->params['imei'] : '';?></textarea>

            <select name="type" style="margin-top: 10px; margin-bottom: 10px" required>
                <option value="">--- Type ---</option>
                <option value="1" <?php echo (isset($this->params) && $this->params['type'] == 1) ? 'selected="selected"' : '';?>>Normal ເຄືອງປົກກະຕິ</option>
<!--                 <option value="2" <?php echo (isset($this->params) && $this->params['type'] == 2) ? 'selected="selected"' : '';?>>Demo</option> -->
                <option value="5" <?php echo (isset($this->params) && $this->params['type'] == 5) ? 'selected="selected"' : '';?>>DEMO ເຄືອງໂຊ</option>
                <option value="3" <?php echo (isset($this->params) && $this->params['type'] == 3) ? 'selected="selected"' : '';?>>Staff ເຄືອງພະນັກງານ</option>
            </select>
        </div>
        <div class="span5">
            <div class="control-group">

                <?php if (isset($this->imei_status_transfer)): ?>
                    <div style="overflow: auto; max-height: 400px; width: 550px">
                        <table class="table table-bordered span5">
                            <thead>
                            <tr>
                                <th style="text-align: center;">IMEI</th>
                                <th style="text-align: center;">Type</th>
                                <th style="text-align: center;">Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if (count($this->imei_status_transfer) > 0) : ?>
                                <?php foreach ($this->imei_status_transfer as $k => $v): ?>
                                    <tr>
                                        <td style="text-align: center;"><?php echo $k; ?></td>

                                        <td style="text-align: center;"><?php if($this->params['type'] == 1){
                                                echo 'Normal';
                                            }else if($this->params['type'] == 5){ 
                                                echo 'DEMO';
                                            }else if($this->params['type'] == 3){
                                                echo "Staff";
                                            }else{ echo'APK';
                                            } ?></td>


                                        <td style="text-align: center;">
                                <span class="label <?php echo ($v['status'] == 1) ? 'label-success' : 'label-warning'; ?>">
                                    <?=$v['message'];?>
                                </span>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <tr>
                                    <td colspan="3">Không tìm thấy</td>
                                </tr>
                            <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                <?php endif; ?>

            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span3">
            <div class="control-group">
                <button id="transfer_btn" type="submit" class="btn btn-success">Transfer</button>
                <span></span>
            </div>
        </div>
        <div class="span5">
            <div id="check_res"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</form>

<script>
    $(document).ready(function () {
        initShowIMEINum();

        $("#transfer_form").submit(function(){
            $("#transfer_btn").attr('disabled', 'disabled');
        });
    });

    function initShowIMEINum() {
        $('#imei').keyup(function (e) {

            var inputnum = 0;

            if ($(this).val() != '')
                inputnum = ($(this).val().split("\n").length).toString();


            $('#num_imei').html(inputnum);

        });
    }
</script>