<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link href="<?php echo HOST ?>css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="<?php echo HOST ?>css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">
<style>
  /*  #d_id{
        margin-left: 0px!important;
        left: 0px!important;
        width: 370px;
    }*/
</style>
<div class="page-header">
    <h1>Warehouse Shipment Info Report</h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('kerry/partials/report_search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
    <?php
        echo $this->render('kerry/partials/report_list.phtml');
    ?>
</div>

<script type="text/javascript" src="/js/jets.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>

<?php echo $this->confirm();?>
<script>

    function showModalAddress(tracking_no,contact_name,phone,address,district_name,amphure_name,provice_name,zipcode){

        $('.text-modal').text('');

        $('#modal-text-tracking_no').text(tracking_no);
        $('#modal-text-contact_name').text(contact_name);
        $('#modal-text-phone').text(phone);
        $('#modal-text-address').text(address);
        $('#modal-text-district_name').text(district_name);
        $('#modal-text-amphure_name').text(amphure_name);
        $('#modal-text-provice_name').text(provice_name);
        $('#modal-text-zipcode').text(zipcode);
    }

    function showModelImage(tracking_no,image,show_hide){

        if(show_hide == 'SHOW'){
            $('.show_hide').removeClass('hide');
        }else{
            $('.show_hide').addClass('hide');
        }

        $('#modal-text-tracking_no_img').text(tracking_no);

        $('#delivery_image').attr('src', '');

        var main_url = '<?=$this->part_image;?>';
        var url = main_url+image;

        $('#delivery_image').attr('src', url);   
    }

    function initTag(){

        $('#myTags').tagit({
            allowSpaces: true,
            fieldName: 'tags[]',
            autocomplete: {
                delay: 0,
                minLength: 2,
                source: "<?php echo HOST;?>get/get-tags"
            }
        });
    }

    function getKerryDetail(sn){
        if (! $('#m_'+sn).parent().parent().next().hasClass('accordion-body')){
            $('#m_'+sn+' .col-sign').html('');
            $('#m_'+sn+' .img-loading').show();

            $.ajax({
                type: 'post',
                url: '/get/market-detail',
                data: {
                    'sn': sn,
                    'list': 'kerryreport',
                    'params': '<?php echo (isset($this->params) ? serialize($this->params) : '')?>'
                },
                error: function(){
                },
                success: function(data){
                    $('.m_'+sn).remove();
                    $('#m_'+sn).parent().parent().after(data);
                    $('#m_'+sn).find('.col-sign').html('-');
                    $('#m_'+sn+' .img-loading').hide();
                }
            });
        }
    }

    $(document).ready(function () {

        $('li').removeClass('active');
        $('.icon-plane').addClass('active');

        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        $('.collapse_a').click(function(){
            var _this = $(this);
            var _this_id = _this.attr('id');
            var sn = _this.attr('rel');

            if (_this.parent().parent().next().hasClass('accordion-body')){

                $('.m_'+sn).toggle();

                if ($('.m_'+sn).is(':visible'))
                    _this.find('.col-sign'). html('-');
                else _this.find('.col-sign'). html('+');

            } else {
                _this.find('.col-sign'). html('');

                getKerryDetail(sn);
            }

        });

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('#cat_id, #good_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var cat_id = $('#cat_id').val();

            if (_self.attr('id')=='cat_id')
                $('#good_id').find('option:not(:first)').remove();

            var good_id = $('#good_id').val();

            $('#good_color').find('option:not(:first)').remove();

            $('#num, #price').val('');

            $.get("/get/load",
                {cat_id: cat_id, good_id: good_id}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    if (data.goods){
                        var obj = data.goods;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    if (data.colors){
                        var obj = data.colors;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    _self.nextAll('.loading').remove();
                });
        });

        $('.lock').click(function(e){
            e.preventDefault();
            alert('Sorry,This information is blocked...You can not delete payment has been made or has been the storage of information!');
        });

        initTag();
    });
</script>