<div class="page-header">
	<h1 style="font-family: Times New Roman;">Financial Document Management</h1>
</div>

<div class="row-fluid" style="border-style: solid; padding-top: 20px; padding-bottom: 30px; display: contents;">
	<div class="span12">

		<div class="span4"> 
			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px; width: 100%;"> 
					<div>
						<img src="https://i.postimg.cc/CxQyztSf/journal.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="/finance/accounting-organization" style="padding-top: 50px; font-size: 24px;"> Accounting organization </a></p>
					</div>
				</div>
			</div>

			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px;">
					<div>
						<img src="https://i.postimg.cc/pdsmhPyJ/customer-service.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="/finance/finance-client" style="padding-top: 50px; font-size: 24px;" > Financial Client </a></p>
					</div>
				</div>
			</div>

		</div>

		<div class="span4"> 
			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px;">
					<div>
						<img src="https://i.postimg.cc/k53c1Fyp/money.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="/finance/finance-warehouse" style="padding-top: 50px; font-size: 24px;" > Financial Warehouse </a></p>
					</div>
				</div>
			</div>

			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px;">
					<div>
						<img src="https://i.postimg.cc/7Z28dkFY/price.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="/finance/cost-item" style="padding-top: 50px; font-size: 24px;" > Cost Item </a></p>
					</div>
				</div>
			</div>

		</div>

		<div class="span4"> 
			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px;">
					<div>
						<img src="https://i.postimg.cc/nhYjx4J5/money-1.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="/finance/finance-warehouse-group" style="padding-top: 50px; font-size: 24px;" > Financial Warehouse Group </a></p>
					</div>
				</div>
			</div>

		</div>

	</div>

</div>