<table class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
                    '#',
                    'name'  => 'Name',
                    'Gift',
                    'Action'
                ),
                $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php
        if (isset($this->bonus) and $this->bonus)
            foreach ($this->bonus as $k=>$good): ?>
        <tr>
            <td>
                <?php
                    $inc = $this->offset + $k + 1;
                    echo $inc;
                ?>
            </td>
            <td><?php echo (isset($this->goods[$good['good_id']]) && $this->goods[$good['good_id']] ? $this->goods[$good['good_id']] : '')  ?></td>
            <td>
                <?php foreach ($good['gift_id'] as $bonus_good): ?>
                    <span class="label"><?php echo (isset($this->goods[$bonus_good]) && $this->goods[$bonus_good] ? $this->goods[$bonus_good] : '') ?></span>
                <?php endforeach ?>
            </td>
            <td class="">
                <a title="Edit" href="/product/bundle-gift-edit?id=<?php echo $good['id'];?>"> <i class="icon-edit"></i></a>
                <a title="Delete" class="confirmLink" href="/product/bundle-gift-delete?id=<?php echo $good['id'];?>"> <i class="icon-trash"></i></a>
            </td>
        </tr>
        <?php endforeach;?>

    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>
<?php echo $this->confirm();?>
