<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>

<style type="text/css">
    #d_id {
        left: -20px !important;
    }

    [class*="span"] {
        margin-left: 10px;
    }

    #d_id {
        margin-bottom: 0;
    }
</style>

<form class="form-search form-horizontal" method="get" action="<?php echo HOST ?>hub/order-control">
    <div class="row">
        <div class="span4">
            <div class="control-group">
                <label for="delivery_sn" class="control-label">Delivery Code</label>
                <div class="controls">
                    <input id="delivery_sn" name="delivery_sn" type="text" value="<?php if(isset($this->params['delivery_sn'])) echo $this->params['delivery_sn'] ?>">
                </div>
            </div>
            <div class="control-group">
                <label for="sn" class="control-label">Sales Order Number</label>
                <div class="controls">
                    <input id="sn" name="sn" type="text" value="<?php isset($this->params['sn']) and printf($this->params['sn']);?>">
                </div>
            </div>
            
            <div class="control-group">
                <label for="warehouse" class="control-label">Warehouse</label>
                <div class="controls">
                    <select name="warehouse[]" id="warehouse" class="multiselect" multiple="multiple">
                        <?php if (isset($this->warehouses) && $this->warehouses): foreach ($this->warehouses as $_id => $_name):?>
                            <option value="<?php echo $_id;?>" 
                                <?php if (isset($this->params['warehouse']) 
                                    and ( (is_array($this->params['warehouse']) and in_array($_id, $this->params['warehouse'])) 
                                    || $_id==$this->params['warehouse']) ):?> selected<?php endif;?>
                                ><?php echo str_replace('Warehouse_', ' ', $_name);?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>
            
            <div class="control-group">
                <label for="hub" class="control-label">Hub</label>
                <div class="controls">
                    <select name="hub[]" id="hub" class="multiselect" multiple="multiple">
                        <?php if (isset($this->hubs) && $this->hubs): foreach ($this->hubs as $_id => $_name):?>
                            <option value="<?php echo $_id;?>" 
                                <?php if (isset($this->params['hub']) 
                                    and ( (is_array($this->params['hub']) and in_array($_id, $this->params['hub'])) 
                                    || $_id==$this->params['hub']) ):?> selected<?php endif;?>
                                ><?php echo $_name;?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>
            
            <div class="control-group">
                <label for="type" class="control-label">Type</label>
                <div class="controls">
                    <select name="type" class="delivery_type" id="type">
                        <option value=>Choose</option>
                        <?php if (isset(My_Delivery_Type::$name) && My_Delivery_Type::$name): foreach (My_Delivery_Type::$name as $_type => $_name):?>
                            <option value="<?php echo $_type;?>" <?php if (isset($this->params['type']) and $_type==$this->params['type']):?> selected="selected"<?php endif;?>><?php echo $_name;?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>

            <div class="control-group" data-type="<?php echo My_Delivery_Type::Inhouse ?>" style="<?php if(!isset($this->params['type']) || My_Delivery_Type::Inhouse != $this->params['type']) echo "display:none;" ?>">
                <label class="control-label" for="staff_id">Staff</label>
                <div class="controls">
                    <input type="text" name="SearchBoxStaff" id="SearchBoxStaff"  placeholder="Search" autocomplete="off">
                    <select name="staff_id" id="staff_id" size="5">
                        <option value>---</option>
                        <?php foreach ($this->staffs as $staff_id => $name): ?>
                            <option value="<?php echo $staff_id ?>"
                                <?php if(isset($this->params['staff_id']) && $this->params['staff_id'] == $staff_id) echo "selected" ?>><?php echo $name ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
            
            <div class="control-group" data-type="<?php echo My_Delivery_Type::Outside ?>" style="<?php if(!isset($this->params['type']) || My_Delivery_Type::Outside != $this->params['type']) echo "display:none;" ?>">
                <label class="control-label" for="carrier">Carrier</label>
                <div class="controls">
                    <select name="carrier" id="carrier">
                        <option value>---</option>
                        <?php foreach (My_Carrier::$name as $carrier_id => $name): ?>
                            <option value="<?php echo $carrier_id ?>"
                                <?php if(isset($this->params['carrier']) && $this->params['carrier'] == $carrier_id) echo "selected" ?>><?php echo $name ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>

            
        </div>
        <div class="span4">
            

            <div class="control-group">
                <label class="control-label" for="receiver">Receiver</label>
                <div class="controls">
                    <input type="text" name="receiver" id="receiver" value="<?php if(isset($this->params['receiver'])) echo $this->params['receiver'] ?>" />
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="address">Address</label>
                <div class="controls">
                    <textarea name="address" id="address"><?php if(isset($this->params['address'])) echo trim($this->params['address']) ?></textarea>
                </div>
            </div>
            
            <div class="control-group">
                <label class="control-label" for="phone">Tel/Mobile</label>
                <div class="controls">
                    <input type="text" name="phone" id="phone" value="<?php if(isset($this->params['phone'])) echo $this->params['phone'] ?>" />
                </div>
            </div>

            <div class="control-group">
                <label for="area_id" class="control-label">Area</label>
                <div class="controls">
                    <select name="area_id[]" id="area" class="multiselect" multiple="multiple">
                        <?php if (isset($this->areas) && $this->areas): foreach ($this->areas as $id=>$name):?>
                            <option value="<?php echo $id;?>" <?php if (isset($this->params['area_id']) and (
                                         (is_array($this->params['area_id']) && in_array($id, $this->params['area_id']))
                                        || $id == $this->params['area_id']
                                    )):?> selected="selected"<?php endif;?>><?php echo $name;?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label for="province" class="control-label">Province</label>
                <div class="controls">
                    <select name="region_id[]" id="region" class="multiselect" multiple="multiple">
                        <?php if (isset($this->regions) && $this->regions): foreach ($this->regions as $id=>$name):?>
                            <option value="<?php echo $id;?>" <?php if (isset($this->params['region_id']) and (
                                         (is_array($this->params['region_id']) && in_array($id, $this->params['region_id']))
                                        || $id == $this->params['region_id']
                                    )):?> selected="selected"<?php endif;?>><?php echo $name;?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label for="district" class="control-label">District</label>
                <div class="controls">
                    <select name="district_id[]" id="district" class="multiselect" multiple="multiple">
                        <?php if (isset($this->districts) && $this->districts): foreach ($this->districts as $id=>$name):?>
                            <option value="<?php echo $id;?>" <?php if (isset($this->params['district_id']) and (
                                         (is_array($this->params['district_id']) && in_array($id, $this->params['district_id']))
                                        || $id == $this->params['district_id']
                                    )):?> selected="selected"<?php endif;?>><?php echo $name;?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>
        </div>

        <div class="span3">
            <div class="control-group">
                <label for="d_id" class="control-label">Retailer Name</label>
                <div class="controls">
                    <input type='text' name='SearchBox' id="SearchBox" placeholder="Search" autocomplete="off" />
                    <select name="d_id" id="d_id" size="5">
                        <option value=>Choose</option>
                        <?php if (isset($this->distributors) && $this->distributors): foreach ($this->distributors as $id=>$name):?>
                            <option value="<?php echo $id;?>" <?php if (isset($this->params['d_id']) and $id==$this->params['d_id']):?> selected="selected"<?php endif;?>><?php echo $name;?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="from">Created From</label>
                <div class="controls">
                    <input type="text" name="from" id="from" class="date" value="<?php if(isset($this->params['from'])) echo $this->params['from'] ?>" />
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="to">Created To</label>
                <div class="controls">
                    <input type="text" name="to" id="to" class="date" value="<?php if(isset($this->params['to'])) echo $this->params['to'] ?>" />
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="status">Status</label>
                <div class="controls">
                    <select name="status" id="status">
                        <option value>All</option>
                        <?php foreach (My_Delivery_Order_Status::$name as $_id => $_name): ?>
                            <option value="<?php echo $_id ?>"
                                <?php if(isset($this->params['status']) && $this->params['status'] == $_id) echo "selected" ?> 
                                ><?php echo $_name ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
    <button type="submit" name="export" value="1" class="btn btn-success">Export</button>
</form>

<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>

<script>
options = {
    selectAllText: 'Select All',
    includeSelectAllOption: true,
    includeSelectAllIfMoreThan: 3,
    disableIfEmpty: true
};

function multi() {
    $('.multiselect').multiselect(options);
}

$(document).ready(function () {
    multi();

    $('.delivery_type').change(show_delivery_type);

    initSearchOptionDistributor('d_id', 'SearchBox');

    $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

    $('#area').change(function(){
        $('.loading').remove();

        $(this).next('.btn-group').append('<span class="loading"></span>');
        var _self = $(this);
        var area_id = $(this).val();
        $('#region').find('option').remove();
        $('#district').find('option').remove();

        $.get("<?php echo HOST ?>get/province-v2",
            {area_id: area_id}
            ,function(data,status){
               for (i in data)
                    $('#region').append('<option value="'+i+'">'+data[i]+'</option>');

                $('#district, #region').multiselect("destroy").multiselect(options);
                $('.loading').remove();
            });
    });

    $('#region').change(function(){
        $('.loading').remove();
        $(this).next('.btn-group').append('<span class="loading"></span>');
        var _self = $(this);
        var region = _self.val();

        $('#district').find('option').remove();

        $.get("/get/district-v2",
            {province_id: region}
            ,function(data,status){
                for (i in data)
                    $('#district').append('<option value="'+i+'">'+data[i]+'</option>');

                $('#district').multiselect("destroy").multiselect(options);
                $('.loading').remove();
            });
    });

});

function show_delivery_type(e) {
    _self = $(e.target);
    type = _self.val();
    $('[data-type*=]').prop('disabled', true).val('').hide().find("select").val('');
    $('[data-type="'+type+'"]').show().prop('disabled', false);

    try { initSearchOption(); } catch(err) {}
}

function initSearchOption(){
    var timeout;
    $("#SearchBoxStaff").on("keyup", function () {
        var userInput = $("#SearchBoxStaff").val();
        window.clearTimeout(timeout);
        timeout = window.setTimeout(function() {
            showOnlyOptionsSimilarToText($("#staff_id"), userInput, true);
        }, 500);

    });
}
</script>