<table class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(

                    'Action'
                ),
                $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php
        if (isset($this->POs) and $this->POs)
            foreach ($this->POs as $k=>$PO): ?>
        <tr>
           
        </tr>
        <?php endforeach;?>

    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>