<form class="form-search form-horizontal" method="get">
    <div class="row">
        <div class="span5">

            <div class="control-group">
                <label for="imei_sn" class="span2">IMEI</label>
                <input id="imei_sn" name="imei_sn" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['imei_sn']) and printf($this->params['imei_sn']);?>">
            </div>

            <div class="control-group">
                <label for="sales_sn" class="span2">Sales SN</label>
                <input id="sales_sn" name="sales_sn" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['sales_sn']) and printf($this->params['sales_sn']);?>">
            </div>

            <div class="control-group">
                <label for="status" class="span2">Status</label>
                <select name="status" id="status">
                    <option value="-1">Select</option>
                    <option value="0" <?php if (isset($this->params['status']) and $this->params['status']== 0) {?>selected="selected" <?php }?>>Pending</option>
                    <option value="1" <?php if (isset($this->params['status']) and $this->params['status']== 1) {?>selected="selected" <?php }?>>Approved</option>
                </select>
            </div>

        </div>

        <div class="span5">
            <div class="control-group">
                <label for="joint_circular_id" class="span2">Joint Circular</label>
                <select name="joint_circular_id" id="joint_circular_id">
                    <option value="">Select</option>
                    <?php foreach ( $this->jointCircularCached as $id=>$name ) {?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['joint_circular_id']) and $this->params['joint_circular_id'] == $id) {?> selected="selected" <?php }?>><?php echo $name;?></option>
                    <?php } ?>
                </select>
            </div>



            <div class="control-group">
                <label for="good_id" class="span4">Product<span style="color: red">*</span>
                    <input type='text' class="span4" name='SearchGoodId' id="SearchGoodId" placeholder="Search" autocomplete="off" />
                    <select name="good_id" class="span4" id="good_id" size="5">
                        <option value="">Please select</option>
                        <?php foreach ( $this->products as $item ) {?>
                            <option value="<?php echo $item['id'];?>" <?php if (isset($this->params['product_id']) and $this->params['product_id'] == $item['id']) {?> selected="selected" <?php }?>><?php echo $item['good_name'];?></option>
                        <?php } ?>
                    </select>
                </label>

            </div>

            <div class="control-group">
                <label class="span4" >Retailer name <span style="color: red">*</span>
                    <input type='text' class="span4" name='SearchBox' id="SearchBox" placeholder="Search" autocomplete="off" />
                    <!-- <select name="d_id" class="span4" id="distributor_id" size="5">
                        <option value="">Please select</option>
                        <?php if (isset($this->distributorsCached)): ?>

                            <?php //foreach ( $this->distributorsCached as $id=>$name ): ?>
                                <option value="<?php echo $id;?>" <?php if (isset($this->params['d_id']) and $this->params['d_id'] == $id) {?> selected="selected" <?php }?>><?php echo $name;?></option>
                            <?php //endforeach; ?>

                        <?php endif; ?>
                    </select> -->

                    <select name="d_id" class="span4" id="distributor_id" size="5">
                        <option value="">Please select</option>
                        <?php if (isset($this->distributorsCached) and isset($this->params['d_id']) and $this->params['d_id'] and isset($this->distributorsCached[$this->params['d_id']])): ?>
                        <option value="<?=$this->params['d_id'];?>" selected="selected"><?=$this->distributorsCached[$this->params['d_id']];?></option>
                        <?php endif; ?>
                    </select>

                </label>
            </div>

        </div>

    </div>
   
	<div class="row">
        <div class="span5">
   	        <button type="submit" class="btn btn-primary">Search</button>
   	        <button type="submit" name="approve" value="1" class="btn btn-success">Approve</button>
 		    <button type="reset" class="btn btn-warning">Reset</button>
            <button type="submit" name="export" value="1" class="btn btn-success">Export</button>
       	</div>
    </div>
   
</form>

<script>
$(document).ready(function () {

    $("*").keypress(function(event){  
         if(event.keyCode==13){  
            return false;  
         }  
    });

    var timeOut;

    $('#SearchBox').live('keyup', function(event) {
        var text = $(this).val();

        if(text.length <= 3){
            return false;
        }

        if(event.keyCode==13){  
            getDataTimeout(text,'bypass');
         }else{
            getDataTimeout(text);
         }

    });


    function getDataTimeout(text,bypass){
        clearTimeOut();

        if(bypass == 'bypass'){

            $('#distributor_id').empty();
            $('#distributor_id').append('<option value="">Please select</option>');

            $.ajax({
                url: '/tool/list-distributor-new',
                type: 'POST',
                data: {text: text},
            })
           .done(function(response) {

            var obj_response = jQuery.parseJSON(response);

                $.each( obj_response, function( key, value ) {
                    $('#distributor_id').append('<option value="'+value.id+'">['+value.store_code+'] '+value.title+' ('+value.id+')</option>');
                });
                $('#distributor_id').trigger('change');
               console.log("success");
           });

        }else{

            timeOut = setTimeout(function() {

                $('#distributor_id').empty();
                $('#distributor_id').append('<option value="">Please select</option>');

                $.ajax({
                    url: '/tool/list-distributor-new',
                    type: 'POST',
                    data: {text: text},
                })
               .done(function(response) {

                    var obj_response = jQuery.parseJSON(response);

                    $.each( obj_response, function( key, value ) {
                        $('#distributor_id').append('<option value="'+value.id+'">['+value.store_code+'] '+value.title+' ('+value.id+')</option>');
                    });
                    $('#distributor_id').trigger('change');
                   console.log("success");
                });

            }, 3000);

        }
        
    }

    function clearTimeOut(){
        clearTimeout(timeOut);
    }
    // initSearchOptionDistributor('good_id', 'SearchGoodId');
})
</script>