<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>
<style> 
.tabs2 {
  display: flex;
  flex-wrap: wrap; // make sure it wraps
}
.tabs2 label {
  order: 1; // Put the labels first
  display: block;
  padding: 1rem 2rem;
  margin-right: 0.2rem;
  cursor: pointer;
  background: #a9a9a9;
  font-weight: bold;
  transition: background ease 0.2s;
}
.tabs2 .tab2 {
  order: 99; // Put the tabs2 last
  flex-grow: 1;
  width: 100%;
  display: none;
  padding: 1rem;
  background: #fff;
}
.tabs2 input[type="radio"] {
  display: none;
}
.tabs2 input[type="radio"]:checked + label {
  background: #fff;
}
.tabs2 input[type="radio"]:checked + label + .tab2 {
  display: block;
}

@media (max-width: 45em) {
  .tabs2 .tab2,
  .tabs2 label {
    order: initial;
  }
  .tabs2 label {
    width: 100%;
    margin-right: 0;
    margin-top: 0.2rem;
  }
}

.tabset > input[type="radio"] {
  position: absolute;
}

.tabset .tab-panel {
  display: none;
}

.tabset > input:first-child:checked ~ .tab-panels > .tab-panel:first-child,
.tabset > input:nth-child(3):checked ~ .tab-panels > .tab-panel:nth-child(2),
.tabset > input:nth-child(5):checked ~ .tab-panels > .tab-panel:nth-child(3),
.tabset > input:nth-child(7):checked ~ .tab-panels > .tab-panel:nth-child(4),
.tabset > input:nth-child(9):checked ~ .tab-panels > .tab-panel:nth-child(5),
.tabset > input:nth-child(11):checked ~ .tab-panels > .tab-panel:nth-child(6) {
  display: block;
}


.tabset > label {
  position: relative;
  display: inline-block;
  border: 1px solid transparent;
  cursor: pointer;
  font-weight: 600;
}

.tabset > label::after {
  content: "";
  position: absolute;
  background: #8d8d8d;
}

.tabset > label:hover,
.tabset > input:focus + label {
  color: #fd0;
}

.tabset > label:hover::after,
.tabset > input:focus + label::after,
.tabset > input:checked + label::after {
  background: #06c;
}

.tabset > input:checked + label {
  border-color: #ccc;

}
</style>
<?php
$userStorage = Zend_Auth::getInstance()->getStorage()->read();
    $user_id = $userStorage->id;
    ?>
<div class="page-header">
    <h1>Dashboard</h1>
</div>
<?php
if (isset($this->markets_sn_wh) and $this->markets_sn_wh) :
    foreach ($this->markets_sn_wh as $k=>$m):
      if($m['total_qulity'] > 0){ $qulity = $m['total_qulity']; }else{ $qulity = "0"; }
      $qulitys[] = $qulity;
      if (isset($this->warehouses_cached[$m['warehouse_name']])) 
      $warehouse = $this->warehouses_cached[$m['warehouse_name']];
      $warehouses[] = $warehouse;
    endforeach;
endif;
?>

<?php if($this->tabsets == 'tabday'){ 
  $myChart = "myChart";
  $myChartDis = "myChartDis";
  $myChartWH = "myChartWH";
  $title = "ຕາມວັນ";
}else if($this->tabsets == 'tabweek'){ 
  $myChart = "myChart2";
  $myChartDis = "myChartDis2";
  $myChartWH = "myChartWH2";
  $title = "ຕາມອາທິດ";
}else if($this->tabsets == 'tabmonth'){
  $myChart = "myChart3";
  $myChartDis = "myChartDis3";
  $myChartWH = "myChartWH3";
  $title = "ຕາມເດືອນ";
}else{ 
  $myChart = "myChart";
  $myChartDis = "myChartDis";
  $myChartWH = "myChartWH";
  $title = "ຕາມວັນ";
} ?>

<div class="tabs2">

  <input type="radio" name="tabs2" id="tabone" checked="checked">
  <label for="tabone">Dealers <?php echo $this->group_id; ?></label>
  <div class="tab2">
      <?php
        if (isset($this->markets_sn_dealer) and $this->markets_sn_dealer) :
            foreach ($this->markets_sn_dealer as $k=>$m): 
                  if($m['total_qulity'] > 0){ $qulity = $m['total_qulity']; }else{ $qulity = "0"; }
                  $qulitys_dis[] = $qulity;
                  $distributor[] = $m['distributors_name'];
        endforeach;
      endif; ?>
    <?php if ($this->group_id == '106' or $this->group_id == '98,108,96' or $this->group_id == '7'){?>
    <form name='theForm' method="GET" action="/index" id='theForm'>
        <div class="row-fluid">
          <div class="tabset">
          <!-- Tab 1 -->
          <input type="radio" name="tabset" value="tabday" id="tab1" aria-controls="marzen2" onChange="autoSubmit();" <?php if ($this->tabsets == 'tabday') { ?>checked='checked' <?php }else{ ?> checked='checked' <?php } ?>>
          <label for="tab1">Day</label>
          <!-- Tab 2 -->
          <input type="radio" name="tabset" value="tabweek" id="tab2" onChange="autoSubmit();" aria-controls="rauchbier2" <?php if ($this->tabsets == 'tabweek') { ?>checked='checked' <?php } ?>>
          <label for="tab2">Week</label>
          <!-- Tab 3 -->
          <input type="radio" name="tabset" value="tabmonth" id="tab3" onChange="autoSubmit();" aria-controls="dunkles2" <?php if ($this->tabsets == 'tabmonth') { ?>checked='checked' <?php } ?>>
          <label for="tab3">Month</label>
          
          <div class="tab-panels">
            <section id="marzen2" class="tab-panel">
              <h2 style="font-family: Phetsarath OT; padding-left: 50px;">ລາຍງານສັ່ງເຄື່ອງຂອງຮ້ານ Dealer (<?php echo $title; ?>)</h2>
              <canvas id="myChartDis"></canvas>
            </section>
            <section id="rauchbier2" class="tab-panel">
              <h2 style="font-family: Phetsarath OT; padding-left: 50px;">ລາຍງານສັ່ງເຄື່ອງຂອງຮ້ານ Dealer (<?php echo $title; ?>)</h2>
              <canvas id="myChartDis2"></canvas>
            </section>
            <section id="dunkles2" class="tab-panel">
              <h2 style="font-family: Phetsarath OT; padding-left: 50px;">ລາຍງານສັ່ງເຄື່ອງຂອງຮ້ານ Dealer (<?php echo $title; ?>)</h2>
              <canvas id="myChartDis3"></canvas>
            </section>
          </div>
        </div>
      </form>
      </div>
      <?php } ?>
  </div>


  <input type="radio" name="tabs2" id="tabtwo">
  <label for="tabtwo">Kerrys</label>
  <div class="tab2">
    <?php if ($this->group_id == '106' or $this->group_id == '107,108' or $this->group_id == '95' or $this->group_id == '7'){?>
      <form name='theForm' method="GET" action="/index" id='theForm'>
        <div class="row-fluid">
          <div class="tabset">
          <!-- Tab 1 -->
          <input type="radio" name="tabset" value="tabday" id="tab1" aria-controls="marzen" onChange="autoSubmit();" <?php if ($this->tabsets == 'tabday') { ?>checked='checked' <?php }else{ ?> checked='checked' <?php } ?>>
          <label for="tab1">Day</label>
          <!-- Tab 2 -->
          <input type="radio" name="tabset" value="tabweek" id="tab2" onChange="autoSubmit();" aria-controls="rauchbier" <?php if ($this->tabsets == 'tabweek') { ?>checked='checked' <?php } ?>>
          <label for="tab2">Week</label>
          <!-- Tab 3 -->
          <input type="radio" name="tabset" value="tabmonth" id="tab3" onChange="autoSubmit();" aria-controls="dunkles" <?php if ($this->tabsets == 'tabmonth') { ?>checked='checked' <?php } ?>>
          <label for="tab3">Month</label>
          
          <div class="tab-panels">
            <section id="marzen" class="tab-panel">
              <h2 style="font-family: Phetsarath OT; padding-left: 50px;">ລາຍງານສັ່ງເຄື່ອງຈາກສາງຕົວແທນ (<?php echo $title; ?>)</h2>
              <canvas id="myChart"></canvas>
            </section>
            <section id="rauchbier" class="tab-panel">
              <h2 style="font-family: Phetsarath OT; padding-left: 50px;">ລາຍງານສັ່ງເຄື່ອງຈາກສາງຕົວແທນ (<?php echo $title; ?>)</h2>
              <canvas id="myChart2"></canvas>
            </section>
            <section id="dunkles" class="tab-panel">
              <h2 style="font-family: Phetsarath OT; padding-left: 50px;">ລາຍງານສັ່ງເຄື່ອງຈາກສາງຕົວແທນ (<?php echo $title; ?>)</h2>
              <canvas id="myChart3"></canvas>
            </section>
          </div>
        </div>
      </div>
    </form>
      <?php } ?>
    </div>




<?php if ($user_id == '717' or $user_id == '1'){?>
  <input type="radio" name="tabs2" id="tabthree">
  <label for="tabthree">WH-OPPO</label>
  <div class="tab2">
    <h2 style="font-family: Phetsarath OT; padding-left: 50px;">ລາຍງານສັ່ງເຄື່ອງຂອງສາງ OPPO (<?php echo $title; ?>)</h2>
        <?php
        if (isset($this->markets_sn) and $this->markets_sn) :
            foreach ($this->markets_sn as $k=>$m): 
              if($m['sum_total'] > 0){ $qulity = $m['sum_total']; }else{ $qulity = "0"; }
                  $qulitys_wh[] = $qulity;
                  $invoice_time[] = $m['invoice_time'];
         endforeach; endif; ?>

      <canvas id="<?php echo $myChartWH; ?>"></canvas>
    </div>
    <?php } ?>
</div>
</div>
<script>
function autoSubmit()
{
    var formObject = document.forms['theForm'];
    formObject.submit();
}
</script>

<br>
<br><br>
<?php if ($this->group_id == '106' or $this->group_id == '107,108' or $this->group_id == '95' or $this->group_id == '7'){?>
<script>
(function ($) {
 "use strict";
  var ctx = document.getElementById(<?php echo json_encode($myChart);?>);
  var myChart  = new Chart(ctx, {
    type: 'bar',
    backgroundColor: ['#000'],
    data: {
      labels: <?php echo json_encode($warehouses); ?>,
      datasets: [{
        data: <?php echo json_encode($qulitys); ?>,
        label: ['ຍອດຂາຍເຄື່ອງຂອງສາງຕົວແທນ'],
        backgroundColor: [
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
        ],
        borderColor: [
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
        ],
        borderWidth: 1
      }]
    },
    options: {
      legend: {
          display: true,
          position: 'bottom',
     },
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero:true
          }
        }]
      }
    }
  });   
})(jQuery);
</script>
<?php } ?>
 <?php if ($this->group_id == '106' or $this->group_id == '98,108,96' or $this->group_id == '7'){?>
  <script>
(function ($) {
 "use strict";
  var ctx = document.getElementById(<?php echo json_encode($myChartDis);?>);
  var myChart  = new Chart(ctx, {
    type: 'horizontalBar',
    backgroundColor: ['#000'],
    data: {
      labels: <?php echo json_encode($distributor); ?>,
      datasets: [{
        data: <?php echo json_encode($qulitys_dis); ?>,
        label: ['ຍອດສັ່ງເຄື່ອງຂອງຕົວແທນ'],
        backgroundColor: [
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
                'rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)','rgba(243, 156, 18, 0.6)',
        ],
        borderColor: [
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
                'rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)','rgba(222, 156, 18 , 1)',
        ],
        borderWidth: 1
      }]
    },
    options: {
      legend: {
          display: true,
          position: 'bottom',
     },
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero:true
          }
        }]
      }
    }
  });   
})(jQuery);
</script>
<?php } ?>
<script> 
(function ($) {
 "use strict";
  var ctx = document.getElementById(<?php echo json_encode($myChartWH);?>);
  var myChart  = new Chart(ctx, {
    type: 'line',
    backgroundColor: ['#000'],
    data: {
      labels: <?php echo json_encode($invoice_time); ?>,
      datasets: [{
        data: <?php echo json_encode($qulitys_wh); ?>,
        label: ['ຍອດສັ່ງເຄື່ອງຈາກສາງ Realme'],
        borderColor: "#ee9800",
        backgroundColor: "#787878",
        fill: false,
      }]
    },
    options: {
      legend: {
          display: true,
          position: 'bottom',
     },
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero:true
          }
        }]
      }
    }
  });   
})(jQuery);

(function ($) {
    $.fn.countTo = function (options) {
        options = options || {};
        
        return $(this).each(function () {
            // set options for current element
            var settings = $.extend({}, $.fn.countTo.defaults, {
                from:            $(this).data('from'),
                to:              $(this).data('to'),
                speed:           $(this).data('speed'),
                refreshInterval: $(this).data('refresh-interval'),
                decimals:        $(this).data('decimals')
            }, options);
            
            // how many times to update the value, and how much to increment the value on each update
            var loops = Math.ceil(settings.speed / settings.refreshInterval),
                increment = (settings.to - settings.from) / loops;
            
            // references & variables that will change with each update
            var self = this,
                $self = $(this),
                loopCount = 0,
                value = settings.from,
                data = $self.data('countTo') || {};
            
            $self.data('countTo', data);
            
            // if an existing interval can be found, clear it first
            if (data.interval) {
                clearInterval(data.interval);
            }
            data.interval = setInterval(updateTimer, settings.refreshInterval);
            
            // initialize the element with the starting value
            render(value);
            
            function updateTimer() {
                value += increment;
                loopCount++;
                
                render(value);
                
                if (typeof(settings.onUpdate) == 'function') {
                    settings.onUpdate.call(self, value);
                }
                
                if (loopCount >= loops) {
                    // remove the interval
                    $self.removeData('countTo');
                    clearInterval(data.interval);
                    value = settings.to;
                    
                    if (typeof(settings.onComplete) == 'function') {
                        settings.onComplete.call(self, value);
                    }
                }
            }
            
            function render(value) {
                var formattedValue = settings.formatter.call(self, value, settings);
                $self.html(formattedValue);
            }
        });
    };
    
    $.fn.countTo.defaults = {
        from: 0,               // the number the element should start at
        to: 0,                 // the number the element should end at
        speed: 1000,           // how long it should take to count between the target numbers
        refreshInterval: 100,  // how often the element should be updated
        decimals: 0,           // the number of decimal places to show
        formatter: formatter,  // handler for formatting the value before rendering
        onUpdate: null,        // callback method for every time the element is updated
        onComplete: null       // callback method for when the element finishes updating
    };
    
    function formatter(value, settings) {
        return value.toFixed(settings.decimals);
    }
}(jQuery));

jQuery(function ($) {
  // custom formatting example
  $('.count-number').data('countToOptions', {
    formatter: function (value, options) {
      return value.toFixed(options.decimals).replace(/\B(?=(?:\d{3})+(?!\d))/g, ',');
    }
  });
  
  // start all the timers
  $('.timer').each(count);  
  
  function count(options) {
    var $this = $(this);
    options = $.extend({}, options || {}, $this.data('countToOptions') || {});
    $this.countTo(options);
  }
});
</script>
