<link href="../css/select2.css" rel="stylesheet"/>
<script src="../js/select2.js"></script>
<form id="form" name="form" class="form-search form-horizontal" action="<?php echo HOST ?>product/discount">
    <div class="row">
        <div class="span10">
            <div class="control-group">
                <label class="control-label" for="good_id">Product Name</label>
                <div class="controls">
                    <select name="good_id" id="good_id" class="span3">
                        <option value>Chooose Option</option>
                        <?php if (isset($this->goods) && $this->goods): ?>
                            <?php foreach ($this->goods as $key => $value): ?>
                                <option value="<?php echo $key ?>"
                                    <?php if(isset($this->params['good_id']) && $this->params['good_id'] == $key) echo "selected" ?>><?php echo $value ?></option>
                            <?php endforeach ?>
                        <?php endif ?>
                    </select>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="span10">
            <div class="controls">
                <button type="submit" class="btn btn-primary">Search</button>
                <button type="reset" class="btn btn-warning">Reset</button>
            </div>
        </div>
    </div>
</form>

<script>
        $(document).ready(function() { $("#good_id").select2(); });
    </script>