<form class="form-search form-horizontal" method="get" action="/checkmoney/list">
    <div class="row">
        <div class="span5">
                
			  <div class="control-group">
             <label class="span2" for="rank">ประเภทร้านค้า<span style="color: red">*</span>
                
                    <select id="rank" name="rank" class="rank span3">
                        <option value="">---</option>
                        <option value="1" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==1 ) { ?> selected<?php }?>>1. ORG-WDS(1)</option>
                        <option value="2" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==2 ) { ?> selected<?php }?>>2. ORG(2)</option>
                        <option value="5" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==5 ) { ?> selected<?php }?>>3. ORG-Dtac/Advice(5)</option>
                        <option value="6" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==6 ) { ?> selected<?php }?>>4. ORG-Lotus/Power by(6)</option>
                        <option value="7" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==7 ) { ?> selected<?php }?>>5. Dealer(7)</option>
                        <option value="8" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==8 ) { ?> selected<?php }?>>6. HUB(8)</option>
                        <option value="9" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==9 ) { ?> selected<?php }?>>7. Laos(9)</option>
                        <option value="3" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==3 ) { ?> selected<?php }?>>8. Online and Staff(3)</option>
                        <option value="10" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==10 ) { ?> selected<?php }?>>9. Brand Shop/Service(10)</option>
                      	<option value="11" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==11 ) { ?> selected<?php }?>>10. King Power(11)</option>
                        <option value="12" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==12 ) { ?> selected<?php }?>>11. Jaymart(12)</option>
                        <option value="13" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==13 ) { ?> selected<?php }?>>12. Brand Shop By Dealer(13)</option>
                        <option value="14" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==14 ) { ?> selected<?php }?>>13. KR Dealer(14)</option> 
                        <option value="15" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==15 ) { ?> selected<?php }?>>14. TRUE(15)</option> 
                    </select>
                </label>
             </div>       
                
        <div class="retailer_name_list"></div> 
            <div class="control-group">
                <label   class="span2">Bank:
				<select name='bank[]' multiple id='bank_id' >
					<?php 
						if( isset( $this->banks ) AND $this->banks    ):
							foreach(  $this->banks as $item   ):
								$selected = '';
                                if(count($this->params['bank'])){
                                    if( in_array($item['id'],$this->params['bank']) ){
                                        $selected = 'selected="selected"';
                                    }
                                }
								echo "<option value='".$item['id']."' $selected>".$item['name']."</option>";
							endforeach;
						endif;
					?>
				</select>
				</label>
            </div><!-- End bank -->
			
     
            
            <div class="control-group">
                <label for="" class="span2">Bank serial:
					<input type='text' name='bank_serial' value='<?php if(isset($this->params['bank_serial']) && $this->params['bank_serial'] ) echo $this->params['bank_serial']; ?>'> 
				</label>
            </div>
            
            <div class="control-group">
                <label for="" class="span2">Bank transaction code:
					<input type='text' name='bank_transaction_code' value='<?php if(isset($this->params['bank_transaction_code']) && $this->params['bank_transaction_code'] ) echo $this->params['bank_transaction_code']; ?>'> 
				</label>
            </div> 
             
        </div><!--  End span -->
        <div class="span5">
			<div class="control-group">
				<label class="span2">SN: </label>
				<input type="text" name='sn' value="<?php (	isset($this->params['sn'])) ? printf($this->params['sn']) : '';?>" />
			</div>		

			<div class="control-group">
				<label class="span2">Invoice Number: </label>
				<input type="text" name='invoice_number' value="<?php (	isset($this->params['invoice_number'])) ? printf($this->params['invoice_number']) : '';?>" />
			</div>

			<div class="control-group">
				<label class="span2">Finance Group: </label>

				<select name="finance_group" id="finance_group">
					<option value="">All</option>
					<?php
					foreach ($this->finance_group as $key) {
						echo '<option value="'.trim($key['finance_group']).'">'.$key['finance_group'].'</option>';
					}
					?>
				</select>

			</div>

			<div class="control-group">
                <label for="cancel" class="span2">Cancel or Not</label>
                <select name="cancel" id="cancel">
                    <option value="">Choose</option>
                    <option value="0" <?php if (isset($this->params['cancel']) and $this->params['cancel']=='0'):?> selected<?php endif;?>>Not Cancel</option>
                    <option value="1" <?php if (isset($this->params['cancel']) and $this->params['cancel']=='1'):?> selected<?php endif;?>>Canceled</option>
                </select>
            </div>
			
			<div class="control-group">
				<label class="span2">Type: </label>
				<?php 
					$arr_type_time = array(
						'' => 'All',
						'1'=> 'In',
						'2'=> 'Out',
						'3'=> 'Transaction creation time'
					);
				?>
				<select name='type_time'>
					<?php 
						foreach($arr_type_time as $key => $value){
							$selected = '';
							if( isset($this->params['type_time']) AND $this->params['type_time'] == $key ){
								if($this->params['type_time'] == $key){
									$selected = 'selected="selected"';
								}
							}
							echo '<option value="'.$key.'"' .$selected.'>'.$value.'</option>';
						}
					?>
				</select>

			</div>

			<div class="control-group">
				<label   class="span2">From collection time: </label>
				<input type='text' id="from_collection_time" name='from_collection_time' value="<?php (	isset($this->params['from_collection_time']) AND $this->params['from_collection_time']	) ? printf($this->params['from_collection_time']) : '';?>" class='datepicker'/>
			</div>
			
			<div class="control-group">
				<label   class="span2">To collection time: </label>
				<input type='text' id="to_collection_time" name='to_collection_time' value="<?php ( isset($this->params['to_collection_time']) AND $this->params['to_collection_time']	) ? printf($this->params['to_collection_time']) : '';?>" class='datepicker'/>
			</div>

			<div class="control-group">
				<label   class="span2">From invoice time: </label>
				<input type='text' id="from_invoice_time" name='from_invoice_time' value="<?php (	isset($this->params['from_invoice_time']) AND $this->params['from_invoice_time']	) ? printf($this->params['from_invoice_time']) : '';?>" class='datepicker'/>
			</div>
			
			<div class="control-group">
				<label   class="span2">To invoice time: </label>
				<input type='text' id="to_invoice_time" name='to_invoice_time' value="<?php ( isset($this->params['to_invoice_time']) AND $this->params['to_invoice_time']	) ? printf($this->params['to_invoice_time']) : '';?>" class='datepicker'/>
			</div>
			
			<div class="control-group">
				<label  class="span2">Type money: </label>
				<?php
                $arr_type_money = unserialize(MONEY_TYPE);
				?>
				<select name='type_money'>
                    <option value="">All</option>
					<?php 
						foreach($arr_type_money as $key => $value){
							$selected = '';
							if( isset($this->params['type_money']) AND $this->params['type_money'] == $key){
								$selected = 'selected="selected"';
							}
							echo '<option value="'.$key.'"' .$selected.'>'.$value.'</option>';
						}
					?>
				</select>
			</div>
			
			<div class="control-group hide">
				<label  class="span2">From money: </label>
				<input type='text' name='from_money' value="<?php (	isset($this->params['from_money'])) ? printf($this->params['from_money']) : '';?>" />
			</div>
			
			<div class="control-group hide">
				<label for="created_by" class="span2">To money: </label>
				<input type='text' name='to_money' value="<?php ( isset($this->params['to_money']) ) ? printf($this->params['to_money']) : '';?>" />
			</div>
			
       
		<div class="control-group">
			<label   class="span2">Note: </label>
			<textarea name='note'><?php (   isset($this->params['note']) AND $this->params['note']  ) ? printf($this->params['note']) : '';?></textarea>
		</div>

		<div class="control-group">
			<label   class="span2">Content: </label>
			<textarea name='content'><?php (   isset($this->params['content']) AND $this->params['content']  ) ? printf($this->params['content']) : '';?></textarea>
		</div>
		
       </div><!-- End span5 -->
    </div>
   
	<div class="row">
        <div class="span12">
   			<button type="submit" class="btn btn-primary">Search</button>
		    <!-- <button type="reset" class="btn btn-warning">Reset</button> -->
		    <!-- <button type="submit" name="export" value="1" class="btn btn-success">Export</button> -->
            <!-- <button type="submit" name="export_retailer" value="1" class="btn btn-success">Export By Retailer</button> -->
            <!-- <button type="submit" name="oppo" value="1" class="btn btn-success">Export oppo</button>  -->
            <button type="submit" name="export" value="2" class="btn btn-success export">Export Cash Collection</button>
            <button type="submit" name="export" value="3" class="btn btn-success export">Daily Cash In View</button>
            <button type="submit" name="export" value="4" class="btn btn-success export">Daily Cash In For Bank Check</button>
            <button type="submit" name="export" value="5" class="btn btn-success export">Export Cash Collection For Service / Brand Shop</button>
        </div>
    </div>
   
</form>

<script type="text/javascript">

    $(document).ready(function () {

    	

    	$("form").submit(function(){

    		var condition1 = $('#sn').val();
            var condition2 = $('#invoice_number').val();

            if(condition1 != '' || condition2 != ''){
                return true;
            }

            var check = 0;

            var params1 = $('#from_collection_time').val();
            var params2 = $('#to_collection_time').val();
            var params3 = $('#from_invoice_time').val();
            var params4 = $('#to_invoice_time').val();

            if(params1 != '' && params2 != ''){
                check++;
            }

            if(params3 != '' && params4 != ''){
                check++;
            }

            if(check == 0){
                alert('กรุณาระบุวันที่ต้องการจะที่จะค้นหา');
                return false;
            }

        });

		<?php if(isset($this->params['finance_group']) && $this->params['finance_group']){?>
			$('#finance_group').val('<?php echo $this->params['finance_group'];?>');
		<?php } ?>

		<?php if(isset($this->rank)) { ?>
	        $('#rank').val(<?= $this->rank ?>);
	        get_distributor_cached_for_search(<?= $this->rank ?>);
	    <?php }?>

	    $('.rank').change(function(event) {
	        get_distributor_cached_for_search($(this).val());
	      });

	    function get_distributor_cached_for_search(rank_id){

	        var rank_id = rank_id;
	              $.ajax({
	                  url: '<?php echo HOST ?>get/distributor-cached-for-search',
	                  type: 'POST',
	                  dataType: 'html',
	                  data: {rank_id: rank_id},
	              })
	              .done(function(data) {
	                  $('.retailer_name_list').empty();
	                  $('.retailer_name_list').append(data);
	                    var jets = new Jets({
	                    searchTag: '#SearchBox',
	                    contentTag: '#d_id'
	                });
	                    <?php if(isset($this->d_id)){ ?>
	                        $('#d_id').val(<?= $this->d_id ?>);
	                    <?php }?>
	                  console.log("success");
	              })
	              .fail(function() {
	                  console.log("error");
	              })
	              .always(function() {
	                  console.log("complete");
	              });
	    }

});

</script>