<table class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
                    '#',
                    'Provice',
                    'District',
                    'Fee',
                    'Additional Fee',
                    'Action'
                ),
                $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php
        if (isset($this->fees) and $this->fees)
            foreach ($this->fees as $k=>$fee): ?>
        <tr>
              <td>
                <?php
                    $inc = $this->offset + $k + 1;
                    echo $inc;
                ?>
            </td>
            <td><?php echo $fee['province_name'] ?></td>
            <td><?php echo $fee['district_name'] ?></td>
            <td><?php echo My_Number::f($fee['value']) ?></td>
            <td><?php echo My_Number::f($fee['additional_value']) ?></td>
            <td class="">
                <a title="Edit" href="/warehouse/delivery-fee-edit?id=<?php echo $fee['id'];?>"> <i class="icon-edit"></i></a>
                <a title="Delete" class="confirmLink" href="/warehouse/delivery-fee-delete?id=<?php echo $fee['id'];?>"> <i class="icon-trash"></i></a>
            </td>
        </tr>
        <?php endforeach;?>

    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<?php echo $this->load();?>
<?php echo $this->confirm();?>