<?php

function product_price($priceFloat) {
    $symbol = ' THB';
    $symbol_thousand = ',';
    $decimal_place = 2;
    $price = number_format($priceFloat, $decimal_place, '.', $symbol_thousand);
    return $price;
}

?>

<table style="margin-left: -50px;" class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
                    '#',
                    'sn'            => 'Sales Order Number',
                    'Product Category',
                    'Product',
                    'Color',
                    'num'           => 'Quantity',
                    'price'         => 'Sales Price',
                    'discount_total'         => 'Discount',
                    'price_total'         => 'Price',


                    'Invoice'       => 'Invoice',
                    'd_id'          => 'Distributor',
                    'group_name'    => 'Distributor Type Group',
                    'area'          => 'Area',
                    'region'        => 'Province',
                    'district'      => 'District',
                    'Discount',
                    'outmysql_time' => 'OUT Time',
                    'pay_time' => 'Finance Confirm',
					'Action'
                ),
                $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php
        $statuses = unserialize(DISCOUNT_STATUS);
        if (isset($this->markets) and $this->markets)
            foreach ($this->markets as $k=>$PO): 
               //print_r($PO);
            $sn_ref = $PO['sn_ref'];
             if($sn_ref==''){
                $sn_ref = $PO['sn'];
             }


             $total_price_amount = ($PO['total_price_amount']*1.07);
             $total_price = ($PO['total_price']*1.07);

                ?>
            <tr>
                <td><a href="#id" rel="<?php echo $PO['sn'] ?>" class="collapse_a btn btn-default btn-small" id="m_<?php echo $PO['sn'] ?>"><span class="col-sign">+</span><img class="img-loading" src="<?php echo HOST?>img/ajax-loader.gif" style="display: none" /></a></td>
                <td><?php echo $sn_ref;?></td>
                <td></td>
                <td></td>
                <td></td>
                <td><?php echo $PO['total_qty'];?></td>
                <td><?php echo product_price($total_price_amount); ?></td>
                <td><?php echo product_price($PO['total_discount']); ?></td>
                <td><?php echo product_price($total_price); ?></td>
                <td><?php if(isset($PO['invoice_number']))echo $PO['invoice_number'];?></td>
                <td><?php if(isset($this->distributors) && isset($this->distributors[$PO['d_id']])) echo $this->distributors[$PO['d_id']]['title'];?></td>
                
                <td><?php switch ($PO['group_type_id']) {
                    case '10':
                    echo 'Brand Shop';
                    break;
                    case '11':
                    echo 'Brand Shop By Dealer';
                    break;
                    case '12':
                    echo 'Brand Shop-ORG';
                    break;
                    case '13':
                    echo 'Brand Shop by KR Dealer';
                    break;
                    case '1':
                    echo 'Dealer and Hub';
                    break;
                    case '8':
                    echo 'Digital';
                    break;
                    case '7':
                    echo 'Export';
                    break;
                    case '3':
                    echo 'KA(ORG)';
                    break;
                    case '2':
                    echo 'KR-Dealer';
                    break;
                    case '5':
                    echo 'Online';
                    break;
                    case '4':
                    echo 'Operator';
                    break;
                    case '9':
                    echo 'Service Shop';
                    break;
                    case '6':
                    echo 'Staff';
                    break;
                    default:
                    echo '-';
                    break;
                } ?></td>

                <td><?php if (isset($PO['district'])) echo My_Region::getValue($PO['district'], My_Region::Area) ?></td>
                <td><?php if (isset($PO['district'])) echo My_Region::getValue($PO['district'], My_Region::Province) ?></td>
                <td><?php if (isset($PO['district'])) echo My_Region::getValue($PO['district'], My_Region::District) ?></td>
                <td><?php echo ( isset($statuses[ $PO['discount'] ]) ? $statuses[ $PO['discount'] ] : '' ); ?></td> 
                <td><?php echo $PO['outmysql_time'];?></td>
                <td><?php echo $PO['pay_time'];?></td>
                <td class="">
                    <a style="display:none;"> href="<?php echo HOST ?>warehouse/product-out-print?sn=<?php echo $PO['sn'];?>&inv_sn=<?php echo $PO['invoice_number'];?>" class="btn <?php if(isset($PO['print_time']) && $PO['print_time']) echo 'btn-info'; else echo 'btn-default'; ?> btn-small" target="_blank"><?php if(isset($PO['print_time']) && $PO['print_time']) echo $PO['print_time']; else echo "Print" ?></a>
                    <!-- print invoice -->
                    <div class="btn-group">
                        <a class="btn dropdown-toggle btn-warning" data-toggle="dropdown" href="#">
                            Print Invoice
                            <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu3">

                            <?php

                            //1=Dealer and Hub,2=KR-Dealer,6=Staff,11=OPPO Brand Shop By Dealer,13=Brand Shop by KR Dealer
                            if(isset($PO['group_type_id']) && in_array($PO['group_type_id'], ['1','2','6','11','13'])){
                            ?>
                                <li role="presentation"><a role="menuitem" tabindex="-1" target="_blank" href="<?php echo HOST ?>warehouse/print-invoice-new?sn=<?php echo $PO['sn'];?>&inv_sn=<?php echo $PO['invoice_number'];?>">Invoice (A4)</a>
                                </li>
                            <?php }else{ ?>
                                <li role="presentation"><a role="menuitem" tabindex="-1" target="_blank" href="<?php echo HOST ?>warehouse/invoice?sn=<?php echo $PO['sn'];?>&inv_sn=<?php echo $PO['invoice_number'];?>">Invoice (DOT)</a>
                                </li>
                            <?php } ?>
                              <!-- <li role="presentation"><a role="menuitem" tabindex="-1" class="invoice_etax" data_sn="<?php echo $PO['sn'];?>" target="_blank" href="">Invoice A4</a>
                              </li> -->
                              <li role="presentation"><a role="menuitem" tabindex="-1" target="_blank" href="<?php echo HOST ?>warehouse/invoice?sn=<?php echo $PO['sn'];?>&inv_sn=<?php echo $PO['invoice_number'];?>&show_imei=1">Invoice Show Imei</a>
                              </li>
                              <!-- <li role="presentation"><a role="menuitem" tabindex="-1" target="_blank" href="<?php echo HOST ?>sales/print-sale?sn=<?php echo $PO['sn'];?>&inv_sn=<?php echo $PO['invoice_number'];?>">ใบจองสินค้า</a> -->
                              </li>
                        </ul>
                    </div>

                    <!-- print invoice -->
                </td>
            </tr>

        <?php endforeach;?>

    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<?php echo $this->load();?>
<?php echo $this->confirm();?>
<script>
    $(document).ready(function () {
        initInvEtax();
    });

    $('.collapse_a').click(function(){
        var _this = $(this);
        var _this_id = _this.attr('id');
        var sn = _this.attr('rel');

        if (_this.parent().parent().next().hasClass('accordion-body')){

            $('.m_'+sn).toggle();

            if ($('.m_'+sn).is(':visible'))
                _this.find('.col-sign'). html('-');
            else _this.find('.col-sign'). html('+');

        } else {
            _this.find('.col-sign'). html('');

            getMarketDetail(sn);
        }

    });

    function getMarketDetail(sn){
        if (! $('#m_'+sn).parent().parent().next().hasClass('accordion-body')){
            $('#m_'+sn+' .col-sign').html('');
            $('#m_'+sn+' .img-loading').show();

            $.ajax({
                type: 'post',
                url: '/get/market-detail',
                data: {
                    'sn': sn,
                    'list': 'product-out',
                    'params': '<?php echo (isset($this->params) ? serialize($this->params) : '')?>'
                },
                error: function(){
                },
                success: function(data){
                    $('.m_'+sn).remove();
                    $('#m_'+sn).parent().parent().after(data);
                    $('#m_'+sn).find('.col-sign').html('-');
                    $('#m_'+sn+' .img-loading').hide();
                }
            });
        }
    }

    function initInvEtax()
      {
          $(document).off('click', '.invoice_etax')
          .on('click', '.invoice_etax', function(e) {
              var data_sn = $(this).attr('data_sn');
              $.get("/sales/view-invoice-pdf-file",
              {data_sn:data_sn}
              ,function(data){
                window.open(data, '_blank');
              });

              return false;
          });
      }

</script>
