<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>

<form class="form-search form-horizontal" method="get" action="/warehouse/product-out-archived">
    <div class="row">
        <div class="span5 offset1">
            <div class="control-group">
                <label for="sn" class="control-label">Sales Order Number</label>
                <div class="controls">
                    <input id="sn" name="sn" type="text" class="form-control" value="<?php isset($this->params['sn']) and printf($this->params['sn']);?>">
                </div>
            </div>

            <div class="control-group">
                <label for="cat_id" class="control-label">PRODUCT CATEGORY</label>
                <div class="controls">
                    <select id="cat_id" class="" name="cat_id">
                        <option value="">Choose</option>
                        <?php if ($this->good_categories): foreach ($this->good_categories as $id=>$name):?>
                            <option value="<?php echo $id;?>" <?php if (isset($this->params['cat_id']) and $id==$this->params['cat_id']):?> selected<?php endif;?>><?php echo $name;?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label for="good_id" class="control-label">Product</label>
                <div class="controls">
                    <select id="good_id" class="" name="good_id">
                        <option value="">Choose</option>
                        <?php if ($this->all_goods): foreach ($this->all_goods as $_id => $_item):?>
                            <option value="<?php echo $_id;?>" <?php if (isset($this->params['good_id']) and $_id==$this->params['good_id']):?> selected<?php endif;?>><?php echo $_item;?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label for="good_color" class="control-label">Color</label>
                <div class="controls">
                    <select id="good_color" class="" name="good_color">
                        <option value="">Choose</option>
                        <?php if ($this->colors): foreach ($this->colors as $_id => $_item):?>
                            <option value="<?php echo $_id;?>" <?php if (isset($this->params['good_color']) and $_id==$this->params['good_color']):?> selected<?php endif;?>><?php echo $_item;?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label for="invoice_number" class="control-label">Invoice Number</label>
                <div class="controls">
                    <input id="invoice_number" name="invoice_number" type="text" class="form-control" value="<?php isset($this->params['invoice_number']) and printf($this->params['invoice_number']);?>">
                </div>
            </div>
            <div class="control-group">
                <label for="out_time_from" class="control-label">OUT Time From</label>
                <div class="controls">
                    <input type="text" class="date" id="out_time_from" name="out_time_from" value="<?php isset($this->params['out_time_from']) and printf($this->params['out_time_from']);?>">
                </div>
            </div>
            <div class="control-group">
                <label for="out_time_to" class="control-label">OUT Time To</label>
                <div class="controls">
                    <input type="text" class="date" id="out_time_to" name="out_time_to" value="<?php isset($this->params['out_time_to']) and printf($this->params['out_time_to']);?>">
                </div>
            </div>
        </div>
        <div class="span5">
            <div class="control-group">
                <label for="" class="control-label">Distributor</label>
                <div class="controls">
                    <input type="text" id="distributor_name" autocomplete="off">
                    <select name="d_id" id="distributor_id" multiple="">
                        <option value>Choose</option>
                        <?php if (isset($this->distributors) && $this->distributors): ?>
                            <?php foreach ($this->distributors as $key => $value): ?>
                                <option value="<?php echo $key ?>"
                                    <?php if (isset($this->params['d_id']) && $this->params['d_id']==$key) echo "selected" ?>><?php echo $value['title'] ?></option>
                            <?php endforeach ?>
                        <?php endif ?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label for="warehouse" class="control-label">Warehouse</label>
                <div class="controls">
                    <select name="warehouse_id[]" id="warehouse" class="multiselect" multiple="multiple">
                        <?php if (isset($this->warehouses) && $this->warehouses): foreach ($this->warehouses as $_id => $_name):?>
                            <option value="<?php echo $_id;?>"
                                <?php if (isset($this->params['warehouse_id'])
                                    and ( (is_array($this->params['warehouse_id']) and in_array($_id, $this->params['warehouse_id']))
                                    || $_id==$this->params['warehouse_id']) ):?> selected<?php endif;?>
                                ><?php echo str_replace('Warehouse_', ' ', $_name);?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label for="area" class="control-label">Area</label>
                <div class="controls">
                    <select name="area_id[]" id="area" class="multiselect" multiple="multiple">
                        <?php if (isset($this->areas) && $this->areas): foreach ($this->areas as $id=>$name):?>
                            <option value="<?php echo $id;?>" <?php if (isset($this->params['area_id']) and (
                                         (is_array($this->params['area_id']) && in_array($id, $this->params['area_id']))
                                        || $id == $this->params['area_id']
                                    )):?> selected="selected"<?php endif;?>><?php echo $name;?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label for="region" class="control-label">Province</label>
                <div class="controls">
                    <select name="region_id[]" id="region" class="multiselect" multiple="multiple">
                        <?php if (isset($this->regions) && $this->regions): foreach ($this->regions as $id=>$name):?>
                            <option value="<?php echo $id;?>" <?php if (isset($this->params['region_id']) and (
                                         (is_array($this->params['region_id']) && in_array($id, $this->params['region_id']))
                                        || $id == $this->params['region_id']
                                    )):?> selected="selected"<?php endif;?>><?php echo $name;?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label for="district" class="control-label">District</label>
                <div class="controls">
                    <select name="district_id[]" id="district" class="multiselect" multiple="multiple">
                        <?php if (isset($this->districts) && $this->districts): foreach ($this->districts as $id=>$name):?>
                            <option value="<?php echo $id;?>" <?php if (isset($this->params['district_id']) and (
                                         (is_array($this->params['district_id']) && in_array($id, $this->params['district_id']))
                                        || $id == $this->params['district_id']
                                    )):?> selected="selected"<?php endif;?>><?php echo $name;?></option>
                        <?php endforeach; endif;?>
                    </select>
                </div>
            </div>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-primary">Search</button>
            <button type="reset" class="btn btn-warning">Reset</button>
            <button type="submit" name="export" value="1" class="btn btn-success">Export</button>
            <button type="submit" name="export" value="2" class="btn btn-success">IMEI Export</button>
        </div>
    </div>
</form>

<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<script type="text/javascript" src="<?php echo HOST ?>js/jets.js"></script>
<script>
options = {
    selectAllText: 'Select All',
    includeSelectAllOption: true,
    includeSelectAllIfMoreThan: 3,
    disableIfEmpty: true
};

function multi() {
    $('.multiselect').multiselect(options);
}

$(document).ready(function () {
    var jets = new Jets({
        searchTag: '#distributor_name',
        contentTag: '#distributor_id'
    });

    multi();

    $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

    $('#cat_id, #good_id').change(function(){
        $(this).after('<span class="loading"></span>');
        var _self = $(this);
        var cat_id = $('#cat_id').val();

        if (_self.attr('id')=='cat_id')
            $('#good_id').find('option:not(:first)').remove();

        var good_id = $('#good_id').val();

        $('#good_color').find('option:not(:first)').remove();

        $('#num, #price').val('');

        $.get("/get/load",
            {cat_id: cat_id, good_id: good_id}
            ,function(data,status){
                var data = $.parseJSON( data );
                if (data.goods){
                    var obj = data.goods;
                    for (var i = 0; i < obj.length; i++) {
                        $('#good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                }
                if (data.colors){
                    var obj = data.colors;
                    for (var i = 0; i < obj.length; i++) {
                        $('#good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                }
                _self.nextAll('.loading').remove();
            });
    });

	$('#area').change(function(){
        $('.loading').remove();

        $(this).next('.btn-group').append('<span class="loading"></span>');
        var _self = $(this);
        var area_id = $(this).val();
        $('#region').find('option').remove();
        $('#district').find('option').remove();

        $.get("<?php echo HOST ?>get/province-v2",
            {area_id: area_id}
            ,function(data,status){
               for (i in data)
                    $('#region').append('<option value="'+i+'">'+data[i]+'</option>');

                $('#district, #region').multiselect("destroy").multiselect(options);
                $('.loading').remove();
            });
    });

    $('#region').change(function(){
        $('.loading').remove();
        $(this).next('.btn-group').append('<span class="loading"></span>');
        var _self = $(this);
        var region = _self.val();

        $('#district').find('option').remove();

        $.get("<?php echo HOST ?>get/district-v2",
            {province_id: region}
            ,function(data,status){
                for (i in data)
                    $('#district').append('<option value="'+i+'">'+data[i]+'</option>');

                $('#district').multiselect("destroy").multiselect(options);
                $('.loading').remove();
            });
    });
});
</script>
