<form id="form" name="form" class="form-search form-horizontal" action="<?php echo HOST ?>warehouse/bad-accessories-management">
    <div class="row">
        <div class="span5">
            <div class="control-group">

                <label for="warehouse_id" class="span2">Warehouse</label>
                <select id="warehouse_id" class="span3" name="warehouse_id">
                    <option value="">Choose</option>
                    <?php if ($this->warehouses): foreach ($this->warehouses as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['warehouse_id']) and $id==$this->params['warehouse_id']):?> selected<?php endif;?>><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">

                <label for="cat_id" class="span2">PRODUCT CATEGORY</label>
                <select id="cat_id" class="span3" name="cat_id" disabled>
                    <option value="">Choose</option>
                    <?php if ($this->goodCategories): foreach ($this->goodCategories as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['cat_id']) and $id==$this->params['cat_id']):?> selected<?php endif;?>><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

        </div>

        <div class="span5">
            <div class="control-group">
                <label for="good_id" class="span2">Product</label>
                <select id="good_id" class="span3" name="good_id">
                    <option value="">Choose</option>
                    <?php if (isset($this->goods_acc) and $this->goods_acc):
                            foreach ($this->goods_acc as $item):
                        ?>
                                <option value="<?php echo $item['id'];?>" <?php if (isset($this->params['good_id']) and $item['id']==$this->params['good_id']):?> selected<?php endif;?>><?php echo $item['name'];?></option>
                    <?php   endforeach; ?>
                    <?php elseif ($this->goods_cached): foreach ($this->goods_cached as $id=>$item):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['good_id']) and $id==$this->params['good_id']):?> selected<?php endif;?>><?php echo $item;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">
                <label for="good_color_id" class="span2">Color</label>
                <select id="good_color_id" class="span3" name="good_color_id">
                    <option value="">Choose</option>
                    <?php if ($this->goodColors): foreach ($this->goodColors as $id=>$item):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['good_color_id']) and $id==$this->params['good_color_id']):?> selected<?php endif;?>><?php echo $item;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>
        </div>
    </div>

	<div class="row">
        <div class="span10">
            <div class="controls">
				<button type="submit" class="btn btn-primary">Search</button>
			    <button type="reset" class="btn btn-warning">Reset</button>
                <!--<button type="submit" name="export" value="1" class="btn btn-success">Export</button>-->
			</div>
		</div>
	</div>
</form>

<script>
    $(document).ready(function () {

        $('#cat_id, #good_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var cat_id = $('#cat_id').val();

            if (_self.attr('id')=='cat_id')
                $('#good_id').find('option:not(:first)').remove();

            var good_id = $('#good_id').val();

            $('#good_color').find('option:not(:first)').remove();

            $('#num, #price').val('');

            $.get("/get/load",
                {cat_id: cat_id, good_id: good_id}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    if (data.goods){
                        var obj = data.goods;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    if (data.colors){
                        var obj = data.colors;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    _self.nextAll('.loading').remove();
                });
        });
    });
</script>