<table class="table table-bordered">
    <thead>
        <tr>
            <th rowspan="2"><div align="center">#</div></th>
            
            <th colspan="3"><div align="center">Warehouse</div></th>
            <th rowspan="2"><div align="center">Category</div></th>
            <th rowspan="2"><div align="center">Product Name</div></th>
            <th rowspan="2"><div align="center">Product Color</div></th>
            <th colspan="2"><div align="center">Stock</div></th>
            
            
            <th rowspan="2"><div align="center">Date</div></th>
            <th rowspan="2"><div align="center">Document Number</div></th>
            <th rowspan="2"><div align="center">Type</div></th>
            
            <th colspan="3"><div align="center">IN</div></th>
            <th colspan="3"><div align="center">OUT</div></th>
            
            <!-- <th colspan="3"><div align="center">Remain Amount</div></th> -->
        </tr>
        <tr >
            <th><div align="center">Name</div></th>
            <th><div align="center">FROM</div></th>
            <th><div align="center">TO</div></th>
            <th><div align="center">Balance</div></th>
            <th><div align="center">Imei</div></th>
            
            <th><div align="center">Quantity</div></th>
            <th><div align="center">Unit Cost</div></th>
            <th><div align="center">Amount</div></th>
            <th><div align="center">Quantity</div></th>
            <th><div align="center">Unit Cost</div></th>
            <th><div align="center">Amount</div></th>
            
            <!-- 
            <th>Amount</th>
            <th>Cost</th>
            <th>Total Cost</th>
            -->
        </tr>
    </thead>
    <tbody>
        <?php
           // print_r($this->stocks);

            $balance_amount=0;$in_amount=0;$out_amount=0;

            if (isset($this->stocks) and $this->stocks) {
                $stocks = $this->stocks;
                
                for ($i=0;$i<count($stocks);$i++) {
                    $cnt = $i + 1;

                    $key_id = $stocks[$i]['good_id'].'_'.$stocks[$i]['good_color'].'_'.$stocks[$i]['warehouse_id'];

                    echo "<tr class='main-row'>";
                    echo "<td>";
                    echo '<button id="d_'.$key_id.'" name="view-more" class="collapse_a btn btn-default btn-small">+</button>';
                    echo '<input type="hidden" name="page" class="'.'p_'.$key_id.'" value="1"/> ';
                    echo "</td>";
                    echo "  <td>".$stocks[$i]['warehouse_name']."</td>";
                    echo "  <td></td>";
                    echo "  <td></td>";
                    echo "  <td>".$stocks[$i]['category']."</td>";
                    echo "  <td>".$stocks[$i]['product_name']."</td>";
                    echo "  <td>".$stocks[$i]['product_color']."</td>";
                    echo "  <td>".number_format($stocks[$i]['balance_stock'],0)."</td>";
                    echo "  <td></td>";
                    echo "  <td></td>";
                    echo "  <td></td>";
                    echo "  <td></td>";
                    echo "  <td></td>";
                    echo "  <td></td>";
                    echo "  <td></td>";
                    echo "  <td></td>";
                    echo "  <td></td>";
                    echo "  <td></td>";
                    echo "</tr>";
                }
            } 
        ?>

    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="/js/bootstrap-modal.js"></script>
<script type="text/javascript" src="/js/bootstrap-modalmanager.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" type="text/css" href="/css/bootstrap-modal.css"/>

<script>
    function initShowTransaction(){
            $('.collapse_a').click(function(){
                var _this   = $(this);
                _this.attr('disabled','disabled');
                var check       = _this.html();
                var d_id        = _this.attr('id');//d_007 :D

                //class cho các dòng được sinh ra
                var _class      =  d_id+'_sub';
                var check_ajax;

                if(check == '+'){
                    _this.html('-');

                    var check_class = $('tr').hasClass(_class);
                    if(check_class){// If data existed then show
                        $('.'+_class).show();
                    }else{
                        var view_more = '<tr class="'+_class+'"><td></td><td colspan="12"><button class="btn pull-right view-more" value="1">view more</button></td></tr>';
                        $(view_more).insertAfter($('#'+d_id).parent().parent());
                           var page = parseInt($('.'+_class+' .view-more').val());

                        check_ajax = loadCheckStock(d_id,_class,page);
                        initViewmore();

                    }
                }else{
                    $('.'+_class).hide();
                    _this.html('+');
                }

                _this.removeAttr('disabled');
            });
        }

        function loadCheckStock(d_id,_class,page){
            var check_ajax = 1;
            var id = d_id.split('_')[1];
            var cat_id='11';
            var good_id='17';
            var color_id='12';
            var warehouse_id='36';
            var from_date='2016-08-01';
            var to_date='2016-08-01';

            var uri = "<?php echo http_build_query($this->params)?>";
            $.ajax({
                type: 'get',
                url: '/warehouse/gettransaction-stock-list?'+uri,
                //url: '/checkmoney/getcheckmoney?'+uri,
                data: {'d_id2': id,'cat_id': cat_id,'good_id': good_id,'color_id': color_id,'warehouse_id': warehouse_id,'from': from_date,'to': to_date,'page':page,'_class':_class},
                error: function(){
                    check_ajax = 0;
                },
                success: function(data){
                    var html = data;
                    //alert(data);
                    if(page == 1){
                        $(html).insertAfter($('#'+d_id).parent().parent());
                    }else{
                        var node_view_more = $('.'+_class+' .view-more');
                        $(html).insertBefore(node_view_more.parent().parent());
                    }

                    var page = parseInt($('.'+_class+' .view-more').val());
                    $('.'+_class+' .view-more').val(page+1);
                    check_ajax = 2;
                }
            });

            return check_ajax;
        }

        function initViewmore(){
            $('.view-more').on('click',function(){

                var _this   = $(this);
                var page    = parseInt(_this.val());
                var _class  = _this.parent().parent().attr('class');
                var d_id    = 'd_'+_class.split('_')[1];
                var check_ajax = 0;
                check_ajax  = loadCheckStock(d_id,_class,page);

            });
        }

    $(document).ready(function(){
        
        initShowTransaction();
        $modal = $('#modal');
        $('.badge.badge-default').click(function(){

            _self = $(this);
            //alert(_self.data('good-color'));
            $('body').modalmanager('loading');
            $.post('<?php echo HOST ?>finance/view-imei-list',
                {
                    sales_sn : _self.data('sales-sn'),
                    good_id : _self.data('good-id'),
                    good_color : _self.data('good-color')
                },
                function(data){
                    //alert(data);
                    $modal.html(data);
                    $modal.modal();
                    var name = _self.parents('tr').children('td:nth-child(6)').html();
                    $modal.find('h3').append(' <small>&bull; '+name+'</small>');
            });
            
        });

    })



</script>
