<form id="form" name="form" action="<?php echo HOST ?>warehouse/list">
	<div class="row" style="padding-left: 50px;">

		<div class="span4">
			<div class="control-group">
				<label class="control-label" for="name">Name</label>
				<div class="controls">
					<input type="text" id="name" name="name" class="span3" placeholder="Name" <?php if( isset($this->params['name']) && $this->params['name'] ) echo 'value="'.$this->params['name'].'"' ?> />
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">Distributor</label>
				<div class="controls">
					<select class="span3" name="distributor">
						<option value=""> Please Selected </option>
						<?php if(isset($this->superie_distributor) && $this->superie_distributor) : ?>
							<?php foreach ($this->superie_distributor as $value) : ?>
								<option value="<?php echo $value['id'] ?>" <?php if(isset($this->params['distributor']) && $this->params['distributor'] == $value['id']) : ?> selected <?php endif; ?> ><?php echo $value['title'] ?></option>
							<?php endforeach; ?>
						<?php endif; ?>
					</select>
				</div>
			</div>
		</div>

		<div class="span4">
			<div class="control-group">
				<label class="control-label" for="status"> Warehouse Status :</label>
				<div class="controls">
					<select class="span3" name="status" class="form-control">
						<option value="1" <?php if( isset($this->params['status']) && $this->params['status'] == 1) : ?> selected <?php endif; ?> > In Cooperation </option>
						<option value="2" <?php if( isset($this->params['status']) && $this->params['status'] == 2) : ?> selected <?php endif; ?> > Suspend Cooperation </option>
						<option value="3" <?php if( isset($this->params['status']) && $this->params['status'] == 3) : ?> selected <?php endif; ?> > Close </option>
					</select>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label"> Warehouse Type : </label>
				<div class="controls">
					<select class="span3" name="type">
						<option value=""> Please Selected </option>
						<?php if(isset($this->warehouseType) && $this->warehouseType) : ?>
							<?php foreach($this->warehouseType as $key => $value) : ?>
								<option value="<?php echo $key ?>" <?php if(isset($this->params['type']) && $this->params['type'] == $key ) : ?> selected <?php endif; ?> ><?php echo $value ?></option>
							<?php endforeach; ?>
						<?php endif; ?>
					</select>
				</div>
			</div>
		</div>

		<div class="span4">
			<div class="control-group">
				<label class="control-label">Office : </label>
				<div class="controls">
					<select class="span3" name="office">
						<option value=""> Please Selected </option>
						<?php if(isset($this->area) && $this->area) : ?>
							<?php foreach($this->area as $key => $value) : ?>
								<option value="<?php echo $key ?>" <?php if(isset($this->params['office']) && $this->params['office'] == $key) : ?> selected <?php endif; ?>><?php echo $value ?></option>
							<?php endforeach; ?>
						<?php endif; ?>
					</select>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">External Serial Number :</label>
				<div class="controls">
					<input type="text" class="span3" name="external_serial" placeholder="Enter" <?php if( isset($this->params['external_serial']) && $this->params['external_serial'] ) echo 'value="'.$this->params['external_serial'].'"' ?>>
				</div>
			</div>
		</div>

	</div>

	<div class="row" style="padding-left: 50px; padding-top: 20px;">
		<div class="span10">
			<div class="controls">
				<button type="submit" class="btn btn-primary">Search</button>
				<button type="reset" class="btn btn-warning">Reset</button>
				<button type="submit" name="export" value="1" class="btn btn-success">Export</button>
			</div>
		</div>
	</div>
</form>