<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Print</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <style type="text/css">
       @page{
        size: auto A4;
        margin: 5mm;
     }

      body{width: 323mm; height: 276mm;font-size:16px;font-family:Tahoma;}
      .top_page{margin-top: 0px;}
      .top{text-align:left;}
      .hid{visibility:hidden;}
      .top p{height:24px;line-height:24px;margin:0}
      .textbox{width:600px;border:1px solid black;height:70px}
      .blank10{height:10px;clear:both}

      .title_page_logo {font-weight:bold;}
      .title_page_logo_small{font-weight: normal;}
      .title_page{width: auto;text-align:center;font-size:15px;font-weight:bold;margin-top: 5px}
      .title_page_small_left{width: auto;text-align:left;height:12px;font-size:12px;line-height:12px;float:left;}
      .title_page_small_right{width: auto;text-align:right;height:12px;font-size:12px;line-height:12px;float:right;margin-top: -10px;}
      .title{width:600px;text-align:center;height:30px;font-size:15px;line-height:30px;background-color:#fabf8f;font-weight:bold}
      .title small {float: right;font-weight: normal;font-size: 8px;padding-right: 2em;}
      .tbl,
      .tbllist{width:90%;margin-top: 5px;}
      .tbllist_imei{margin-top: -30px;}
      .tbllist_height{height: 30mm;}
      .tbl_col1_list{width:230px;padding: 5px;}
      .tbl_col2_list{width:310px;padding: 5px;}
      .tbl_col3_list{width:30px;margin-right: 10px;text-align: left;padding: 5px;}
      .tbl_col4_list{width:80px;margin-left: 0px;text-align: right;padding: 5px;}
      .tbl_col5_list{width:120px;margin-left: 0px;text-align: right;padding: 5px;}
      .tbl_col6_list{width:100px;margin-left: 0px;text-align: right;padding: 5px;}
      .tbl_col7_list{width:100px;margin-left: 0px;text-align: right;padding: 5px;}
      .tbl_col8_list{width:100px;margin-left: 0px;text-align: right;padding: 5px;}
      .tbl_col9_list{width:120px;margin-left: 0px;text-align: right;padding: 5px;}

      .tbl_col1_list_sum{width:230px;}
      .tbl_col2_list_sum{width:350px;}
      .tbl_tr_list_sum{margin-left: 410px;margin-top: -13px;position: absolute;width:750px;height: 30px;}
      .tbl_col3_list_sum{margin-left: 5px;text-align: center;position: absolute;}
      .tbl_col4_list_sum{margin-left: -50px;text-align: right;position: absolute;}
      .tbl_col5_list_sum{margin-left: 170px;text-align: right;position: absolute;}
      .tbl_col6_list_sum{margin-left: 280px;text-align: right;position: absolute;}
      .tbl_col7_list_sum{margin-left: 390px;text-align: right;position: absolute;}
      .tbl_col8_list_sum{margin-left: 500px;text-align: right;position: absolute;}
      .tbl_col9_list_sum{margin-left: 600px;text-align: right;position: absolute;}

      .tbl tr{margin:0}
      .tbl tr td,
      .tbllist tr td{background-color:#fff}.tbl .firsttd{width:145px}.tbl .secondtd{width:100px}.tbl .thirdtd{width:36px}.tbl .forthtd{width:65px}
      

         .note{border-bottom:1px dotted #ccc;width:300px;float:left;margin:9px 0 0 25px}.green{text-align:center}.green td{background-color:#ccffcc!important}#logo{
  float:left;
  display:block;
  left: 261px;
  top: 71px;
}#logo img{width:136px;margin-top:10px}
.trcenter{text-align:center}
.invoice{width:453px;display:block;clear:both;margin-left:119px}
.invoice-number{float:left;padding-left:37px}
.order-type{float:right;text-align:right}
         .right{text-align:right}
         .detail{width:842px}
         .title_page_col_left{float:left;width: 300px; margin-top: -70px;}
         .title_page_col_right{float:right;width: 850px;margin-top: -70px;}

         .below_page_col_left{float:left;width: 100px;}
         .below_page_col_right{float:right;width: 200px;margin-left: -300px;}
         .below_page_col_right_1{float:right;width: 400px;margin-left: -200px;}
         
         .below_detail .col1 span{width:300px;float:left;font-weight:bold;}
         .below_detail .col2 span{width:309px;float:left;font-weight:normal;}

         
         .below_detail_left{width:309px;float:left;font-weight:normal;}

         .assign{width: 200px;font-weight: bold;float: left;
         
         /* margin-top: 10px; */
         border-top: 1px dotted black;
         margin-left: 0px;
         margin-top: 40px;
         text-align: center;
         padding-top: 10px;}

         .signature_page_col_right{float:right;}

         .detail .col1{width:109px;float:left}
         .detail .col1 span{width:109px;float:left;font-weight:bold}
         .detail .col2{width:224px;float:left}
         .detail .col2_title{width:600px;float:left}
         .detail .col2 span{font-weight:bold}
         .detail .col3{width:100px;float:left}
         .detail .col3 span{font-weight:bold}
         .clear{clear:both}
         .colleft{float:left;width:300px}
         .colright{float:right;width:165px}
         .tablelist {font-size:10px;}
        

         .vat{width:435px!important;float:right!important}#vatnumber{clear:both}#vatnumber .sn{width:54px;border:1px solid black;height:14px;float:left}.marksn{float:left;border-left:1px solid black;font-weight:bold;padding-left:3px}.order{float:left;margin-left:10px}.order .sn{width:5px;height:10px;border:1px solid black;float:left;margin-left:5px}.order .alert{margin-left:16px;margin-bottom:4px}
         
        input[type="text"]
        {
            display: block;
            margin: 0px;
            font-family: time new roman;
            font-weight: bold;
            text-align: center;
            font-size: 10px;
            border: none;
        }
        .model
        {font-size: 8px !important;
            text-transform:uppercase;
        }
        .imgbutton{width:40px !important;cursor:pointer;position:  absolute;}
        @media print{.print,.no-print{display:none!important}}
        .print{width:20px !important;.print,.no-print{display:none!important}}
        .scroll{overflow:hidden;}
        .number{width:10px;}
        .signname{  width: 549px;            margin: auto;            padding-left: 70px;}
        .single_record{page-break-after: always;}
    </style>

    <script type="text/javascript">
        function Print()
        {
            //$( ".imgbutton" ).remove();
            window.print();
        }

    </script>
        <?php
            $item=$this->sales;
            //print_r($item);
            $item_total=count($item);
            $item_per_page=12;
            $item_imei_per_page=7;

            $max_show_imei=100;

            $row_product=0;$row_product_imei=0;
            $pg_total= ceil($item_total/$item_per_page);

            $g_total_num=0;
            $g_correct_amount=0;$g_difference_amount=0;
            $g_total_balance=0;$g_total_VAT=0;$g_total_amount=0;
            $g_total_price=0;$g_correct_bal_amount=0;

            $retailer_name="";$prepared_by_name="";
            //print_r($this->sales[0]);
            $retailer_name= $this->sales[0]['unames'];
            //$prepared_by_name= $this->sales[0]['prepared_by'];

            $add_tax = $this->sales[0]['add'];
            $distributor_tax = $this->sales[0]['mst_sn'];
            $cn_no= $this->sales[0]['creditnote_sn_view'];
            $create_date=$this->sales[0]['create_date_cn_view'];
            $create_date= date("d-m-Y", strtotime($create_date));
            
            $parent=$this->sales[0]['parent'];
            if($parent==0){
                $branch_name='สำนักงานใหญ่';
                $branch_no=$this->sales[0]['branch_no'];

            }else{
                $branch_name='สาขา';
                $branch_no=$this->sales[0]['branch_no'];
            }

        ?>
</head>
<body>

    <div class="top_page" ></div>
    <div id="logo" class="hid">
        <?php if ($this->market['warehouse_id'] != 8){?>
        <img src="<?php echo HOST ?>img/logoprint.png" />
        <br />
        <?php } ?>
        
    </div>

    <br>
    <div class="top hid">

        <div style="float:right;" class="title_page_logo hid"><?php echo $pg_number;?></div>
        <div class="title_page_logo hid">บริษัท ไทย ออปโป้ จำกัด</div>
        <div class="title_page_logo hid">THAI OPPO CO., LTD</div></br>
        <div class="title_page_logo_small hid">สำนักงานใหญ่:  อาคาร เอไอเอ แคปปิตอล เซ็นเตอร์ ชั้น 31 ห้อง 5-7 เลขที่ 89 ถนนรัชดาภิเษก แขวงดินแดง เขตดินแดง กรุงเทพฯ 10400 โทร.02-013-1810 โทรสาร 02-013-1820</div>
        <div class="title_page_logo_small hid">Head Office: AIA Capital Center Building Fl 31 Unit 5-7  89 Ratchadaphisek Road, DinDaeng, DinDaeng, Bangkok 10400 Tel.02-013-1810 Fax: 02-013-1820</div>
    </div>
    <div style="float:right;margin-right: 140px;"><?php echo $pg_number;?></div>
    <div class="title_page hid">ต้นฉบับใบลดหนี้/ใบกำกับภาษี/ใบรับคืนสินค้า</div>
    <div class="title_page_small_left hid">เลขประจำตัวผู้เสียภาษี : <?=$distributor_tax?></div></br>
    <div class="title_page_small_right hid">(เอกสารออกเป็นชุด)</div></br>
    <div class="title_page_col_left">
        <div class="detail clear">
            <div class="col1 hid"><span>วันที่</span></div>  <div class="col2"><?=$create_date;?></div></br>
            <div class="col1 hid"><span>เลขที่ใบลดหนี้</span></div>  <div class="col2"><?=$cn_no?></div></br>
            <div class="col1 hid"><span>ชื่อสาขา</span></div>  <div class="col2"><?=$branch_name?></div></br>
            <div class="col1 hid"><span>สาขาที่</span></div>  <div class="col2"><?=$branch_no?></div></br>
        </div>
    </div>
    <div class="title_page_col_right">
        <div class="detail clear">
            <div class="col1 hid"><span>ชื่อลูกค้า</span></div>  <div class="col2_title"><?= $retailer_name?></div></br>
            <div class="col1 hid"><span>ที่อยู่</span></div>  
            <div class="col2_title"><?=$add_tax?></br> 
            เลขประจำตัวผู้เสียภาษี : <?=$distributor_tax?>
        </div>
        </div>
    </div>
    </br>
    <div class="blank10"></div>

<div class="blank10"></div>
</br>
<?php
  //for($pg=1;$pg<=$pg_total;$pg++)
 // {
    /*
    if($pg==1){
        echo '<div style="margin-top: 0px;"></div>';
    }else if($pg==2){
        echo '<div style="margin-top: -120px;"></div>';
    }else{
        echo '<div style="margin-top: -210px;"></div>';
    }  
    */
    $pg_number= $pg."/".$pg_total; 

?>
<table class="tbllist_imei" cellspacing="0" cellpadding="1">
    <tr style="text-align: left;">
        <td class="hid">IMEI code: </td>
    </tr>

    <tr style="text-align: left; height: 200px;vertical-align:top;">
        <td >
                <?php
            $imei_sn_list='';
            $product_item_list=$this->sales;
            $item_list=$this->imei_return_list;
            $show_item_product='';
           // print_r($item_list);
            for($i=0;$i<count($product_item_list);$i++){
            
                $invoice_number=$item_list[$row_product_imei]['invoice_number'];
                $product_name= $item_list[$row_product_imei]['product_detail'];
                $product_detail= $product_name;
                $product_detail_imei ='';$imei_list='';$count_item=0;$row_imei=0;$count_row_imei=0;

                //echo $invoice_number;echo $product_name;

                 echo $product_detail_imei ='['.$invoice_number.']'.$product_detail.'</br>['.rtrim($imei_list,',').']</br>';

                for($j=0;$j<count($item_list);$j++){
                  //echo $j;
                    //$show_item_product=$item_list[$j]['product_detail'];
                    $show_item_product = $item_list[$j]['product_detail'];
                    $show_invoice_number=$item_list[$j]['invoice_number'];


                    //echo $product_name;echo $show_item_product;
                    if($product_name==$show_item_product && $invoice_number==$show_invoice_number)
                    {     $count_item+=1;
                           
                        if($row_imei==0){
                          if($count_item==5){
                            $imei_list.=$item_list[$j]['imei_sn'].'</br>,';
                            $count_item=0;
                          }else{
                            $imei_list.=$item_list[$j]['imei_sn'].',';
                          }
                        }else{
                          if($count_item==8){
                            $imei_list.=$item_list[$j]['imei_sn'].'</br>,';
                            $count_item=0;
                          }else{
                            $imei_list.=$item_list[$j]['imei_sn'].',';
                          }
                        }
                        $row_imei+=1;                    
                    }  
                }

              $product_detail_imei ='['.$invoice_number.']'.$product_detail.'['.rtrim($imei_list,',').']';

                if(strlen($product_detail_imei)<=130){
                  //echo $product_detail_imei.'</br>';
                }else{
                 // echo $product_detail_imei ='['.$invoice_number.']'.$product_detail.'</br>['.rtrim($imei_list,',').']</br>';
                }
              $row_product_imei+=1;
            }
          
        ?>
        </td>
    </tr>
</table>
</br>
<div id="logo" style="position:  absolute;" >
    <img src="<?php echo HOST ?>img/print.png" class="imgbutton print"  onclick="Print()" id="print"  />
</div>
<div class="single_record"></div>
<?php //} ?>
</body>
</html>

