<style>
    body{
        font-family: phetsarath ot;
    }
    button{
        font-family: phetsarath ot;
    }
    span{
       font-family: phetsarath ot;"
    }
    strong{
        font-size: 14px;
    }
</style>

<div class="page-header">
    <?php if (isset($this->sales) and $this->sales):?>
        <h1>Edit Price Protection Auto Check</h1>
    <?php else:?>
        <h1>Confirm Price Protection Auto Check ຢືນຢັນການປັບລາຄາ</h1>
    <?php endif;?>
</div>

<?php

if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
    ?>

    <div class="row">
       <div class="span12">
        <iframe name="ifrmSave" id="ifrmSave" width="100%" style="display:none;"></iframe>
        <form role="form" id="form" action="<?php echo HOST.'finance/save-cp-auto-check-imei'?>" method="post" target="ifrmSave" class="form-inline">
        	<?php 
            $userStorage = Zend_Auth::getInstance()->getStorage()->read();
            $show_create_cn_menu = $this->show_create_cn_menu;
            $create_cn = "checked"; 
            //$active_cn = "checked";   
            $hide = '';
            if (isset($this->sales) and $this->sales){

                $return_sn = $this->sales[0]['sale']->sn_ref;
                if($return_sn==''){
                    $return_sn = $this->sales[0]['sale']->sn;  
                }

                $create_cn = $this->sales[0]['sale']->create_cn;
                if($create_cn==1){
                    $create_cn = "checked";
                }else{
                    $hide = 'hide';
                    $create_cn ="";
                }

            //$active_cn = $this->sales[0]['sale']->active_cn;
                if($active_cn==1){
                    $active_cn = "checked";
                }else{
                    $active_cn ="";
                }
            }

            $imei_cp = count($this->imei_check['result_by_imei']);
            $imei_timing = count($this->imei_check_log['result_check_timing']);
            $imei_log = count($this->imei_check_log['result_check_imei']);
            if($imei_cp >0 || $imei_timing >0 || $imei_log >0){
                $edit_good_id="disabled";
                $check_edit=1;
            }else{
                $edit_good_id="";
                $check_edit=0;
            }
        ?>

            <div class="row">
                <div class="span5">
                    <div class="control-group">
                        <label for="lot_number" class="span2">ລະຫັດ Lot No <span style="color: red">*</span></label>
                        <input type="text" readonly="true" name="lot_number" id="lot_number" required="required" value="<?php isset($this->cp_imei) and $this->cp_imei and printf($this->cp_imei[0]['lot_number']);?>" />
                    </div>
                    <div class="control-group">
                        <label for="detail" class="span2">ລາຍລະອຽດ <span style="color: red">*</span></label>
                        <textarea id="detail" rows="3" class="detail" required="required" name="detail"><?php isset($this->cp_imei) and $this->cp_imei and printf($this->cp_imei[0]['detail']);?></textarea>
                    </div>
                    <div class="control-group">
                        <label for="good_id" class="span2">ສິນຄ້າ <span style="color: red">*</span></label>
                        <select id="good_id" <?php echo $edit_good_id;?> class="span2" name="good_id">
                            <option value="">Choose</option>
                            <?php if ($this->goods): foreach ($this->goods as $key):?>
                                <option value="<?php echo $key->id;?>" required="required" <?php if (isset($this->cp_imei[0]['good_id']) and $key->id==$this->cp_imei[0]['good_id']):?> selected<?php endif;?>><?php echo $key->name;?></option>
                            <?php endforeach; endif;?>
                        </select>
                    </div>
                    <div class="control-group">
                        <label for="price" class="span2">ຍອດເງິນທີ່ຈະປັບລາຄາ <span style="color: red">*</span></label>
                        <input type="text" name="price" class="span1 price" id="price" required="required" value="<?php isset($this->cp_imei) and $this->cp_imei and printf($this->cp_imei[0]['price']);?>" />
                    </div>

                    <div class="control-group">
                        <label for="new_price" class="span2">ລາຄາທີ່ປະກາດຂາຍໃໝ່ <span style="color: red">*</span></label>
                        <input type="text" name="new_price" class="span1 new_price" id="new_price" required="required" value="<?php isset($this->cp_imei) and $this->cp_imei and printf($this->cp_imei[0]['new_price']);?>" />
                    </div>

                </div> 
                <div class="span5"  >
                    <div class="control-group">
                        <label for="remark" class="span2">ໝາຍເຫດ <span style="color: red">*</span></label>
                        <textarea id="remark" rows="3" class="remark" required="required" name="remark"><?php isset($this->cp_imei) and $this->cp_imei and printf($this->cp_imei[0]['remark']);?></textarea>
                    </div>

                    <div class="control-group">
                        <label for="cp_date" class="span2">ວັນທີ່ຈະເລີ່ມໃຊ້ລາຄາໃໝ່ <span style="color: red">*</span></label>
                        <input type="text" name="cp_date" class="span2 cp_date" id="cp_date" required="required" value="<?php isset($this->cp_imei) and $this->cp_imei and printf($this->cp_imei[0]['cp_date']);?>" />
                    </div> 
                    <!-- <div class="control-group">
                        <label for="cp_date" class="span2">ร้านลูกตู้บุญชัย </label>
                        
                        <input class="allow_use" type="checkbox" id="check_sub_d_id" name="check_sub_d_id" value="1" <?php // if(isset($this->cp_imei[0]['sub_d_id']) && $this->cp_imei[0]['sub_d_id']) echo "checked" ?> />
                    </div> --> 

                    <div class="control-group">
                        <label for="finance_group" class="span2">Finance Group <span style="color: red">*</span></label>
                        <select id="finance_group" required="required"  <?php echo $edit_good_id;?> class="span2 finance_group" name="finance_group">
                            <option value="">Choose</option>
                            <?php if ($this->finance_group): foreach ($this->finance_group as $key):?>
                                <option value="<?php echo $key['finance_group_name'];?>" required="required" <?php if (isset($this->cp_imei[0]['finance_group']) and $key['finance_group_name']==$this->cp_imei[0]['finance_group']):?> selected<?php endif;?>><?php echo $key['finance_group_name'];?></option>
                            <?php endforeach; endif;?>
                        </select>
                    </div>

                    <div class="control-group">
                        <label for="check_cost" class="span2">ໃຊ້ການຄຳນວນແບບຕົ້ນທຶນ </label>
                        
                        <input class="cal_cost" type="checkbox" id="check_cost" name="check_cost" value="1" <?php if(isset($this->cp_imei[0]['check_cost']) && $this->cp_imei[0]['check_cost']) echo "checked" ?> />
                    </div>
                    <div class="control-group">
                        <label for="price_limit" class="span2">ຍອດເງິນທີ່ຈ່າຍສູງສຸດ </label>
                        
                        <input type="text" name="price_limit" class="span1 price_limit" id="price_limit" value="<?php isset($this->cp_imei) and $this->cp_imei and printf($this->cp_imei[0]['price_limit']);?>" />
                    </div> 
                </div>      
            </div>
        </p>
        <div class="row">
            <div class="span4">
                <div class="control-group">
                    <input type="hidden" name="good_id" id="good_id" value="<?php echo $this->cp_imei[0]['good_id']; ?>" />
                    <input type="hidden" name="check_edit" id="check_edit" value="<?php echo $check_edit;?>" />
                    <input type="hidden" name="data_phone" id="data_phone" value="data_phone" />
                    <input type="hidden" id="back_url" name="back_url" value="/finance/cp-auto-check-imei-list">
                    <input type="hidden" id="lot_sn" name="lot_sn" value="<?php isset($this->cp_imei) and $this->cp_imei and printf($this->cp_imei[0]['lot_sn']);?>">
                    <div class="span9">
                        <?php  
                            $cp_confirm="";
                            
                            //echo $userStorage->group_id;
                            if (My_Staff_Group::inGroup($userStorage->group_id, array(ADMINISTRATOR_ID, FINANCE_CONFIRM_PRICE_PROTECTION)) or ($exception_case and in_array
                                ($userStorage->id, $exception_case))){
                                $cp_confirm="";
                            }else{
                                $cp_confirm="disabled='true'";
                            }

                            $chk = $this->imei_check_confirm[0];
                            if($chk['total_imei']==$chk['total_finance_confirm_imei']){
                                $cp_confirm="disabled='true'";
                            }

                        ?>
                        <div class="span2">  
                            <button type="submit" class="btn btn-primary save_data">Save</button>
                            <button type="button" class="btn btn-danger go-back">Go back</button>
                        </div>
                        <div class="span6">
                            
                            <button type="submit" <?php echo $cp_confirm; ?> value="finance_confirm" name="imei_confirm" id="imei_confirm" style="text-align: right;" class="btn btn-success imei_confirm">Approve by AC MGR</button>

                        </div>

                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <hr>
        <div class="row">

            <div class="span3">

                <label style="display: none;" for="imei" class="span2">IMEI SN:
                    <?php if ($this->sales){
                        $num_imei=0; 
                        foreach ($this->imei_return as $imei){
                           $imei_return_list .= $imei['imei_sn']."\n";
                           $num_imei +=1;
                       }

                       ?>
                       <textarea name="imei" id="imei" cols="20" rows="10"><?=$imei_return_list?></textarea>
                       <?php }else{ ?>
                       <textarea name="imei" id="imei" cols="20" rows="10"></textarea>
                       <?php } ?>
                   </label>
                   <div class="span12">
                    <button style="display: none;" type="button" class="btn btn-check-imei btn-success">Check Imei</button>
                </div>
                <div class="row">

                    <div class="span3">

                        <label class="span4"></p>
                            <span><strong id="num_imei">
                                <?php
                                if ($this->sales){
                                 echo $num_imei;     
                             }else{
                                 echo "0";     
                             }
                             ?>
                         </strong> IMEI</span>
                     </label>


                 </div>

             </div>

        <div class="row">
            <div class="span3">
                <?php 
                    $num_imei_log=0; $imei_not_list="";
                    //print_r($this->imei_check_log['result_check_imei']);

                    foreach ($this->imei_check_log['result_check_imei'] as $imei){
                       if($imei['imei_sn']!=""){
                           $imei_not_list .= $imei['imei_sn']."\n";
                           $num_imei_log +=1;
                       }
                   }
                   ?>
                <p/><span style="color: red">Imei ທີ່ບໍ່ສາມາດໃຊ້ງານໄດ້ *</span>
                    <span><strong id="num_imei"><?php echo $num_imei_log;?> IMEI</strong></span>
                <p/>
                <label for="" class="span2">  
                   <textarea readonly="true" class="imei_not_cp" name="imei_not_cp" id="imei_not_cp" cols="20" rows="5"><?=$imei_not_list?></textarea>
                   <?php  ?>
                </label>
            </div>

            <div class="span3"> 
                <?php 
                    $num_imei_log=0; $imei_not_list="";
                    //print_r($this->imei_check_log);
                    foreach ($this->imei_check_log['result_check_timing'] as $imei){
                       if($imei['imei_sn']!=""){
                           $imei_not_list .= $imei['imei_sn']."\n";
                           $num_imei_log +=1;
                       }
                   }
                   ?>
                <p/><span style="color: red">Imei (ວັນລາຍງານຍອດຕ່ຳກ່ວາວັນປັບລາຄາ)*</span>
                    <span><strong id="num_imei"><?php echo $num_imei_log;?> IMEI</strong></span>
                <p/>
                <label for="" class="span2"> 
                   <textarea readonly="true" class="imei_not_cp" name="imei_not_cp" id="imei_not_cp" cols="20" rows="5"><?=$imei_not_list?></textarea>
                   <?php  ?>
                </label>
            </div>

            <div class="span3">
                <?php 
                    $num_imei_log=0; $imei_not_list="";
                    //print_r($this->imei_check_log['result_check_imei']);

                    foreach ($this->imei_check_log['result_check_imei'] as $imei){
                       if($imei['imei_sn']!="" && $imei['remark']=='duplicate'){
                           $imei_not_list .= $imei['imei_sn']."\n";
                           $num_imei_log +=1;
                       }
                   }
                   ?>
                <p/><span style="color: red">Imei ທີ່ມີຊ້ຳກັບການປັບລາຄານີ້ *</span>
                    <span><strong id="num_imei"><?php echo $num_imei_log;?> IMEI</strong></span>
                <p/>
                <label for="" class="span2">
                   <textarea readonly="true" class="imei_not_cp" name="imei_not_cp" id="imei_not_cp" cols="20" rows="5"><?=$imei_not_list?></textarea>
                   <?php  ?>
                </label>
            </div>
        </div>


</div>

<div class="span9">   
    <div class="SearchBoxImei">                       
        <table id="return_by_distributorTable" class="table table-bordered">
            <thead>
                <tr>
                    <?php echo $this->sorting(array(
                        '#',
                        'store_code'  => 'Store Code',
                        'title'  => 'Distributor Name',
                        'rank_price'  => 'Rank Price',
                        'margin'  => 'Margin',
                        'type_name'  => 'Imei Type',
                        'total_imei'  => 'Total Imei',
                        'spc_discount'  => 'Special Discount',
                        'sale_off_percent'  => 'Sell Off Discount',
                        'unit_price'  => 'Unit Price',
                        'total_amount'  => 'Total Amount',
                        'invoice_price'  => 'Invoice Price',
                        'active_cn'  => 'เปิดใช้งาน <br><input type="checkbox" class="active_cn_all" name="active_cn_all" />',
                        'creditnote_sn'  => 'Creditnote No',
                        'money_to_d_id'  => 'ร้านลูกตู้(บุญชัย)ที่ได้รับเงิน',
                        'imei_list'  => 'Imei List',
                        'delete_cn'  => 'ลบข้อมูล',
                    ),
                    $this->url, $this->sort, $this->desc); ?>
                </tr>
            </thead>
            <tbody>
                <?php
                $row=1;$imei_total=0;$total_price=0;
                $max = count($this->imei_check['result_by_imei']);
                $imei_array = $this->imei_check['result_by_imei'];
                //print_r($this->imei_check['result_by_imei']);
                foreach ($this->imei_check['result_by_distributor'] as $imei)
                {
                    $imei_list_show='';$key_cp='';

                            //$key_cp=$imei['distributor_id'].'-'.$imei['type'].'-'.$imei['margin'].'-'.$imei['creditnote_sn'];
                    for ($j = 0; $j < $max; $j++)
                    {
                        if($this->group_by_imei=="1")
                        {
                                //print_r($imei);die;
                                $imei_list_show = trim($imei['imei_sn']).",";
                                $key_cp=rtrim($imei_list_show, ',');
                        }else{
                            if($imei['distributor_id']==$imei_array[$j]['distributor_id'] && $imei['unit_price']==$imei_array[$j]['unit_price'] && $imei['type']==$imei_array[$j]['type'] && $imei['margin']==$imei_array[$j]['margin']&& $imei['creditnote_sn']==$imei_array[$j]['creditnote_sn'] && $imei['invoice_price']==$imei_array[$j]['invoice_price']){


                                    $imei_list_show .= trim($imei_array[$j]['imei_sn']).",";
                                    $key_cp=rtrim($imei_list_show, ','); 
                            }
                        }
                        if($imei['creditnote_sn']==''){
                            $key_imei=$imei['creditnote_sn'].';'.$key_cp;
                        }else{
                            $key_imei=$imei['creditnote_sn'].';'.$key_cp;
                        }
                    }
                        if($imei['creditnote_sn'] !=""){
                            $delete_cn_active="disabled='true'";
                            $delete_cn_imei="";
                        }else{
                            $delete_cn_active="";
                            $delete_cn_imei=rtrim($imei_list_show, ',');
                        }
                    ?>
                    <tr>
                        <td><?php echo $row;?><input type='hidden' value='<?php echo $imei['distributor_id']?>' name='d_id[]'/></td>
                        <td><?php echo $imei['store_code']?></td>
                        <td><?php echo $imei['title']?></td>
                        <td><?php echo $imei['rank_price_name']?></td>
                        <td style="text-align: center;"><?php echo $imei['margin']?>%</td>
                        <td style="text-align: center;"><?php echo $imei['type_name']?></td>
                        <td style="text-align: center;"><?php echo $imei['count_imei']?></td>
                        <td style="text-align: center;"><?php echo number_format($imei['spc_discount'],0)?>%</td>
                        <td style="text-align: center;"><?php echo number_format($imei['sale_off_percent'],0)?>%</td>
                        <td style="text-align: center;"><?php echo number_format($imei['unit_price'],2)?></td>
                        <td style="text-align: center;"><?php echo number_format($imei['cn_price'],2)?></td>
                        <td style="text-align: center;"><?php echo number_format($imei['invoice_price'],2)?></td>
                        <td style="text-align: center;" ><input class='active_cn' <?php if($imei['active_cn']=='1'){echo "checked=true";} ?> name='active_cn[]' value='<?php echo $key_imei?>' type='checkbox'/></td>
                        <td style="text-align: center;width: 100px;"><?php echo $imei['creditnote_sn']?></td>
                        <td>
                            <?php 
                            $show_sub_d_id="";//บริษัท บุญชัย
                            //print_r($imei);
                            if($this->group_by_imei=="1")
                            {
                                $show_sub_d_id_required=" required='required'";
                            }
                            if (!in_array($imei['distributor_id'],array(38243,3691))){ $show_sub_d_id="disabled";$show_sub_d_id_required=""; }?>
                            <select class='span2 sub_d_id_list' name='sub_d_id_list[]' <?php echo $show_sub_d_id;?><?php echo $show_sub_d_id_required;?>  >
                                <option value=''>-- Please select --</option>
                                <?php foreach ($this->sub_d_id as $sub_d_id):
                                    ?> 
                                    <option class="sub_d_id_<?php echo $sub_d_id->id;?>" value='<?php echo $imei['imei_sn'];?>-<?php echo $imei['distributor_id'];?>-<?php echo $sub_d_id->id;?>' <?php if($sub_d_id->id==$imei['sub_d_id']){?> selected<?php };?>><?php echo $sub_d_id->title."(".$sub_d_id->id.")";?></option> 
                                    <?php 
                                endforeach;?>
                            </select>
                        </td>
                        <td><textarea name='imei_list_show[<?php echo $imei['creditnote_sn']?>]' class='span2 imei_list_show'><?php echo rtrim($imei_list_show, ',');?></textarea></td>
                        <td><button  type="submit" <?php echo $delete_cn_active; ?> value="<?php echo $delete_cn_imei;?>" name="delete_cn[]" id="delete_cn" style="text-align: right;" class="btn btn-danger delete_cn">ลบ</button></td>
                    </tr>

                    <?php
                    $row +=1;
                    $imei_total += $imei['count_imei'];
                    $total_price += str_replace(',', '', $imei['cn_price']);

                }
                ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td style="text-align: center;"><?php echo number_format($imei_total,0); ?></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td style="text-align: center;"><?php echo number_format($total_price,2); ?></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr> 
            </tbody>
        </table>


    </div>

</div>


</div>
</div>
</div>

</br>

</form>
</div>
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script src="/js/jquery.blockUI.js"></script>

<style>
.blockOverlay{
    z-index: 10000 !important;
}
.blockPage{
    z-index: 10001 !important;
}
#SearchBox{
  width: 360px!important;
}
#distributor_id{
  z-index: 0!important;
}
.dropdown{
  z-index: 2;
  }.span122 {
    margin-left: : 25px;
}
.SearchBoxImei{
    width: 1000px!important;
    margin-left: : 25px!important;
}

</style>

<script>
    $(document).ready(function () {
        //initSearchOptionDistributor('distributor_id', 'SearchBox');
        initGoBack();
        initReset();
        initShowIMEINum();
        initCheckCPImei();
        $('.active_cn_all').change(active_cn_all);

        $(document).on('focus',".cp_date", function(){ 
         $(this).datepicker({ dateFormat: "dd/mm/yy" });
     });

        $(document).ajaxStart(function(){
            $.blockUI({ css: { 
                border: 'none', 
                padding: '15px', 
                backgroundColor: '#000', 
                '-webkit-border-radius': '10px', 
                '-moz-border-radius': '10px', 
                opacity: .5, 
                color: '#fff' 
            } });
        });

        function active_cn_all(e) {
            _self = $(e.target);
            var div_parent = _self.parent().parent();
            $('.active_cn').prop('checked', _self.is(":checked"));
        }

        $(document).ajaxStop(function(){
            $.unblockUI();
        });

        $('.save_data').click(function(event)
        {
            if (confirm('ต้องการบันทึกข้อมูลใช่หรือไม่ ?')){
            // return  true;
            }else{
                event.preventDefault();
                // $('#submit_btn').removeAttr('disabled');
                $.unblockUI();
                return  false;
            }

        }); 

        $('.imei_confirm').click(function(event)
        {
            if (confirm('ยืนยันการปรับราคา ใช่หรือไม่ ?')) {
                $('#form').submit();
            }else{
                event.preventDefault();
                $.unblockUI();
                return  false;
            }

        }); 

        $('.delete_cn').click(function(event)
        {
            if (confirm('ต้องการลบข้อมูลใช่หรือไม่ ?')) {
            // return  true;
            }else{
                event.preventDefault();
                // $('#submit_btn').removeAttr('disabled');
                $.unblockUI();
                return  false;
            }

        }); 

        $(document).on("submit", "form", function(e){

            $.blockUI({ css: { 
                border: 'none', 
                padding: '15px', 
                backgroundColor: '#000', 
                '-webkit-border-radius': '10px', 
                '-moz-border-radius': '10px', 
                opacity: .5, 
                color: '#fff' 
            } });

            // $.unblockUI();

        });

        $('#ifrmSave').load(function() {
            $.unblockUI();
        });

        $('.good_id_sel').click(function(e){
            var g_id = $(this).val();
            if (g_id != ''){
                $('#good_id').val(g_id); 
            }   
         });

        var check_edit = $('#check_edit').val();
        if(check_edit==1){
            $(document).off('focus','.cp_date');
            $('.cp_date').attr('readonly', true);
            $('.price').attr('readonly', true);
            $('.new_price').attr('readonly', true);
            $('.remark').attr('readonly', true);
            $('.detail').attr('readonly', true);
            $('.price_limit').attr('readonly', true);
        }else{
            $(document).on('focus','.cp_date');
            $('.cp_date').attr('readonly', false);
            $('.price').attr('readonly', false);
            $('.new_price').attr('readonly', false);
            $('.remark').attr('readonly', false);
            $('.detail').attr('readonly', false);
            $('.price_limit').attr('readonly', false);
        }

    });

    <?php if(isset($this->sales[0]['sale']->return_type) && $this->sales[0]['sale']->return_type){?>
        $('#return_type').val('<?=$this->sales[0]['sale']->return_type;?>');
        <?php } ?>

        function initShowIMEINum(){
            $('#imei').keyup(function (e){

                var inputnum = 0;

                if ($(this).val() != '')
                    inputnum = ($(this).val().split("\n").length).toString();


                $('#num_imei').html(inputnum);

            });
        }

        function initGoBack(){
            $('.go-back').click(function(e){
                window.location.href = $('#back_url').val();
                return false;
            });
        }

    //Only number and one dot
    function onlyDecimal(element, decimals)
    {
        $(element).keypress(function(event)
        {
            num = $(this).val() ;
            num = isNaN(num) || num === '' || num === null ? 0.00 : num ;
            if ((event.which != 46 || $(this).val().indexOf('.') != -1) && (event.which < 48 || event.which > 57))
            {
                event.preventDefault();

            }
            if($(this).val() == parseFloat(num).toFixed(decimals))
            {
                event.preventDefault();
            }
        });
    }

    function initCheckCPImei()
    {
        $('.btn-check-imei').click(function(e){

            var imei = $('#imei').val();
            if (imei == ''){
                alert('Please Input Imei SN !');
                return;
            }

            var imei_v = $.trim(imei).split("\n");
            var imei_list = '';
            
           /* $.each(imei_v , function(i, val) { 
                imei_list += $.trim(imei_v[i])+',';
            });*/

            $.each(imei_v , function(i, val) { 
                imei_list += "'"+$.trim(imei_v[i])+"',";
            });

            var lot_sn = $('#lot_sn').val();
            var price = $('#price').val();
           // distributor_id=1266;warehouse_id=1;
           

           $.post("/get/check-price-protection-imei-auto-check",
            {lot_sn: lot_sn,price: price, imei_list: imei_list.slice(0, -1)}
            ,function(data,status){
                console.log(data);

                $('#data_phone').val(data);
                var data = $.parseJSON(data);

                   // $('.data_phone_return').val('');
                   if (data.check==1){
                    var obj = data.result_return_by_distributor;
                    var obj_imei = data.result_return_by_imei;
                    var total_row = obj.length-1;var j=1;
                        //$('#myTable').empty();

                        
                        //$('#result_return_by_imei').val(obj_imei);
                        $('#return_by_distributorTable tbody').remove();
                        for (var i = 0; i < obj.length; i++)
                        {
                            var imei_list_show='';
                            for (var j = 0; j < obj_imei.length; j++)
                            {
                                if(obj_imei[j]['distributor_id']==obj[i]['distributor_id']){
                                    imei_list_show += $.trim(obj_imei[j]['imei_sn'])+",";
                                }
                            }
                            //imei_list "+imei_list_show+"
                            if(obj[i]['distributor_id'] != null){
                                $('#return_by_distributorTable').append("<tr><td>"+j+"<input type='hidden' value='"+obj[i]['distributor_id']+"' name='d_id[]'/></td><td>"+obj[i]['store_code']+"</td><td>"+obj[i]['title']+"</td><td>"+obj[i]['rank_price_name']+"</td><td>"+obj[i]['count_imei']+"</td><td>"+obj[i]['unit_price']+"</td><td>"+obj[i]['cn_price']+"</td><td><input class='active_cn' name='active_cn[]' value='"+obj[i]['distributor_id']+"' checked='true'  type='checkbox'</input></td><td><textarea name='remark_text[]' class='span2 remark_text'></textarea></td><td><textarea name='imei_list_show[]' class='span2 imei_list_show'>"+imei_list_show.substring(0, imei_list_show.length - 1)+"</textarea></td></tr>");

                                j +=1;
                            }
                            
                        }

                    }else if(data.check==2){
                        alert('Imei Exist in Return Data!');
                        //$('select, input:text, input.num, input.price, input.total').val('');
                    }else{
                        alert('No Data !');
                        //$('select, input:text, input.num, input.price, input.total').val('');
                    }
                });

           return false;
       });
    }

    function initReset(){
        $('button.btn-reset').click(function(e){
            e.preventDefault();
            $('select, input:text, input.num, input.price').val('');
            $('textarea').val('');

            $('#num_imei').html(0);
        })
    }
</script>
<style>
label input,
label select {
  margin-right: 25px;
}
</style>