<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link href="<?php echo HOST ?>css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="<?php echo HOST ?>css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">
<style>
  /*  #d_id{
        margin-left: 0px!important;
        left: 0px!important;
        width: 370px;
    }*/

    #sn_munti{
        width: 256px;
        background-color: #fff;
        border: 1px solid #ccc;
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
        display: inline-block;
        padding: 4px 6px;
        margin-bottom: 10px;
        color: #555;
        vertical-align: middle;
        border-radius: 4px;
        max-width: 100%;
        line-height: 22px;
        cursor: text;
    }
</style>
<div class="page-header">
    <h1>Report Stock Product IN/OUT</h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 200px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('finance/partials/report-stock-product-inout-search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
    <?php
        echo $this->render('finance/partials/report-stock-product-inout-list.phtml');
    ?>
</div>

<script type="text/javascript" src="/js/jets.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>

<?php echo $this->confirm();?>
<script>
   

    $(document).ready(function () {

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('#cat_id, #good_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var cat_id = $('#cat_id').val();

            if (_self.attr('id')=='cat_id')
                $('#good_id').find('option:not(:first)').remove();

            var good_id = $('#good_id').val();

            $('#good_color').find('option:not(:first)').remove();

            $('#num, #price').val('');

            $.get("/get/load-product-stock",
                {cat_id: cat_id, good_id: good_id}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    if (data.goods){
                        var obj = data.goods;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    if (data.colors){
                        var obj = data.colors;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    _self.nextAll('.loading').remove();
                });
        });

     });   
</script>