<style type="text/css">
    .show{display: none;}

</style>


<div class="page-header" xmlns="http://www.w3.org/1999/html">
    <h1>Finance Confirm Order</h1>
</div>

<?php
//print_r($this->sales[0]['retailer_rank']);

$show_cash_menu = $this->sales[0]['show_cash_menu'];
$retailer_rank = $this->sales[0]['retailer_rank'];

$pay_time=date('Y-m-d H:i:s');

if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<div class="row">
	<div class="span12">
        <form role="form" id="form" enctype="multipart/form-data" action="<?php echo HOST.'finance/sales-confirm';?>" method="post" class="form-inline">
        	<?php if (isset($this->sales) and $this->sales):?>
        		<div class="row">
        			<div class="span8">
        				<label class="span3">Sales order number</label>
		                <span class="span3"><strong><?php if(isset($this->sales) and isset($this->sales[0]['sale']->sn)) echo $this->sales[0]['sale']->sn_ref;?></strong></span>
        			</div>
        		</div>
            <?php endif;?>

			<div class="row">
    			<div class="span8">
                    <label class="span3">Warehouse</label>
                    <span class="span3"><strong><?php echo $this->sales[0]['warehouse_name'];?></strong></span>
            	</div>
    		</div>

			<div class="row">
    			<div class="span8">
                    <label class="span3">Retailer name</label>
                    <span class="span3"><strong><?php echo $this->sales[0]['retailer_name'];?></strong></span>
            	</div>
    		</div>

            <div class="row">
                <div class="span8">
                    <label class="span3">Maximun Credit</label>
                    <span class="span3" ><font id="f_amount" ><strong id="s_amount"><?php echo number_format($this->sales[0]['credit_amount'],2); ?></strong></font></span>
                </div>
            </div>

            <div class="row">
                <div class="span8">
                    <label class="span3">Credit type</label>
                    <span class="span3"><strong><?php echo $this->sales[0]['credit_type'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span8">
                    <label class="span3">Main Retailer</label>
                    <span class="span3"><strong><?php echo $this->main_retailer['title'];?></strong></span>
                </div>
            </div>

			<div class="row">
    			<div class="span8">
                    <label class="span3">Sales Admin</label>
                    <span class="span3"><strong><?php echo $this->sales[0]['salesman_name'];?></strong></span>
            	</div>
    		</div>

            <div class="row">
                <div class="span8">
                    <label class="span3">Sales Catty</label>
                    <span class="span3"><strong><?php echo $this->sales[0]['salescatty_name'];?></strong></span>
                </div>
            </div>

			<div class="row">
    			<div class="span8">
                    <label class="span3">Order maker</label>
                    <span class="span3"><strong><?php echo $this->sales[0]['created_by_name'];?></strong></span>
            	</div>
    		</div>

            <div class="row">
                <div class="span8">
                    <label class="span3">Order time</label>
                    <span class="span3"><strong><?php echo $this->sales[0]['sale']->add_time;?></strong></span>
                </div>
            </div>

			<div class="row">
    			<div class="span8">
                    <label class="span3">Order Type</label>
                    <span class="span3"><?php echo My_Sale_Order_Type::getLabel($this->sales[0]['sale']['type']) ?></span>
            	</div>
    		</div>

            <div class="row">
                <div class="span8">
                    <label class="span3">Balance for this retailer:</label>
                    <span class="span3"><strong><?php echo number_format($this->distributor_balance);?></strong></span>
                </div>
            </div>


    		<div class="row">
    			<div class="span8">
                    <label class="span3">Total Remain balance (main and sub retailer):</label>
                    <span class="span3"><strong><?php echo number_format($this->remain_balance);?></strong></span>
            	</div>
    		</div>


            <div class="row">
                <div class="span8 show">
                    <label class="span3">Discount (CK):</label>
                    <span class="span3"><strong><?php echo number_format($this->discount);?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span8 show">
                    <label class="span3">Discount (DIAMOND):</label>
                    <span class="span3"><strong><?php echo number_format($this->diamond_discount);?></strong></span>
                </div>
            </div>

             <div class="row">
                <div class="span8 show">
                    <label class="span3">Discount (BVG):</label>
                    <span class="span3"><strong><?php echo number_format($this->discount_bvg);?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span8">
                    <label class="span3">Office:</label>
                    <span class="span3"><strong><?php if(isset($this->office_area) AND $this->office_area) echo $this->office_area['title'];?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span12">
                    <table class="table table-bordered span12">
                        <thead>
                            <tr>
                                <th>Products category</th>
                                <th>Product</th>
                                <th>Color</th>
                                <th>Quantity</th>
                                <th>Price</th>
                                <th>Total Price</th>
                                <th>Discount</th>
                                <th>Delivery Fee</th>
                                <th>Total Amount</th>
                                <th>Remark</th>
                                <th>Campaign</th>
                            </tr>
                        </thead>

                        <tbody>

                        <?php
                        $total_num = $total_price = $total_total = 0;$total_discount=0;

                        $list_cn='';
                        //print_r($this->sales[0]['credit_note_list']);
                         foreach ($this->sales[0]['credit_note_list'] as $k => $datas) 
                         {
                            $creditnote_sn = $datas['creditnote_sn'];
                            $total_discount += $datas['total_discount'];

                            if($creditnote_sn!=''){
                                $list_cn .=$creditnote_sn.'='.$total_discount.' B </br> ';
                            }
                         }

                        $payment_type ='';$payment_type_code ='';
                        foreach ($this->sales as $item):
                            $sale = $item['sale'];
                            $total_num += $sale->num;
                            $total_price += $sale->price;
                            //$total_discount = $item['total_discount'];
                            $payment_type_code = $sale->payment_type;
                            if($sale->payment_type=="CA"){
                                $payment_type = 'เงินสด';
                            }else if($sale->payment_type=="CR"){
                                $payment_type = 'เครดิต';
                            }

                            $delivery_fee = $sale->delivery_fee;
                            $total_total += $sale->total;
                            $total_amount = $total_total-$total_discount+$delivery_fee;

                        ?>

                            <tr>
                                <td><?php if(isset($item['category'])) echo $item['category'];?></td>
                                <td><?php if(isset($item['good'])) echo $item['good'];?></td>
                                <td><?php if(isset($item['color'])) echo $item['color'];?></td>
                                <td><?php if(isset($sale->num)) echo $sale->num;?></td>
                                <td><?php if(isset($sale->price)) echo My_Number::f($sale->price);?></td>
                                <td><?php if(isset($sale->total)) echo  My_Number::f($sale->total);?></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td><?php if(isset($sale->text)) echo $sale->text;?></td>
                                <td><?php if(isset($this->campaign[$sale->campaign])) echo $this->campaign[$sale->campaign];?></td>
                            </tr>

                        <?php endforeach;?>

                        </tbody>

                        <tfoot>
                            <tr>
                                <td colspan="3"><strong>SUMMARY</strong></td>
                                <td><strong><?php echo $total_num;?></strong></td>
                                <td><strong></td>
                                <td><strong id="s_total" ><?php echo  My_Number::f($total_total);?></strong></td>
                                <td><strong id="s_total" ><?php echo  My_Number::f($total_discount);?></strong></td>
                                <td><strong id="s_total" ><?php echo  My_Number::f($delivery_fee);?></strong></td>
                                <td><strong id="s_total" ><?php echo  My_Number::f($total_amount);?></strong></td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                            </tr>
                        </tfoot>
                    </table>
                    <!-- include view table discount -->
                    <?php echo $this->render('finance/partials/table-discount.phtml');?>
                    <!-- include view table bvg -->
                    <?php echo $this->render('finance/partials/table-bvg.phtml'); ?>
                    <!-- include view table fee -->
                    <?php //echo $this->render('finance/partials/table-fee.phtml'); ?>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Credit Note Discount List</label>
                    <span class="span3">
                        <?php
                            echo $list_cn;
                        ?>
                    </span>
                </div>
            </div>
            <div class="row">
                <div class="span6">
                    <label class="span2">Shipping  <span style="color: red">* </span></label>
                    <span class="span3"><input id="shipping" checked name="shipping" type="checkbox" value="1">
                    </span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Payment Type <span style="color: red">* </span></label>
                    <span class="span2">
                    <input type='text' name='payment_order' 
                     value="<?php echo $payment_type;?>" readonly="true"/>
                     </span>
                </div>
            </div>           

            <div class="row">
                <div class="span6">
                    <label class="span2">  </label>
                    <?php if($payment_type_code=='CA'){ ?>
                        <span class="span2">
                            <label >Company</label>
                            <select name="show_company_id" id="show_company_id" class="show_company_id" readonly="readonly" disabled="true">
                                    <option value="">choose</option>
                                    <option selected value="1">OPPO</option>
                                    <option value="2">SMARTMOBILE</option>
                                </select>
                             </p></p>
                             <?php  
                             $uploaded_dir = HOST . 'public' . DIRECTORY_SEPARATOR . 'files'
                             . DIRECTORY_SEPARATOR . 'finance';

                             for($i=0;$i<count($this->transaction);$i++){

                                $file_pay_slip = $uploaded_dir.$this->transaction[$i]['file_pay_slip'];

                              ?>
                            <label >Bank</label>
                            <label >Payment Order</label>
                            <input type='text' name='payment_order' 
                            value="<?php echo $this->transaction[$i]['bank_name'];?>" readonly="true"/>


                                
                            <label >Payment Order</label>
                            <input type='text' name='payment_order' readonly="true" 
                            value="<?php echo number_format($this->transaction[$i]['pay_money'],2);?>" />

                            <label >Fee Bank Transfer</label>
                            <input type='text' name='pay_banktransfer' readonly="true" 
                            value="<?php echo number_format($this->transaction[$i]['pay_banktransfer'],2);?>" />

                            <label >Service Charge</label>
                            <input type='text' name='pay_servicecharge' readonly="true" 
                            value="<?php echo number_format($this->transaction[$i]['pay_servicecharge'],2);?>" />

                            <label >ค่าอะไหล่และค่าบริการ</label>
                            <input type='text' name='pay_service' readonly="true" 
                            value="<?php echo number_format($this->transaction[$i]['pay_service'],2);?>" />

        <label>Date time:</label>
        <input type='text' name='pay_time' id='pay_time' readonly class='form-control datepicker' autocomplete='off' 
        value="<?=$this->transaction[$i]['pay_time']?>" 
        />

                            <label >Payment Slip</label>
                            <img class="badge badge-default" data-file-pay-slip="<?php echo $this->transaction[$i]['file_pay_slip']; ?>" src="<?php echo $file_pay_slip; ?>" alt="Payment Slip" height="100" width="100">
                            </br></br>
                            <?php } ?>
                        </span>
                        <?php } ?>
                </div>
                

                <div class="span6">
                    <div class="control-group">
                        <label for="myTags" class="span2">Tags
                            <ul class="form-control span3" id="myTags"><?php
                            if (isset($this->a_tags) and $this->a_tags):
                                foreach ($this->a_tags as $ta)
                                    echo '<li>'.$ta.'</li>';
                            endif;
                            ?></ul>
                        </label>
                    </div>
                </div>
            </div>
            </p></p>
            

            <div class="row">
                <div class="span12">
                    <label class="span2">Payment Notes</label>

                    <span class="span4"><textarea name="pay_text" class="span2"><?php if(isset($this->sales[0]['sale']->pay_text)) echo $this->sales[0]['sale']->pay_text;?></textarea></span>
                </div>
            </div>

            <div class="row">
                <div class="span12">
                    <label class="span2">Delivery Notes</label>
                    <span class="span4"><textarea name="shipping_text" class="span2"><?php if(isset($this->sales[0]['sale']->shipping_text)) echo $this->sales[0]['sale']->shipping_text;?></textarea></span>
                </div>
            </div>

            <div class="row">
                <div class="span12">
                    <span class="span4" style="color: red">* Please confirm information,This action can not be reversed!!...</span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <div class="control-group">
                        <input type="hidden" name="sn" value="<?php isset($this->sales) and $this->sales and printf($this->sales[0]['sale']->sn);?>">
                        <div class="span4">
                            <button type="submit" class="btn btn-primary">Confirm</button>
                            <input type="hidden" name="back_url" id="back_url" value="/finance/sales">
                            <input type="hidden" name="company_id" id="company_id" value="1">
                            <input type="hidden" name="payment_type" class ="payment_type" id="payment_type" value="<?=$payment_type_code?>">
                            <input type="hidden" name="total_amount" class ="total_amount" id="total_amount" value="<?=$total_amount?>">
                            <input type="hidden" name="retailer_rank" class ="retailer_rank" id="retailer_rank" value="<?=$retailer_rank?>">
                            <button type="button" class="btn btn-danger go-back">Go back</button>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </form>
    </div>
</div>
<div id='dialog' title='message'></div>
<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>

<script src="<?php echo HOST?>js/jquery.datetimepicker.js"></script>

<link rel="stylesheet" href="<?php echo HOST?>css/jquery-ui.css">
<script src="<?php echo HOST?>js/jquery-ui.js"></script>
<script src="<?php echo HOST?>js/numeral.min.js"></script>

<script src="../js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>
<link href="../css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="../css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="<?php echo HOST?>css/jquery.datetimepicker.css" />
<link rel="stylesheet" type="text/css" href="/css/bootstrap-modal.css"/>
<script type="text/javascript" src="/js/bootstrap-modal.js"></script>
<script type="text/javascript" src="/js/bootstrap-modalmanager.js"></script>

<script>

 

if ($('#s_total').html() > $('#s_amount').html()) {
    $('#f_amount').attr('color','red');
}


    function initTag(){

        $('#myTags').tagit({
            allowSpaces: true,
            fieldName: 'tags[]',
            autocomplete: {
                delay: 0,
                minLength: 2,
                source: "<?php echo HOST;?>get/get-tags"
            }
        });

    }

    function initDatepicker(){
        $( ".datetimepicker" ).datetimepicker({
            format:'Y-m-d H:i'
        });
    }

    function initRemoveBank(){
        $('.remove-bank').click(function(e){
            $(this).parent().parent().parent().remove();
            $('#div-company').hide();
            return false;
        });
    }

    function initAddBank(){
        $('.add-bank').click(function(e){
            var old_div = $('.div-payment_cash');
            var new_div = old_div.clone();

            new_div.insertAfter($(this).parent().parent().parent()).show();

            initRemoveBank();

            return false;
        });
    }

    $(document).ready(function () {
        initTag();
        initDatepicker();
        initAddBank();
        initRemoveBank();


        //------------View Pay Slip------------------
        
        $modal = $('#modal');
        $('.badge.badge-default').click(function(){
            _self = $(this);
            $('body').modalmanager('loading');
            $.post('<?php echo HOST ?>finance/view-pay-slip',
                {
                    file_pay_slip : _self.data('file-pay-slip')
                },
                function(data){
                    //alert(data);
                    $modal.html(data);
                    $modal.modal();
                    var name = _self.parents('tr').children('td:nth-child(1)').html();
                    $modal.find('h3').append(' <small>&bull; '+name+'</small>');
            });
            
        });


        //------------------------------

        $('#form').submit(function (e){
            return true;
        });
        initGoBack();
    });

    function initGoBack(){
        $('.go-back').click(function(e){
            window.location.href = $('#back_url').val();
            return false;
        });
    }



</script>
<style>
	label input,
	label select {
		margin-right: 25px;
	}
</style>