<div id="confirm_modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Confirm &bullet; <span class="staff_name"></span></h3>
    </div>
    <div class="modal-body">
        <p>Note:</p>
        <textarea class="note" maxlength="255"></textarea>
    </div>
    <div class="modal-footer">
        <button class="btn btn-info confirm_btn">Confirm</button>
        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>