<div class="page-header">
    <h1>Delivery <small>order control</small></h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="row">
    <div class="span12">
        <p class='pull-right'><a href="<?php echo HOST ?>delivery/mass-update-status" class="btn btn-success btn-mini"><span><i class="icon-list"></i> Mass Update Status</span></a></p>
    </div>
</div>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('delivery/partials/order-control-search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive" id="table">
    <?php
        echo $this->render('delivery/partials/order-control-list.phtml');
    ?>
</div>

<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        $('.get_detail_btn').click(get_detail);
    });

    function get_detail(e) {
        _self = $(e.target);
        _item = _self.parents('.item');

        if (_item.hasClass('expanded')) {
            _item.next('tr').remove();
            _item.removeClass('expanded');
            _self.text('+');
            return false;
        }

        id = _self.data('id');

        if (!id) return false;

        $('.loading').remove();

        _self.html('<span class="loading"></span>')

        $.ajax({
            url: '<?php echo HOST ?>get/delivery-order-detail',
            type: 'post',
            dataType: 'json',
            data: {id: id},
            cache: true
        })
        .done(function(data) {
            console.log(data);
            console.log("success");

            if (data) {
                elm = '<tr><td></td><td colspan="2">Packages: '+data.num_package+'</td><td colspan="2">Weight: '+data.weight+'</td><td colspan="6">';
                
                for (i in data.detail) {
                    elm += '<p>'+data.detail[i].cat+': ';
                    // elm += data.detail[i].good+' / ';
                    elm += data.detail[i].quantity+'</p>';
                }

                elm += '</td></tr>';
                
                _item.after(elm).addClass('expanded');
                _self.text('-');
            }
        })
        .fail(function() {
            console.log("error");
        })
        .always(function() {
            $('.loading').remove();
            console.log("complete");
        });
        
    }

    function get_sn(e) {
        _self = $(e.target);
        id = _self.data('id');

        if (!id) return false;

        _self.html('<span class="loading"></span>');
        $.ajax({
            url: '<?php echo HOST ?>delivery/get-order',
            type: 'post',
            dataType: 'json',
            data: {id: id},
        })
        .done(function(data) {
            console.log("success");

            if (data && typeof data.code !== "undefined" && data.code === 1) {
                data = data['result'];
                elm = '';
                for (i in data) {
                    
                    elm += '<a href="<?php echo HOST ?>sales/view?sn='+data[i].sn+'" target="_blank">'+data[i].sn+'</a><br />';
                }

                _self.after(elm);
                _self.remove();

            } else {
                _self.after('<span>'+data.result+'</span>');
                _self.remove();
            }
        })
        .fail(function() {
            console.log("error");
        })
        .always(function() {
            console.log("complete");
        });
        
    }
</script>