<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link href="<?php echo HOST ?>css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="<?php echo HOST ?>css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">
<div class="page-header">
    <h1>Cancel Dilivery <small>management</small></h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('delivery/partials/order-cancel-search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
    <?php
        echo $this->render('delivery/partials/order-cancel-list.phtml');
    ?>
</div>

    <div class="modal hide" id="cancelSO">
        <div class="modal-header">
            <button class="close" data-dismiss="modal">×</button>
            <h3>Cancel Delivery Confirm</h3>
        </div>
        <div class="modal-body " id="remark_">
            <p><storage>Canceled By : </storage> </p>
            <p><storage>Canceled date : </storage> </p>
            <p><storage>Remark : </storage> </p>
        </div>

        <div class="modal-footer">
            <input type="hidden" name="sn" class="sn" id="_sn" />
            <button type="button" class="btn-danger" data-dismiss="modal">Close</button>
            <button type="button" class="btn-success" id="cancel-delivery" >Confirm</button>
        </div>
    </div>





<script type="text/javascript" src="<?php echo HOST ?>js/jets.js"></script>
<!-- <script type="text/javascript" src="<?php echo HOST ?>js/bootstrap.min.js"></script> -->

<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>
<?php echo $this->confirm();?>
<script>
    function getMarketDetail(sn){
        if (! $('#m_'+sn).parent().parent().next().hasClass('accordion-body')){
            $('#m_'+sn+' .col-sign').html('');
            $('#m_'+sn+' .img-loading').show();

            $.ajax({
                type: 'get',
                url: '/get/market-detail',
                data: {
                    'sn': sn,
                    'list': 'cancel',
                    'params': '<?php echo (isset($this->params) ? serialize($this->params) : '')?>'
                },
                error: function(){
                },
                success: function(data){
                    $('.m_'+sn).remove();
                    $('#m_'+sn).parent().parent().after(data);
                    $('#m_'+sn).find('.col-sign').html('-');
                    $('#m_'+sn+' .img-loading').hide();
                }
            });
        }
    }

    function initTag(){

        $('#myTags').tagit({
            allowSpaces: true,
            fieldName: 'tags[]',
            autocomplete: {
                delay: 0,
                minLength: 2,
                source: "<?php echo HOST;?>get/get-tags"
            }
        });

    }
    // $(document).on("click", ".open-cancel", function () {
    //     var sn = $(this).data('sn');
        
    //      $(".modal-body #_sn").val(sn);
       
    // });
    $(document).on("click", ".open-cancel", function () {
        sn = $(this).data('sn');
        $(".modal-body #_sn").val(sn);
        $.ajax({
            url: '<?php echo HOST ?>get/get-mark-cancel',
            type: 'GET',
            data: {sn: sn},
        })
        .done(function(data) {
            $('#remark_').html(data);
            console.log("success");
        })
        .fail(function() {
            console.log("error");
        })
        .always(function() {
            console.log("complete");
        });
        
        
        
    });

    $(document).on("click", ".open-cancel", function () {
    var sn = $(this).data('sn');
     $("#_sn").val(sn);
    });

    $('#cancel-delivery').click(function(){
             sn = $("#_sn").val();
            $.ajax({
                url: '<?php echo HOST ?>get/mark-cancel-order-delivery',
                type: 'GET',
                data: {sn: sn},
            })
            .done(function(data) {
                    if (data==0){ //success
                        alert("ทำรายการเรียบร้อย");
                        location.reload();
                        //_self.replaceWith('<span>Canceled</span>');
                    } else if (data==-1){
                        alert('Order number is empty!');
                    } else if (data==-2){
                        alert('Order number is invalid!');
                    } else if (data==-3){
                        alert('Order status is invalid!');
                    } else if (data==-4){
                        alert('Cannot update, please try again!');
                    } else if (data==-5){
                        alert('You cannot cancel this Order!');
                    }else if (data==-6){
                        alert('This order have Create Credit Note! You cannot cancel this Order!');
                    }
                    
                console.log("success");
            })
            .fail(function() {
                console.log("error");
            })
            .always(function() {
                console.log("complete");
            });
            
        });
    $(document).ready(function () {
        
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        $(".cancel").click(function(e) {
            e.preventDefault();

            var _self = $(this);
            var sn = _self.attr('rel');

            $("#dialog").dialog({
                buttons : {
                    "Confirm" : function() {
                        $.post('<?php echo HOST ?>get/mark-cancel-order', {sn: sn}, function(data) {
                            
                            if (data==0){ //success
                                _self.replaceWith('<span>Canceled</span>');
                            } else if (data==-1){
                                alert('Order number is empty!');
                            } else if (data==-2){
                                alert('Order number is invalid!');
                            } else if (data==-3){
                                alert('Order status is invalid!');
                            } else if (data==-4){
                                alert('Cannot update, please try again!');
                            } else if (data==-5){
                                alert('You cannot cancel this Order!');
                            }else if (data==-6){
                                alert('This order have Create Credit Note! You cannot cancel this Order!');
                            }
                        });
                        $(this).dialog("close");
                    },
                    "Cancel" : function() {
                        $(this).dialog("close");
                    }
                }
            });

            $("#dialog").dialog("open");
        });

        $('.lock').click(function(e){
            e.preventDefault();
            alert('Sorry,This information is blocked...You can not delete payment has been made or has been the storage of information!');
        });

        $('.collapse_a').click(function(){
            var _this = $(this);
            var _this_id = _this.attr('id');
            var sn = _this.attr('rel');

            if (_this.parent().parent().next().hasClass('accordion-body')){

                $('.m_'+sn).toggle();

                if ($('.m_'+sn).is(':visible'))
                    _this.find('.col-sign'). html('-');
                else _this.find('.col-sign'). html('+');

            } else {
                _this.find('.col-sign'). html('');

                getMarketDetail(sn);
            }

        });

        initTag();

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('#cat_id, #good_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var cat_id = $('#cat_id').val();

            if (_self.attr('id')=='cat_id')
                $('#good_id').find('option:not(:first)').remove();

            var good_id = $('#good_id').val();

            $('#good_color').find('option:not(:first)').remove();

            $('#num, #price').val('');

            $.get("/get/load2",
                {cat_id: cat_id, good_id: good_id}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    if (data.goods){
                        var obj = data.goods;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    if (data.colors){
                        var obj = data.colors;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    _self.nextAll('.loading').remove();
                });
        });

        $('#area').change(function(){
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();

            $.get("<?php echo HOST ?>get/region",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#region').find('option:not(:first)').remove();
                    $('#district').find('option:not(:first)').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#region').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('.loading').remove();
                });
        });

        $('#region').change(function(){

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var region = _self.val();

            $('#district').find('option:not(:first)').remove();

            $.get("/get/district",
                {region: region}
                ,function(data,status){
                    var data = $.parseJSON( data );

                    for (var i = 0; i < data.length; i++) {
                        $('#district').append('<option value="'+data[i]['id']+'">'+data[i]['name']+'</option>');
                    }

                    _self.nextAll('.loading').remove();
                });
        });
    });
</script>