<style type="text/css">
    textarea {
        max-width: 100%;
    }
</style>

<div class="page-header">
    <h1>Delivery Man <small><?php if(isset($this->man)) echo "Edit"; else echo "Create"; ?></small></h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<form class="form-horizontal" action="<?php echo HOST ?>delivery/staff-save" method="post">
    <div class="control-group">
        <label class="control-label">Name</label>
        <div class="controls">
            <input type="text" placeholder="Name" id="name" name="name" value="<?php if(isset($this->staff['username'])) echo $this->staff['username'] ?>" disabled>
        </div>
    </div>
    
    <div class="control-group">
        <label for="hub_id" class="control-label">Hub</label>
        <div class="controls">
            <div id="group_list">
                <?php if (isset($this->hub) && $this->hub): ?>
                    <?php foreach ($this->hub as $key => $value): ?>
                        <div class="list_item">
                            <select id="hub_id" name="hub_id[]">
                                <option value>----</option>
                                <?php if (isset($this->hubs) && $this->hubs): ?>
                                    <?php foreach ($this->hubs as $_id => $item):?>
                                        <option value="<?php echo $_id;?>" <?php if ($value['hub_id'] and $_id==$value['hub_id']):?>selected<?php endif;?>><?php echo $item;?></option>
                                    <?php endforeach;?>
                                <?php endif ?>
                            </select>
                        </div>
                    <?php endforeach ?>
                <?php else: ?>
                    <div class="list_item">
                        <select id="hub_id" name="hub_id[]">
                            <option value>----</option>
                            <?php if (isset($this->hubs) && $this->hubs): ?>
                                <?php foreach ($this->hubs as $_id => $item):?>
                                    <option value="<?php echo $_id;?>"><?php echo $item;?></option>
                                <?php endforeach;?>
                            <?php endif ?>
                        </select>
                    </div>
                <?php endif ?>
            </div>
        </div>
    </div>
    
    <div class="control-group">
        <label for="carrier_id" class="control-label">Carrier</label>
        <div class="controls">
            <select id="carrier_id"  name="carrier_id">
                <option value>----</option>
                <?php foreach (My_Carrier::$name as $_id => $_name):?>
                    <option value="<?php echo $_id;?>" <?php if (isset($this->carrier['carrier_id']) and $_id==$this->carrier['carrier_id']):?>selected<?php endif;?>><?php echo $_name;?></option>
                <?php endforeach;?>
            </select>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <input type="hidden" name="staff_id" value="<?php if(isset($this->staff['id'])) echo $this->staff['id'] ?>">
            <input type="hidden" name="refer" value="<?php if(isset($this->refer)) echo $this->refer ?>">
            <button class="btn btn-primary">Save</button>
            <a href="<?php echo My_Url::refer('delivery/staff') ?>" class="btn btn-default">Cancel</a>
        </div>
    </div>
</form>

<script type="text/javascript">
select_cbb_html = '<div class="list_item new">'+
'<select id="hub_id" name="hub_id[]">' +
    '<option value>----</option>' +
    '<?php if (isset($this->hubs) && $this->hubs): ?>' +
        '<?php foreach ($this->hubs as $_id => $item):?>' +
            '<option value="<?php echo $_id;?>"><?php echo $item;?></option>' +
        '<?php endforeach;?>' +
    '<?php endif ?>' +
'</select> '+
'</div>';


$(document).ready(function() {
    $('#group_list').addMore({
        select_html: select_cbb_html
    });
});
</script>