<div class="page-header">
    <h1>Last Input</h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="row">
    <div class="span12">
        <span class="pull-right">
            <button type="button" class="btn btn-success" onclick="window.open('<?php echo HOST ?>checkmoney/add','_blank');"><i class="icon-plus"></i></button>
        </span>
    </div>
</div>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                   echo $this->render('checkmoney/partials/search_last_input.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
 	<?php
        echo $this->render('checkmoney/partials/list_last_input.phtml');
    ?>
</div>

<link rel="stylesheet" href="<?php echo HOST?>css/checkmoney.css" />
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" href="<?php echo HOST?>js/chosen.css" />
<script src="<?php echo HOST?>js/chosen.jquery.js"></script>

<?php echo $this->load();?>
<?php echo $this->confirm();?>
<script>
    $(document).ready(function(){
		$( ".datepicker" ).datepicker({ dateFormat: "yy-mm-dd" }); 
		
		$('.confirmLink').bind("contextmenu",function(e){
		    return false;
		});
		
	    $('.lock').click(function(e){
	        e.preventDefault();
	        alert('Sorry,This information is blocked...You can not delete payment has been made or has been the storage of information!');
	    });
	    
	    $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        initSearchOptionDistributor('d_id', 'SearchBox');

    })
</script>