<div class="page-header">
    <h1>Product List</h1>
    <small> ລາຍການສິນຄ້າ </small>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('product/product/partials/search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="span12">
        <span class="pull-right">
            <button class="btn-success" type="button" onclick="window.location='<?php echo HOST ?>product/product-create'">
                <i class="icon-plus"></i>
            </button>
        </span>
    </div>
</div><div class="table-responsive load-ajax">
    <?php
        echo $this->render('product/product/partials/list.phtml');
    ?>
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>

<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });


    //Update By PungPond
    function change_price(id,price,name){  
              var html = "<form class='form-horizontal' action='<?php echo HOST ?>product/product-update' name='form'  method='post'>";
                  html += "<div class='control-group'>";
                  html += "<p>Name Product : <span style='font-size: 20px;'>"+name+"</span></p>";
                  html += "<label class='' for='price_3'>Retail Price : </label><div class=''>";
                  html += "<input type='text' id='price_3' name='price_3'  value='"+price+"' /><input type='hidden' name='id' id='id' value='"+id+"'>";
               
              
                  html += "</div></div><div class='pull-right'>";
                html += "<button type='submit' id='submit_btn' class='btn btn-primary'>Submit</button>  ";
                // html += "<button type='button' id='cancel_btn' class='btn btn-warning'>Cancel</button>";
            html += "</div></form>";

                $("#dialog").html(html);
                $( "#dialog" ).dialog("open");
                $('#dialog').dialog({
                       
                        title: 'Adjust the price',
                        
                    });
       }
    

    
</script>