<style>

a{
    margin-right: 2.5px;
    margin-left: 2.5px;
}
.status_enable{
    width: 70px;
    background: #99ff66;
    text-align: center;
}
.status_disable{
    width: 70px;
    background: #ff8c66;
    text-align: center;
}
.hilight
{
    background: #E8ADAA;
    /*color:white;*/
}
.hilight:hover
{
    /*color:black;*/
}
</style>


<table class="table table-bordered">
    <thead>
        <tr>
            <?php 
            echo $this->sorting(array(
                    '#',
                    'imei1'  => 'Imei 1',
                    'imei2'  => 'Imei 2',
                    'good_code'  => 'Good Code',
                    'color'  => 'Color',
                    'created_by' => 'Import By',
                    'created_date' => 'Import Date'
                ),
                $this->url, $this->sort, $this->desc); 

            ?>
        </tr>
    </thead>
    <tbody>
        <?php
        if (isset($this->get_resule) and $this->get_resule){
            foreach ($this->get_resule as $k=>$m):
            ?>
                <tr>
                    <td>#</td>
                    <td><?php echo $m['imei1'] ?></td>
                    <td><?php echo $m['imei2'] ?></td>
                    <td><?php echo $m['good_code'] ?></td>
                    <td><?php echo $m['color'] ?></td>
                    <td><?php echo $m['staff_name'] ?></td>
                    <td><?php echo $m['created_date'] ?></td>               
                    
                </tr>
            <?php endforeach;?>   
        <?php } ?>
    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<script type="text/javascript" src="/js/jets.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>

<script>
    

$(document).ready(function () {
    
     
});


</script>