
    <table class="table table-bordered">
        <thead>
            <tr>
                <?php echo $this->sorting(array(
                        '<input type="checkbox" id="check-all"> All',
                        '#',
                        'user'          =>'User Name',
                        'imei_log'      =>'Imei',
                        'created_at'    =>'Date Create',
                        'Action'
                    ),
                    $this->url, $this->sort, $this->desc); ?>
            </tr>
        </thead>
        <tbody>
            <?php
            
                if(isset($this->lockimeis) and $this->lockimeis)
                foreach($this->lockimeis as $k => $lockimei):
            ?> 
                    <tr>
                        <td><input type="checkbox" class="data-check" value="<?php echo $lockimei['id']; ?>"></td>
                        <td>
                            <?php 
                            $inc = $this->offset + $k + 1;
                            echo $inc;
                            ?>
                        </td>
                        <td><?php echo $lockimei['username'];?></td>
                        <td><?php echo $lockimei['imei_log'];?></td>
                        <td><?php echo ($lockimei['created_date'] ? date('d/m/Y', strtotime($lockimei['created_date'])) : '');
                            ?>  
                        </td>
                        <td>
                        <center>
                            <a title="Unlock" class="confirmLink btn btn-warning" href="/tool/del?id=<?php echo $lockimei['id']; ?>&imei=<?php echo $lockimei['imei_log'] ?>" onclick="return confirm('Are you sure you want to unlock!')">
                                <i class="icon-unlock-alt"></i>
                            </a>
                        </center>
                        </td>
                    </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="paging">
        <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
    </div>
    <script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<?php echo $this->load();?>
<?php echo $this->confirm();?> 

