
<html>
    <head>
        <style type="text/css">
            .r-board{ margin: 0 auto; }
            .col-sm-2 {
                float: left;
                width: 15%;
                padding: 10px;
                height: 100px;
            }
            .card {
              border-color: #d7dfe3;
              border-radius: 4px;
              border-radius: 50px/15px;

              background: #ffffff;
              border: 1px solid #DCDCDC;

              /*สีพื้นในช่อง start*/
              background: rgb(254,255,255); /* Old browsers */
              background: -moz-linear-gradient(top,  rgba(254,255,255,1) 0%, rgba(210,235,249,1) 100%); /* FF3.6+ */
              background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(254,255,255,1)), color-stop(100%,rgba(210,235,249,1))); /* Chrome,Safari4+ */
              background: -webkit-linear-gradient(top,  rgba(254,255,255,1) 0%,rgba(210,235,249,1) 100%); /* Chrome10+,Safari5.1+ */
              background: -o-linear-gradient(top,  rgba(254,255,255,1) 0%,rgba(210,235,249,1) 100%); /* Opera 11.10+ */
              background: -ms-linear-gradient(top,  rgba(254,255,255,1) 0%,rgba(210,235,249,1) 100%); /* IE10+ */
              background: linear-gradient(to bottom,  rgba(254,255,255,1) 0%,rgba(210,235,249,1) 100%); /* W3C */
              filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#feffff', endColorstr='#d2ebf9',GradientType=0 ); /* IE6-9 */
               /*สีพื้นในช่อง end*/

              /*width: 100%;*/
              height: 100px;

              -webkit-box-shadow: 20px 10px 20px rgba(0, 0, 0, 0.10);
              box-shadow: 20px 10px 20px rgba(0, 0, 0, 0.10); 
            }
           
            html body .font-light {
            font-weight: 300;
            text-align: center; 
            
           }

            .text-muted {
            color: #99abb4 !important; 
            text-align: center; 
           }

            html body .m-l-10 {
            margin-left: 10px; }

            .round {
              width: 30px;
              height: 20px;
              margin: 0px 0px 0px 10px;
            }

        </style>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
        <!-- /stylesheet Icon/ -->
    </head>

        <body>
            
            <div class="container">
                <div class="row r-board">
                  <div class="col-sm-2">
                    <div class="card">
                      <div class="card-body">
                        <div class="align-self-center round">
                            <i class="fa fa-bookmark-o fa-3x" aria-hidden="true"></i>
                        </div>
                          <div class="m-l-10 align-self-center">
                            <h2 class="font-light"><?php echo $this->total_storage; ?></h2>
                            <h3 class="text-muted ">Total Storage</h3></div>
                      </div>
                    </div>
                  </div>
                    <!-- Colum -->
                    <!-- Colum -->
                
                  <div class="col-sm-2">
                    <div class="card">
                      <div class="card-body">
                        <div class="align-self-center round">
                            <i class="fa fa-bookmark-o fa-3x" aria-hidden="true"></i>
                        </div>
                          <div class="m-l-10 align-self-center">
                            <h2 class="font-light"><?php echo $this->total_available; ?></h2>
                            <h3 class="text-muted ">Total Available</h3></div>
                      </div>
                    </div>
                  </div>
                  <!-- Colum -->
                  <!-- Colum -->

                  <div class="col-sm-2">
                    <div class="card">
                      <div class="card-body">
                        <div class="align-self-center round">
                            <i class="fa fa-bookmark-o fa-3x" aria-hidden="true"></i>
                        </div>
                          <div class="m-l-10 align-self-center">
                            <h2 class="font-light">
                              <?php echo $this->total_bill['count_so']; ?></h2>
                            <h3 class="text-muted ">Total Billed</h3></div>
                      </div>
                    </div>
                  </div> 
                  <!-- Colum -->
                  <!-- Colum -->
                
                  <div class="col-sm-2">
                    <div class="card">
                      <div class="card-body">
                        <div class="align-self-center round">
                            <i class="fa fa-bookmark-o fa-3x" aria-hidden="true"></i>
                        </div>
                          <div class="m-l-10 align-self-center">
                            <h2 class="font-light">
                              <?php echo $this->total_financ['count_so']; ?></h2>
                            <h3 class="text-muted ">Total Financed</h3></div>
                      </div>
                    </div>
                  </div>
                  <!-- Colum -->
                  <!-- Colum -->
                
                  <div class="col-sm-2">
                    <div class="card">
                      <div class="card-body">
                        <div class="align-self-center round">
                            <i class="fa fa-bookmark-o fa-3x" aria-hidden="true"></i>
                        </div>
                          <div class="m-l-10 align-self-center">
                            <h2 class="font-light">
                              <?php echo $this->total_scaned['count_so']; ?></h2>
                            <h3 class="text-muted ">Total Scaned out</h3></div>
                      </div>
                    </div>
                  </div>
                  <!-- Colum -->
                </div>
            </div>      
            <div class="paging">
                <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
            </div>
            <?php echo $this->load();?>
        </body>
</html>