<?php  if(isset($this->res) && $this->res): ?>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Item Name</th>
				<th>Color</th>
				<th>Qulity</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->res as $k => $v): ?>
				<tr>
					<td><?php echo ( !empty( $this->goods[$v['good_id']] ) ? $this->goods[$v['good_id']] : 'n/a' ) ?></td>
					<td><?php echo ( !empty( $this->good_colors[$v['good_color']] ) ? $this->good_colors[$v['good_color']] : 'n/a' ) ?></td>
					<td><?php echo ( !empty( $v['count'] ) ? $v['count'] : 'n/a' ) ?></td>
				</tr>
			<?php endforeach ?>
		</tbody>
	</table>
<?php endif; ?>
