<style>

a{
    margin-right: 2.5px;
    margin-left: 2.5px;
}
.status_enable{
    width: 70px;
    background: #99ff66;
    text-align: center;
}
.status_disable{
    width: 70px;
    background: #ff8c66;
    text-align: center;
}
.hilight
{
    background: #E8ADAA;
    /*color:white;*/
}
.hilight:hover
{
    /*color:black;*/
}
</style>
<div class="table-responsive">
    <?php
        $userStorage = Zend_Auth::getInstance()->getStorage()->read();
        if (My_Staff_Group::inGroup($userStorage->group_id, array(ADMINISTRATOR_ID, CHECK_MONEY)) or ($exception_case and in_array
        ($userStorage->id, $exception_case))){
            $view_import="";
        }else{
            $view_import='style="display: none;"';
        }
    ?>
    <span class="pull-left">
        <button class="btn btn-success" type="button" onclick="window.location='<?php echo HOST ?>tool/service-product-upload-list'">
            Import Product Upload List File
        </button>
        <button class="btn btn-success" type="button" onclick="window.location='<?php echo HOST ?>tool/service-stock-shop-upload-list'">
            Import Stock Shop Upload List File
        </button>
        <button class="btn btn-success" type="button" onclick="window.location='<?php echo HOST ?>tool/service-product-model-upload-list'">
            Import Product Model Upload List File
        </button>
        <hr>
        <button class="btn btn-success" type="button" onclick="window.location='<?php echo HOST ?>tool/service-product-stock-in-upload'">
            Import ยอดอะไหล่เข้า
        </button>
        <button class="btn btn-success" type="button" onclick="window.location='<?php echo HOST ?>tool/service-product-stock-out-upload'">
            Import ยอดใช้อะไหล่
        </button>
        <button class="btn btn-success" type="button" onclick="window.location='<?php echo HOST ?>tool/service-product-stock-out-acc-upload'">
            Import ยอดใช้ ACC
        </button>
        <hr>
    </span>

</br></br>
    <span class="pull-right" style="display: none;">
        <button class="btn btn-info btn-confirm-status" value="1" id="btn-confirm-enable" type="button">เปิดใช้งาน</button>&nbsp;

        <button class="btn btn-danger btn-confirm-status" value="0" id="btn-confirm-disable" type="button">ปิดใช้งาน</button>
    </span>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <?php 
            if($this->data_type=="1"){  //รายการสินค้า
                echo $this->sorting(array(
                    '#',
                    'good_code'  => 'Good Code',
                    'good_replacement_code'  => 'Good Replacement Code',
                    'detail'  => 'Detail',
                    'channel'  => 'Channel',
                    'price'  => 'Cost Price (USD)',
                    'retail_price'  => 'Retail Price (Bath)',
                    'create_by' => 'Import By',
                    'create_date' => 'Last Import Date',
                     'Action'
                ),
                $this->url, $this->sort, $this->desc); 
            }else if($this->data_type=="2"){ //รายการสินค้าคงเหลือ
                echo $this->sorting(array(
                    '#',
                    'warehouse_name'  => 'Warehouse Name',
                    'good_code'  => 'Good Code',
                    'good_model_name'  => 'Good Model Name',
                    'detail'  => 'Detail',
                    'num'  => 'Num',
                    'create_by' => 'Import By',
                    'create_date' => 'Last Import Date',
                     'Action'
                ),
                $this->url, $this->sort, $this->desc); 
            }else if($this->data_type=="3"){ //รายการสินค้าโมเดล
                echo $this->sorting(array(
                    '#',
                    
                    'good_code'  => 'Good Code',
                    'good_model_name'  => 'Good Model Name',
                    'detail'  => 'Detail',
                    'num'  => 'Num',
                    'create_by' => 'Import By',
                    'create_date' => 'Last Import Date',
                     'Action'
                ),
                $this->url, $this->sort, $this->desc); 
            }else if($this->data_type=="4"){ //รายการยอดอะไหล่เข้า
                echo $this->sorting(array(
                    '#',
                    
                    'good_code'  => 'Good Code',
                    'good_model_name'  => 'Good Model Name',
                    'detail'  => 'Detail',
                    'num'  => 'Num',
                    'create_by' => 'Import By',
                    'create_date' => 'Last Import Date',
                     'Action'
                ),
                $this->url, $this->sort, $this->desc); 
            }else if($this->data_type=="5"){ //รายการยอดใช้อะไหล่
                echo $this->sorting(array(
                    '#',
                    
                    'good_code'  => 'Good Code',
                    'good_model_name'  => 'Good Model Name',
                    'detail'  => 'Detail',
                    'num'  => 'Num',
                    'create_by' => 'Import By',
                    'create_date' => 'Last Import Date',
                     'Action'
                ),
                $this->url, $this->sort, $this->desc); 
            }else if($this->data_type=="6"){ //รายการยอดใช้ ACC
                echo $this->sorting(array(
                    '#',
                    'good_code'  => 'Good Code',
                    'good_model_name'  => 'Good Model Name',
                    'detail'  => 'Detail',
                    'num'  => 'Num',
                    'create_by' => 'Import By',
                    'create_date' => 'Last Import Date',
                     'Action'
                ),
                $this->url, $this->sort, $this->desc); 
            }else if($this->data_type=="R01"){    //Report 01 : Inventory / Purchase / Consumption
                echo $this->sorting(array(
                    '#',
                    'Report'  => 'Report',
                     'Action'
                ),
                $this->url, $this->sort, $this->desc); 
            }else if($this->data_type=="R02"){    //Report 02 : Inventory by Branch
                echo $this->sorting(array(
                    '#',
                    'Report'  => 'Report',
                     'Action'
                ),
                $this->url, $this->sort, $this->desc); 
            }else if($this->data_type=="R03"){    //Report 03 : Turn Over Stock
                echo $this->sorting(array(
                    '#',
                    'Report'  => 'Report',
                     'Action'
                ),
                $this->url, $this->sort, $this->desc); 
            }else if($this->data_type=="R04"){    //Report 04 : Stock Aging
                echo $this->sorting(array(
                    '#',
                    'Report'  => 'Report',
                     'Action'
                ),
                $this->url, $this->sort, $this->desc); 
            }else if($this->data_type=="R05"){    //Report 05 : Used spare part by ITEM
                echo $this->sorting(array(
                    '#',
                    'Report'  => 'Report',
                     'Action'
                ),
                $this->url, $this->sort, $this->desc); 
            }

            ?>
        </tr>
    </thead>
    <tbody>
        <?php
        $statuses = unserialize(DISCOUNT_STATUS);
        if (isset($this->get_resule) and $this->get_resule){
            foreach ($this->get_resule as $k=>$m):

            ?>
            <?php if($this->data_type=="1"){    ////รายการสินค้า ?>
                <tr>
                    <td>#</td>
                    <td><?php echo $m['good_code'] ?></td>
                    <td><?php echo $m['good_replacement_code'] ?></td>
                    <td><?php echo $m['detail'] ?></td>
                    <td><?php echo $m['channel'] ?></td>
                    <td><?php echo number_format($m['price'],2) ?></td>
                    <td><?php echo number_format($m['retail_price'],2) ?></td>
                    <td><?php echo $m['staff_name'] ?></td>
                    <td><?php echo $m['create_date'] ?></td>               
                    <td><a title="Print" target="_blank" href="/sales/print-withholding-tax?wht_sn=<?php echo $m['wht_sn'];?>"> <i class="icon-print" style="color: red"></i></a></td>
                </tr>
            <?php }else if($this->data_type=="2"){ //รายการสินค้าคงเหลือ ?>
                <tr>
                    <td>#</td>
                    <td><?php echo $m['warehouse_name'] ?></td>
                    <td><?php echo $m['good_code'] ?></td>
                    <td><?php echo $m['good_model_name'] ?></td>
                    <td><?php echo $m['detail'] ?></td>
                    <td><?php echo number_format($m['total_num'],0) ?></td>
                    <td><?php echo $m['staff_name'] ?></td>
                    <td><?php echo $m['create_date'] ?></td>               
                    <td><a title="Print" target="_blank" href="/sales/print-withholding-tax?wht_sn=<?php echo $m['wht_sn'];?>"> <i class="icon-print" style="color: red"></i></a></td>
                </tr>
            <?php }else if($this->data_type=="3"){ //รายการสินค้าโมเดล ?>
                <tr>
                    <td>#</td>
                    <td><?php echo $m['good_code'] ?></td>
                    <td><?php echo $m['good_model_name'] ?></td>
                    <td><?php echo $m['detail'] ?></td>
                    <td><?php echo number_format($m['total_num'],0) ?></td>
                    <td><?php echo $m['staff_name'] ?></td>
                    <td><?php echo $m['create_date'] ?></td>               
                    <td><a title="Print" target="_blank" href="/sales/print-withholding-tax?wht_sn=<?php echo $m['wht_sn'];?>"> <i class="icon-print" style="color: red"></i></a></td>
                </tr>
            <?php }else if($this->data_type=="4"){ //รายการยอดอะไหล่เข้า ?>
                <tr>
                    <td>#</td>
                    <td><?php echo $m['good_code'] ?></td>
                    <td><?php echo $m['good_model_name'] ?></td>
                    <td><?php echo $m['detail'] ?></td>
                    <td><?php echo number_format($m['total_num'],0) ?></td>
                    <td><?php echo $m['staff_name'] ?></td>
                    <td><?php echo $m['create_date'] ?></td>               
                    <td><a title="Print" target="_blank" href="/sales/print-withholding-tax?wht_sn=<?php echo $m['wht_sn'];?>"> <i class="icon-print" style="color: red"></i></a></td>
                </tr>
            <?php }else if($this->data_type=="5"){ //รายการยอดใช้อะไหล่ ?>
                <tr>
                    <td>#</td>
                    <td><?php echo $m['good_code'] ?></td>
                    <td><?php echo $m['good_model_name'] ?></td>
                    <td><?php echo $m['detail'] ?></td>
                    <td><?php echo number_format($m['total_num'],0) ?></td>
                    <td><?php echo $m['staff_name'] ?></td>
                    <td><?php echo $m['create_date'] ?></td>               
                    <td><a title="Print" target="_blank" href="/sales/print-withholding-tax?wht_sn=<?php echo $m['wht_sn'];?>"> <i class="icon-print" style="color: red"></i></a></td>
                </tr>
            <?php }else if($this->data_type=="6"){ //รายการยอดใช้ ACC ?>
                <tr>
                    <td>#</td>
                    <td><?php echo $m['good_code'] ?></td>
                    <td><?php echo $m['good_model_name'] ?></td>
                    <td><?php echo $m['detail'] ?></td>
                    <td><?php echo number_format($m['total_num'],0) ?></td>
                    <td><?php echo $m['staff_name'] ?></td>
                    <td><?php echo $m['create_date'] ?></td>               
                    <td><a title="Print" target="_blank" href="/sales/print-withholding-tax?wht_sn=<?php echo $m['wht_sn'];?>"> <i class="icon-print" style="color: red"></i></a></td>
                </tr>            
            <?php } ?>

        <?php endforeach;?>
		<?php }else{ ?>
                <?php if($this->data_type=="R01"){ //Report 01 : Inventory / Purchase / Consumption ?>
                <tr>
                    <td>#</td>
                    <td>Report 01 : Inventory / Purchase / Consumption</td>            
                    <td><a title="Print" target="_blank" href="/tool/print-inventory-purchase-consumption?start_date=<?php echo $this->params['start_date'];?>&end_date=<?php echo $this->params['end_date'];?>&warehouse_name=<?php echo $this->params['warehouse_name'];?>&good_code=<?php echo $this->params['good_code'];?>"> <i class="icon-print" style="color: red"></i></a>
                    </td>
                </tr>
                <?php }else if($this->data_type=="R02"){ //Report 02 : Inventory by Branch ?>
                    <tr>
                        <td>#</td>
                        <td>Report 02 : Inventory by Branch</td>            
                        <td><a title="Print" target="_blank" href="/tool/print-inventory-by-branch?start_date=<?php echo $this->params['start_date'];?>&end_date=<?php echo $this->params['end_date'];?>&warehouse_name=<?php echo $this->params['warehouse_name'];?>&good_code=<?php echo $this->params['good_code'];?>"> <i class="icon-print" style="color: red"></i></a>
                        </td>
                    </tr>
                <?php }else if($this->data_type=="R03"){ //Report 03 : Turn Over Stock ?>
                    <tr>
                        <td>#</td>
                        <td>Report 03 : Turn Over Stock</td>            
                        <td><a title="Print" target="_blank" href="/tool/print-turn-over-stock?start_date=<?php echo $this->params['start_date'];?>&end_date=<?php echo $this->params['end_date'];?>&warehouse_name=<?php echo $this->params['warehouse_name'];?>&good_code=<?php echo $this->params['good_code'];?>"> <i class="icon-print" style="color: red"></i></a>
                        </td>
                    </tr>
                <?php }else if($this->data_type=="R04"){ //Report 04 : Stock Aging ?>
                    <tr>
                        <td>#</td>
                        <td>Report 04 : Stock Aging</td>            
                        <td><a title="Print" target="_blank" href="/tool/print-stock-aging?start_date=<?php echo $this->params['start_date'];?>&end_date=<?php echo $this->params['end_date'];?>&warehouse_name=<?php echo $this->params['warehouse_name'];?>&good_code=<?php echo $this->params['good_code'];?>"> <i class="icon-print" style="color: red"></i></a>
                        </td>
                    </tr>
                <?php }else if($this->data_type=="R05"){ //Report 05 : Used spare part by ITEM ?>
                    <tr>
                        <td>#</td>
                        <td>Report 05 : Used spare part by ITEM</td>            
                        <td><a title="Export" target="_blank" href="/tool/print-used-spare-part-by-item?start_date=<?php echo $this->params['start_date'];?>&end_date=<?php echo $this->params['end_date'];?>&warehouse_name=<?php echo $this->params['warehouse_name'];?>&good_code=<?php echo $this->params['good_code'];?>"> <i class="icon-file-text-alt" style="color: red"></i></a>
                        </td>
                    </tr>                
                <?php } ?>

        <?php } ?>
    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<script type="text/javascript" src="/js/jets.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>

<script>
    

$(document).ready(function () {
    
     
});


</script>