<div class="page-header">
	<h1 style="font-family: Times New Roman;">Bank Account Management</h1>
</div>


<div class="row-fluid" style="border-style: solid; padding-top: 20px; padding-bottom: 30px; display: contents;">
	<div class="span12">

		<div class="span4"> 
			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px; width: 100%;"> 
					<div>
						<img src="https://i.postimg.cc/LsKcVZc2/atm-card.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="/finance/bank-account-my-side" style="padding-top: 50px; font-size: 24px;"> Bank Account (My Side) </a></p>
					</div>
				</div>
			</div>

		</div>

		<div class="span4">
			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px;">
					<div>
						<img src="https://i.postimg.cc/1tW7bgjg/credit-card.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="/finance/bank-account-your-side" style="padding-top: 50px; font-size: 24px;" > Bank Account (Your Side) </a></p>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>