<link rel="stylesheet" href="<?php echo HOST?>css/select2.css" />
<script src="<?php echo HOST?>js/select2.js"></script>

<?php 
if(isset($this->action_type) && in_array($this->action_type,array(1,3))) {
	$input_status = 'disabled';
}elseif($this->action_type == 2) {
	$edit_input_status = 'disabled';
}
?>

<div class="page-header">
	<?php if(isset($this->action_type) && $this->action_type == 1) : ?>
		<h1 style="font-family: Times New Roman;">Detail Support Fund</h1>
	<?php elseif($this->action_type == 2) : ?>
		<h1 style="font-family: Times New Roman;">Edit Support Fund</h1>
	<?php else: ?>
		<h1 style="font-family: Times New Roman;">Add Support Fund</h1>
	<?php endif; ?>
</div>

<form class="form-horizontal" method="post" action="<?php echo HOST ?>finance/save-support-fund" >
	<div class="row" style="border-style: solid; padding: 30px 10px 300px 10px; border-color: lavender; margin-right: 0px">

		<div class="span6">

			<div class="control-group">
				<label for="dis_id" class="control-label" style="width: 180px; padding-right: 20px;">Distributor(My Side) : <span style="color: red">*</span></label>
				<div class="controls">
					<select class="span3" name="dis_id" id="dis_id" required <?php echo $input_status ?> <?php echo $edit_input_status ?> >
						<option value=""> Please Selected </option>

						<?php if(isset($this->distributor) && $this->distributor) : ?>
							<?php foreach ($this->distributor as $value) : ?>
								<option value="<?php echo $value['id'] ?>" <?php if(isset($this->supportFund) && $this->supportFund->d_id == $value['id']) : ?> selected <?php endif; ?> ><?php echo $value['title'] ?> </option>
							<?php endforeach; ?>
						<?php endif; ?>
					</select>
				</div>
			</div>

			<div class="control-group">
				<label for="finance_client" class="control-label" style="width: 180px; padding-right: 20px">Financial customers : <span style="color: red">*</span></label>
				<div class="controls">
					<select class="span3" name="finance_client" id="finance_client" required <?php echo $input_status ?> >
						<option value=""> Please Selected </option>

						<?php if(isset($this->financeClient) && $this->financeClient) : ?>
							<?php foreach($this->financeClient as $value) : ?>
								<option value="<?php echo $value['id'] ?>" <?php if(isset($this->supportFund) && $this->supportFund->finance_client_id == $value['id']) : ?> selected <?php endif; ?> ><?php echo $value['name'] ?></option>
							<?php endforeach; ?>
						<?php endif; ?>

					</select>
				</div>
			</div>

			<div class="control-group">
				<label for="amount" class="control-label" style="width: 180px; padding-right: 20px">Amount : <span style="color: red">*</span></label>
				<div class="controls">
					<input type="number" class="span3" name="amount" id="amount" required <?php echo $input_status ?> value="<?php isset($this->supportFund) && printf($this->supportFund->amount) ?>" >
				</div>
			</div>

			<div class="control-group">
				<label for="cost_id" class="control-label" style="width: 180px; padding-right: 20px">Cost Item : <span style="color: red">*</span></label>
				<div class="controls">
					<select class="span3" name="cost_id" id="cost_id" required <?php echo $input_status ?> >
						<option value=""> Please Selected </option>

						<?php if(isset($this->costItem) && $this->costItem) : ?>
							<?php foreach($this->costItem as $value) : ?>
								<option value="<?php echo $value['id'] ?>" <?php if(isset($this->supportFund) && $this->supportFund->cost_id == $value['id']) : ?> selected <?php endif; ?> ><?php echo $value['cost_name'] ?></option>
							<?php endforeach; ?>
						<?php endif; ?>

					</select>
				</div>
			</div>

		</div>

		<div class="span6">

			<div class="control-group">
				<label for="bussiness_date" class="control-label" style="width: 180px; padding-right: 20px">Business date : <span style="color: red">*</span></label>
				<div class="controls">
					<input type="text" class="span3 date" name="bussiness_date" id="bussiness_date" required <?php echo $input_status ?> value="<?php isset($this->supportFund) && printf($this->supportFund->business_date) ?>">
				</div>
			</div>

			<div class="control-group">
				<label for="remark" class="control-label" style="width: 180px; padding-right: 20px">Remarks :</label>
				<div class="controls">
					<textarea class="span3" cols="2" rows="3" name="remark" <?php echo $input_status ?>><?php isset($this->supportFund) && printf($this->supportFund->remark) ?></textarea>
				</div>
			</div>

		</div>

		<div class="span12" style="display: flex; align-items: center; justify-content: center; padding-top: 50px;">
			<input type="hidden" name="id" value="<?php isset($this->supportFund) && printf($this->supportFund->id) ?>">

			<?php if(isset($this->action_type) && $this->action_type == 1) : ?>
				<button type="reset" class="btn btn-danger" onclick="history.back()">Back</button>
			<?php elseif($this->action_type == 3): ?>
				<button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal"> Approved </button> &nbsp;
				<button type="button" class="btn btn-danger" onclick="history.back()"> Cancel </button>
			<?php else: ?>
				<button type="submit" class="btn btn-success">Save</button> &nbsp;
				<button type="reset" class="btn btn-danger" onclick="history.back()">Cancel</button>
			<?php endif; ?>
		</div>

	</div>
</form>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Approved</h3>
	</div>

	<div class="modal-body" style="display: flex; justify-content: center;">
		<form method="post" id="modalForm">
			<div class="row">
				<div class="control-group">
					<label class="">Review Remarks : </label>
					<div class="controls">
						<textarea cols="2" rows="5" class="span3" name="remark"></textarea>
					</div>
				</div>
			</div>
		</div>

		<div class="modal-footer">
			<input type="hidden" name="id" value="<?php if(isset($this->supportFund) && printf($this->supportFund->id)) ?>">
			<input type="hidden" name="action_type" value="3">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			<button type="submit" class="btn btn-success" id="approved">Approved</button>
		</div>
	</form>
	
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>

<script type="text/javascript">

	$(document).ready(function () {

		$('#modalForm').submit(function(event) {
			event.preventDefault();

			var data = $(this).serialize();

			$.ajax({
				url: '/finance/approved-support-fund',
				type: 'POST',
				data: data,
				success: function(response) {
					Swal.fire({
						title: 'Deleted!',
						text: 'Your data has been deleted.',
						icon: 'success',
						showConfirmButton: false
					});
                // Reload page after 2 seconds (optional)
					setTimeout(function(){ window.location.href ='/finance/support-fund-management' }, 2000);
				},
				error: function(error) {
        		// Handle the error response
					alert('Error submitting data!');
				}
			});
		});


		$( '.date' ).datepicker({ dateFormat: "yy-mm-dd" });

		$("#dis_id").change(function() {
			var distributor_id = $("#dis_id").val();

			$.get("/finance/load-bank-account-my",
				{distributor_id : distributor_id}
				,function(data,status){
					var data = $.parseJSON( data );

					if (data.financeClient){
						var obj = data.financeClient;
						$('#finance_client').html('<option value="0"> Please Selected </option>');
						for (var i = 0; i < obj.length; i++) {
							$('#finance_client').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
						}
					}
				})
		})
	});

</script>