<div class="page-header">
	<h1 style="font-family: Times New Roman;">Finance Clients Contact Management</h1>
</div>


<div class="row-fluid" style="border-style: solid; padding-top: 20px; padding-bottom: 30px; display: contents;">
	<div class="span12">

		<div class="span4"> 
			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px; width: 100%;"> 
					<div>
						<img src="https://i.postimg.cc/0yQn8RX2/quote.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="/finance/sale-receipt" style="padding-top: 50px; font-size: 24px;"> Sales Receipt </a></p>
					</div>
				</div>
			</div>

			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px; width: 100%;"> 
					<div>
						<img src="https://i.postimg.cc/LsKcVZc2/atm-card.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="/finance/client-contact-note" style="padding-top: 50px; font-size: 24px;"> Clients Contact Note </a></p>
					</div>
				</div>
			</div>

			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px; width: 100%;"> 
					<div>
						<img src="https://i.postimg.cc/LsKcVZc2/atm-card.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="#" style="padding-top: 50px; font-size: 24px;"> Assure Bill Management </a></p>
					</div>
				</div>
			</div>

		</div>

		<div class="span4">
			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px;">
					<div>
						<img src="https://i.postimg.cc/CMsskLWx/cash-back.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="/finance/sale-refund" style="padding-top: 50px; font-size: 24px;" > Sales Refund </a></p>
					</div>
				</div>
			</div>

			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px;">
					<div>
						<img src="https://i.postimg.cc/1tW7bgjg/credit-card.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="/finance/distributor-account-reconciliation" style="padding-top: 50px; font-size: 24px;" > Distributor Account Reconciliation </a></p>
					</div>
				</div>
			</div>

		</div>

		<div class="span4">
			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px;">
					<div>
						<img src="https://i.postimg.cc/1tW7bgjg/credit-card.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="/finance/contact-note" style="padding-top: 50px; font-size: 24px;" > Contact Note </a></p>
					</div>
				</div>
			</div>

			<div class="control-group">
				<div style="background-color: #E3E3E3; display: block; height: 120px; text-align: center; align-content: center; border-radius: 20px;">
					<div>
						<img src="https://i.postimg.cc/Jh8r77Q2/humanity.png" width="50px" height="50px">
						<p style="padding-top: 10px"><a href="/finance/support-fund-management" style="padding-top: 50px; font-size: 24px;" > Support fund management </a></p>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>