<link href="../css/select2.css" rel="stylesheet" />
<script src="../js/select2.js"></script>

<div class="page-header">
    <?php if (isset($this->PO) and $this->PO):?>
    <h1>Edit PO</h1>
    <?php else:?>
    <h1 style="font-family: Noto Sans Lao;">Create PO ຊື້ເຄື່ອງເຂົ້າລະບົບ</h1>
    <?php endif;?>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>
<?php
    $sn_ref=$this->PO->sn_ref;
    if($sn_ref==''){
        $sn_ref=$this->PO->sn;
    }
?>
<div class="span12">
    <div class="hero-unit">
        <form role="form" id="form" action="<?php echo HOST.'/po/create';?>" method="post" class="form-horizontal">
            <div class="col">
                <div class="span6">
                    <?php if (isset($this->PO) ):?>
                    <div class="control-group">
                        <label class="span2">Purchase order ID</label>
                        <span
                            class="span3"><strong><?php isset($this->PO) and $this->PO and printf($this->PO->id);?></strong></span>
                    </div>

                    <div class="control-group">
                        <label class="span2">Purchase order number</label>
                        <span
                            class="span3"><strong><?php isset($this->PO) and $this->PO and printf($sn_ref);?></strong></span>
                    </div>

                    <?php endif;?>

                    <div class="control-group">
                        <label for="type" class="span2">PO Type : <span style="color: red">*</span></label>
                        <select id="type" class="span3" name="type" required="required">
                            <option value="">Please select</option>
                            <?php foreach (My_Po_Type::$name as $_key => $_name):?>
                            <option value="<?php echo $_key;?>"
                                <?php if (isset($this->PO) and $_key == $this->PO->type):?> selected<?php endif;?>>
                                <?php echo $_name;?></option>
                            <?php endforeach;?>
                        </select>
                    </div>

                    <div class="control-group">
                        <label for="cat_id" class="span2">Products category : <span style="color: red">*</span></label>
                        <select id="cat_id" class="span3" name="cat_id" required="required">
                            <option value="">Please select</option>
                            <?php foreach ($this->good_categories as $id => $good_category):?>
                            <option value="<?php echo $id;?>"
                                <?php if (isset($this->PO) and $id == $this->PO->cat_id):?> selected<?php endif;?>>
                                <?php echo $good_category;?></option>
                            <?php endforeach;?>
                        </select>
                    </div>

                    <div class="control-group">
                        <label for="good_id" class="span2">Purchase of products : <span
                                style="color: red">*</span></label>
                        <select id="good_id" class="span3" name="good_id" required="required">
                            <option value="">Please select</option>
                            <?php if (isset($this->goods) && $this->goods): ?>
                            <?php foreach ($this->goods as $good):?>
                            <option value="<?php echo $good->id;?>"
                                <?php if (isset($this->PO) and $good->id == $this->PO->good_id):?>
                                selected<?php endif;?>><?php echo $good->brand_id ?> <?php echo $good->name;?></option>
                            <?php endforeach;?>
                            <?php endif ?>
                        </select>
                    </div>

                    <div class="control-group">
                        <label for="good_color" class="span2">Color of products : <span
                                style="color: red">*</span></label>
                        <select id="good_color" class="span3" name="good_color" required="required">
                            <option value="">Please select</option>
                            <?php if (isset($this->colors) && $this->colors): ?>
                            <?php foreach ($this->colors as $color):?>
                            <option value="<?php echo $color->id;?>"
                                <?php if (isset($this->PO) and $color->id == $this->PO->good_color):?>
                                selected<?php endif;?>><?php echo $color->name;?></option>
                            <?php endforeach;?>
                            <?php endif ?>
                        </select>
                    </div>

                    <div class="control-group">
                        <label for="warehouse_id" class="span2">Purchaser Warehouse : <span
                                style="color: red">*</span></label>
                        <select id="warehouse_id" class="span3" name="warehouse_id" required="required">
                            <option value="">Please select</option>
                            <?php if (isset($this->warehouses) && $this->warehouses): ?>
                            <?php foreach ($this->warehouses as $id => $warehouse):?>
                            <option value="<?php echo $id;?>"
                                <?php if (isset($this->PO) and $id == $this->PO->warehouse_id):?>
                                selected<?php endif;?>>
                                <?php echo $warehouse;?></option>
                            <?php endforeach;?>
                            <?php endif ?>
                        </select>
                    </div>

                    <div class="control-group">
                        <label for="num" class="span2">Purchase quantity : <span style="color: red">*</span></label>
                        <input type="number" name="num" style="width: 300px auto" id="num" required="required"
                            value="<?php isset($this->PO) and $this->PO and printf($this->PO->num);?>" />
                    </div>

                    <div class="control-group">
                        <label for="price" class="span2">Purchase price <span style="color: red">*</span></label>
                        <input type="text" name="price" id="price" style="width: 300px auto" required="required"
                            value="<?php isset($this->PO) and $this->PO and printf (My_Number::f($this->PO->price));?>" />
                    </div>

                </div>

                <div class="span6">
                    <div class="control-group">
                        <label for="text" class="span2">Purchase remark : </label>
                        <textarea id="text"
                            name="text"><?php isset($this->PO) and $this->PO and printf($this->PO->text);?></textarea>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="span6">
                    <div class="control-group">
                        <input type="hidden" name="id" id="id"
                            value="<?php isset($this->PO) and $this->PO and printf($this->PO->id);?>">
                        <input type="hidden" name="sn" id="sn"
                            value="<?php isset($this->PO) and $this->PO and printf($this->PO->sn);?>">
                        <div class="span4">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button type="reset" class="btn btn-warning">Reset</button>
                            <input type="hidden" name="back_url" id="back_url" value="/po">
                            <button type="button" class="btn btn-danger go-back">Go back</button>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
    </div>
    </form>
</div>
</div>

<script>
// End Search by product
$(document).ready(function() {
    $('#good_id, #cat_id, #type, #good_color, #warehouse_id').select2();

    $('.go-back').click(function(e) {
        window.location.href = $('#back_url').val();
        return false;
    });

    $('#cat_id, #good_id').change(function() {
        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit', function(e) {
            e.preventDefault();
        });

        $('.loading').remove();
        $(this).after('<span class="loading"></span>');
        var _self = $(this);
        var cat_id = $('#cat_id').val();

        if (_self.attr('id') == 'cat_id')
            $('#good_id').find('option:not(:first)').remove();

        var good_id = $('#good_id').val();

        $('#good_color').find('option:not(:first)').remove();

        $('#num, #price').val('');

        $.get("/get/load", {
            cat_id: cat_id,
            good_id: good_id
        }, function(data, status) {
            var data = $.parseJSON(data);
            if (data.goods) {
                var obj = data.goods;
                for (var i = 0; i < obj.length; i++) {
                    $('#good_id').append('<option value="' + obj[i]['id'] + '">'+ obj[i]['brand_name'] +' ' + obj[i][
                        'name'
                    ] + '</option>');
                }
            }
            if (data.colors) {
                var obj = data.colors;
                for (var i = 0; i < obj.length; i++) {
                    $('#good_color').append('<option value="' + obj[i]['id'] + '">' + obj[i][
                        'name'
                    ] + '</option>');
                }
            }

            $('button[type=submit]').prop('disabled', false);
            $('form').unbind('submit');
            $('.loading').remove();
        });
    });

    $('#num').keyup(function() {
        calc($(this));
    });

    $('#num').change(function() {
        calc($(this));
    });

    $('button:reset').click(function(e) {
        e.preventDefault();
        $('select, input:text').val('');
        $('textarea').text('');
    })
});

function calc(elm) {
    $('button[type=submit]').prop('disabled', true);
    $('form').bind('submit', function(e) {
        e.preventDefault();
    });

    $('.loading').remove();
    elm.after('<span class="loading"></span>');
    var num = $('#num').val();
    var good_id = $('#good_id').val();
    $.get("/get/load-price", {
        num: num,
        good_id: good_id
    }, function(data, status) {
        $('button[type=submit]').prop('disabled', false);
        $('form').unbind('submit');

        $('#price').val(data);
        $('.loading').remove();
    });
}
</script>