<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo HOST ?>css/jquery-ui-1.8.12.custom.css"/>
<link href="<?php echo HOST ?>css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="<?php echo HOST ?>css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">

<style type="text/css">
    #d_id {
        left: -20px !important;
    }
</style>

<form class="form-search form-horizontal" method="get" action="<?php echo HOST ?>force-sale">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="campaign_id" class="control-label">Campaign ID</label>
                <div class="controls">
                    <input type="text" class="form-control search-query" id="campaign_id" name="campaign_id" value="<?php isset($this->params['campaign_id']) and printf($this->params['campaign_id']);?>">
                </div>
            </div>

            <div class="control-group">
                <label for="campaign_name" class="control-label">Campaign Name</label>
                <div class="controls">
                        <input type="text" class="form-control search-query" id="campaign_name" name="campaign_name" value="<?php isset($this->params['campaign_name']) and printf($this->params['campaign_name']);?>">
                </div>
            </div>

        </div>

        <div class="span5">
             <div class="control-group">
                <label for="start_date" class="control-label">Start Date</label>
                <div class="controls">
                    <input type="text" class="form-control search-query date" id="start_date" name="start_date" value="<?php isset($this->params['start_date']) and printf($this->params['start_date']);?>">
                </div>
            </div>

            <div class="control-group">
                <label for="end_date" class="control-label">End Date</label>
                <div class="controls">
                        <input type="text" class="form-control search-query date" id="end_date" name="end_date" value="<?php isset($this->params['end_date']) and printf($this->params['end_date']);?>">
                </div>
            </div>

        </div>
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
</form>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<script type="text/javascript" src="<?php echo HOST ?>js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>

<script>
options = {
    selectAllText: 'Select All',
    includeSelectAllOption: true,
    includeSelectAllIfMoreThan: 3,
    disableIfEmpty: true
};

function multi() {
    $('.multiselect').multiselect(options);
}

    $(document).ready(function () {
        multi();

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('#cat_id, #good_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var cat_id = $('#cat_id').val();

            if (_self.attr('id')=='cat_id')
                $('#good_id').find('option:not(:first)').remove();

            var good_id = $('#good_id').val();

            $('#good_color').find('option:not(:first)').remove();

            $('#num, #price').val('');

            $.get("/get/load",
                {cat_id: cat_id, good_id: good_id}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    if (data.goods){
                        var obj = data.goods;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    if (data.colors){
                        var obj = data.colors;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    _self.nextAll('.loading').remove();
                });
        });

        $('#area').change(function(){
            $('.loading').remove();
            $(this).next('.btn-group').append('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();
            $('#region').find('option').remove();
            $('#district').find('option').remove();

            $.get("<?php echo HOST ?>get/province-v2",
                {area_id: area_id}
                ,function(data,status){
                    for (i in data)
                        $('#region').append('<option value="'+i+'">'+data[i]+'</option>');

                    $('#district, #region').multiselect("destroy").multiselect(options);
                    $('.loading').remove();
                });
        });

        $('#region').change(function(){
            $('.loading').remove();
            $(this).next('.btn-group').append('<span class="loading"></span>');
            var _self = $(this);
            var region = _self.val();
            $('#district').find('option').remove();

            $.get("/get/district-v2",
                {province_id: region}
                ,function(data,status){
                    for (i in data)
                        $('#district').append('<option value="'+i+'">'+data[i]+'</option>');

                    $('#district').multiselect("destroy").multiselect(options);
                    $('.loading').remove();
                });
        });

        initTag();
        initSearchOptionDistributor('d_id', 'SearchBox');
    });

    function initTag(){

        $('#myTags').tagit({
            allowSpaces: true,
            fieldName: 'tags[]',
            autocomplete: {
                delay: 0,
                minLength: 2,
                source: "<?php echo HOST;?>get/get-tags"
            }
        });

    }
</script>
