<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">

    <title>OWAY WMS System</title>

    <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <?php if ($this->meta_refresh):?>
    <meta http-equiv="Cache-control" content="no-cache">
    <meta http-equiv="refresh" content="<?php echo $this->meta_refresh;?>">
    <?php endif;?>
    <link rel="icon" type="image/ico" href="/img/mini-icon.png" />
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Lao&display=swap" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/10.10.1/sweetalert2.min.css"
        rel="stylesheet">

    <link href="/css/font-awesome.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <link href="/css/default.css" rel="stylesheet">
    <link href="/css/pages/dashboard.css" rel="stylesheet">
    <link href="/css/alertify.core.css" rel="stylesheet">
    <link href="/css/alertify.default.css" rel="stylesheet">

        <style>
    * {
        font-family: 'Noto Sans Lao', sans-serif;
    }

    .main{
        position: relative;
        display: inline-block;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #F6F4F4;
        background-clip: border-box;
        border: 1px solid rgb(0, 0, 0, 0.09);
        border-radius: 0.4rem;
    }

    body {

        color: #34495E;
    }

    a {
        color: #01867d;
    }

    h1 {

        letter-spacing: -2px;
        font-size: 2.5em;

    }

    table {
        border-collapse: collapse;
        width: 100%;

    }

    .table {
        border: 2px solid #01867d;
    }

    th,
    td {
        text-align: center;
        padding: 5px 0;
    }



    tbody tr:hover {
        background: #BDC3C7;
        color: #333333;
    }

    .fixed {
        top: 0;
        position: fixed;
        width: auto;
        display: none;
        border: none;
    }

    .scrollMore {
        margin-top: 600px;
    }

    .up {
        cursor: pointer;
    }

    .dropbtn {
        background-color: #04AA6D;
        color: white;
        padding: 10px;
        font-size: 16px;
        border: none;
    }

    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        left: -90px;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
        z-index: 1;
    }

    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

    .dropdown-content a:hover {
        background-color: #ddd;
    }

    .dropdown:hover .dropdown-content {
        display: block;
    }

    .dropdown:hover .dropbtn {
        background-color: #3e8e41;
    }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
    <script src="/js/jquery-1.7.2.min.js"></script>
    <script defer src="/js/bootstrap.js"></script>
    <script defer src="/js/alertify.js"></script>
    <script defer src="/js/base.js"></script>
    <script defer src="/js/charts/Chart2020.min.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/10.10.1/sweetalert2.min.js"></script>

    <script defer type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-37492225-3']);
    _gaq.push(['_setDomainName', 'opposhop.vn']);
    _gaq.push(['_setAllowLinker', true]);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') +
        'stats.g.doubleclick.net/dc.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();
    </script>
    
</head>

<!-- <style>
    #mod-page{
        margin-left:15% !important;
    }
</style> -->

<body>
    <?php echo $this->render('navbar.phtml') ?>
    <!-- /navbar -->

    <div class="subnavbar">
        <div class="subnavbar-inner">
            <div class="container">
                <?php echo $this->render('menu.phtml') ?>
            </div>
        </div>
    </div>
    <!-- /subnavbar -->
    <div class="main" style="padding-bottom: 500px;">
        <div class="main-inner">
            <div class="container">
                <?php    
                $userStorage = Zend_Auth::getInstance()->getStorage()->read();
                ?>
                <p id="bg-text"><?php echo $userStorage->id;?></p>
                <?php echo $this->layout()->content; ?>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /main-inner -->
    </div>
    <!-- /main -->
    <script defer>
    $(document).ready(function() {
        $('.subnavbar .container > ul li').click(function(e) {
            // e.preventDefault();
            _self = $(this);
            len = _self.find('ul.dropdown:visible').length;

            //has no submenu
            if (_self.find('ul.dropdown').length === 0)
                _self.click(function() {
                    window.location = $('a', this).attr('href');
                    return false;
                });

            if (len === 0) {
                $('.subnavbar .container > ul li').find('ul.dropdown').removeClass('show');
                _self.find('ul.dropdown').addClass('show');
            } else
                _self.find('ul.dropdown').removeClass('show');
        });

        $('.subnavbar .container>ul>li>a').click(function(e) {
            _self = $(this);
            len = _self.next('ul.dropdown').length;

            if (len > 0)
                e.preventDefault();
        });
    });

    $(document).mouseup(function(e) {
        var container = $(".subnavbar .container > ul li");

        if (!container.is(e.target) // if the target of the click isn't the container...
            &&
            container.has(e.target).length === 0) // ... nor a descendant of the container
        {
            container.find('ul.dropdown').removeClass('show');
        }
    });
    </script>

    <script defer>
    (function(i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function() {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-87805771-1', 'auto');
    ga('send', 'pageview');
    </script>
    <!-- /footer -->

</body>

</html>