<meta charset="utf-8">
<?php 
    if (isset($this->order)): 
?>
<table  border=0>
    <tr height="79px">
        <td width="300px" valign="bottom">
            <font face="Angsana New" size="1pt">
                <table width="100%" height="100%" border=0>
                    <tr>
                        <td width="100px"></td>
                        <td colspan="2" align="center">OPPO</td>
                    </tr>
                </table>
            </font>
        </td>
        <td ></td>
        <td width="275px"></td>
    </tr>
    <tr height="157px" valign="top"> <!-- 117 -->
        <td>
            <font face="Angsana New" size="1pt">
                <table width="300px" border=0 cellpadding="0" cellspacing="0">
                    <tr height="15px">
                        <td colspan="3"><td>
                    </tr>
                    <tr>
                        <td width="60px"></td>
                        <td >
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            บริษัท ไทย ออปโป้ จำกัด <br/>
                            230 ถ.บางขุนเทียนชายทะเล แขวงแสมดำ เขตบางขุนเทียน กทม 10150
                        </td>
                        <td width="10px"></td>
                    </tr>
                    <tr height="5px">
                        <td colspan="3"><td>
                    </tr>
                    <tr>
                        <td colspan="2" align="center">
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            คุณนพวัตน์ 098-878-3637
                        </td>
                        <td></td>
                    </tr>
                    <tr height="10px">
                        <td colspan="3"><td>
                    </tr>
                    <tr>
                        <td colspan="3">
                            <table width="100%" height="100%" border=0 cellpadding="0" cellspacing="0">
                                <tr>
                                    <td align="center"  width="80px">101150</td>
                                    <td align="center">
                                        0922468952
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </font>
        </td>
        <td valign="top">
            <font face="Angsana New" size="3pt">
                <?php echo $this->order['title']; ?> <br/>
                <?php echo $this->order['d_contact']; ?> <br/>
                <?php echo $this->order['address']; ?> <br/>
                <?php echo $this->order['tel']; ?> <br/>
                <?php echo $this->order['d_code']." (".$this->order['sales_sn_ref'].")"; ?>
            </font>
        </td>
        <td></td>
    </tr>
    <tr height="38px">
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td valign="top">
            <font face="Angsana New" size="3pt">
                โทรศัพท์ : <?php echo $this->order['cnt_phone']; ?> <br/>
                ถุง : <?php echo $this->order['cnt_bag']; ?> <br />
                อุปกรณ์เสริม : <?php echo $this->order['cnt_acc']; ?> <br />
            </font>
        </td>
        <td></td>
    </tr>
</table>
<!--
        <a href="<?php echo $this->refer ?>" class="no_print">Back - Click here if not automatically redirect browsers</a>
        <div class="wrapper">
            <p class="element name"><?php echo $this->order['receiver'];  ?></p>
            <p class="element address"><?php echo $this->order['address']; ?></p>
            <p class="element tel"><?php echo $this->order['phone_number']; ?></p>
            <p class="element province">
                <?php if (isset($this->order['district'])) echo My_Region::getValue($this->order['district'], My_Region::Province) ?>
            </p>
            <p class="element district">
                <?php if (isset($this->order['district'])) echo My_Region::getValue($this->order['district'], My_Region::District) ?>
            </p>
            <p class="element weight"><?php //echo $this->order['weight']; ?></p>
            <p class="element package"><?php //echo $this->order['number_of_package']; ?></p>
        </div>
-->
    <script>
        try {
            (function() {

                var beforePrint = function() {
                    // console.log('before');
                };

                var afterPrint = function() {
                    window.location.href = "<?php echo $this->refer ?>";
                    // console.log('after');
                };

                if (window.matchMedia) {
                    var mediaQueryList = window.matchMedia('print');
                    mediaQueryList.addListener(function(mql) {
                        if (mql.matches)
                            beforePrint();
                        else
                            afterPrint();
                    });
                }

                window.onbeforeprint = beforePrint;
                window.onafterprint = afterPrint;
                window.print();
            }());
        } catch (err) {
            console.log(err.message);
        }
    </script>
<?php endif ?>

