<meta charset="utf-8">
<?php if (isset($this->order)): ?>
<style>
/*
    .wrapper {
        position: relative;
        top: 60px;
        left: 50px;
        border:none;
        font-size:12px;
        width: 250px;
    }

    .element {
        position: absolute;
    }

    .name {
        top: 0px;
        left: 40px;
       
    }

    .address {
        top: 35px;
        left: 10px;
        line-height:23px;
        width: 260px;
        text-transform: capitalize;
    }

    .tel {
        top:140px;
        left:50px;
    }

    .province {
        top: 100px;
        left: 140px;
        width: 200px;
    }
    .district{
        top: 100px;
        left: -10px;
    }
    .package{
        top: 25px;
        left: 290px;
    }
    .weight{
        top: 25px;
        left: 340px;
    }
            
    @media print {
        .no_print {
            display: none;
        }
    }
*/
</style>
<!-- 
<table width="100%" height="50%" border=1>
    <tr>
        <td></td>
        <td></td>
        <td align="center">test</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td align="center">test</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>
-->
<?php //print_r($this->order); ?>
<table  border=0>
    <tr height="79px">
        <td width="300px"></td>
        <td ></td>
        <td width="275px"></td>
    </tr>
    <tr height="157px"> <!-- 117 -->
        <td></td>
        <td valign="top">
            <font face="Angsana New" size="3pt">
                <?php echo $this->order['title']; ?> <br/>
                <?php echo $this->order['d_contact']; ?> <br/>
                <?php echo $this->order['address']; ?> <br/>
                <?php echo $this->order['tel']; ?> <br/>
                <?php echo $this->order['d_code']." (".$this->order['sales_sn_ref'].")"; ?>
            </font>
        </td>
        <td></td>
    </tr>
    <tr height="38px">
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td valign="top">
            <font face="Angsana New" size="3pt">
                โทรศัพท์ : <?php echo $this->order['cnt_phone']; ?> <br/>
                ถุง : <?php echo $this->order['cnt_bag']; ?> <br />
                อุปกรณ์เสริม : <?php echo $this->order['cnt_acc']; ?> <br />
            </font>
        </td>
        <td></td>
    </tr>
</table>
<!--
        <a href="<?php echo $this->refer ?>" class="no_print">Back - Click here if not automatically redirect browsers</a>
        <div class="wrapper">
            <p class="element name"><?php echo $this->order['receiver'];  ?></p>
            <p class="element address"><?php echo $this->order['address']; ?></p>
            <p class="element tel"><?php echo $this->order['phone_number']; ?></p>
            <p class="element province">
                <?php if (isset($this->order['district'])) echo My_Region::getValue($this->order['district'], My_Region::Province) ?>
            </p>
            <p class="element district">
                <?php if (isset($this->order['district'])) echo My_Region::getValue($this->order['district'], My_Region::District) ?>
            </p>
            <p class="element weight"><?php //echo $this->order['weight']; ?></p>
            <p class="element package"><?php //echo $this->order['number_of_package']; ?></p>
        </div>
-->
    <script>
        try {
            (function() {

                var beforePrint = function() {
                    // console.log('before');
                };

                var afterPrint = function() {
                    window.location.href = "<?php echo $this->refer ?>";
                    // console.log('after');
                };

                if (window.matchMedia) {
                    var mediaQueryList = window.matchMedia('print');
                    mediaQueryList.addListener(function(mql) {
                        if (mql.matches)
                            beforePrint();
                        else
                            afterPrint();
                    });
                }

                window.onbeforeprint = beforePrint;
                window.onafterprint = afterPrint;
                window.print();
            }());
        } catch (err) {
            console.log(err.message);
        }
    </script>
<?php endif ?>

