<link rel="stylesheet" href="<?php echo HOST?>css/select2.css" />
<script src="<?php echo HOST?>js/select2.js"></script>

<form class="form-search form-horizontal" method="get">
	<div class="row">

		<div class="span5">

			<div class="control-group">
				<label for="dis_id" class="control-label">Distributor(My Side) : </label>
				<div class="controls">
					<select class="span3" name="dis_id" id="dis_id">
						<option value=""> Please Selected </option>
						<?php foreach ($this->distributor as $value) : ?>
							<option value="<?php echo $value['id'] ?>" <?php if(isset($this->params['dis_id']) && $this->params['dis_id'] == $value['id']) : ?> selected <?php endif; ?>><?php echo $value['title'] ?></option>
						<?php endforeach; ?>
					</select>
				</div>
			</div>

			<div class="control-group">
				<label for="account_pp" class="control-label">Account Property : </label>
				<div class="controls">
					<select class="span3" name="account_pp" id="account_pp">
						<option value=""> Please Selected </option>
						<option value="1" <?php if(isset($this->params['account_pp']) && $this->params['account_pp'] == 1) : ?> selected <?php endif; ?> > Personal Account </option>
						<option value="2" <?php if(isset($this->params['account_pp']) && $this->params['account_pp'] == 2) : ?> selected <?php endif; ?> > Company Account </option>
					</select>
				</div>
			</div>

			<div class="control-group">
				<label for="bank_id" class="control-label">Bank : </label>
				<div class="controls">
					<select class="span3" id="bank_id" name="bank_id">
						<option value=""> Please Selected </option>

						<?php if(isset($this->bank) && $this->bank) : ?>
							<?php foreach($this->bank as $key => $value) : ?>
								<option value="<?php echo $key ?>" <?php if(isset($this->params['bank_id']) && $this->params['bank_id'] == $key) : ?> selected <?php endif; ?> ><?php echo $value ?></option>
							<?php endforeach; ?>
						<?php endif; ?>
					</select>
				</div>
			</div>

			<div class="control-group">
				<label for="account" class="control-label">Account : </label>
				<div class="controls">
					<input type="text" name="account" id="account" class="span3" value="<?php if(isset($this->params['account']) && printf($this->params['account'])) ?>">
				</div>
			</div>

		</div>

		<div class="span5">

			<div class="control-group">
				<label for="finance_client" class="control-label">Finance Client : </label>
				<div class="controls">
					<select class="span3" name="finance_client" id="finance_client">
						<option value=""> Please Selected </option>

						<?php if(isset($this->financeClient) && $this->financeClient) : ?>
							<?php foreach($this->financeClient as $value) : ?>
								<option value="<?php echo $value['id'] ?>" <?php if(isset($this->params['finance_client']) && $this->params['finance_client'] == $value['id']) : ?> selected <?php endif; ?> ><?php echo $value['name'] ?></option>
							<?php endforeach; ?>
						<?php endif; ?> 

					</select>
				</div>
			</div>

			<div class="control-group">
				<label for="my_bank" class="control-label">My Bank Account : </label>
				<div class="controls">
					<select class="span3" name="my_bank" id="my_bank">
						<option value=""> Please Selected </option>

						<?php if(isset($this->bankAccountMy) && $this->bankAccountMy) : ?>
							<?php foreach($this->bankAccountMy as $value) : ?>
								<option value="<?php echo $value['id'] ?>" <?php if(isset($this->params['my_bank']) && $this->params['my_bank'] == $value['id']) : ?> selected <?php endif; ?> ><?php echo $value['bank_account'] ?></option>
							<?php endforeach; ?>
						<?php endif; ?>
					</select>
				</div>
			</div>

			<div class="control-group">
				<label for="card_no" class="control-label">Card No./Account : </label>
				<div class="controls">
					<input type="text" name="card_no" id="card_no" class="span3" value="<?php if(isset($this->params['card_no']) && printf($this->params['card_no'])) ?>">
				</div>
			</div>

		</div>

		<div class="span2">
			<button type="submit" class="btn btn-primary">Search</button>
			<button type="reset" class="btn btn-warning">Reset</button>
		</div>

	</div>
</form>

<script type="text/javascript">

	$('#dis_id, #bank_id, #finance_client').select2();

	$(document).ready(function () {

		$( "#dis_id" ).change(function() {
			var distributor_id    = $('#dis_id').val();

			$.get("/finance/load-bank-account-my",
				{distributor_id : distributor_id}
				,function(data,status){
					var data = $.parseJSON( data );

					if (data.bankaccount){
						var obj = data.bankaccount;
						$('#my_bank').html('<option value="0"> Please Selected </option>');
						for (var i = 0; i < obj.length; i++) {
							$('#my_bank').append('<option value="'+obj[i]['id']+'">'+obj[i]['bank_account']+'</option>');
						}
					}

					if (data.financeClient){
						var obj = data.financeClient;
						$('#finance_client').html('<option value="0"> Please Selected </option>');
						for (var i = 0; i < obj.length; i++) {
							$('#finance_client').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
						}
					}
				})
		});
	});

</script>