<table class="table table-bordered">
	<thead>
		<tr>
			<th>Finance Warehouse Group Code</th>
			<th>Distributor (My Side)</th>
			<th>Finance Warehouse Group</th>
			<th>Creation Time</th>
			<th>Creator</th>
			<th>Modified Time</th>
			<th>Last Modifier</th>
			<th>Remarks</th>
			<th>Operation</th>
		</tr>
	</thead>
	<tbody>

		<?php if(isset($this->finance_warehouse_group) && $this->finance_warehouse_group) : ?>
			<?php foreach($this->finance_warehouse_group as $value) : ?>

				<tr>
					<td><?php echo $value['id'] ?></td>
					<td><?php echo $this->distributor_cache[$value['d_id']] ?></td>
					<td><?php echo $value['group_name'] ?></td>
					<td><?php echo $value['created_at'] ?></td>
					<td><?php echo $this->staffs[$value['created_by']] ?></td>
					<td><?php echo $value['updated_at'] ?></td>
					<td><?php echo $this->staffs[$value['updated_by']] ?></td>
					<td><?php echo $value['remark'] ?></td>
					<td>
						<a href="<?php echo HOST ?>finance/add-finance-warehouse-group?id=<?php echo $value['id'] ?>"> Edit </a>
						| <a href="#" style="color: red;" data-id="<?php echo $value['id']; ?>" class="Confirm_data"> Delete </a>
					</td>
				</tr>

			<?php endforeach; ?>
		<?php endif; ?>

	</tbody>
</table>

<div class="paging">
	<?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('.Confirm_data').on('click', function (event) {
			event.preventDefault();
			var id = $(this).data('id');

			Swal.fire({
				title: 'Confirm to delete?',
				text: 'ຢືນຢັນການລຶບ ຂໍ້ມູນ ຫຼື ບໍ່? ຫຼັງຈາກລົບໄປເເລ້ວຈະບໍ່ສາມາດກູ້ຄືນໄດ້',
				icon: 'question',
				showCancelButton: true,
				confirmButtonColor: '#3085d6',
				cancelButtonColor: '#d33',
				confirmButtonText: '<b style="font-family:Phetsarath OT">ຢືນຢັນ</ b>',
				cancelButtonText: '<b style="font-family:Phetsarath OT">ຍົກເລີກ</ b>',
			}).then((result) => {

				if (result.isConfirmed) {
					window.location.href="/finance/delete-finance-warehouse-group?id="+id;
				}

			});
		});

	});

</script>