<link rel="stylesheet" href="<?php echo HOST ?>css/jquery-ui.css">
<link href="<?php echo HOST ?>css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="<?php echo HOST ?>css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">
<link href="<?php echo HOST ?>css/bootstrap-modal.css" rel="stylesheet" type="text/css">
<style>
    .loader {
        top: -120px;
        left: 160px;
      border: 20px solid #f3f3f3;
      border-radius: 50%;
      border-top: 20px solid #00925F;
      border-bottom: 20px solid #00925F;
      width: 50px;
      height: 50px;
      -webkit-animation: spin 2s linear infinite;
      animation: spin 2s linear infinite;
      position: relative;
    }

    @-webkit-keyframes spin {
      0% { -webkit-transform: rotate(0deg); }
      100% { -webkit-transform: rotate(360deg); }
    }

    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }

    #btn-calculate{margin-top:20px;}

    .distributor-info{
        padding: 10px;
        border: 1px solid #ccc;
        margin-left: 30px;
    }
    .distributor-info label{
        font-weight: bold;

    }
    .customer-info{
        padding: 10px;
        border: 1px solid #ccc;
        margin-left: 30px;
    }
    .customer-info label{
        font-weight: bold;

    }
    .no_show{
        display: none;
    }
    .total_price{
        margin-left: 850px;
        margin-top: -100px;
        position: absolute;
    }
    .address_textarea{
        width: 350px;
        height: 50px;
    }
    label input,
    label select {
        margin-right: 25px;
    }

    #myTags{
        display: block;
        margin: 0px;
        min-width: 400px;
    }

    #qs_retailer{
        width: 100px!important;
    }
    .loading-mask{display: none;}
    .info_nvmm,.info_ingame{
        margin-bottom: 20px;
        padding-bottom: 20px;
        padding-left: 30px;
        /*border-bottom: 1px solid #E39A2D;*/
    }

    #object_id{
        position: relative;
        border-top: none;
        top: -20px;
        left: -20px;
        -webkit-appearance: button;
        -webkit-border-radius: 2px;
        -webkit-box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.1);
        -webkit-padding-end: 20px;
        -webkit-padding-start: 2px;
        -webkit-user-select: none;
        background-image: -webkit-linear-gradient(#fafafa, #f4f4f4 40%, #e5e5e5);
        /* background-position: 97% center; */
        background-repeat: no-repeat;
        border: 1px solid #AAA;
        color: #555;
        font-size: inherit;
        margin: 20px;
        overflow: hidden;
        padding: 5px 10px;
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow-y: scroll;
    }
    .payment_date{
        width: 100px!important;
    }
    .nvmm_money{
        width: 100px!important;
    }

    .add_row_nvmm{
        margin-left: 30px;
    }
    .delivery_fee{
        text-align: right; max-width: 100px;
    }
    .not_show{display: none;}
</style>



<div class="page-header">
    <?php if (isset($this->sales) and $this->sales):?>
        <h1>Edit Sales order</h1>
    <?php else:?>
        <h1>Create Sales order</h1>
    <?php endif;?>
</div>


<?php

$total_amount_all= $this->total_amount_all;
$delivery_fee_all= $this->delivery_fee_all;
$sales_order=$this->sales_order;
//echo $total_amount_all;
$delivery_fee = 0;
$delivery_fee = $this->sales[0]['sale']->delivery_fee;
if($delivery_fee<=0){
    //$delivery_fee=60;
}

if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;

$customer_id = $this->sales[0]['sale']->customer_id;
$area_id = $this->sales[0]['sale']->area_id;

?>


<form role="form" id="form" action="<?php echo HOST.'sales/save';?>" method="post" class="form-inline">

<?php if (isset($this->sales) and $this->sales):?>
    <input type="hidden" name="edit" value="1">
    <div class="row">
        <div class="span6">
            <label class="span2">Sales order number</label>
            <span class="span3"><strong><?php isset($this->sales) and $this->sales and isset($this->sales[0]['sale']->sn_ref) and printf($this->sales[0]['sale']->sn_ref);?></strong></span>
        </div>
    </div>
    <div class="row">
        <div class="span6">
            <label class="span2">Order Maker</label>
            <span class="span3"><strong><?php isset($this->sales) and $this->sales and isset($this->staffs_cached[ $this->sales[0]['sale']->user_id]) and printf($this->staffs_cached[ $this->sales[0]['sale']->user_id]);?></strong></span>
        </div>
    </div>
    <div class="row">
        <div class="span6">
            <label class="span2">Order Time</label>
            <span class="span3"><strong><?php isset($this->sales) and $this->sales and isset( $this->sales[0]['sale']->add_time) and printf( $this->sales[0]['sale']->add_time );?></strong></span>
        </div>
    </div>
<?php endif;?>

<div class="row">
    <div class="span6">
        <!--
        <div id="tooltip_type" style="display: none">
            <p>For Retailer: Đơn hàng xuất cho đại lý</p>
            <p>For Demo: Đơn hàng trải nghiệm</p>
            <p>For Staffs: Đơn hàng cho nhân viên</p>
            <p>For Lending: Đơn hàng cho mượn</p>
        </div>
        -->

        <div id="tooltip_type" style="display: none">
            <p>For Retailer: Export Orders for agents</p>
            <p>For Demo: Orders experience</p>
            <p>For Staffs: Orders for employees</p>
            <p>For Lending: Orders loan</p>
        </div>

        <label class="span4 tooltip-r" for="type" data-toggle="tooltip">Order Type <span style="color: red">*</span>
            <select id="type" class="span4 type" name="type" required="required">
                <option value="">Please select</option>
                <?php
                    if(isset($this->arr_order_type) AND $this->arr_order_type):
                        foreach($this->arr_order_type as $key => $value):
                            ?>
                            <option value="<?php echo $key;?>" <?php if ( isset($this->sales[0]['sale']) and $this->sales[0]['sale']->type == $key):?> selected <?php endif;?>>
                                <?php echo $value;?>
                            </option>
                        <?php
                        endforeach;
                    endif;
                ?>
            </select>
        </label>
        
        <?php
            if($this->sales[0]['sale']->salesman ==''){
                $sales_admin = $this->staff_id;
                $sales_catty_id="";
            }else{
                $sales_admin = $this->sales[0]['sale']->salesman;
                $sales_catty_id = $this->sales[0]['sale']->sales_catty_id;
            }
        ?>

    <input type="hidden" class="span4" id="salesman" name="salesman" placeholder="Sales Admin" required="required" 
        value="<?php echo $sales_admin;?>" />

        <?php //echo $this->render('sales/partials/po-list.phtml') ?>
        <?php if (isset($this->sales[0]['sale']->d_id) and $this->sales[0]['sale']->d_id) { ?>
            <label class="span4" >Retailer name<span style="color: red">*</span><br/>
                <span style="font-size: 18px;">    <?PHP echo $this->dis_name[$this->sales[0]['sale']->d_id] ?></span>
                <input type="hidden" name="price_clas" class="price_clas" value="<?=$this->sales[0]['sale']->price_clas?>">
                <input type="hidden" name="distributor_id" id="distributor_id" value="<?=$this->sales[0]['sale']->d_id?>">
            </label>
        <?PHP }else{ ?>      
                <label class="span4" for="rank">ประเภทร้านค้า<span style="color: red">*</span>
                
                    <select id="rank" name="rank" class="rank span4">
                        <option value="">---</option>
                        <option value="1" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==1 ) { ?> selected<?php }?>>1. ORG-WDS(1)</option>
                        <option value="2" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==2 ) { ?> selected<?php }?>>2. ORG(2)</option>
                        <option value="5" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==5 ) { ?> selected<?php }?>>3. ORG-Dtac/Advice(5)</option>
                        <option value="6" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==6 ) { ?> selected<?php }?>>4. ORG-Lotus/Power by(6)</option>
                        <option value="7" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==7 ) { ?> selected<?php }?>>5. Dealer(7)</option>
                        <option value="8" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==8 ) { ?> selected<?php }?>>6. HUB(8)</option>
                        <option value="9" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==9 ) { ?> selected<?php }?>>7. Laos(9)</option>
                        <option value="3" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==3 ) { ?> selected<?php }?>>8. Online and Staff(3)</option>
                        <option value="10" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==10 ) { ?> selected<?php }?>>9. Brand Shop/Service(10)</option>
                      
                    </select>
                </label>
                    
                
        <div class="retailer_name_list"></div>    
    <?PHP     } ?>

        <label class="span4" for="salesman">Sales Catty
            <select id="salesman_catty" class="span4 salesman_catty" name="salesman_catty">
                <option value="">Please select</option>
            </select>
            <input type="hidden" class="span4" id="sales_catty_id" name="sales_catty_id" value="<?php echo $sales_catty_id;?>" />
        </label>

        <div class="clearfix"></div>

        <div class='customer-info'>
            <p>
                <button class="btn-success pull-right view-more" type="button">
                    -
                </button>
            </p>
            <p id= 'customer_name_select'>
                <label>Customer Name: </label>

                <select id="customer_id"  class="customer_id"  name="customer_id" onchange="getCustomerInfo()">
                      
                    <?php
                    // foreach($this->customerbrandshop as $val):
                    //     $selected = '';
                    //  if($val['customer_id']==$customer_id){
                    //      $selected = 'selected';
                    //  }
                    //     echo '<option '.$selected.' value="'.$val['customer_id'].'">'.$val['customer_name'].'</option>';
                    // endforeach;
                    ?>
                </select>       
                <button class="btn-success customer add_customer" type="button">
                    เพิ่ม
                </button>
            </p> 
            <p id= 'customer_name_add'>
                <label>Customer Name: </label>
                <input type="text" name="customer_name" class="customer_name" id="customer_name" value="">
                <button class="btn-success customer customer_save" type="button">
                    บันทึก
                </button>
                <button class="btn-success customer change_search" type="button">
                    <i class="icon-search"></i>
                </button>
            </p>

            <p >
                <label>Tax Number: </label>
                <?php if($customer_id !=''){
                    $customer_tax_number = '';
                    foreach($this->customerbrandshop as $val):    
                        if($val['customer_id']==$customer_id){
                            $customer_tax_number=$val['tax_number'];
                        } 
                    endforeach;
                    ?>

                <input type="text" class="customer_tax_number" id="customer_tax_number" value="<?=$customer_tax_number?>" placeholder="Enter Tax Number" name="customer_tax_number">
                <?php }else{ ?>
                <input type="text" class="customer_tax_number" id="customer_tax_number" value="" placeholder="Enter Tax Number" name="customer_tax_number">
                <?php } ?>
            </p>
            

            <p <?php if($this->sales[0]['sale']->customer_tax_address==''){?> class='customer_tax_address' <?php } ?>>
                <label>Tax Address : </label>
                <textarea name="customer_tax_address" class="customer_tax_address address_textarea"><?php if(isset($this->sales[0]['sale']->customer_tax_address)) echo $this->sales[0]['sale']->customer_tax_address;?></textarea>
            </p>
            <div class="loader"></div>
        </div>
    </div>


    <div class="span6">

        <div class="control-group">
            <label for="myTags" class="span2">Tags
                <ul class="form-control span3" id="myTags"><?php
                if (isset($this->a_tags) and $this->a_tags):
                    foreach ($this->a_tags as $ta)
                        echo '<li>'.$ta.'</li>';
                endif;
                ?></ul>
            </label>
        </div>

        <label class="span4" for="warehouse_id">Warehouse <span style="color: red">*</span>
            <select id="warehouse_id" class="span4" name="warehouse_id" required="required">
                <option value="">Please select</option>
                <?php foreach ($this->warehouses as $warehouse):?>
                    <option value="<?php echo $warehouse->id;?>" <?php if (isset($this->sales) and $warehouse->id == $this->sales[0]['sale']->warehouse_id):?> selected<?php endif;?>><?php echo $warehouse->name;?></option>
                <?php endforeach;?>
            </select>
        </label>
        <div class="clearfix"></div>
        <div class='distributor-info clearfix'>
            <p>
                <button class="btn-success pull-right view-more" type="button">
                    -
                </button>
            </p>
            <p class='retailer_name'>
                <label>Retailer name: </label>
                <span></span>
            </p>
            
            <p <?php if($this->sales[0]['sale']->delivery_address==''){?> class='add' <?php } ?>
            >
                <label>Address Delivery: </label>
                <textarea name="add_delivery_new" class="address_textarea"></textarea>
                <textarea  name="add_delivery_old" style="display:none;" class="address_textarea "><?php if(isset($this->sales[0]['sale']->delivery_address)) echo $this->sales[0]['sale']->delivery_address;?></textarea>
                <!-- <select name="sipping_add" id="sipping_add" class="_search" style="width:100%">
                        <?php if (isset( $this->districts ) && $this->districts): ?>
                            <?php foreach ($this->districts as $key => $region): ?>
                                <option value="<?php echo $key ?>" <?php if( isset($this->shipping_address['districts_id']) && $this->shipping_address['districts_id'] == $key ) echo "selected='selected'" ?>><?php echo $region['name'] ?></option>
                            <?php endforeach ?>
                        <?php endif ?>
                    </select>     -->
            </p>
            <p class='credit_status'>
                <label>ใช้วงเงินเครดิต : </label>
                <span></span>
            </p>
            <p class='credit_amount'>
                <label>Maximum Credit : </label>
                <strong><font color="red"><span></span></p></font></strong>
            </p>
            <p style="display: none;" class='balance'>
                <label>Balance for this retailer : </label>
                <span></span>
            </p>
            <p class='total_balance'>
                <label>Total Remain balance (main and sub retailer) : </label>
                <span></span>
            </p>
            <p class='credit_type'>
                <label>Credit Type : </label>
                <span></span>
            </p>

            <p class='spc_discount_show'>
                <label>Special Discount (%) : </label>
                <span></span>
            </p>

        </div>
        
    </div>
</div>

<br />

<div class="row">
    <div class="span12">
        <label class="span2" for="life_time">Order Life time <span style="color: red">*</span>
        </label>

        <div class="span4">
            <input class="span1" type="number" name="life_time" maxlength="3" max="5" min="1" id="life_time" required="required" <?php if (! $this->life_time_editable) {?> disabled<?php }?> value="<?php if ( isset($this->sales[0]['sale']) and $this->sales[0]['sale']->life_time ) echo $this->sales[0]['sale']->life_time / ( 24*60*60 ); else echo 1;?>"><span class="1">day(s)</span>
        </div>
    </div>
</div>

<div class="row">
    <div class="span12">
        <p class="pull-right">Free delivery for orders from 10,000THB</p>
    </div>
</div>

<?php echo $this->render('sales/partials/fee.phtml') ?>


<br />



<?php if ($this->sales):?>

    <?php foreach ($this->sales as $item):
        $sale = $item['sale'];
        $goods = $item['goods'];
        $colors = $item['colors'];
    ?>

        <div class="row detail_good">
            <div class="span12 addItem">
                
                <label class="span1">Category <span style="color: red">*</span>
                    <select class="span1 cat_id" name="cat_id[]" required="required">
                        <option value="">Please select</option>
                        <?php foreach ($this->good_categories as $good_category):?>
                            <option value="<?php echo $good_category->id;?>" <?php if ($good_category->id == $sale->cat_id):?> selected<?php endif;?>><?php echo $good_category->name;?></option>
                        <?php endforeach;?>
                    </select>
                </label>

                <label class="span1">Product <span style="color: red">*</span>
                    <select class="span1 good_id" name="good_id[]" required="required">
                        <option value="">Please select</option>
                        <?php foreach ($goods as $good):?>
                            <option value="<?php echo $good->id;?>" <?php if ($good->id == $sale->good_id):?> selected<?php endif;?>><?php echo $good->name;?></option>
                        <?php endforeach;?>
                    </select>
                </label>

                <label class="span1">Color <span style="color: red">*</span>
                    <select class="span1 good_color" name="good_color[]" required="required">
                        <option value="">Please select</option>
                        <?php foreach ($colors as $color):?>
                            <option value="<?php echo $color->id;?>" <?php if ($color->id == $sale->good_color):?> selected<?php endif;?>><?php echo $color->name;?></option>
                        <?php endforeach;?>
                    </select>
                </label>

                <label class="span1 quantity">Quantity <span style="color: red">*</span>
                    <input type="number" min="1" class="span1 num" name="num[]" required="required" maxlength="5" style="width: 50px" value="<?php printf($sale->num);?>" />
                </label>

                <label class="span1">Price <span style="color: red">*</span>
                    <input type="text" min="1" required="required" class="span1 price" name="price[]" value="<?php echo My_Number::f($sale->price);?>" />
                </label>

                <label class="span1">Sale off <span style="color: red">*</span>
                    <select disabled class="span1 sale_off_percent" name="sale_off_percent[]" required="required">
                    <option value="0" <?php if ($sale->sale_off_percent == 0){?> selected<?php }?>>0%</option>
                    <option value="1" <?php if ($sale->sale_off_percent == 1){?> selected<?php }?>>1%</option>
                    <option value="10" <?php if ($sale->sale_off_percent == 10){?> selected<?php }?>>10%</option>
                    <option value="15" <?php if ($sale->sale_off_percent == 15){?> selected<?php }?>>15%</option>
                    <option value="16" <?php if ($sale->sale_off_percent == 16){?> selected<?php }?>>16%</option>
                    <option value="18" <?php if ($sale->sale_off_percent == 18){?> selected<?php }?>>18%</option>
                    <option value="20" <?php if ($sale->sale_off_percent == 20){?> selected<?php }?>>20%</option>
                    <option value="22" <?php if ($sale->sale_off_percent == 22){?> selected<?php }?>>22%</option>
                    <option value="23" <?php if ($sale->sale_off_percent == 23){?> selected<?php }?>>23%</option>
                    <option value="24" <?php if ($sale->sale_off_percent == 24){?> selected<?php }?>>24%</option>
                    <option value="25" <?php if ($sale->sale_off_percent == 25){?> selected<?php }?>>25%</option>
                    <option value="27" <?php if ($sale->sale_off_percent == 27){?> selected<?php }?>>27%</option>
                    <option value="29" <?php if ($sale->sale_off_percent == 29){?> selected<?php }?>>29%</option>
                    <option value="30" <?php if ($sale->sale_off_percent == 30){?> selected<?php }?>>30%</option>
                    <option value="31" <?php if ($sale->sale_off_percent == 31){?> selected<?php }?>>31%</option>
                    <option value="40" <?php if ($sale->sale_off_percent == 40){?> selected<?php }?>>40%</option>
                    <option value="50" <?php if ($sale->sale_off_percent == 50){?> selected<?php }?>>50%</option>
                    <option value="100" <?php if ($sale->sale_off_percent == 100){?> selected<?php }?>>ของแถม</option>
                        
                    </select>
                </label>

                <label class="span2">Total<span style="color: red">*</span>
                <input readonly type="text" min="0" required="required" class="span2 total" name="total[]" value="<?php echo My_Number::f($sale->total);?>" />
                </label>

                <label class="span2">Remark
                    <textarea name="text[]" class="span2 text"><?php if(isset($sale->text)) echo $sale->text;?></textarea>
                </label>
                <div class="no_show">
                <label class="span1 campaign">Campaign<span style="color: red">*</span>
                    <input type="checkbox" class="span1 campaign_ck" name="campaign_ck[]"  <?php if(isset($sale->campaign) and $sale->campaign) echo 'checked="checked"'; ?> />
                    <input type="hidden" class="campaign_val" name="campaign[]" value="<?php if(isset($sale->campaign) and $sale->campaign) echo $sale->campaign; ?>" />
                </label>
                </div>
                <label class="span1">&nbsp;<button type="button" class="btn-danger remove-sales"><i class="icon-minus"></i></button></label>

                <input type="hidden" name="ids[]" class="ids" value="<?php if(isset($sale->id)) echo $sale->id;?>">
            </div>

            <!-- Button add nhan vien mua may -->
            <div class="span12 btn_add_row_nvmm" style="display: none">
                <label for="" class="span12">
                    <button class="add_row_nvmm btn btn-small btn-success" type="button">+</button>
                </label>
            </div>

            <?php
                if(isset($this->staff_nvmm)){
                    foreach($this->staff_nvmm as $k => $value){
                        if($value['market_id'] == $item['sale']['id']){
            ?>

            <?php if($item['sale']['d_id'] == OPPO_STAFF){ ?>
                <div class="span12 info_nvmm" >
                    <input type="hidden" name="product_color_key[]" class="product_color_key" value/>
                    <label class="span3">For staff <span style="color: red">*</span>
                        <input type="text" class="span3 name_staff" required value="<?php echo $value['staff_name'];?>"/>
                        <input type="hidden" class="span3 id_staff" data-name="<?php echo $value['staff_name_2'];?>" name="id_staff[]" value="<?php echo $value['staff_id'];?>" />
                    </label>

                    <label class="span1">Add staff<span style="color: red"></span>
                        <button type="button" class="btn-warning id_for_staff"><i class="icon-plus"></i></button>
                    </label>

                    <label class="span1 wrap_shipment_type">Loại <span style="color: red"></span>
                        <select class="span1 shipment_type" name="shipment_type[]">
                            <option value="0">----</option>
                            <?php
                                if(isset($this->arr_shipment_type) AND $this->arr_shipment_type){
                                    foreach($this->arr_shipment_type as $_k => $_v){
                                        ?>
                                        <option value="<?php echo $_k;?>" <?php if(isset($value['shipment_type']) AND $_k == $value['shipment_type']) echo 'selected';?>><?php echo $_v;?></option>
                                    <?php
                                    }
                                }
                            ?>
                        </select>
                    </label>

                    <label class="span1">num <span style="color: red">*</span>
                        <input type="number" min="1" class="span1 staff_num" name="staff_num[]" required="required" maxlength="5" style="width: 50px"
                               value="<?php if( isset($value['num']) ) echo $value['num']; ?>"/>
                    </label>

                    <label class="span2">จำนวนของคะแนนที่ได้รับ <span style="color: red"></span>
                        <input type="text" class="span2 sophieuthu nvmm_money" name="sophieuthu[]" value="<?php if( isset($value['number_sales_order']) ) echo $value['number_sales_order']; ?>"/>
                    </label>

                    <label class="span2">จำนวนเงินที่ชำระ<span style="color: red"></span>
                        <input type="text" class="span2 sotienthucte nvmm_money" name="sotienthucte[]" value="<?php if( isset($value['actual_amount_paid']) ) echo $value['actual_amount_paid']; ?>"/>
                    </label>

                    <label class="span1">ยอดคงเหลือ <span style="color: red"></span>
                        <input type="text" class="span2 sodu nvmm_money" name="sodu[]" readonly/>
                    </label>

                    <label class="span2"> วันที่ชำระเงิน:<span style="color: red"></span><br />
                        <input type="text" name="payment_date[]" class="payment_date" value="<?php if( isset($value['payment_date']) ) echo date('d/m/Y',strtotime($value['payment_date'])); ?>" />
                    </label>

                    <label class="span1">
                        <button type="button" class="remove_nvmm btn btn-small btn-danger">-</button>
                    </label>
                </div>
            <?php }elseif($item['sale']['d_id'] == OPPO_INGAME){?>

            <div class="span12 info_ingame">

                <label class="span2">Name<span style="color: red">*</span>
                    <input type="hidden" name="product_color_key[]" class="product_color_key" value/>
                    <input type="text" class="span2 name_staff_ingame" name="name_staff_ingame[]" value="<?php echo $value['name']?>"/>

                </label>

                <label class="span2">IDNumber<span style="color: red"></span>
                    <input type="text" class="span2 cmnd_staff_ingame" name="cmnd_staff_ingame[]" value="<?php echo $value['id_number']?>" />
                </label>

                <label class="span1 ">Loại <span style="color: red"></span>
                    <select class="span1 shipment_type" name="shipment_type[]">
                        <option value="0">----</option>
                        <?php
                        if(isset($this->arr_shipment_type) AND $this->arr_shipment_type){
                            foreach($this->arr_shipment_type as $_k => $_v){
                                ?>
                                <option value="<?php echo $_k;?>" <?php if(isset($value['shipment_type']) AND $_k == $value['shipment_type']) echo 'selected';?>><?php echo $_v;?></option>
                            <?php
                            }
                        }
                        ?>
                    </select>
                </label>

                <label class="span1">num <span style="color: red">*</span>
                    <input type="number" min="1" class="span1 staff_num" name="staff_num[]" required="required" maxlength="5" style="width: 50px"
                           value="<?php if( isset($value['num']) ) echo $value['num']; ?>"/>
                </label>

                <label class="span2">จำนวนของคะแนนที่ได้รับ <span style="color: red"></span>
                    <input type="text" class="span2 sophieuthu nvmm_money" name="sophieuthu[]" value="<?php if( isset($value['number_sales_order']) ) echo $value['number_sales_order']; ?>"/>
                </label>

                <label class="span2">จำนวนเงินที่ชำระ<span style="color: red"></span>
                    <input type="text" class="span2 sotienthucte nvmm_money" name="sotienthucte[]" value="<?php if( isset($value['actual_amount_paid']) ) echo $value['actual_amount_paid']; ?>"/>
                </label>

                <label class="span1">ยอดคงเหลือ <span style="color: red"></span>
                    <input type="text" class="span2 sodu nvmm_money" name="sodu[]" readonly/>
                </label>

                <label class="span2"> วันที่ชำระเงิน:<span style="color: red"></span><br />
                    <input type="text" name="payment_date[]" class="payment_date" value="<?php if( isset($value['payment_date']) ) echo date('d/m/Y',strtotime($value['payment_date'])); ?>"/>
                </label>

                <label class="span1">
                    <button type="button" class="remove_nvmm btn btn-small btn-danger">-</button>
                </label>
            </div>
            <?php }?>

            <?php
                        }// End if
                    }// End foreach
                }// End if
            ?>
        </div>
<?php endforeach;?>


<?php else:?>
    <div class="row detail_good">
        <div class="span12">

            <label class="span1">Category <span style="color: red">*</span>
                <select class="span1 cat_id" name="cat_id[]" required="required">
                    <option value="">Please select</option>
                    <?php foreach ($this->good_categories as $good_category):?>
                        <option value="<?php echo $good_category->id;?>"><?php echo $good_category->name;?></option>
                    <?php endforeach;?>
                </select>
            </label>

            <label class="span1">Product <span style="color: red">*</span>
                <select class="span1 good_id" name="good_id[]" required="required">
                    <option value="">Please select</option>
                </select>
            </label>

            <label class="span1">Color <span style="color: red">*</span>
                <select class="span1 good_color" name="good_color[]" required="required">
                    <option value="">Please select</option>
                </select>
            </label>

            <label class="span1">Quantity <span style="color: red">*</span>
                <input type="number" min="1" class="span1 num" name="num[]" required="required" maxlength="5" style="width: 50px" />
            </label>

            <label class="span1">Price <span style="color: red">*</span>
                <input type="text" min="1" step="any" required="required"  class="span1 price" name="price[]" />
            </label>

            <label class="span1">Sale off <span style="color: red">*</span>
                <select class="span1 sale_off_percent" name="sale_off_percent[]" required="required">
                    <option value="0">0%</option>
                    <option value="1">1%</option>
                    <option value="10">10%</option>
                    <option value="15">15%</option>
                    <option value="16">16%</option>
                    <option value="18">18%</option>
                    <option value="20">20%</option>
                    <option value="22">22%</option>
                    <option value="23">23%</option>
                    <option value="24">24%</option>
                    <option value="25">25%</option>
                    <option value="27">27%</option>
                    <option value="29">29%</option>
                    <option value="30">30%</option>
                    <option value="31">31%</option>
                    <option value="40">40%</option>
                    <option value="50">50%</option>
                    <option value="100">ของแถม</option>
                </select>
            </label>

            <label class="span2">Total<span style="color: red">*</span>
                <input type="text" min="0" step="any" required="required" readonly value="0" class="span2 total" name="total[]" />
            </label>

            <label class="span2">Remark
                <textarea name="text[]" class="span2 text"></textarea>
            </label>
            <div class="no_show">
            <label class="span1 campaign">Campaign<span style="color: red">*</span>
                <input type="checkbox" class="span1 campaign_ck not_show" name="campaign_ck[]"  />
                <input type="hidden" class="campaign_val" name="campaign[]" value="" />
            </label>
            </div>
            <label class="span1">&nbsp;<button type="button" class="btn-danger remove-sales"><i class="icon-minus"></i></button></label>

            <input type="hidden" name="ids[]" class="ids" />
        </div>

        <!-- Button add nhan vien mua may -->
        <div class="span12 btn_add_row_nvmm" style="display: none">
            <label for="" class="span12">
                <button class="add_row_nvmm btn btn-small btn-success" type="button">+</button>
            </label>
        </div>
    </div>
    <div class="add-gift"></div>
<?php endif;?>

<div class="row">
    <div class="span12">
        <label class="span3"><button type="button" class="btn-success add-sales"><i class="icon-plus"></i></button></label>
    </div>
</div>

<br>

<!--bvg -->
<?php if ($this->sales_product):?>

    <?php foreach ($this->sales_product as $kitem => $item):
        $sale = $item['sale'];
        $goods = $item['goods'];
    ?>

<div class="row" >
    <div class="span12">
        <label class="span2">Joint Circular <span style="color: red">*</span>
           <select class="span2 joint" name="joint[]" required="required" >
                <option value="">Please select</option>
                <?php foreach ($this->joint as $k => $v):?>
                    <option value="<?php echo $k;?>" <?php if ($k == $sale->joint):?>selected<?php endif;?>><?php echo $v;?></option>
                <?php endforeach;?>
            </select>
        </label>


     <label class="span2">Product <span style="color: red">*</span>
                    <select class="span2 good_id" name="good_id_bvg[]" required="required">
                        <option value="">Please select</option>
                        <?php foreach ($goods as $good):?>
                            <option  value="<?php echo $good->id;?>" <?php if ($good->id == $sale->good_id):?> selected<?php endif;?>><?php echo $good->name;?></option>
                        <?php endforeach;?>
                    </select>
                </label>

    <label class="span2">Price <span style="color: red">*</span>
            <input type="text" readonly min="1" required="required" class="span2 price_bvg" name="price_bvg[]" value="<?php printf(My_Number::f($sale->price));?>" />
    </label>

    <label class="span2">Quantity <span style="color: red">*</span>
            <input type="number" min="1" class="span2 num_bvg" name="num_bvg[]" readonly required="required" maxlength="5" value="<?php printf($sale->num);?>" />
    </label>

    <label class="span2">Total<span style="color: red">*</span>
            <input type="text" readonly min="0" required="required" class="span2 total_bvg" name="total_bvg[]" value="<?php printf(My_Number::f($sale->total));?>" />
        </label>

           <label class="span1">&nbsp;<button type="button" class="btn-danger remove-sales"><i class="icon-minus"></i></button></label>


    <label class="span12">
        <select  name="bvg_imei[]" class="bvg_imei"  readonly multiple="multiple" size="5" >
        <?php if(isset($this->imei) and $this->imei):
                    $list_imei = array();
          ?>
        <?php foreach($this->imei[$kitem] as $k => $v ) :
                    $list_imei[] = $v['id'];
         ?>

            <option selected="selected" value="<?php echo $v['id'] ?>"> <?php echo $v['imei_sn'] ?></option>

        <?php endforeach; endif; ?>
        </select>
    </label>
           <input type="hidden" name="ids_bvg_imei[]" class="ids_imei" value="<?php if(isset($list_imei) and $list_imei) echo $list_imei[0]; ?>"  />
           <input type="hidden" name="ids_bvg[]" class="ids"  value="<?php if(isset($sale->id)) echo $sale->id;?>" />
   </div>
</div>

    <?php endforeach;endif;?>
<!--end bvg-->




<div class="row not_show">
    <div class="span6">
        <div class="span6">
            <p><button type="button" id="btn-calculate" class="btn btn-warning add-bvg">Create Protect Price</button></p>
        </div>
    </div>
</div>
<br>


<?php if ($this->sales_discount):?>

    <?php foreach ($this->sales_discount as $sale):    ?>

<div class="row" >
    <div class="span12">
        <label class="span2">Joint Circular Discount<span style="color: red">*</span>
           <select class="span2 joint_discount" name="joint_discount[]" required="required" >
                <option value="">Please select</option>
                <?php foreach ($this->joint_discount as $k => $v):?>
                    <option value="<?php echo $k;?>" <?php if ($k == $sale->joint_circular_id):?>selected<?php endif;?>><?php echo $v;?></option>
                <?php endforeach;?>
            </select>
        </label>



    <label class="span2">Price Discount <span style="color: red">*</span>
            <input type="text" min="1" required="required" class="span2 price_discount" name="price_discount[]" value="<?php printf(My_Number::f($sale->price));?>" />
    </label>


           <label class="span1">&nbsp;<button type="button" class="btn-danger remove-sales"><i class="icon-minus"></i></button></label>
           <input type="hidden" name="ids_discount[]" class="ids"  value="<?php if(isset($sale->id)) echo $sale->id;?>" />
   </div>
</div>

    <?php endforeach;endif;?>
<!--end discount-->

<div class="row not_show">
    <div class="span6">
        <div class="span6">
            <p><button type="button" id="btn-discount" class="btn btn-primary btn-sale">Create Discount</button></p>
        </div>
    </div>
</div>

<!---   Credit Note -->
<?php if ($this->credits_note_sales_order):?>
<?php 
foreach ($this->credits_note_sales_order as $sale):   
    $creditnote_sn = $sale['creditnote_sn'];
    $balance_total = $sale['balance_total'];
    $use_total = $sale['use_discount'];
 ?>

<div class="row" >
<div class="span12">
<label class="span2">Discount Credit Note<span style="color: red">*</span>
   <select class="span2 discount_creditnote" name="discount_creditnote[]" >
        <option value="">Please select</option>
        <?php 

        $row_total=count($this->credits_note);

        foreach ($this->credits_note as $k):
            for($row=0;$row<=$row_total;$row++){
            if($k[$row]['creditnote_sn']!=''){
        ?>
            <option value="<?php echo $k[$row]['balance_total'];?>" 
              <?php if ($k[$row]['creditnote_sn'] == $creditnote_sn):?>selected<?php endif;?>>
              <?php echo $k[$row]['creditnote_sn'];?>
            </option>
        <?php 
            }
        } 
        endforeach;?>
    </select><?=$creditnote_sn?>
</label>

    <label class="span2">Discount Balance Total <span style="color: red">*</span>
            <input type="text" readonly min="1"  class="span2 price_balance_discount_creditnote" name="price_balance_discount_creditnote[]" value="<?php printf(My_Number::f($balance_total));?>" />
    </label>

    <label class="span2">Use Discount Price <span style="color: red">*</span>
            <input type="text" min="1" required="required" class="span2 price_use_discount_creditnote" name="price_use_discount_creditnote[]" value="<?php printf(My_Number::f($use_total));?>" />
    </label>


           <label class="span1">&nbsp;<button type="button" class="btn-danger remove-credit-note"><i class="icon-minus"></i></button></label>
           <input type="hidden" name="ids_discount_creditnote[]" class="span2 ids_discount_creditnote"  value="<?=$creditnote_sn?>" />
   </div>
</div>

    <?php endforeach;endif;?>

<div class="row">
    <div class="span6">
        <div class="span6">
            <p><button type="button" id="btn-discount-creditnote" class="btn btn-primary btn-sale">Create Discount Credit Note</button></p>
        </div>
    </div>
</div>

<!--- End  Credit Note -->

 <!--- Summary Total Price --> 
 <div class="row">
 <input type="hidden" name="txt_sum_total" id="txt_sum_total" value="0">
 <input type="hidden" name="txt_sum_discount_creditnote" id="txt_sum_discount_creditnote" value="0">
 <input type="hidden" name="txt_sum_discount" id="txt_sum_discount" value="0">
 <input type="hidden" name="txt_sum_discount_protection_price" id="txt_sum_discount_protection_price" value="0">
 <input type="hidden" name="total_amount_all" class="total_amount_all" id="total_amount_all" value="<?=$total_amount_all?>">
 <input type="hidden" name="delivery_fee_all" class="delivery_fee_all" id="delivery_fee_all" value="<?=$delivery_fee_all?>">
 <input type="hidden" name="distributor_no_check_limit" class="distributor_no_check_limit" id="distributor_no_check_limit">
 <input type="hidden" name="product_total_qty" class="product_total_qty" id="product_total_qty">

 <input type="hidden" name="sales_order" class="sales_order" id="sales_order" value="<?=$sales_order?>">
<div class="total_price">
        <div align="right"  style="font-weight:bold" >

            <div id="box_delivery_fee" class="box_delivery_fee" name="box_delivery_fee"> ค่าจัดส่ง <span style="color: red">* </span>: <input type="text" class="delivery_fee" name="delivery_fee" id="delivery_fee" value="<?=$delivery_fee?>"></div>
            <input type="hidden" name="delivery_fee_status" class="delivery_fee_status" id="delivery_fee_status" value="0">
            

        <div  style="margin-top: 3%;">
            มูลค่าการสั่งซื้อก่อน VAT : <label id="total_total" name="total_total">0</label></div>
        <div class="not_show no_show"> ค่าจัดส่ง(มูลค่าก่อน VAT) : <label id="ext_vat_delivery" name="ext_vat_delivery">0</label></div>
        <div class="not_show"> ส่วนลดใบลดหนี้(มูลค่าก่อน VAT) : <label id="ext_sum_discount_price" name="ext_sum_discount_price">0</label></div>
        <div> ภาษี 7% : <label id="vat_amount" name="vat_amount">0</label></div>
        <div> มูลค่าการสั่งซื้อรวม VAT : <label id="total_amount" name="total_amount">0</label></div>
        <div> ..........................................................</div>        
        <div> หัก ส่วนลดใบลดหนี้ : <label id="sum_discount_price" name="sum_discount_price">0</label></div>
        <div class="no_show"> บวก ค่าจัดส่ง : <label id="in_vat_delivery" name="in_vat_delivery">0</label></div>
        <div> ยอดเงินที่ต้องชำระ : <label id="priceall" name="priceall">0</label></div>
</div>
</div>
</div>
 <!--- End  Summary Total Price -->  

<div class="row">
    <div class="span6">
        <div class="control-group">
            <input type="hidden" name="sn" id="sn" value="<?php isset($this->sales) and $this->sales and printf($this->sales[0]['sale']->sn);?>">
            <input type="hidden" name="sn_ref" value="<?php echo $this->sn_ref?>">
            <input type="hidden" name="market_general_id" value="<?php echo (isset($this->sales[0]['sale']->market_general_id) ? $this->sales[0]['sale']->market_general_id : 0);?>">
            <div class="span4">
                <button type="button" class="btn btn-primary" id="submit_btn">Submit</button>
                <button type="submit" style="display:none;"></button>
                <button type="reset" id='reset' class="btn btn-warning">Reset</button>
                <input type="hidden" name="back_url" id="back_url" value="/sales">
                
                <button type="button" class="btn btn-danger go-back">Go back</button>
                <button type="button" id="btn_auto_remark" class="btn btn-success">Auto create remark</button>

                
                <input type="hidden" name="sel_customer_id" class="sel_customer_id" id="sel_customer_id" value="<?=$customer_id?>">
                <input type="hidden" name="group_id" class="group_id" id="group_id" value="<?=$this->group_id?>">
                <input type="hidden" name="area_id" class="area_id" id="area_id" value="<?=$area_id?>">

                <input type="hidden" name="rank" class="rank" id="rank" value="">
                <input type="hidden" name="total_spc_discount" class="total_spc_discount" id="total_spc_discount" value="0">
                <input type="hidden" name="spc_discount" class="spc_discount" id="spc_discount" value="0">
                <input type="hidden" name="spc_discount_phone" class="spc_discount_phone" id="spc_discount_phone" value="0">
                <input type="hidden" name="spc_discount_acc" class="spc_discount_acc" id="spc_discount_acc" value="0">
                <input type="hidden" name="spc_discount_digital" class="spc_discount_digital" id="spc_discount_digital" value="0">

                <input type="hidden" name="save_service" class="save_service" id="save_service" value="sales">
                <input type="hidden" name="order_date" id="order_date" value="<?php isset($this->sales) and $this->sales and isset( $this->sales[0]['sale']->add_time) and printf( $this->sales[0]['sale']->add_time );?>">


                
             </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
</br>
</br>

</form>


<?php echo $this->render('sales/partials/common-clone.phtml'); ?>

<div id="dialog" title="Confirmation"></div>
<div id="dialog1" title="Confirmation"></div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="/js/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" href="/css/style_ui.css">
<link rel="stylesheet" href="/css/themes/smoothness/jquery-ui.css">
<script type="text/javascript" src="/js/select2.full.js"></script>
<link href="/css/select2.min.css" type="text/css" rel="stylesheet" />

<style>
  .custom-customer_id {
    position: relative;
    display: inline-block;
  }
  .custom-customer_id-toggle {
    position: absolute;
    top: 0;
    bottom: 0;
    margin-left: -1px;
    padding: 0;
  }
  .custom-customer_id-input {
    margin: 0;
    padding: 5px 10px;
  }
  </style>

    <script>
  (function( $ ) {
    $.widget( "custom.combobox", {
      _create: function() {
        this.wrapper = $( "<span>" )
          .addClass( "custom-customer_id" )
          .insertAfter( this.element );
        this.element.hide();
        this._createAutocomplete();
        this._createShowAllButton();
      },
 
      _createAutocomplete: function() {
        var selected = this.element.children( ":selected" ),
          value = selected.val() ? selected.text() : "";
        this.input = $( "<input>" )
          .appendTo( this.wrapper )
          .val($.trim(value))
          .attr( "customer_name", "" )
          .addClass( "custom-customer_id-input ui-widget ui-widget-content ui-state-default ui-corner-left" )
          .autocomplete({
            delay: 0,
            minLength: 0,
            source: $.proxy( this, "_source" ),
          })
          .tooltip({
            tooltipClass: "ui-state-highlight"
          });
 
        this._on( this.input, {
          autocompleteselect: function( event, ui ) {
            ui.item.option.selected = true;
            this._trigger( "select", event, {
              item: ui.item.option
            });
            getCustomerInfo();

          },
 
          autocompletechange: "_removeIfInvalid"
        });
      },
 
      _createShowAllButton: function() {
        var input = this.input,
          wasOpen = false;
 
        $( "<a>" )
          .attr( "tabIndex", -1 )
          .attr( "title", "Show All Items" )
          .tooltip()
          .appendTo( this.wrapper )
          .button({
            icons: {
              primary: "ui-icon-triangle-1-s"
            },
            text: false
          })
          .removeClass( "ui-corner-all" )
          .addClass( "custom-customer_id-toggle ui-corner-right" )
          .mousedown(function() {
            wasOpen = input.autocomplete( "widget" ).is( ":visible" );
          })
          .click(function() {
            input.focus();
 
            // Close if already visible
            if ( wasOpen ) {
              return;
            }
 
            // Pass empty string as value to search for, displaying all results
            input.autocomplete( "search", "" );
          });
      },
 
      _source: function( request, response ) {
        if(request.term !=''){
            $('.customer_name').val(request.term);
        }

        var matcher = new RegExp( $.ui.autocomplete.escapeRegex(request.term), "i" );
        response( this.element.children( "option" ).map(function() {
          var text = $( this ).text();
          if ( this.value && ( !request.term || matcher.test(text) ) ){
            return {
              label: text,
              value: $.trim(text),
              option: this
            };
        }
        }) );
      },
 
      _removeIfInvalid: function( event, ui ) {
 
        // Selected an item, nothing to do
        if ( ui.item ) {
          return;
        }
      },
 
      _destroy: function() {
        this.wrapper.remove();
        this.element.show();
      }
    });
  })( jQuery );
 
  $(function() {
    // $( "#customer_id" ).combobox();
  });
  </script>

  <script>
 $(document).ready(function(){
    chexk_disabled();
    $("._search").select2({
        placeholder: "Select...",
        allowClear: true
    });
    $(".salesman").select2();
    $(".salesman_catty").select2();
    $( ".customer_id" ).select2();
    $('body').on('change', '.price', function () {
    var price = parseFloat($(this).val().split(',').join(''));
    var div_parent = $(this).parent().parent().parent();
    // alert(div_parent.find('.num').val());
    var numX = div_parent.find('.num').val();
    var total_sum = Math.round(price*parseFloat(numX.split(',').join('')),2);
    div_parent.find('.total').val(total_sum);
  });
  $('.rank').change(function(event) {
      var rank_id = $(this).val();
      if (rank_id == 1 || rank_id == 2 || rank_id ==5 || rank_id ==6 || rank_id ==7 || rank_id ==8 ) {
        $('.price').prop('disabled', true);
      }else if(rank_id == 3 || rank_id ==9 || rank_id == 10){
        $('.price').prop('disabled', false);

      }
      $.ajax({
          url: '/sales/list-distributor-for-create',
          type: 'POST',
          dataType: 'html',
          data: {rank_id: rank_id},
      })
      .done(function(data) {
          $('.retailer_name_list').empty();
          $('.retailer_name_list').append(data);
            initSearchOption();
          console.log("success");
      })
      .fail(function() {
          console.log("error");
      })
      .always(function() {
          console.log("complete");
      });
      
  });
 
});
function chexk_disabled(){
    var rank_id = $('.price_clas').val();
    // alert(rank_id);
        if (rank_id == 1 || rank_id == 2 || rank_id ==5 || rank_id ==6 || rank_id ==7 || rank_id ==8 ) {
        $('.price').prop('disabled', true);
      }else if(rank_id == 3 || rank_id ==9 || rank_id == 10){
        $('.price').prop('disabled', false);

      }
}
$("#customer_name_add").hide();
 $('.add_customer').click(function() {
      $("#customer_name_select").hide();
      $("#customer_name_add").show();
    });

  $('.change_search').click(function() {
        $("#customer_name_add").hide();
        $("#customer_name_select").show();
        $("#customer_name").prop('disabled', false);
    });
  $('.customer_save').click(function() {
        $("#customer_name").prop('disabled', true);
    });
  $( ".bg" ).hide();
  $( ".loader" ).hide();





  function check_campain_auto_add(){
  var form = $('#form');
  // alert('55555555');
   // console.log( form.serialize() );
      $.ajax({
        url: '/get/check-campain-auto-add',
        type: 'post',
        data: form.serialize(),
      })
      .done(function(data) {
        // alert(data);
        if (data ==0) {
          alert('จำนวนของแถมไม่เท่ากับจำนวนสินค้า');
        $('button, input, select').prop('disabled', false);

          window.stop();
          // location.reload();
          return false;
          
        }else{
          return true;
        }
        console.log("success");
      })
      .fail(function() {
        console.log("error");
      })
      .always(function() {
        console.log("complete");
      });
  
}
 $('#submit_btn').on('click',function(event){
        check_campain_auto_add();

    });
</script>

<?php echo $this->render('sales/partials/common-script.phtml'); ?>