<style type="text/css">
    .formrule {
        /*margin-left:auto;*/
        /*margin-right:auto;*/
        height: 100%;

        /*max-width: 500px;*/
        background: #FFF;
        padding: 30px 30px 20px 30px;
        box-shadow: rgba(187, 187, 187, 1) 0 0px 20px -1px;
        -webkit-box-shadow: rgba(187, 187, 187, 1) 0 0px 20px -1px;
        font: 12px Arial, Helvetica, sans-serif;
        color: #666;
        border-radius: 10px;
        -webkit-border-radius: 10px;
    }

    .formselect {
        /*margin-left:auto;*/
        /*margin-right:auto;*/
        /*max-width: 500px;*/
        background: #FFF;
        padding: 30px 30px 20px 30px;
        box-shadow: rgba(187, 187, 187, 1) 0 0px 20px -1px;
        -webkit-box-shadow: rgba(187, 187, 187, 1) 0 0px 20px -1px;
        font: 12px Arial, Helvetica, sans-serif;
        color: #666;
        border-radius: 10px;
        -webkit-border-radius: 10px;
    }

    .white-pink h1 {
        font: 25px "Trebuchet MS", Arial, Helvetica, sans-serif;
        padding: 0px 0px 10px 40px;
        display: block;
        border-bottom: 1px solid #F5F5F5;
        margin: -10px -30px 10px -30px;
        color: #969696;
        font-family: phetsarath ot;
    }

    h2 {
        font: 20px "Trebuchet MS", Arial, Helvetica, sans-serif;
        padding: 0px 0px 10px 40px;
        display: block;
        border-bottom: 1px solid #F5F5F5;
        margin: -30px  -30px -18px -30px;
        color: #969696;
        font-family: phetsarath ot;
    }
    h3 {
        font: 15px "Trebuchet MS", Arial, Helvetica, sans-serif;
        padding: 3px 0px 25px 26px;
        display: block;
        margin: -25px  -27px -18px -30px;
        color: #333333;
        font-family: phetsarath ot;
    }
    h4 {
        font: 25px "Trebuchet MS", Arial, Helvetica, sans-serif;
        padding: 3px 0px 25px 26px;
        display: block;
        margin: -25px  -27px -18px -30px;
        color: #333333;
        font-family: phetsarath ot;
    }
    p {
        font: 13px, sans-serif;
        padding: 4px 0px 19px 35px;
        display: block;
        margin: -24px  -26px -19px -29px;
        color: #333333;
        font-family: phetsarath ot;
    }

    .buttonsave{
        text-align: right;
        font-family: phetsarath ot;
    }
   .add-img{
    float: right;
    margin-top: 4px;
   font-family: phetsarath ot;
   }
    
    .uploadpdf{
        display: block;
        widows: 100px;
        padding: 7px 0;
        text-align: center;
        background: #333333;
        border-bottom: 0px solid #DDD;
        color: #FFF;
    }

    .form-group{
        border: 2px solid #ccc;
        padding: 30px 30px 20px 30px;
        width: 50%;
        border-radius: 5px;
        margin: 20px 0 ;
    }
    .qq-uploader {
        position: relative;
        width: 92% !important;
        } 
    .input-file-add{
            margin-top: 2px;
    }
    body{
        font-family: phetsarath ot;
    }

</style>
<div class="page-header">
    <h1>Create Document ເພີ່ມເອກະສານປະກອບ</h1>
</div>

<div class="row">
    <div class="formrule">
        <h4>ຂໍ້ກຳນົດ</h4>
        <p>1.ຕ້ອງ UpLoad ຮູບປື້ມບັນຊີເງິນຝາກຂອງເຈົ້າຂອງຮ້ານ, ຮູບບັດປະຈຳຕົວຫຼືພາສປອດ, ຮູບໜ້າຮ້ານ, ຮູບໃບສັນຍາເປີດຮ້ານຄ້າ, ຮູບຮັບເງິນ 2,500,000 ກີບ. ຖ້າເອກະສານບໍ່ຄົບຕາມຈຳນວນ ການເປີດຮ້ານຄ້າກໍຈະບໍ່ສົມບູນ.</p>
    </div>
</div>
<br />

<div class="row ">
    <div style="width: 100%;">
        <div class="formselect">
            <div class="page-header">
                <h2>Select Document</h2>
            </div>
            <form class="form-horizontal" action="<?php echo HOST ?>sales/create-document" name="form" id="form" method="post" enctype="multipart/form-data">      
                <!-- <div class="form-group" >
                    <div class="input-group ">
                        <select class="selectId"  name="selectId[]" id="select" style="width: 400px; height: 40px; ">
                            <option hidden>Select Document</option>
                            <option value="1">แบบคำขอเปิดหน้าบัญชี</option>
                            <option value="2">สำเนาบัตรประชาชนของกรรมการผู้มีอำนาจลงนามหรือเจ้าของ</option>
                            <option value="3">สำเนาหนังสือรับรองการจดทะเบียนนิติบุคคล</option>
                            <option value="4">สำเนาใบทะเบียนภาษีมูลค่าເພີ່ມ(ภพ.20)</option>
                            <option value="5">นามบัตรเจ้าของกิจการ</option>
                            <option value="6">สำเนาสมุดเงินฝาก</option>
                            <option value="7">รูปถ่ายหน้าร้าน/แผนที่</option>
                        </select>  
                        <input type="hidden" class="selectxx" name="select[]" value="">  
                            <button type="button" class="btn btn-danger remove-sel" style="width: 50px;height: 40px; margin-bottom:1px;"><i class="icon-minus"></i></button>     
                    </div>
                </div> -->

                <div class="form-group" >
                    <h3>1.ປື້ມບັນຊີຂອງຮ້ານຄ້າຫຼືເຈົ້າຂອງຮ້ານ <span style="color:red; font-size: 20px; ">*</span></h3>
                    <input type="hidden" class="selectxx" name="select[]" value="1"> 
                    <div class="upload" >
                            <div class="file-uploader" ></div>
                            <input type="hidden"  name="photo[1][]" id="photo"  />
                            <input type="hidden" class="onprogress" />
                            <div class="buttonupload">
                            <button type="button" class="btn btn-success add-img" value="1">ເພີ່ມ Upload</button></div>
                            <!-- <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p> -->
                    </div>
                </div>
                <div class="form-group" >
                    <h3>2.ໃບສັນຍາເປີດຮ້ານຄ້າ<span style="color:red; font-size: 20px; ">*</span></h3>
                    <input type="hidden" class="selectxx" name="select[]" value="2"> 
                    <div class="upload" >
                            <div class="file-uploader" ></div>
                            <input type="hidden"  name="photo[2][]" id="photo"  />
                            <input type="hidden" class="onprogress" />
                            <div class="buttonupload">
                            
                            </div>
                            <button type="button" class="btn btn-success add-img" value="2">ເພີ່ມ Upload</button>
                            <!-- <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p> -->
                    </div>
                </div>
                <div class="form-group" >
                    <h3>3.ບິນຮັບເງິນ 2,500,000 ກີບ (ສອງລ້ານຫ້າແສນກີບ)<span style="color:red; font-size: 20px; ">*</span></h3>
                    <input type="hidden" class="selectxx" name="select[]" value="3">
                    <div class="upload" >
                            <div class="file-uploader" ></div>
                            <input type="hidden"  name="photo[3][]" id="photo"  />
                            <input type="hidden" class="onprogress" />
                            <div class="buttonupload">
                            <button type="button" class="btn btn-success add-img" value="3">ເພີ່ມ Upload</button></div>
                            <!-- <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p> -->
                    </div>
                </div>
                <div class="form-group" >
                    <h3>4.ບັດປະຈຳຕົວຫຼືພັສປອດ<span style="color:red; font-size: 20px; ">*</span></h3>
                    <input type="hidden" class="selectxx" name="select[]" value="4">
                    <div class="upload" >
                            <div class="file-uploader" ></div>
                            <input type="hidden"  name="photo[4][]" id="photo"  />
                            <input type="hidden" class="onprogress" />
                            <div class="buttonupload">
                            
                            <!-- <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p> -->
                    </div><button type="button" class="btn btn-success add-img" value="4">ເພີ່ມ Upload</button></div>
                </div>
                <div class="form-group" >
                    <h3>5.ຮູບໜ້າຮ້ານທີ່ມີປ້າຍຊື່ຮ້ານ<span style="color:red; font-size: 20px; ">*</span></h3>
                    <input type="hidden" class="selectxx" name="select[]" value="5">
                    <div class="upload" >
                            <div class="file-uploader" ></div>
                            <input type="hidden"  name="photo[5][]" id="photo"  />
                            <input type="hidden" class="onprogress" />
                            <div class="buttonupload">
                            <button type="button" class="btn btn-success add-img" value="5">ເພີ່ມ Upload</button></div>
                            <!-- <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p> -->
                    </div>
                </div>


                <!-- <div class="form-group" >
                    <h3>6.สำเนาสมุดเงินฝาก<span style="color:red; font-size: 20px; ">*</span></h3>
                    <input type="hidden" class="selectxx" name="select[]" value="6">
                    <div class="upload" >
                            <div class="file-uploader" ></div>
                            <input type="hidden"  name="photo[6][]" id="photo"  />
                            <input type="hidden" class="onprogress" />
                            <div class="buttonupload">
                            <button type="button" class="btn btn-success add-img" value="6">ເພີ່ມ Upload</button></div>
                             <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p>
                    </div>
                </div> -->

                <!-- <div class="form-group" >
                    <h3>7.รูปถ่ายหน้าร้าน/แผนที่<span style="color:red; font-size: 20px; ">*</span></h3>
                    <input type="hidden" class="selectxx" name="select[]" value="7">
                    <div class="upload"  >
                            <div class="file-uploader" ></div>
                            <input type="hidden"  name="photo[7][]" id="photo"  />
                            <input type="hidden" class="onprogress" />
                            
                            <div class="buttonupload">
                            <button type="button" class="btn btn-success add-img" value="7">ເພີ່ມ Upload</button></div>
                            <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p>
                    </div>
                </div>
                <div class="form-group" >
                    <h3>8.หนังสือสัญญาแต่งตั้งการเป็นตัวแทนจำหน่าย</h3>
                    <input type="hidden" class="selectxx" name="select[]" value="8">
                    <div class="upload"  >
                            <div class="file-uploader" ></div>
                            <input type="hidden"  name="photo[8][]" id="photo"  />
                            <input type="hidden" class="onprogress" />
                            
                            <div class="buttonupload">
                            <button type="button" class="btn btn-success add-img" value="8">ເພີ່ມ Upload</button></div>
                             <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p>
                    </div>
                </div> -->

                <?php 

                $userStorage = Zend_Auth::getInstance()->getStorage()->read();
                // group id 78 = Brand Shop Secret Upload
                if (My_Staff_Group::inGroup($userStorage->group_id,array(ADMINISTRATOR_ID,78))){
                
                ?>

                <!-- <div class="form-group" >
                    <h3>9.สัญญาเช่าพื้นที่ห้าง</h3>
                    <input type="hidden" class="selectxx" name="select[]" value="9">
                    <div class="upload"  >
                            <div class="file-uploader" ></div>
                            <input type="hidden"  name="photo[9][]" id="photo"  />
                            <input type="hidden" class="onprogress" />
                            
                            <div class="buttonupload">
                            <button type="button" class="btn btn-success add-img" value="9">ເພີ່ມ Upload</button></div>
                            <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p>
                    </div>
                </div>
                <div class="form-group" >
                    <h3>10.สัญญาแต่งตั้งตัวแทนจำหน่าย</h3>
                    <input type="hidden" class="selectxx" name="select[]" value="10">
                    <div class="upload"  >
                            <div class="file-uploader" ></div>
                            <input type="hidden"  name="photo[10][]" id="photo"  />
                            <input type="hidden" class="onprogress" />
                            
                            <div class="buttonupload">
                            <button type="button" class="btn btn-success add-img" value="10">ເພີ່ມ Upload</button></div>
                             <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p> 
                    </div>
                </div>
                <div class="form-group" >
                    <h3>11.ใบเสร็จชำระเงินประกันความเสียหายของสัญญาแต่งตั้งตัวแทนจำหน่าย</h3>
                    <input type="hidden" class="selectxx" name="select[]" value="11">
                    <div class="upload"  >
                            <div class="file-uploader" ></div>
                            <input type="hidden"  name="photo[11][]" id="photo"  />
                            <input type="hidden" class="onprogress" />
                            
                            <div class="buttonupload">
                            <button type="button" class="btn btn-success add-img" value="11">ເພີ່ມ Upload</button></div>
                             <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p> 
                    </div>
                </div>
                <div class="form-group" >
                    <h3>12.ใบเสร็จที่Dealerเช่าร้านกับOPPO</h3>
                    <input type="hidden" class="selectxx" name="select[]" value="12">
                    <div class="upload"  >
                            <div class="file-uploader" ></div>
                            <input type="hidden"  name="photo[12][]" id="photo"  />
                            <input type="hidden" class="onprogress" />
                            
                            <div class="buttonupload">
                            <button type="button" class="btn btn-success add-img" value="12">ເພີ່ມ Upload</button></div>
                             <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p> 
                    </div>
                </div> -->

                <?php } ?>

               <!--  <div class="form-group" >
                    <h3>13.สัญญาเช่าพื้นที่ในการจำหน่ายสินค้า</h3>
                    <input type="hidden" class="selectxx" name="select[]" value="13">
                    <div class="upload"  >
                            <div class="file-uploader" ></div>
                            <input type="hidden"  name="photo[13][]" id="photo"  />
                            <input type="hidden" class="onprogress" />
                            
                            <div class="buttonupload">
                            <button type="button" class="btn btn-success add-img" value="13">ເພີ່ມ Upload</button></div>
                            <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p> 
                    </div>
                </div> -->

               <input type="hidden" class="id" name="id" value="<?=$_GET['id']?><?=$m['id'];?>">

             <!-- <button type="plus" id="plus" class="plus-select btn btn-success"  style="float: left;">ເພີ່ມ Document</button> -->
            <div class="buttonsave">
                <button type="submit" class="btn btn-primary">Save</button>
                <a href="distributor-document?id=<?=$_GET['id']?>" class="btn btn-danger go-back">Go back</a>
            </div>
        </div>
        </from>
    </div>
</div> 
<br />


<!-- <div style="display: none" class="form-group select"  >
    <div class="input-group ">
        <select class="selectId"  name="selectId[]" id="select" style="width: 400px; height: 40px; " >
            <option hidden>Select Document</option>
            <option value="1">แบบคำขอเปิดหน้าบัญชี</option>
            <option value="2">สำเนาบัตรประชาชนของกรรมการผู้มีอำนาจลงนามหรือเจ้าของ</option>
            <option value="3">สำเนาหนังสือรับรองการจดทะเบียนนิติบุคคล</option>
            <option value="4">สำเนาใบทะเบียนภาษีมูลค่าເພີ່ມ(ภพ.20)</option>
            <option value="5">นามบัตรเจ้าของกิจการ</option>
            <option value="6">สำเนาสมุดเงินฝาก</option>
            <option value="7">รูปถ่ายหน้าร้าน/แผนที่</option>
        </select>
         <input type="hidden" class="selectxx" name="select[]" disabled>  
           <button type="button" class="btn btn-danger remove-sel" style="width: 50px;height: 40px; margin-bottom:1px;"><i class="icon-minus"></i></button> 
    </div> 

</div> -->

<div style="display: none " class="input-file-add div-img-add">
    <div class="upload" >
        <div class="delete">
        <button type="button" class="btn btn-danger remove-img" style="float:right;" ><i class="icon-minus"></i></button>
        </div>
        <div class="file-uploader" ></div>
        <input type="hidden"  name="photo[]" id="photo" disabled />
        <input type="hidden" class="onprogress" />
        
        <!-- <p><span style="color: red">**</span><span style="font-style: italic;color: gray;"></span></p> -->   
    </div>
</div>

<!-- </div> -->
<!--  <input type='file' id="pdfFile" name="file" onchange="ValidateSingleInput(this);" />
        <img id="target"  style="width: 200px; height: 150px;" alt="อัพโหลดไฟล์" src="" /> -->
<link rel="stylesheet" type="text/css" href="/js/file-uploader/fileuploader.css"/>
<script src="/js/file-uploader/fileuploader.js" type="text/javascript"></script>

<script type="text/javascript">
    $(document).ready(function () {
         createUploader ($('form'));
        // Select();
        // AddSelect();
        // RemoveSelect();
        // initAddImages();
        initRemoveImages();
        AddImages();
        

    });
    // function Select(){
    //       $(function() {
    //       $('.selectId').change(function() {
    //         selected = $(this).val();
    //         $('.selectId').not(this).find('option[value="' + selected + '"]').remove();
    //       });
    //     });
    // }  

    // function AddSelect(){
        
    //         $('.plus-select').click(function(e){
    //             var old_div = $('.select');
    //             var new_div = old_div.clone();
    //             new_div.removeClass('select').find('select').removeAttr('disabled');
    //             new_div.insertBefore($(this)).show();

    //             // createUploader (new_div);
    //             initAddImages();
    //             RemoveSelect();
    //             Select();
                
                
    //             return false;
    //         });
    //     }
   

    // function initAddImages(){
    //         $('.selectId').change(function(e){
    //             var id = $(this).parent().find('.selectId').val();
    //             var xx = $(this).parent().find('.selectxx').val(id);
    //             $(this).parent().find('.selectId').attr('disabled', true);
    //             $(this).parent().find('.selectxx').removeAttr('disabled');
               
    //             var old_div = $('.div-img-add');
    //             var new_div = old_div.clone();
    //             new_div.removeClass('div-img-add').find('input').removeAttr('disabled');
    //             var a = new_div.find('.file-uploader');
    //             // var b  = $(this).parent();
    //             // new_div.find(".aaa").append('<input type="hidden" name="photo['+id+']" id="photo" />');
    //             // $("#file["+id+"]").val(id)
    //             // new_div.find('.col-md-12').append('<input type="hidden" name="photo['+id+']"  >');
    //             // var count = new_div.find('#photo').val('photo['+id+']');
    //             // alert(count.length)
    //             new_div.find('#photo').attr('name','photo['+id+'][]');
         
    //             // $('[name="photo[0]"]').attr('name','photo[3]')
    //             new_div.insertAfter($(this).parent()).show();

    //             createUploader (new_div);
                
    //             // 

    //             initRemoveImages();
    //             AddImages();

    //             return false;
    
    //         });
    // }

    // function RemoveSelect(){
    //         $('.remove-sel').click(function(e){
    //               // alert("0000");
    //             // $(this).parent().prev().remove();
    //             $(this).parent().parent().remove();
    //             // var y = parseInt(document.getElementById("uploaded_before").value);
    //             // $('#uploaded_before').val(y-=1);
    //             return false;
    //         });
    // }

    function AddImages(){
        $('.add-img').click(function(e){
             var id = $(this).parent().parent().parent().find('.add-img').val();
             // alert(id);
            
            var old_add = $('.div-img-add');
            var new_add = old_add.clone();
            new_add.removeClass('div-img-add').find('input').removeAttr('disabled');
            new_add.find('.add-img').remove();
            // new_div.find('.aaa').append('<input type="hidden" name="photo['+id+']"  >');
                // new_div.find('#photo').append('name','photo['+id+']');
            // new_add.find('.aaa').append('<input type="hidden"  name="photo[]" id="photo" />');
            new_add.find('#photo').attr('name','photo['+id+'][]');
           

            new_add.insertBefore($(this)).show();
            createUploader (new_add);
                        // $(".aaa").append('<input type="hidden" name="photo['+id+']"  >')

            
         
            initRemoveImages();


            return false;
        });
    }

    function initRemoveImages(){
        $('.remove-img').click(function(e){
            // alert("asfasf");
            $(this).parent().parent().remove();
            // $(this).parent().parent().parent().remove();
            // var y = parseInt(document.getElementById("uploaded_before").value);
            // $('#uploaded_before').val(y-=1);
            return false;
        });
    }

    function createUploader(selector){
        selector.find('.file-uploader').each(function (){
            var _self = $(this);
            var uploader = new qq.FileUploader({
                element: _self[0],
                action: '/sales/upload',
                multiple: false,
                // ex. ['jpg', 'jpeg', 'png', 'gif'] or []
                allowedExtensions: ['jpg', 'jpeg', 'pdf'],
                sizeLimit: 2 * 1024 * 1024,
                onProgress: function(id, fileName, loaded, total){
                    $('.fix-msg').addClass('show');

                    $('#btn_submit').attr('disabled', 'disabled');
                    $("form").submit(function (e) {
                        e.preventDefault();
                    });

                    $(window).on('beforeunload', function() {
                        return 'Please wait your upload proccess complete!';
                    });
                },
                onComplete: function(id, fileName, responseJSON){
                    if ( responseJSON.success==true ){
                        _self.next().val( responseJSON.uniqid + '_located_' + fileName );
                    }

                    $("#btn_submit").removeAttr("disabled");

                    $("form").unbind('submit');
                    var x = parseInt(document.getElementById("uploaded_before").value);
                
                $('#uploaded_before').val(x+=1);
                    window.onbeforeunload = null;

                },
                onCancel: function(id, fileName){},
                onError: function(id, fileName, xhr){}
            });
        });
    }

   

</script>