<style>
    iframe {
        width: 100%;
        height: 500px;
    }

    .bar {
        line-height: 18px;
    }
</style>
<div class="page-header">
    <h1>Create order from excel</h1>    
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>

<form class="form-horizontal" action="<?php echo HOST ?>sales/create-order-excel" name="form" id="form" method="post" enctype="multipart/form-data" target="frame">
    <div class="row-fluid">
        <div class="span5">
            <div class="control-group">
                <label class="control-label" for="title">Source File</label>
                <div class="controls">
                    <input type="file" name="file" />
                    <p class="help-block"></p>
                </div>
            </div>            
        </div>
        <div class="span5">
            
        </div>
    </div>
    <div class="row-fluid">
        <div class="span10">
            <button type="submit" id="submit_btn" class="btn btn-primary">Submit</button>
            <button type="button" class="btn btn-danger go-back">Go back</button>
        </div>
    </div>
</form>
<iframe src="" name="frame" style="height: 300px; width: 100%; border: none;">
    
</iframe>
<script>
    $(document).ready(function () {
        $('.go-back').click(function(e){
            e.preventDefault();
            parent.history.back();
            return false;
        });
    });
</script>