<style>
    iframe {
        width: 100%;
        height: 500px;
    }

    .bar {
        line-height: 18px;
    }
</style>
<div class="page-header">
    <h1>Create Distributor <small>Mass Upload - TGDĐ</small></h1>    
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="well">
    <div class="row-fluid">
        <div class="span4">
            Template <a class="btn btn-info btn-mini" href="<?php echo HOST ?>files/sales/template/TGDD_Distributor_List_template.xlsx">Download</a>
        </div>
        <div class="span4">
            List of uploaded files <a class="btn btn-success btn-mini" href="<?php echo HOST ?>sales/mou-log">View Logs</a></p>
        </div>
    </div>
</div>
<form class="form-horizontal" action="<?php echo HOST ?>sales/distributor-mass-upload-save" name="form" id="form" method="post" enctype="multipart/form-data" target="frame">
    <div class="row-fluid">
        <div class="span5">
            <div class="control-group">
                <label class="control-label" for="title">Source File</label>
                <div class="controls">
                    <input type="file" name="file" />
                    <p class="help-block"></p>
                </div>
            </div>            
        </div>
        <div class="span5">
            
        </div>
    </div>
    <div class="row-fluid">
        <div class="span10">
            <button type="button" id="submit_btn" class="btn btn-primary">Submit</button>
            <button type="button" class="btn btn-danger go-back">Go back</button>
        </div>
    </div>
</form>
<!--  -->
<div class="row">
    <div class="span12">
        <div class="progress progress-striped active">
            <div class="bar" style="width: 0%;"></div>
        </div>
    </div>
</div>
<!--  -->
<iframe src="" name="frame" frameborder="0"></iframe>
<!--  -->
<div class="row-fluid">
    <div class="span12">
        <div id="result_div">
            
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('.go-back').click(function(e){
            e.preventDefault();
            parent.history.back();
            return false;
        });

        $('#submit_btn').click(submit_form);
    });

    function submit_form(e) {
        // $('iframe').get(0).contentWindow.clear_content();
        
        $('#form').submit();

        if (!!window.EventSource) {
            var source = new EventSource('<?php echo HOST ?>get/progress');

            source.addEventListener('message', function (e) {
                var data = e.data;
                $('.bar').width(e.data+'%');
                $('.bar').html(e.data+'%');
                console.log(e.data);

                if (e.data >= 100) source.removeEventListener('message');
                // console.log(data.id, data.msg);
            }, false);

            source.addEventListener('mou', function (e) {
                var data = e.data;
                console.log('-' + e.data);
            }, false);
        } else {
            console.log('No EventSource');
        }
    }
</script>