<style>

</style>
<div class="page-header">
    <h1>Check Staff Privileges Position</h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('sales/partials/ep-privileges-check-staff-position-search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>
<div class="table-responsive">
    <?php
        echo $this->render('sales/partials/ep-privileges-check-staff-position-list.phtml');
    ?>
</div>

