<div class="page-header">
    <h1>Member Brand Shop List</h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('sales/partials/search-member-brandshop.phtml');
                ?>
            </div>
        </div>
    </div>
</div> 
<div class="row">
    <div class="span12">
        <p class="pull-right">
            <button class="btn btn-success" type="button" onclick="window.location='<?php echo HOST ?>sales/create-member-brandshop'"><i class="icon-plus"></i> Add New</button>
        </p>
    </div>
</div>
<div class="table-responsive">
    <?php
        echo $this->render('sales/partials/list-member-brandshop.phtml');
    ?>
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });
</script>