<div class="page-header">
    <?php if (isset($this->sales) and $this->sales):?>
        <h1>Edit Returned goods</h1>
    <?php else:?>
        <h1>Create Returned Auto Check</h1>
    <?php endif;?>
</div>

<?php

if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<div class="row">
	<div class="span12">
        <iframe name="ifrmSave" id="ifrmSave" width="100%" style="display:none;"></iframe>
        <form role="form" id="form" action="<?php echo HOST.'sales/save-return';?>" method="post" target="ifrmSave" class="form-inline">
        	<?php 
            $show_create_cn_menu = $this->show_create_cn_menu;
            $create_cn = "checked"; 
            $active_cn = "checked";   
            $hide = '';
            if (isset($this->sales) and $this->sales):
            
            $return_sn = $this->sales[0]['sale']->sn_ref;
            if($return_sn==''){
                $return_sn = $this->sales[0]['sale']->sn;  
            }

            $create_cn = $this->sales[0]['sale']->create_cn;
            if($create_cn==1){
                $create_cn = "checked";
            }else{
                $hide = 'hide';
                $create_cn ="";
            }

            $active_cn = $this->sales[0]['sale']->active_cn;
            if($active_cn==1){
                $active_cn = "checked";
            }else{
                $active_cn ="";
            }
         
            ?>
        		<div class="row">
        			<div class="span6">
        				<label class="span2">Return order number</label>
		                <span class="span3"><strong><?=$return_sn?></strong></span>
        			</div>
        		</div>
            <?php endif;?>

            <div class="row">

                <div class="span6">
                </br>
                    <label for="" class="span2">IMEI Code:
                    <?php if ($this->sales){
                        $num_imei=0; 
                       foreach ($this->imei_return as $imei){
                             $imei_return_list .= $imei['imei_sn']."\n";
                             $num_imei +=1;
                       }

                    ?>
                        <textarea name="imei" id="imei" cols="20" rows="10"><?=$imei_return_list?></textarea>
                    <?php }else{ ?>
                        <textarea name="imei" id="imei" cols="20" rows="10"></textarea>
                    <?php } ?>
                    </label>
                    <div class="span12">
                        <button type="button" class="btn btn-check-imei btn-success">Check Imei</button>
                    </div>

                <div class="span6">
                <?php if($show_create_cn_menu==true){  ?>
                    </br>
                    <input id="create_cn" class="create_cn" name="create_cn" type="checkbox" <?=$create_cn?> value="1"> สร้างรหัส CN <span style="color: red">*</span></input><?php } ?>
                    </br>
                    <input id="active_cn" class="active_cn" name="active_cn" type="checkbox" 
                     <?=$active_cn?>
                     value="1"> เปิดใช้งาน CN <span style="color: red">*</span></input>
                </div>
                <div class="span6 div-return-type <?=$hide;?>">
                    <br/>Retrun Type<br/>
                        <select class="span2" id="return_type" name="return_type">
                            <option value="1">Defective</option>
                            <option value="2">Adjustment</option>
                            <option value="3">Demo</option>
                        </select>
                </div>
                <div class="span6">
                    <br/>Return to <span style="color: red">*</span><br/>
                    </label>
                        <select id="warehouse_id" class="span4" name="warehouse_id" required="required">
                            <option value="">Please select</option>
                            <?php foreach ($this->warehouses as $warehouse):?>
                                <option value="<?php echo $warehouse->id;?>" <?php if (isset($this->sales) and $warehouse->id == $this->sales[0]['sale']->backs_d_id):?> selected<?php endif;?>><?php echo $warehouse->name;?></option>
                            <?php endforeach;?>
                        </select>
                    
                </div>
            </div>
                <div class="span6">
                    <label class="span4">
                        &nbsp;&nbsp;
                    </label>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span4">
                        <span><strong id="num_imei">
                            <?php
                                if ($this->sales){
                                   echo $num_imei;     
                                }else{
                                   echo "0";     
                                }
                            ?>
                        </strong> IMEI(s)</span>
                    </label>
                </div>

            </div>

            <div class="row">
                <div class="span6">
                    <div class="control-group">
                        <input type="hidden" id="back_url" name="back_url" value="/sales/return-list">
                        <input type="hidden" name="sn" value="<?php isset($this->sales) and $this->sales and printf($this->sales[0]['sale']->sn);?>">
                        <div class="span4">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button type="button" class="btn btn-warning btn-reset">Reset</button>
                            
                            <button type="button" class="btn btn-danger go-back">Go back</button>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </form>
    </div>
</div>

<div style="display: none" class="row div-add">
    <div class="span12">

        <label class="span2">Products category <span style="color: red">*</span>
            <select class="span2 cat_id" name="cat_id[]" required="required" disabled>
                <option value="">Please select</option>
                <?php foreach ($this->good_categories as $good_category):?>
                    <option value="<?php echo $good_category->id;?>"><?php echo $good_category->name;?></option>
                <?php endforeach;?>
            </select>
        </label>

        <label class="span2">Product <span style="color: red">*</span>
            <select class="span2 good_id" name="good_id[]" required="required" disabled>
                <option value="">Please select</option>
            </select>
        </label>

        <label class="span1">Color <span style="color: red">*</span>
            <select class="span1 good_color" name="good_color[]" required="required" disabled>
                <option value="">Please select</option>
            </select>
        </label>

        <label class="span1">Quantity <span style="color: red">*</span>
            <input type="number" min="1" class="span1 num" name="num[]" required="required" maxlength="5" style="width: 50px" disabled />
        </label>

        <label class="span1">Price <span style="color: red">*</span>
            <input type="number" min="1" required="required" readonly class="span1 price" name="price[]" disabled />
        </label>

        <label class="span1">Total Price <span style="color: red">*</span>
            <input type="number" min="0" step="0.01" required="required" class="span1 total" name="total[]" disabled />
        </label>

        <label class="span2">Invoice No<span style="color: red">*</span>
            <select class="span2 invoice_sn" name="invoice_sn[]"  disabled>
                <option value="">Please select</option>
            </select>
        </label>

        <label class="span2">Remark
            <textarea name="text[]" class="span2 text disabled"></textarea>
        </label>

        <label class="span1">&nbsp;<button type="button" class="btn-danger remove-sales"><i class="icon-minus"></i></button></label>

        <input type="hidden" name="ids[]" disabled />
    </div>
</div>
<style>
#SearchBox{
		width: 360px!important;
	}
	#distributor_id{
		z-index: 0!important;
	}
	.dropdown{
		z-index: 2;
	}
</style>
<script>
    $(document).ready(function () {
        initSearchOptionDistributor('distributor_id', 'SearchBox');
        initGoBack();
        initAddSales();
        initRemoveSales();
        initSelectProduct();
        initSelectQuantity();
        initReset();
        initShowIMEINum();
        initCheckReturnImei();

        $('#create_cn').change(function(e) {
            if(this.checked) {
                $('.div-return-type').removeClass('hide');
            }else{
                $('.div-return-type').addClass('hide');
            }
        });
    });

    <?php if(isset($this->sales[0]['sale']->return_type) && $this->sales[0]['sale']->return_type){?>
            $('#return_type').val('<?=$this->sales[0]['sale']->return_type;?>');
    <?php } ?>

    function initShowIMEINum(){
        $('#imei').keyup(function (e){

            var inputnum = 0;

            if ($(this).val() != '')
                inputnum = ($(this).val().split("\n").length).toString();


            $('#num_imei').html(inputnum);

        });
    }

    function palert(msg){
        $('.alert-error').remove();
        $('.page-header').after('<div class="alert alert-error">'+msg+'</div>');

        return;
    }

    function initGoBack(){
        $('.go-back').click(function(e){
            window.location.href = $('#back_url').val();
            return false;
        });
    }

    function initRemoveSales(){
        $('.remove-sales').click(function(e){
            $(this).parent().parent().parent().remove();
            return false;
        });
    }

    function initAddSales(){
        $('.add-sales').click(function(e){
            var old_div = $('.div-add');
            var new_div = old_div.clone();

            new_div.removeClass('div-add').find('select, input, textarea').removeAttr('disabled');

            new_div.insertBefore($(this).parent().parent().parent()).show();

            initSelectProduct();
            initSelectQuantity();
            initRemoveSales();

            return false;
        });
    }

    function SelectProduct(this_id,cat_id,good_id,good_color,qty,price,total_price,sn_ref,invoice_number,distributor_id){
            var div_parent = this_id.parent().parent().parent();
            var _self = this_id;

            $.get("/get/load",
                {cat_id: cat_id, good_id: ''}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    if (data.goods){
                        var obj = data.goods;
                        for (var i = 0; i < obj.length; i++) {
                            var select ='';
                            if(good_id==obj[i]['id'])
                            {
                                select='selected';    
                                div_parent.find('.good_id').append('<option '+select+' value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            }else{
                                div_parent.find('.good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            } 
                        }
                    }
                    
                });

            $.get("/get/load",
                {cat_id: cat_id, good_id: good_id}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    if (data.colors){
                        div_parent.find('.good_color').empty();
                        var obj = data.colors;
                        for (var i = 0; i < obj.length; i++) {
                            var select ='';
                            if(good_color==obj[i]['id']){
                                select='selected'; 
                                div_parent.find('.good_color').append('<option '+select+' value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            }else{
                                div_parent.find('.good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            }
                        }
                    }
                    
                });

            div_parent.find('.num').val(qty);
            div_parent.find('.price').val(price);
            div_parent.find('.total').val(total_price);

            div_parent.find('.invoice_sn').empty();
            $.get("/get/load-invoice",
            {distributor_id: distributor_id, good_id: good_id, good_color: good_color}
            ,function(data,status){
                //alert(data);
                var data = $.parseJSON( data );
                if (data.invoice_sn){
                    var obj = data.invoice_sn;
                    for (var i = 0; i < obj.length; i++) {
                        var select ='';
                        if(sn_ref==obj[i]['sn_ref']){
                                select='selected'; 
                            div_parent.find('.invoice_sn').append('<option '+select+' value="'+obj[i]['invoice_number']+'">'+obj[i]['invoice_number']+'/'+obj[i]['sn_ref']+'</option>');
                        }else{
                            div_parent.find('.invoice_sn').append('<option value="'+obj[i]['invoice_number']+'">'+obj[i]['invoice_number']+'/'+obj[i]['sn_ref']+'</option>');
                        }
                    }
                }

                _self.nextAll('.loading').remove();
            });
    }

    function AddSales(total_row,index_row,cat_id,good_id,good_color,qty,price,total_price,sn_ref,invoice_number,distributor_id)
    {
            if(index_row>0)
            {
                var i=0;
                $('.cat_id').each(function(){
                    if(i>total_row)
                    {
                        $(this).parent().parent().parent().remove();
                    }
                    i+=1;
                });
                var old_div = $('.div-add');
                var new_div = old_div.clone();
                new_div.removeClass('div-add').find('select, input, textarea').removeAttr('disabled');
                new_div.insertBefore($('.add-sales').parent().parent().parent()).show();
                initSelectProduct();
                initSelectQuantity();
                initRemoveSales();
            }
            var i=0;
            $('.cat_id').each(function(){
                if(index_row==i){
                    $('.cat_id option[value='+cat_id+']').attr('selected','selected');
                    SelectProduct($(this),cat_id,good_id,good_color,qty,price,total_price,sn_ref,invoice_number,distributor_id);
                }
                i+=1;
            });

    }

     function initCheckReturnImei()
     {
        $('.btn-check-imei').click(function(e){

            var imei = $('#imei').val();
            if (imei == ''){
                alert('Please Input Imei SN !');
                return;
            }

            var imei_v = $.trim(imei).split("\n");
            var imei_list = '';
            
           /* $.each(imei_v , function(i, val) { 
                imei_list += $.trim(imei_v[i])+',';
            });*/

             $.each(imei_v , function(i, val) { 
                imei_list += "'"+$.trim(imei_v[i])+"',";
            });

            var distributor_id = $('#distributor_id').val();
            var warehouse_id = $('#warehouse_id').val();

           // distributor_id=1266;warehouse_id=1;
           
            if (distributor_id && warehouse_id) {
                $.post("/get/check-return-imei",
                {warehouse_id: warehouse_id,distributor_id: distributor_id, imei_list: imei_list.slice(0, -1)}
                ,function(data,status){
                   // console.log(data);
                   // alert(data);
                    var data = $.parseJSON(data);
                    
                    if (data.check==1){
                        var obj = data.result;
                        var total_row = obj.length-1;
                        for (var i = 0; i < obj.length; i++) {
                            var cat_id=obj[i]['cat_id'];
                            var good_id=obj[i]['good_id'];
                            var good_color=obj[i]['good_color'];
                            var qty=obj[i]['qty'];
                            var price=obj[i]['out_price'];
                            var total_price=obj[i]['total_price'];
                            var sn_ref=obj[i]['sn_ref'];
                            var invoice_number=obj[i]['invoice_number'];
                            AddSales(total_row,i,cat_id,good_id,good_color,qty,price,total_price,sn_ref,invoice_number,distributor_id);
                        }
                    }else if(data.check==2){
                        alert('Imei Exist in Return Data!');
                        $('select, input:text, input.num, input.price, input.total').val('');
                    }else{
                        alert('No Data !');
                        $('select, input:text, input.num, input.price, input.total').val('');
                    }
                });
            } else{
                alert('Please select Retailer/Warehouse !');
            }
            return false;
        });
    }



    function initSelectProduct(){
        $('.cat_id, .good_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var div_parent = $(this).parent().parent().parent();
            var _self = $(this);
            var cat_id = div_parent.find('.cat_id').val();

            if (_self.hasClass('cat_id'))
                div_parent.find('.good_id').find('option:not(:first)').remove();

            var good_id = div_parent.find('.good_id').val();

            div_parent.find('.good_color').find('option:not(:first)').remove();

            div_parent.find('.num, .price, .total').val('');

            $.get("/get/load",
                {cat_id: cat_id, good_id: good_id}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    if (data.goods){
                        var obj = data.goods;
                        for (var i = 0; i < obj.length; i++) {
                            div_parent.find('.good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    if (data.colors){
                        div_parent.find('.good_color').empty();
                        var obj = data.colors;
                        for (var i = 0; i < obj.length; i++) {
                            div_parent.find('.good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    _self.nextAll('.loading').remove();
                });
        });
    }

    function initSelectQuantity(){
        $('.num').change(function(){
        	$('.loading').remove();
            var div_parent = $(this).parent().parent().parent();
            var _self = $(this);
            var num = _self.val();
            var good_id = div_parent.find('.good_id').val();
            var good_color = div_parent.find('.good_color').val();
            var distributor_id = $('#distributor_id').val();
            if (distributor_id) {
                $(this).after('<span class="loading"></span>');
                $.get("/get/load-price-return",
                    {num: num, good_id: good_id, good_color: good_color, is_sales_price: 1, is_return: 1, distributor_id: distributor_id}
                    ,function(data,status){
                        if (data=='-1'){
                            alert('The product quantity is 0');
                        } else if (data.indexOf("-2") !== -1){
                            var myarr = data.split("|");
                            alert('The product quantity is only '+myarr[1]);
                        } else {
                            var price = 0;

                            if (data > 0 && num > 0) price = data/num;

                            div_parent.find('.price').val(price);
                            div_parent.find('.total').val(data);
                        }
                        _self.nextAll('.loading').remove();
                    });

               div_parent.find('.invoice_sn').empty();

               $.get("/get/load-invoice",
                {distributor_id: distributor_id, good_id: good_id, good_color: good_color}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    if (data.invoice_sn){
                        var obj = data.invoice_sn;
                        for (var i = 0; i < obj.length; i++) {
                            div_parent.find('.invoice_sn').append('<option value="'+obj[i]['invoice_number']+'">'+obj[i]['invoice_number']+'/'+obj[i]['sn_ref']+'</option>');
                        }
                    }

                    _self.nextAll('.loading').remove();
                });
                 
            } else{
                _self.val('');
                alert('Please select Retailer!');
            }
        });
    }

    function initReset(){
        $('button.btn-reset').click(function(e){
            e.preventDefault();
            $('textarea').val('');
        })
    }
</script>
<style>
	label input,
	label select {
		margin-right: 25px;
	}
</style>