<?php
function product_price($priceFloat) {
    $symbol = ' THB';
    $symbol_thousand = ',';
    $decimal_place = 2;
    $price = number_format($priceFloat, $decimal_place, '.', $symbol_thousand);
    return $price;
}
?>
<div class="page-header">
    <h1>View Return Order</h1>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<div class="row">
	<div class="span12">
        <?php if (isset($this->sales) and $this->sales):
            $return_sn = $this->sales[0]['sale']->sn_ref;
            $creditnote_sn = $this->sales[0]['sale']->creditnote_sn;
            if($return_sn==''){
                $return_sn = $this->sales[0]['sale']->sn;  
            }

            $create_cn = $this->sales[0]['sale']->create_cn;
            $active_cn = $this->sales[0]['sale']->active_cn;

            if($create_cn==1){
                $create_nc = "checked";
            }else{
                $create_nc ="";
            }

            if($active_cn==1){
                $active_cn = "checked";
            }else{
                $active_cn ="";
            }

        ?>
            <div class="row">
                <div class="span6">
                    <label class="span2">Return order number</label>
                    <span class="span3"><strong><?=$return_sn?></strong></span>
                    <label class="span2">Credit Note number</label>
                    <span class="span3"><strong><?=$creditnote_sn?></strong></span>
                </div>

            </div>
        <?php endif;?>

        <div class="row">
            <div class="span6">
                <label class="span2">สร้างรหัส CN <span style="color: red">*</span></label>
                <span class="span3"><input id="create_cn" class="create_cn" name="create_cn" type="checkbox" 
                <?=$create_nc?> disabled value="1" ></span>

                <label class="span2">เปิดใช้งาน CN <span style="color: red">*</span></label>
                    <span class="span3"><input id="active_cn_show" class="active_cn_show" name="active_cn_show" type="checkbox" 
                    <?=$active_cn?> disabled value="1" ></span>
            </div>
        </div>

        <?php if($create_cn){?>

        <div class="row">
            <div class="span6">
                <label class="span2">Return Type</label>
                <span class="span3"><strong>
                <?php 

                    $rtn_number="";
                    if($this->sales[0]['sale']->rtn_number !='')
                    {
                        $rtn_number = ' : '.$this->sales[0]['sale']->rtn_number;
                    }
                    switch ($this->sales[0]['sale']->return_type) {
                        case '1':
                            echo 'เครื่องเสีย DOA/DAP';
                            break;
                        case '2':
                            echo 'Adjustment';
                            break;
                        case '3':
                            echo 'Demo';
                            break;
                        case '4':
                            echo 'กรณีพิเศษ/อื่นๆ';
                            break;
                        case '5':
                            echo 'EOL';
                            break; 
                        case '6':
                            echo 'RTN'.$rtn_number;
                            break;            
                }?>
                </strong></span>
            </div>
        </div>

        <?php } ?>

        <div class="row">
            <div class="span6">
                <label class="span2">Retailer name</label>
                <span class="span3"><strong><?php echo $this->sales[0]['retailer_name'];?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Return to Warehouse</label>
                <span class="span3"><strong><?php echo $this->sales[0]['backs_d_name'];?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Sale staffs</label>
                <span class="span3"><strong><?php echo $this->sales[0]['created_by_name'];?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Order time</label>
                <span class="span3"><strong><?php echo $this->sales[0]['sale']->add_time;?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Payment time</label>
                <span class="span3"><strong><?php echo $this->sales[0]['sale']->pay_time;?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Payment staffs</label>
                <span class="span3"><strong><?php echo $this->sales[0]['pay_user_name'];?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Payment notes</label>
                <span class="span3"><strong><?php printf($this->sales[0]['sale']->pay_text);?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span12">
                <table class="table table-bordered span12">
                    <thead>
                        <tr>
                            <th>Products category</th>
                            <th>Product</th>
                            <th>Color</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Total Price</th>
                            <th>Invoice No</th>
                            <th>Remark</th>
                        </tr>
                    </thead>

                    <tbody>

                    <?php
                    $total_num = $total_price = $total_total = 0;
                    foreach ($this->sales as $item):
                        $sale = $item['sale'];
                        $total_num += $sale->num;
                        $total_price += $sale->price;
                        $total_total += $sale->total;
                    ?>

                        <tr>
                            <td><?php echo $item['category'];?></td>
                            <td><?php echo $item['brand_name'] ?> <?php echo $item['good'];?></td>
                            <td><?php echo $item['color'];?></td>
                            <td><?php if(isset($sale->num)) echo $sale->num;?></td>
                            <td><?php if(isset($sale->price)) echo product_price($sale->price);?></td>
                            <td><?php if(isset($sale->total)) echo product_price($sale->total);?></td>
                            <td><?php if(isset($sale->invoice_number)) echo $sale->invoice_number;?></td>
                            <td><?php if(isset($sale->text)) echo $sale->text;?></td>
                        </tr>

                    <?php endforeach;?>

                    </tbody>

                    <tfoot>
                        <tr>
                            <td colspan="3"><strong>SUMMARY</strong></td>
                            <td><strong><?php echo $total_num;?></strong></td>
                            <td><strong><?php echo product_price($total_price);?></strong></td>
                            <td><strong><?php echo product_price($total_total);?></strong></td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Payment or not</label>
                <span class="span3"><input id="payment" name="payment" type="checkbox" value="1" <?php if (isset($this->sales[0]['sale']->pay_user) and $this->sales[0]['sale']->pay_user):?>checked="checked" <?php endif;?>></span>
            </div>
        </div>

        <div class="row">
            <div class="span12">
                <label class="span2">Payment Notes</label>
                <span class="span4"><textarea name="pay_text" class="span2"><?php if(isset($this->sales[0]['sale']->pay_text)) echo $this->sales[0]['sale']->pay_text;?></textarea></span>
            </div>
        </div>

        <div class="row">
            <div class="span12">
                <label class="span2">IMEI Return List</label>
                <span class="span4"><textarea name="pay_text" class="span2" rows="<?php echo (isset($this->imei_return_list) ? count($this->imei_return_list) : 1); ?>"><?php
                        if(isset($this->imei_return_list) and $this->imei_return_list) :
                            foreach ($this->imei_return_list as $item)
                                echo $item['imei_sn']."\n";
                        endif;

                        if(isset($this->imei_return_digital_list) and $this->imei_return_digital_list) :
                            foreach ($this->imei_return_digital_list as $item)
                                echo $item['sn']."\n";
                        endif;

                        ?></textarea></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <div class="control-group">
                    <div class="span4">
                        <button type="button" class="btn btn-danger go-back">Go back</button>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        initGoBack();
    });

    function initGoBack(){
        $('.go-back').click(function(e){
            e.preventDefault();
            parent.history.back();
            return false;
        });
    }
</script>
<style>
	label input,
	label select {
		margin-right: 25px;
	}
</style>