
<style>
    h1{
        font-family: phetsarath ot;
    }
</style>

<?php
function product_price($priceFloat) {
    $symbol = ' THB';
    $symbol_thousand = ',';
    $decimal_place = 2;
    $price = number_format($priceFloat, $decimal_place, '.', $symbol_thousand);
    return $price;
}

function cal_sale_off_percent($sale_off_percent,$price,$num,$price_total){
    if($sale_off_percent>0){
        $price_sale_off = $price - (($price*$sale_off_percent/100)*100)/100;
    }else{
        $price_sale_off = $price;
    }
    return $price_sale_off;
}

function format_number_4($num){
   return decimal_remove_comma(number_format($num, 2));
}

function decimal_remove_comma($priceFloat)
{
    $price = str_replace(",","",$priceFloat);;
    return $price;
}

function ext_vat($num){
   return $num/1.07;
}

?>

<div class="page-header" xmlns="http://www.w3.org/1999/html">
    <h1>List Orders <small>Sell In ລາຍລະອຽດການສັ່ງຊື້</small></h1>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;

?>

<div class="row">
	<div class="span6">
        <?php if (isset($this->sales) and $this->sales):?>
            <div class="row">
                <div class="span6">
                    <label class="span2">Sales order number</label>
                    <span class="span3"><strong><?php isset($this->sales[0]['sale']) and $this->sales and printf( $this->sales[0]['sale']->sn_ref) ;?></strong></span>
                </div>
            </div>
        <?php endif;?>

        <div class="row">
            <div class="span6">
                <label class="span2">Warehouse</label>
                <span class="span3"><strong><?php echo $this->sales[0]['warehouse_name'];?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Retailer name</label>
                <span class="span3"><strong><?php echo $this->sales[0]['retailer_name'];?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Sale Admin</label>
                <span class="span3"><strong><?php echo $this->sales[0]['salesman_name'];?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Sale Catty</label>
                <span class="span3"><strong><?php echo $this->sales[0]['salescatty_name'];?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Order maker</label>
                <span class="span3"><strong><?php echo $this->sales[0]['created_by_name'];?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Order time</label>
                <span class="span3"><strong><?php echo $this->sales[0]['sale']->add_time;?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Invoice time</label>
                <span class="span3"><strong><?php echo $this->sales[0]['sale']->invoice_time;?></strong></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Invoice Number</label>
                <span class="span3"><strong><?php echo $this->sales[0]['sale']->invoice_number;?></strong></span>
            </div>
        </div>
    </div>


        <div class="span6">
            <div class="row">
                <div class="span6">
                    <label class="span2">Pay User</label>
                    <span class="span3"><strong><?php echo $this->sales[0]['pay_user'] ? $this->sales[0]['pay_user'] : 'x';?></strong></span>
                </div>
            </div>


            <div class="row">
                <div class="span6">
                    <label class="span2">Pay Time</label>
                    <span class="span3"><strong><?php  if(isset($this->sales[0]['pay_time']) and $this->sales[0]['pay_time']) echo date('d-m-Y h:i:s', strtotime($this->sales[0]['pay_time']));  else echo 'x';
                                ?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Out User</label>
                    <span class="span3"><strong><?php echo $this->sales[0]['outmysql_user'] ? $this->sales[0]['outmysql_user'] : 'x';?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Out Time</label>
                    <span class="span3"><strong><?php  if(isset($this->sales[0]['outmysql_time']) and $this->sales[0]['outmysql_time']) echo date('d-m-Y h:i:s', strtotime($this->sales[0]['outmysql_time']));  else echo 'x';
                            ?></strong></span>
                </div>
            </div>

            <div class="row">
                <div class="span6">
                    <label class="span2">Order Last Updated At</label>
                    <span class="span3"><strong><?php  if(isset($this->sales[0]['last_updated_at']) and $this->sales[0]['last_updated_at']) echo date('d-m-Y h:i:s', strtotime($this->sales[0]['last_updated_at']));  else echo 'x';
                            ?></strong></span>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="span12">
                <table class="table table-bordered span12">
                    <thead>
                        <tr>
                            <th>Products category</th>
                            <th>Product</th>
                            <th>Color</th>
                            <th>Unit Price</th>
                            <th>Quantity</th>
                            <th>Total Price Ext VAT</th>
                            <th>Delivery Fee</th>
                            <th style="font-family: phetsarath ot;">ສ່ວນຫຼຸດພິເສດ</th>
                            <th>Total</th>
                            <th>Remark</th>
                        </tr>
                    </thead>

                    <tbody>

                    <?php
                    $total_num = $total_price = $total_total = 0;$delivery_fee=0;$total_discount=0;$total_deposit=0;
                    $g_total_discount=0;
                    $list_cn='';
                     foreach ($this->sales[0]['credit_note_list'] as $k => $datas) 
                     {
                        $creditnote_sn = $datas['creditnote_sn'];
                        $total_discount = $datas['total_discount'];

                        if($creditnote_sn!=''){
                            $list_cn .=$creditnote_sn.'='.$total_discount.' B </br> ';
                            $g_total_discount +=$total_discount;
                            $total_discount = $item['total_discount'];
                        }
                     }

                     $list_deposit="";

                     foreach ($this->sales[0]['deposit_list'] as $k => $datas) 
                     {
                        $deposit_sn = $datas['deposit_sn'];
                        $deposit = $datas['total_deposit'];
                        $total_deposit += $datas['total_deposit'];

                        if($deposit_sn!=''){
                            $list_deposit .=$deposit_sn.'='.$deposit.' B </br> ';
                            $g_total_deposit +=$deposit;
                            $total_deposit = $item['total_deposit'];
                        }
                     }
                            
                    $total_discount_ext=0;
                    foreach ($this->sales as $item):

                    $sale = $item['sale'];
                    $product_unit_price = product_price(format_number_4(cal_sale_off_percent($sale->sale_off_percent,$sale->price,$sale->num,$sale->total)));
                    $total_num += $sale->num;
                    $product_total_price = $sale->num * decimal_remove_comma($product_unit_price);  
                    $delivery_fee = decimal_remove_comma(product_price(ext_vat($sale->delivery_fee)));
                    $total_discount_ext = ext_vat($g_total_discount);
                    $total_total += $product_total_price;
                    $total_amount = $total_total-$total_discount_ext+$delivery_fee;

                   $special_discount = 0;
                   date_default_timezone_set('Asia/Bangkok');
                   $date = new DateTime('2017-01-04 00:00:00');
                   $date_start= date_format($date,"Y-m-d H:i:s");
                   $date_order = $this->sales[0]['sale']->add_time;
                   
                   if($date_order < $date_start){
                        if ($this->sales[0]['sale']->d_id=='3691') {
                            if($item['category']==11){
                                $total_discount_ext = (($total_amount) *0.01)*-1;
                            }else{
                               $total_discount_ext =0; 
                            }
                        }else if ($this->sales[0]['sale']->d_id=='3025') 
                        {
                            $total_discount_ext = (($total_amount) *0.01)*-1;
                        }else if ($this->sales[0]['sale']->sn_ref=='SO590913-00382') {
                            $total_discount_ext = (($total_amount) *0.01)*-1;
                        }else{
                            $total_discount_ext=0;
                        }

                    }else{
                        $total_discount_ext = ($item['total_spc_discount'])*-1;
                    }
                    ?>

                        <tr>
                            <td><?php echo $item['category'];?></td>
                            <td><?php echo $item['brand_name'] ?> <?php echo $item['good'];?></td>
                            <td><?php echo $item['color'];?></td>
                            <td><?php echo $product_unit_price;?></td>
                            <td><?php echo $sale->num;?></td>
                            <td><?php echo product_price($product_total_price*1);?></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><?php echo $sale->text;?></td>
                        </tr>

                    <?php endforeach;?>

                    </tbody>
                <?php 
                    $pay_banktransfer=($this->sales[0]['all_payment_order'][0]['pay_banktransfer']);
                    $pay_servicecharge=($this->sales[0]['all_payment_order'][0]['pay_servicecharge']);
                    $pay_service=($this->sales[0]['all_payment_order'][0]['pay_service']);


                $g_total = (($total_total+$delivery_fee)-($total_discount_ext*-1));
                $d_id = $this->sales[0]['sale']->d_id;
                if ($d_id=='25760' || $d_id=='21088' || $d_id=='25550'){
                    $g_total_vat = 0;
                }else{
                    $g_total_vat = ($g_total*1)-$g_total;
                }
                
                $g_total_inc_vat = decimal_remove_comma(product_price($g_total))+decimal_remove_comma(product_price($g_total_vat));
                // $g_total_inc_vat_amount = $g_total_inc_vat+$pay_banktransfer+$pay_servicecharge+$pay_service-$g_total_discount - $g_total_deposit;
                $g_total_inc_vat_amount = $g_total_inc_vat-$g_total_discount - $g_total_deposit;
                ?>
                    <tfoot>
                        <tr>
                            <td colspan="3"><strong>SUMMARY</strong></td>
                            <td><strong></strong></td>
                            <td><strong><?php echo $total_num;?></strong></td>
                            <td><strong><?php echo product_price($total_total);?></strong></td>
                            <td><strong><?php echo product_price($delivery_fee);?></strong></td>
                            <td><strong><?php echo product_price($total_discount_ext);?></strong></td>
                            <td><strong><?php echo product_price($g_total);?></strong></td>
                            <td>&nbsp;</td>
                        </tr>
                    </tfoot>
                </table>

               <!-- include view table discount -->
                <?php echo $this->render('finance/partials/table-discount.phtml');?>
                <!-- include view table bvg -->
                <?php echo $this->render('finance/partials/table-bvg.phtml'); ?>
                <!-- include view table fee -->
                <?php echo $this->render('finance/partials/table-fee.phtml'); ?>
           
                

            </div>
        </div>

        <div class="row">
                <div class="span6 ">
                    <label class="span2">Credit Note Discount List</label>
                    <span class="span3">
                        <?=$list_cn?>
                    </span>
                </div>
        </div>
        <br/>
        <div class="row">
                <div class="span6 ">
                    <label class="span2">Deposit List</label>
                    <span class="span3">
                        <?=$list_deposit?>
                    </span>
                </div>
        </div>
            
        <div class="row">
            <div class="span6">
                <label class="span2">Payment or not</label>
                <span class="span3"><input id="payment" name="payment" type="checkbox" value="1" <?php if (isset($this->sales[0]['sale']->pay_user) and $this->sales[0]['sale']->pay_user):?>checked="checked" <?php endif;?>></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <label class="span2">Shipping</label>
                <span class="span3"><input id="shipping" name="shipping" type="checkbox" value="1" <?php if (isset($this->sales[0]['sale']->shipping_yes_id) and $this->sales[0]['sale']->shipping_yes_id):?>checked="checked" <?php endif;?>></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">  
                <label class="span2">Fee Bank Transfer</label>
                <span class="span3"><input type='text' name='pay_banktransfer' readonly="true" value="<?=product_price($pay_banktransfer)?>" /></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">  
                <label class="span2">Service Charge</label>
                <span class="span3"><input type='text' name='pay_servicecharge' readonly="true" value="<?=product_price($pay_servicecharge)?>" /></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">  
                <label class="span2" style="font-family: phetsarath ot;">ຄ່າອາໄຫຼ່ແລະຄ່າບໍລິການ</label>
                <span class="span3"><input type='text' name='pay_service' readonly="true" value="<?=product_price($pay_service)?>" /></span>
            </div>
        </div>

        <div class="row">
            <div class="span12">
                <label class="span2">Payment Notes</label>
                <span class="span4"><textarea name="pay_text" class="span2"><?php echo $this->sales[0]['sale']->pay_text;?></textarea></span>
            </div>
        </div>

        <div class="row">
            <div class="span12">
                <label class="span2">Delivery Notes</label>
                <span class="span4"><textarea name="shipping_text" class="span2"><?php echo $this->sales[0]['sale']->shipping_text;?></textarea></span>
            </div>
        </div>

        <div class="row">
            <div class="span6">
                <div class="control-group">
                    <div class="span4">
                        <button type="button" class="btn btn-danger go-back">Go back</button>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>


<script>
    $(document).ready(function () {
        initGoBack();
    });

    function initGoBack(){
        $('.go-back').click(function(e){
            e.preventDefault();
            parent.history.back();
            return false;
        });
    }
</script>
<style>
	label input,
	label select {
		margin-right: 25px;
	}
</style>