<div class="page-header">
    <h1>Withholding Tax Print List</h1>
</div>

<?php

if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
    ?>

    <div class="row">
       <div class="span12">
        <iframe name="ifrmSave" id="ifrmSave" width="100%" style="display:none;"></iframe>
        <form role="form" id="form" action="<?php echo HOST.'sales/print-withholding-tax'?>" method="post" class="form-inline">
        </p>
        <div class="row">

            <div class="span3">

                <label for="" class="span2">WT RUNNING NO:
                    <textarea name="wht_running_no" id="wht_running_no" cols="20" rows="10"></textarea>
                </label>
                   
                <div class="row">

                    <div class="span3">

                        <label class="span4"></p>
                            <span><strong id="num_wht">
                                <?php
                                    echo "0"; 
                                ?>
                         </strong> SN</span>
                     </label>


                 </div>

             </div>
             <div class="row">
            <div class="span4">
                <div class="control-group">
                    <input type="hidden" id="back_url" name="back_url" value="/sales/wht-manual-print-list">
                    <div class="span9">

                        <div class="span2">  
                            <button type="submit"  class="btn btn-primary save_data">Print</button>
                            <button type="button" class="btn btn-danger go-back">Go back</button>
                        </div>

                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <hr>
</div>

</div>
</div>
</div>

</br>

</form>
</div>
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script src="/js/jquery.blockUI.js"></script>

<style>
.blockOverlay{
    z-index: 10000 !important;
}
.blockPage{
    z-index: 10001 !important;
}
#SearchBox{
  width: 360px!important;
}
#distributor_id{
  z-index: 0!important;
}
.dropdown{
  z-index: 2;
  }.span122 {
    margin-left: : 25px;
}
.SearchBoxImei{
    width: 1000px!important;
    margin-left: : 25px!important;
}

</style>

<script>

    $(document).ready(function () {
        //initSearchOptionDistributor('distributor_id', 'SearchBox');
        initGoBack();
        initShowWHTNum();




       /* $('.save_data').click(function(event)
        {
            if (confirm('ต้องการบันทึกข้อมูลใช่หรือไม่ ?')) {
            // return  true;
            }else{
                event.preventDefault();
                // $('#submit_btn').removeAttr('disabled');
                $.unblockUI();
                return  false;
            }

        }); */

        $(document).on("submit", "form", function(e){

            $.blockUI({ css: { 
                border: 'none', 
                padding: '15px', 
                backgroundColor: '#000', 
                '-webkit-border-radius': '10px', 
                '-moz-border-radius': '10px', 
                opacity: .5, 
                color: '#fff' 
            } });

            // $.unblockUI();

        });


    });

    <?php if(isset($this->sales[0]['sale']->return_type) && $this->sales[0]['sale']->return_type){?>
        $('#return_type').val('<?=$this->sales[0]['sale']->return_type;?>');
        <?php } ?>

        function initShowWHTNum(){
            $('#wht_running_no').keyup(function (e){

                var inputnum = 0;

                if ($(this).val() != '')
                    inputnum = ($(this).val().split("\n").length).toString();
                $('#num_wht').html(inputnum);

            });
        }

        function initGoBack(){
            $('.go-back').click(function(e){
                window.location.href = $('#back_url').val();
                return false;
            });
        }


    function initReset(){
        $('button.btn-reset').click(function(e){
            e.preventDefault();
            $('select, input:text, input.num, input.price').val('');
            $('textarea').val('');

            $('#num_wht').html(0);
        })
    }
</script>
<style>
label input,
label select {
  margin-right: 25px;
}
</style>