<table class="table table-bordered">
	<thead>
		<tr>
			<th>Number</th>
			<th>Store</th>
			<th>Financial customers</th>
			<th>Business Date</th>
			<th>Settlement Type</th>
			<th>My Bank Account</th>
			<th>Amount</th>
			<th>Finance Date</th>
			<th>Remarks</th>
			<th>Creation Date</th>
			<th>Creator</th>
			<th>Review Status</th>
			<th>Operation</th>
		</tr>
	</thead>
	<tbody>

		<?php if(isset($this->sale_refund) && $this->sale_refund) : ?>
			<?php foreach($this->sale_refund as $value) : ?>

				<?php 
					if($value['status'] == 1) { 
						$status = "<span style='color: blue'>Pending Review</span>"; 
					} elseif($value['status'] == 2) {
					 	$status = "<span style='color: green'>Approved</span>";
					} elseif($value['status'] == 3) {
						$status = "<span style='color: blue'>Re-review</span>";
					} else {
						$status = "<span style='color: orange'>Unapproved</span>";
					}
					 
				?>

				<tr>
					<td><?php echo $value['code'] ?></td>
					<td>
						<?php echo $this->warehouse[$value['refund_dealer']]; ?>
						<?php echo $this->store[$value['refund_dealer']]; ?>
					</td>
					<td><?php echo $value['finance_client_name'] ?></td>
					<td><?php echo $value['business_date'] ?></td>
					<td><?php echo $this->accounttype[$value['refund_type']] ?></td>
					<td><?php echo $value['bank_account'] ?></td>
					<td><?php echo number_format($value['amount'],0) ?></td>
					<td><?php echo $value['finance_date'] ?></td>
					<td><?php echo $value['approved_remark'] ?></td>
					<td><?php echo $value['created_at'] ?></td>
					<td><?php echo $this->staff[$value['created_by']] ?></td>
					<td><?php echo $status ?></td>
					<td>
						<a href="<?php echo HOST ?>finance/add-sale-refund?id=<?php echo $value['id'] ?>&action_type=1"> Detail </a>

						<?php if(in_array($value['status'], array(1,3))) : ?>
							| <a href="<?php echo HOST ?>finance/add-sale-refund?id=<?php echo $value['id'] ?>&action_type=2"> Edit </a>
						<?php endif; ?>

						<?php if(in_array($value['status'], array(1,3))) : ?>
							| <a href="<?php echo HOST ?>finance/add-sale-refund?id=<?php echo $value['id'] ?>&action_type=3"> Approved </a>
						<?php endif; ?>

						<?php if(in_array($value['status'], array(2))) : ?>
							| <a href="<?php echo HOST ?>finance/approved-sale-refund=?id=<?php echo $value['id'] ?>&action_type=4" style="color: orange;"> Re-review </a>
						<?php endif; ?>

						<?php if(in_array($value['status'], array(1,3))) : ?>
							| <a href="<?php echo HOST ?>finance/approved-sale-refund=?id=<?php echo $value['id'] ?>&action_type=5" style="color: red;"> Delete </a>
						<?php endif; ?>
					</td>
				</tr>

			<?php endforeach; ?>
		<?php endif; ?>

	</tbody>
</table>