<table class="table table-bordered">
	<thead>
		<tr>
			<th>Document No.</th>
			<th>Financial customers</th>
			<th>Amount</th>
			<th>Cost Item</th>
			<th>Review Status</th>
			<th>Creator</th>
			<th>Business Date</th>
			<th>Creation Date</th>
			<th>Remarks</th>
			<th>Approve Remark</th>
			<th>Operation</th>
		</tr>
	</thead>
	<tbody>
		<?php if(isset($this->support_fund) && $this->support_fund) : ?>
			<?php foreach($this->support_fund as $value) : ?>

				<?php 
				if($value['status'] == 1) { 
					$status = "<span style='color: blue'>Pending Review</span>"; 
				} elseif($value['status'] == 2) {
					$status = "<span style='color: green'>Approved</span>";
				} elseif($value['status'] == 3) {
					$status = "<span style='color: blue'>Re-review</span>";
				} else {
					$status = "<span style='color: orange'>Unapproved</span>";
				}

				?>

				<tr>
					<td><?php echo $value['doc_no'] ?></td>
					<td><?php echo $value['finance_client_name'] ?></td>
					<td><?php echo number_format($value['amount'],0) ?></td>
					<td><?php echo $value['cost_item_name'] ?></td>
					<td><?php echo $status ?></td>
					<td><?php echo $this->staff[$value['created_by']] ?></td>
					<td><?php echo $value['business_date'] ?></td>
					<td><?php echo $value['created_at'] ?></td>
					<td><?php echo $value['remark'] ?></td>
					<td><?php echo $value['approved_remark'] ?></td>
					<td>
						<a href="<?php echo HOST ?>finance/add-support-fund?id=<?php echo $value['id'] ?>&action_type=1"> Detail </a>

						<?php if(in_array($value['status'], array(1,3))) : ?>
							| <a href="<?php echo HOST ?>finance/add-support-fund?id=<?php echo $value['id'] ?>&action_type=2"> Edit </a>
						<?php endif; ?>

						<?php if(in_array($value['status'], array(1,3))) : ?>
							| <a href="<?php echo HOST ?>finance/add-support-fund?id=<?php echo $value['id'] ?>&action_type=3"> Approved </a>
						<?php endif; ?>

						<?php if(in_array($value['status'], array(2))) : ?>
							| <a href="<?php echo HOST ?>finance/approved-support-fund=?id=<?php echo $value['id'] ?>&action_type=4" style="color: orange;"> Re-review </a>
						<?php endif; ?>

						<?php if(in_array($value['status'], array(1,3))) : ?>
							| <a href="<?php echo HOST ?>finance/approved-support-fund=?id=<?php echo $value['id'] ?>&action_type=5" style="color: red;"> Delete </a>
						<?php endif; ?>
					</td>
				</tr>
			<?php endforeach; ?>
		<?php endif; ?>

	</tbody>
</table>