<link rel="stylesheet" href="<?php echo HOST?>css/select2.css" />
<script src="<?php echo HOST?>js/select2.js"></script>

<form class="form-search form-horizontal" method="get">
	<div class="row">

		<div class="span6">

			<div class="control-group">
				<label for="distributor_ids" class="control-label">Distributor(My Side) : </label>
				<div class="controls">
					<select class="span3" name="distributor_ids" id="distributor_ids">
						<option value=""> Please Selected </option>

						<?php if(isset($this->distributor) && $this->distributor) : ?>
							<?php foreach ($this->distributor as $value) : ?>
								<option value="<?php echo $value['id'] ?>" <?php if(isset($this->params['distributor_ids']) & $this->params['distributor_ids'] == $value['id']) : ?> selected <?php endif; ?> ><?php echo $value['title'] ?></option>
							<?php endforeach; ?>
						<?php endif; ?>

					</select>
				</div>
			</div>

			<div class="control-group">
				<label for="finance_client" class="control-label"> Fianace Client : </label>
				<div class="controls">
					<select class="span3" name="finance_client" id="finance_client">
						<option value=""> Please Selected </option>

						<?php if(isset($this->financeclient) && $this->financeclient) : ?>
							<?php foreach($this->financeclient as $value) : ?>
								<option value="<?php echo $value['id'] ?>" <?php if(isset($this->params['finance_client']) && $this->params['finance_client'] == $value['id'] ) : ?> selected <?php endif; ?> ><?php echo $value['name'] ?></option>
							<?php endforeach; ?>
						<?php endif; ?> 

					</select>
				</div>
			</div>

		</div>

		<div class="span6">

			<div class="control-group">
				<label for="code" class="control-label"> Finance Code :</label>
				<div class="controls">
					<input type="text" name="code" id="code" value="<?php if(isset($this->params['code']) && printf($this->params['code'])) ?>" class="span3" >
				</div>
			</div>

		</div>

		<div class="span12">
			<button type="submit" class="btn btn-primary">Search</button>
			<button type="reset" class="btn btn-warning">Reset</button>
			<button type="submit" class="btn btn-success" name="export" value="1"> Export </button>
		</div>

	</div>
</form>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>

<script type="text/javascript">
	$(document).ready(function () {
		$( '.date' ).datepicker({ dateFormat: "yy-mm-dd" });
		$('#distributor_ids, #finance_client').select2();


		$('#distributor_ids').change(function(){
			var distributor_id = $("#distributor_ids").val();

			$.get("/finance/load-store-by-distributor",
				{distributor_id : distributor_id}
				,function(data,status){
					var data = $.parseJSON( data );


					if (data.financeClient){
						var obj = data.financeClient;
						$('#finance_client').html('<option value="0"> Please Selected </option>');
						for (var i = 0; i < obj.length; i++) {
							$('#finance_client').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
						}
					}

				})
		})
	});
</script>