<?php 
    $userStorage = Zend_Auth::getInstance()->getStorage()->read(); 
?>

<table class="table table-bordered">
	<thead>
		<tr>
			<th>Customer Code</th>
			<th>Certificate Name</th>
			<th>Client Name(In Short)</th>
			<th>Distributor Quantity</th>
			<th>Shop Numbers</th>
			<th>Legal Representative/Actual Controller</th>
			<th>Client Level</th>
			<th>Phone Number</th>
			<th>Actual Cooperate Date</th>
			<th>Modifier</th>
			<th>Modified Time</th>
			<th>Status</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>

		<?php
		if (isset($this->client) and $this->client) :
			foreach ($this->client as $k => $c):
				?>

				<tr>
					<td><?php echo $c['customer_code'] ?></td>
					<td><?php echo $c['client_name'] ?></td>
					<td><?php echo $c['short_name'] ?></td>
					<td></td>
					<td></td>
					<td><?php echo $c['custormer'] ?></td>
					<td><?php echo $c['level'] ?></td>
					<td><?php echo $c['phone_number'] ?></td>
					<td><?php echo $c['cooperate_date'] ?></td>
					<td><?php echo $this->staff[$c['updated_by']] ?></td>
					<td><?php echo $c['updated_at'] ?></td>
					<td>
						<?php
						if($c['status'] == 1) {
							$status = 'Official';
						}elseif($c['status'] == 2) {
							$status = 'Freeze';
						}else{
							$status = 'Close';
						}
						echo $status;
						?>
					</td>
					<td>
						<?php if($c['status'] == 2) { ?>
							
							<a href="<?php echo HOST ?>sales/client-detail?id=<?php echo $c['id'] ?>"> Detail </a>

							<?php if(in_array($userStorage->group_id, array(ADMINISTRATOR_ID))) : ?>
								
								| <a href="<?php echo HOST ?>sales/freeze-client?id=<?php echo $c['id'] ?>&status=<?php echo $c['status'] ?>" style="color: red;" onclick="return confirm('Delete entry?')"> Unfreeze </a> 

							<?php endif; ?>

						<?php }elseif($c['status'] == 1) { ?>

							<a href="<?php echo HOST ?>sales/client-detail?id=<?php echo $c['id'] ?>"> Detail </a>

							<?php if(in_array($userStorage->group_id,array(ADMINISTRATOR_ID))) : ?>

								| <a href="<?php echo HOST ?>sales/add-client?id=<?php echo $c['id'] ?>"> Edit </a>
								| <a href="<?php echo HOST ?>sales/freeze-client?id=<?php echo $c['id'] ?>&status=<?php echo $c['status'] ?>" style="color: red;" onclick="return confirm('Delete entry?')"> Freeze </a>

							<?php endif; ?>

						<?php }else{ ?>


						<?php } ?> 

					</td>
				</tr>


			<?php endforeach;?>
		<?php endif; ?>

	</tbody>
</table>

 <div class="paging">
  <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>