
<script src="<?php echo HOST ?>js/jquery-ui.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>
<script src="<?php echo HOST ?>js/bootstrap-modal.js"></script>
<script src="<?php echo HOST ?>js/bootstrap-modalmanager.js"></script>
<script src="<?php echo HOST ?>js/jquery.blockUI.js"></script>
<script type="text/javascript" src="<?php echo HOST ?>js/sales.po.js"></script>
<script src="<?php echo HOST?>js/numeral.min.js"></script>
<script type="text/javascript" src="/js/select2.full.js"></script>
<link href="/css/select2.min.css" type="text/css" rel="stylesheet" />
<script>

    $(document).ready(function () {
        initChangeWarehouse();
        initChangeRetailer();
        initGoBack();
        initAddSales();
    //Add nvmm
    initAddNvmm();
    initSelectPaid();
    initSelectTotal();
    initSearchObjectOption();
    
    initAddBVG();
    initRemoveSales();
    initSelectProduct();
    initSelectQuantity();
    initSelectShipmentTypeQuantity();
    initSelectPercent();
    initSelectOrderType();
    initReset();
    initTag();
    initDialog();
    initCheckDemoBeforeSubmit();
    initTooltip();
    initGetSettedRetailer();
    initSearchOptionDistributor('distributor_id', 'SearchBox');
    initSelectJoint();
    initSelectQuantityBVG();
    initSelectProductBVG();
    initAddDiscount();
    initChangeInvoice();
    initChangeSalesCatty();
    initSelectPrice();

   // initChangeCustomer();
   initConfirmCampaign();
   get_po_list("<?php isset($this->sales) and $this->sales and isset($this->sales[0]['sale']['po_id']) and printf($this->sales[0]['sale']['po_id']);?>", "#distributor_po");
   $('#add_po_btn').click(show_add_po_modal);
   var rank_id = $('.rank').val();
    // alert(rank_id);
    if (rank_id == 1 || rank_id == 2 || rank_id ==5 || rank_id ==6 || rank_id ==7 || rank_id ==8 ) {
        $('.price').prop('disabled', true);
    }else if(rank_id == 3 || rank_id ==9 || rank_id == 10){
        $('.price').prop('disabled', false);

    }
    $(document).off('change', '[class*="total"]').on('change', '[class*="total"]', calculate_fee);

    //NHAN VIEN MUA MAY
    addRowNVMM();
    removeRowNVMM();
    initSelectAreaService();
    autoRemarkForStaff();
    changePartner();
    show_shipment_type();

    //Tanong     
    initChangeDiscount();

    initAddDiscountDeposit();
    initSelectDiscountDeposit();
    initChangeDiscountDeposit();
    initRemoveDeposit();


    //Tanong     
    initAddDiscountCreditNote();
    initSelectDiscountCreditNote();
    initChangeDiscountCreditNote();
    initRemoveCreditNote();


    initChangeDeliveryFee();
    $('.box_delivery_fee').hide();
   // $('#btn-discount-creditnote').attr('disabled','disabled');

   Auto_Summary_TotalPrice();

   $('#delivery_fee').keypress(function(event) {
    return /\d/.test(String.fromCharCode(event.keyCode));
});

//     $(document).on("submit", "form", function(e)
//     {

//         var total_amout = $('#priceall').text();
//         var delivery_fee =$('#delivery_fee').val();
//         var delivery_fee_status =$('#delivery_fee_status').val();
//         // alert(total_amout+'='+delivery_fee+'='+delivery_fee_status)
//         var totals = parseFloat(total_amout.split(',').join(''));

//         if(delivery_fee<=0 && delivery_fee_status==1){
//             if (confirm('มูลค่าจัดส่งไม่ถูกต้อง ! ต้องการดำเนินการต่อหรือไม่ ?')) {
//                 return  true;
//             }else{
//                 e.preventDefault();
//                 return  false;
//             }
//         }


//         if(!isNaN(totals)){
//             price_discount = totals;
//         }
//         if(price_discount <0){
//             alert('ยอดค่าใช้จ่ายของท่านไม่ถูกต้อง !');
//             return  false;
//         }
//     });
});

    $('#type').change(function(event) {
      $('#temp_d_id').val();
      $('#distributor_id').val();
      $('#rank').val('');
      $('#rank').change();
  });

    $(document).on('focus',".payment_date", function(){ 
     $(this).datepicker({ dateFormat: "dd/mm/yy" });
 });

//Add id nhân viên mua máy
function initAddNvmm(){
    $('.id_for_staff').live('click',function(e) {
        $id_staff = $('.object_id').val();
        var data_name = $('.object_id option:selected').attr('data-name');
        console.log(data_name);
        $name_staff = $( ".object_id option:selected" ).text().replace("Please select", "");
        if($id_staff == '' || $id_staff == 0){
            alert('Vui lòng chọn nhân viên');
        }else{
            var for_staff = $(this).closest('.span12').find('.name_staff');
            var id_staff = $(this).closest('.span12').find('.id_staff');
            for_staff.val($name_staff);
            id_staff.val($id_staff);
            id_staff.attr('data-name',data_name);
        }

    });
}

//thay đổi số tiền thực tế thanh toán 
function initSelectPaid(){
    $('.sotienthucte').live('change', function(e) {
        var _self = $(this);
        paid  = _self.val();
        
        total = $(this).closest('.row').find('.total').val().split('.').join('');
        var so_du = parseInt(paid) - parseInt(total);
        
        $(this).closest('.row').find('.sodu').val(float_f(so_du));
    });
}
//thay đổi giá máy không khớp với giá trên lô => hiện thông báo nếu có chọn lô máy 
function initSelectTotal(){
    $(document).off('change', '.total')
    .on('change', '.total', function(e) {

        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        // alert(_self.val());
        total  = _self.val().split('.').join('');
        var num = div_parent.find('.num').val();
        var price = div_parent.find('.price').val().split('.').join('');
        var good_id = div_parent.find('.good_id').val();
        var shipment = $('.shipment_id').val();
        
        var price_2 = total/num;
        if(shipment){
            if(price != price_2){
                $(this).after('<span class="loading"></span>');
                $.get("/sales/check-price-shipment",
                    {shipment:shipment, good_id:good_id, price: price_2}
                    ,function(data){
                        if (data == "false"){
                        alert("Other prices in batch plant price !");//alert("Giá khác giá trong lô máy !");
                        $('.loading').remove();
                    }
                    else if(data == "true"){
                        alert("Price right in batch plant !");//alert("Giá đúng trong lô máy !");
                        $('.loading').remove();
                    }
                });
            }
        }
        
        var sum = 0;
        $('.total').each(function(){
            var totals = parseInt($(this).val().split('.').join(''));
            if(!isNaN(totals)){
                sum += totals;
            }
        });
        
        var paid = $('.paid').val();
        var so_du = parseInt(paid) - parseInt(sum);
        $('.so_du').val(float_f(so_du));
        
        $('#txt_sum_total').val(sum);
        Auto_Summary_TotalPrice();

    });
}

//pond
function initSelectPrice(){
    $(document).off('change', '.price')
    .on('change', '.price', function(e) {
        
        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        //alert(_self.val());
        total  = _self.val().split('.').join('');
        var num = div_parent.find('.num').val();
        var price = div_parent.find('.price').val().split('.').join('');
        var good_id = div_parent.find('.good_id').val();
        var shipment = $('.shipment_id').val();
        
        var price_2 = total/num;
        if(shipment){
            if(price != price_2){
                $(this).after('<span class="loading"></span>');
                $.get("/sales/check-price-shipment",
                    {shipment:shipment, good_id:good_id, price: price_2}
                    ,function(data){
                        if (data == "false"){
                        alert("Other prices in batch plant price !");//alert("Giá khác giá trong lô máy !");
                        $('.loading').remove();
                    }
                    else if(data == "true"){
                        alert("Price right in batch plant !");//alert("Giá đúng trong lô máy !");
                        $('.loading').remove();
                    }
                });
            }
        }
        
        var sum = 0;
        $('.total').each(function(){
            var totals = parseInt($(this).val().split('.').join(''));
            if(!isNaN(totals)){
                sum += totals;
            }
        });
        //alert(sum);
        var paid = $('.paid').val();
        var so_du = parseInt(paid) - parseInt(sum);
        $('.so_du').val(float_f(so_du));
        
        $('#txt_sum_total').val(sum);
        Auto_Summary_TotalPrice();

    });
}
//reset lại khi chọn lô máy
function initSelectShipment(){
    $(document).off('change', '.shipment_id').on('change', '.shipment_id', function(e) {
        $('.num, .price, .total, .paid, .so_du, .shipment_type').val('');
    });
}

function initSearchObjectOption(){
    var timeout;
    $("#SearchBoxObject").live("keyup", function () {
        var userInput = $("#SearchBoxObject").val();
        window.clearTimeout(timeout);
        timeout = window.setTimeout(function() {
            showOnlyOptionsSimilarToText($(".object_id"), userInput, true, '');
        }, 500);

    });
}

//end NVMM

function initResetRebate(){
    $(document).off('change', 'form .cat_id,form .good_id,form .good_color,form .num,form .price,form .sale_off_percent,form .total')
    .on('change', 'form .cat_id,form .good_id,form .good_color,form .num,form .price,form .sale_off_percent,form .total,form .id_for_staff', function(e) {
        $("#rebate_price").val('');
    });
}

function initConfirmCampaign(){
    $("#dialogcampaign").hide();
    $(".campaign_ck").click(function(e) {
        _self = $(this);
        if(!$(this).is(":checked"))
        {
            $("#dialogcampaign").html('Destroy campaign discount');
            var destroy = true;
        }
        e.preventDefault();
        var div_parent = _self.parent().parent().parent();

        var campaign_val = div_parent.find('.campaign_val');
        $("#dialogcampaign").dialog({
            buttons : {
                "Confirm" : function() {
                 if(!destroy)
                 {
                     var campaign = $('._campaign').val();
                     if(!campaign)
                     {
                         alert('please choose campaign');
                         return false;
                     }
                     _self.prop("checked", !_self.prop("checked"));
                     div_parent.find('.campaign_val').val(campaign);
                     div_parent.find('.total').val(0);

                 }

                 else
                 {
                     _self.prop("checked", false);
                     $('button[type=submit]').prop('disabled', true);
                     $('form').bind('submit',function(e){e.preventDefault();});
                     $.blockUI({ overlayCSS: { backgroundColor: '#009B72' } });
                     var num = div_parent.find('.num').val();
                     var good_id = div_parent.find('.good_id').val();
                     var good_color = div_parent.find('.good_color').val();
                     var cat_id = div_parent.find('.cat_id').val();
                     var id = div_parent.find('.ids').val();
                     var warehouse_id = $('#warehouse_id').val();
                     var distributor_id = $('#distributor_id').val();
                     var type = $('#type').val();
                     div_parent.find('.campaign_val').val('');
                     var sale_off_percent = div_parent.find('.sale_off_percent').val();
                     if (distributor_id && warehouse_id) {
                         if(xhr){
                             xhr.abort();
                         }
                         xhr = $.get("/get/load-price",
                         {
                             num: num,
                             good_id: good_id,
                             is_sales_price: 1,
                             distributor_id: distributor_id,
                             good_color: good_color,
                             cat_id: cat_id,
                             warehouse_id: warehouse_id,
                             type: type,
                             id: id
                         }, function (data, status) {
                             if (data.indexOf("-3") !== -1) {
                                var myarr = data.split("|");
                                        // alert('ຈຳນວນເຄື່ອງທີ່ມີຢູ່ໃນສາງແມ່ນ: ' + myarr[1]);
                                        Swal.fire("Sorry","Stock is not enough ຈຳນວນເຄື່ອງທີ່ມີຢູ່ໃນສາງແມ່ນ:"+myarr[1],"error")
                                        div_parent.find('.num').val('');
                                        div_parent.find('.sale_off_percent').val(0);
                                        div_parent.find('.total').val(0);
                                    } else {
                                     var price = 0;

                                     if (data > 0 && num > 0) price = data / num;

                                     div_parent.find('.price').val(float_f(price));

                                     var total_price = data;

                                     if (data > 0 && sale_off_percent > 0)
                                         total_price = data - Math.round(data * sale_off_percent / 100);

                                     div_parent.find('.total').val(float_f(total_price)).change();
                                 }

                                 $('button[type=submit]').prop('disabled', false);
                                 setTimeout($.unblockUI, 300);
                                 $('form').unbind('submit');
                                 $('.loading').remove();
                             });

                         _self.prop('checked', false);

                     }
                     else
                     {
                         alert('Please select Warehouse/Retailer!');
                         return;
                     }
                 }

                 $(this).dialog("close");
                 return true;
             },
             "Cancel" : function() {
                $(this).dialog("close");
            }
        }
    });

$("#dialogcampaign").dialog("open");
});
}

function initRebate(){
    var timeout1;
    $("#btn-calculate").on("click", function () {
        window.clearTimeout(timeout1);
        timeout1 = window.setTimeout(function() {
            calculateRebatePrice();
        }, 500);

    });
}

function calculateRebatePrice(){
    var total_price = 0;
    var rebate_price = $("#rebate_price").val();

    if (rebate_price == '')
        return;

    $('button[type=submit]').prop('disabled', true);
    $('form').bind('submit',function(e){e.preventDefault();});

    $('form .total').each(function(){
        var div_parent = $(this).parent().parent().parent();
        if (div_parent.find('.cat_id').val() == '<?php echo PHONE_CAT_ID;?>') {
            if ($(this).val() == ''){
                alert('Please choose Total price');
                $("#rebate_price").val('');
                return;
            }
            total_price += Math.round( $(this).val() );
        }
    });

    if ( total_price > 0 ){
        var $rebate_percent = rebate_price/total_price;

        $('form .total').each(function(){
            var div_parent = $(this).parent().parent().parent();
            if (div_parent.find('.cat_id').val() == '<?php echo PHONE_CAT_ID;?>') {
                $v = $(this).val();
                if ($v > 0){
                    var $re = $v - Math.round($v * $rebate_percent);
                    $(this).val($re);
                }
            }
        });

    } else {
        alert('Please choose Total price');
        $("#rebate_price").val('');
    }

    $('button[type=submit]').prop('disabled', false);
    $('form').unbind('submit');
    return;
}

function initSearchOption(){
    var timeout;
    $("#SearchBox").on("keyup", function () {
        var userInput = $("#SearchBox").val();
        window.clearTimeout(timeout);
        timeout = window.setTimeout(function() {
            showOnlyOptionsSimilarToText($("#distributor_id"), userInput, true, 'initChangeRetailer');
        }, 500);

    });
}

function initDialog(){
    $("#dialog").dialog({
        autoOpen: false,
        modal: true
    });
}

function initCheckDemoBeforeSubmit(){
    $('#submit_btn').on('click',function(event){
        initCheckGoodDemo();
        add_product_color_key_nvmm();

    });
}

function initTooltip(){
    $('.tooltip-r').tooltip({
        placement: 'right',
        html: true,
        title: $('#tooltip_type').html()
    });
}

function initTag(){

    $('#myTags').tagit({
        allowSpaces: true,
        fieldName: 'tags[]',
        autocomplete: {
            delay: 0,
            minLength: 2,
            source: "<?php echo HOST;?>get/get-tags" 
        }
    });

}

$('.bs_campaign').change(check_campaign);

function check_campaign(e){
      //alert(1);
      _self = $(e.target);
      check_operation_campaign();
  }

  function check_open_market_campaign()
  {
      
      if($('.open_market_campaign').is(":checked")==true){
          check_open_market_campaign_by_operation();
      }else{
       $("#warehouse_id option[value='123']").remove(); 
   }
}


function check_open_market_campaign_by_operation()
{
    var rank_id = $('.rank').val();
    var distributor_id = $('#distributor_id').val();
    var operation_id = 'truemove';
    //console.log(distributor_id);
    //console.log(rank_id);

    $.ajax({
        url: '<?php echo HOST.'get/get-open-market-campaign-by-operation';?>',
        type: 'POST',
        data: {operation_id: operation_id,distributor_id: distributor_id},
    })
    .done(function(response) {
        var obj_response = jQuery.parseJSON(response);
        //console.log(obj_response.result[0]['partner_code']);

        if(obj_response.result[0]['partner_code']!=null){
          if(rank_id !=10){ //No Brand Shop Show Open Market
            $("#warehouse_id option[value='123']").remove();
            $('#warehouse_id').append('<option value="123">Open Market</option>');
            $('#warehouse_id').val(123);
        }
    }else{
        alert("ຮ້ານຄ້ານີ້ຍັງບໍ່ທັນໄດ້ເຂົ້າຮ່ວມ Campaign Open Market !");
        $("#warehouse_id option[value='123']").remove();
        $('.open_market_campaign').attr('checked', false);
    }
});
    

}

//06FL0021
function check_firm_focus(valus)
{
  //alert(valus.attr('name'));
  var chk_good_firm_focus=0;
  $('.good_id').each(function(){
      var good_id = $(this).val();
      //alert(good_id);
      if(!isNaN(good_id)){
        var arrFocus = ['411','410','409','408','407','406','405','404','387','386','384','383','382','381','380','379','378','377','376','375','419','420','421','422','425','426','427','428','429','430','431','432'];
        if(jQuery.inArray(good_id, arrFocus) !="-1")
        {
          //alert("OK");
          chk_good_firm_focus += 1;
      }
  }
});
    //alert(chk_good_firm_focus);
    if(chk_good_firm_focus >0)
    {
        $('.show_staff_code').show();
        $("#staff_code").attr("required", true);
    }else{
        $('.show_staff_code').hide();
        $("#staff_code").attr("required", false);
    }    
} 

function check_operation_campaign()
{
  if($('.bs_campaign').is(":checked")==true){
      $('.add-sales').hide();
      $('.add-sales').prop('disabled', true);
      $('.remove-sales').hide();
      $('.remove-sales').prop('disabled', true);
      $('.price').attr('readonly', false);
      $('.price').prop('disabled', false);
      $('.sale_off_percent').prop('disabled', true);
          // $('.num').val(1);
          $('.price').css("background-color", "yellow");

          $('.show_phone_number').show();
          $('.phone_number').attr('required', true);
          //$('.num').attr('readonly', true);

      }else{
        $('.add-sales').show();
        $('.add-sales').prop('disabled', false);
        $('.remove-sales').show();
        $('.remove-sales').prop('disabled', false);
        var rank_id = $('.rank').val();
        if(rank_id==3){
          $('.price').attr('readonly', false);
          $('.price').prop('disabled', false);
      }else{
          $('.price').attr('readonly', true);
          $('.price').prop('disabled', true);
      }
      
      $('.num').attr('readonly', false);
      $('.sale_off_percent').prop('disabled', false);
      $('.price').css("background-color", "white");

      $('.show_phone_number').hide();
      $('.phone_number').attr('required', false);
  }
} 

function initChangeRetailer(){//change retailer

    
    var sn = $('#sn').val();
    if(sn !=''){
      check_operation_campaign();
  }

  $('.distributor-info').hide();
  $('.customer-info').hide();
  $('.extra_customer').removeAttr('required');

  $(document).off('change', '#distributor_id')
  .on('change', '#distributor_id', function(e) {

    $('#sipping_add').empty();

    $('#sipping_add').attr('required',true);

    var d_id = $('#distributor_id').val();
    if (d_id == '24026' || d_id == '34807' || d_id == '45020')
    {
        $('.delivery_add').show();
        $('#sipping_add').prop('disabled', false);
        $('#customerName').show();
        
        $('#custom_name').prop('disabled', false);
    }else{
     
        $('#customerName').hide();
        $('#custom_name').prop('disabled', true);

    }

        /*if (d_id == '3028'){ //บริษัท ทรู ดิสทริบิวชั่น แอนด์ เซลส์ จำกัด
            $('.show_bs_campaign').show();
        }else{
           
            $('.show_bs_campaign').hide();
        }*/

        
        getRetailerInfo($(this));

        var presales_sn = $('#presales_sn').val();
        if(presales_sn==''){
          $('#form .num,#form .sale_off_percent,#form .total,#form .price').val('');
          $('.detail_good').find('input,textarea,select,hidden,number').val('');
      }else{
          //$('.num').val().change();
          //$(".num").append(this);
      }

       // DiscountCreditNote();
       //alert(1);
       check_open_market_campaign();
   });
  
  initViewMore();
}



function initChangeWarehouse(){//change warehouse

    $('#warehouse_id').live('change', function(e) {
        $('#form .num,#form .sale_off_percent,#form .total,#form .price').val('');

        $('.detail_good').find('input,textarea,select,hidden,number').val('');
    });

    $('#form .good_id, #form .good_color').live('change', function(e)
    {
        var div_parent = $(this).parent().parent().parent();
        div_parent.find('.price').val('');
        div_parent.find('.total').val('');
        div_parent.find('.num').val('');
        div_parent.find('.sale_off_percent').val('');

        check_operation_campaign();
        check_firm_focus($(this));

        Auto_Summary_TotalPrice();
    });

}

function initAddMethodPayment()
{
    var old_div = $('.div-payment');
    var new_div = old_div.clone();
    new_div.removeClass('.div-payment').find('select').removeAttr('disabled');
    new_div.attr('id', 'payment');
    new_div.insertAfter($('.distributor-info').parent().parent()).show();
}

function initChangeInvoice()
{
    if($('#invoice_type').val() == 1)
    {
        $('.invoice_div').show();
        $('.invoice_div').find('select, input, textarea').removeAttr('disabled');
    }
    else
    {
        $('.invoice_div').hide();
        $('.invoice_div').find('select, input, textarea').prop('disabled', true);
    }

    $(document).off('change', '#invoice')
    .on('change', '#invoice', function(e) {
        initChangeInvoice();
    });
}



function initGetSettedRetailer(){
    var d_id = $('#distributor_id').val();
    if(d_id){
        getRetailerInfo($('#distributor_id'));
    }
}

function initViewMore(){
    $(document).off('click', '.view-more')
    .on('click', '.view-more', function(e) {
        $('.distributor-info .info ').toggle();
        var text = $(this).text();
        if(text == '+'){
            $(this).text('-');
        }else{
            $(this).text('+');
        }
    });
}

function initChangeSalesCatty(){
    $(document).off('change', '.salesman_catty')
    .on('change', '.salesman_catty', function(e) {
        // alert(1);
    });
    
}

// function getRetailerInfo(_this){
  
//     var id = _this.val();
//     //$('#sipping_add').empty();
//     if(id == <?php echo OPPO_SERVICE_CLUB ?>)
//     {
//         alert('Bạn đã chọn đơn hàng cho Service Club, bạn vui lòng chọn trung tâm bảo hành');

//         var old_div = $('.div-service');

//         var new_div = old_div.clone();

//         new_div.removeClass('div-service').find('select, input, textarea').removeAttr('disabled');

//         new_div.attr('id', 'service_id');

//         new_div.insertAfter($('.distributor-info').parent().parent()).show();

//         return false;
//     }
//     else
//     {
//         $('#service_id').remove();
//     }
//         ///// don hang cho nhan vien muon //////
//         if(id == <?php echo OPPO_BORROW ?> )
//         {
//             alert('Bạn đã chọn đơn hàng mượn, Hệ thống sẽ ghi nhận trường hợp này');

//             return false;
//         }

//         ///// don hang cho nhan vien mua may //////

//         if(id == <?php echo OPPO_STAFF ?> || id == <?php echo OPPO_KVL ?>)
//         {

//             $('#invoice').remove();
//             alert('Bạn đã chọn đơn hàng bán máy cho nhân viên , KVL , Vui lòng chọn chính xác có lấy hóa đơn hay không?');
//             var old_div = $('.div-invoice');
//             var new_div = old_div.clone();

//             new_div.removeClass('div-invoice').find('select, input, textarea').removeAttr('disabled');
//             new_div.attr('id', 'invoice');
//             new_div.insertAfter($('.distributor-info').parent().parent()).show();

//             initChangeInvoice();
//             $(".object_id :selected").focus();

//             if(id == <?php echo OPPO_STAFF ?>){
//                 var for_partner = "<?php  echo isset($this->for_partner) ? intval($this->for_partner) : 0;?>";
//                 $('.wrap_for_partner').show();
//                 $('#form .wrap_list_staff').show();
//                 $('.btn_add_row_nvmm').show();
//                 $('.info_nvmm').show();
//                 $('.info_ingame').hide();
//                 $('#div-number-sales').remove();
//                 var old_div = $('.div-number-sales');
//                 var new_div = old_div.clone();
//                 new_div.attr('id', 'div-number-sales');
//                 new_div.insertAfter($('#form .wrap_list_staff')).show();

//             }else{
//                 $('.wrap_for_partner').hide();
//                 ResetNvmm();
//             }
//             return false;
//         }
        
//         ///// don hang cho nhan vien ingame //////
//         if(id == <?php echo OPPO_INGAME ?>)
//         {
//             $('.wrap_for_partner').show();
//             $('#invoice').remove();

//             alert('Bạn đã chọn đơn hàng bán máy cho nhân viên , KVL , Vui lòng chọn chính xác có lấy hóa đơn hay không?');
//             var old_div = $('.div-invoice');
//             var new_div = old_div.clone();
//             new_div.removeClass('div-invoice').find('select, input, textarea').removeAttr('disabled');
//             new_div.attr('id', 'invoice');
//             new_div.insertAfter($('.distributor-info').parent().parent()).show();
//             initChangeInvoice();
//             $(".object_id :selected").focus();


//             $('#form .wrap_list_staff').hide();
//             $('.btn_add_row_nvmm').show();
//             $('.info_nvmm').hide();

//             $('#form .info_ingame').show();
//             $('.info_ingame').show();

//             $('#div-number-sales').remove();
//             var old_div = $('.div-number-sales');
//             var new_div = old_div.clone();
//             new_div.attr('id', 'div-number-sales');
//             new_div.insertAfter($('#form .wrap_list_staff')).show();
//             return false;
//         }
        
//         else
//         {
//             $('#invoice').remove();
//             $('#div-number-sales').remove();
//             $('#div-shipment').remove();
//             $('#div-outsite').remove();
//         }

//         ///// don hang tặng cho nhân viên /////

//         if(id == <?php echo OPPO_GIFT ?> || id == <?php echo OPPO_SUPER_DAY?>)
//         {
//             if(id == <?php echo OPPO_GIFT?>)
//              alert('Bạn đã chọn đơn hàng tặng cho nhân viên');
//          else
//             alert('Bạn đã chọn đơn hàng SUPER DAY , vui lòng chọn khu vực tương ứng');

//         var old_div = $('.div-gift');

//         var new_div = old_div.clone();

//         new_div.removeClass('div-gift').find('select').removeAttr('disabled');

//         new_div.attr('id', 'gift');

//         new_div.insertAfter($('.distributor-info').parent().parent()).show();

//         initChangeInvoice();

//         return false;
//     }
//     else
//     {
//         $('#gift').remove();
//     }

//     if(id == <?php echo OPPO_DEMO ?> || id == <?php echo OPPO_EVENT ?>)
//     {
//         alert('Bạn đã chọn đơn hàng phụ kiện, vui lòng chọn khu vực');

//         var old_div = $('.div-gift');

//         var new_div = old_div.clone();

//         new_div.removeClass('div-gift').find('select').removeAttr('disabled');

//         new_div.attr('id', 'gift');

//         new_div.insertAfter($('.distributor-info').parent().parent()).show();

//         initChangeInvoice();

//         return false;
//     }
//     else
//     {
//         $('#gift').remove();
//     }

//     var distributor_rank=0;    
//     if(id == ''){
//         $('.distributor-info').slideUp();
//         $('.customer-info').slideUp();
//         $('.extra_customer').removeAttr('required');
//     }else{

//       $order_type = $('#type').val();

//       $.ajax({
//         type: 'get',
//         url : '/checkmoney/getbalance',
//         data: {'id':id,'type':$order_type},
//         success: function(data){
//             if(data.status == 9){

//               alert(data.result.alert);
//               $('.row').find('input,textarea,select,hidden,number,button').attr('disabled','disabled');
//           }
//           if(data.status == 1){

//               $('.list-warehouse').addClass('hide');
//               $('#warehouse_id').val('');
//               $('#list-warehouse-'+data.result.warehouse_id).removeClass('hide');

//               if(data.result.group_type_id == '4'){
//                     $('#list-warehouse-116').removeClass('hide'); //Operator Locked SIMCARD - TRUE
//                     $('#list-warehouse-129').removeClass('hide'); //Operator Locked SIMCARD - AWN
//                     $('#list-warehouse-134').removeClass('hide'); //WMOPT - คลังสินค้า Operator
//                 }

//                 <?php if (isset($this->sales) and $this->sales){?>
//                     $('#warehouse_id').val('<?=$this->sales[0]['sale']->warehouse_id;?>');
//                 <?php }else{ ?>
//                     $('#warehouse_id').val(data.result.warehouse_id);
//                 <?php } ?>

//                 $('#group_type_id').val(data.result.group_type_id);
                
//                 if(data.result.group_type_id == '1' && data.result.rank == '7'){
//                     $('.salesman_catty').removeAttr('disabled'); 
//                     $('.salesman_catty').attr('required', 'required');
//                 }else{
//                     $('.salesman_catty').attr('disabled', 'disabled');
//                     $('.salesman_catty').removeAttr('required'); 
//                 }

//                  // console.log(data.result.group_type_id);
//                  // console.log(data.result.rank);
//                    // alert(JSON.stringify(data));
//                    //alert(data.result.balance);
//                    var credit_status='';var spc_discount_show='';var spc_discount=0;
//                    if(data.result.credit_status==1){
//                        credit_status='ໃຊ້ວົງເງິນເຄຍດິດໄດ້';
//                    }else{
//                        credit_status='ບໍ່ສາມາດໃຊ້ວົງເງິນເຄຍດິດໄດ້';
//                    }
                   
//                    //alert(data.result.spc_discount);
                   
//                    if(data.result.spc_discount >0){
//                        spc_discount_show='ส่วนลดพิเศษ '+data.result.spc_discount+'%' ;
//                        spc_discount = data.result.spc_discount;
//                    }else{
//                        spc_discount_show='ບໍ່ມີສ່ວນຫຼຸດພິເສດ' ;
//                        spc_discount = 0;
//                    }
                   
//                    //alert(data.result.main_distributor_id);
                   
                   
//                    $('.distributor-info .retailer_name span').html(data.result.retailer_name);
//                    $('.distributor-info .add textarea').html(data.result.add);
//                    $('.distributor-info .add input').html(data.result.add);
//                    $('.distributor-info .credit_amount span').html(data.result.credit_amount);
//                    $('#main_distributor_id').val(data.result.main_distributor_id);
//                     //alert($('#main_distributor_id').val());
//                     $('.distributor-info .balance span').html(data.result.balance);
//                     $('.distributor-info .total_balance span').html(data.result.total_balance);
//                     $('.distributor-info .credit_type span').html(data.result.credit_type);
//                     $('.distributor-info .credit_status span').html(credit_status);
//                     $('.distributor-info .spc_discount_show span').html(spc_discount_show);
//                     $('.rank').val(data.result.rank);

//                     //console.log(spc_discount);
//                     $('#spc_discount').val(spc_discount);
//                     $('#spc_discount_phone').val(data.result.spc_discount_phone);
//                     $('#spc_discount_acc').val(data.result.spc_discount_acc);
//                     $('#spc_discount_digital').val(data.result.spc_discount_digital);

//                     //console.log($('#spc_discount').val());
//                     //return false;
//                     distributor_rank = data.result.rank; 
//                     $('#sipping_add').empty();
                    
//                     var shipping_address_id = '';

//                     <?php if(isset($this->sales[0]['sale']->shipping_address) and $this->sales[0]['sale']->shipping_address){ 
//                         ?>

//                         var shipping_address_id = <?=$this->sales[0]['sale']->shipping_address;?>

//                     <?php } ?>

//                     if (data.result.shipping) {
//                         for (var i = 0; i < data.result.shipping.length; i++) {

//                             var selected_shipping_address = '';

//                             if(data.result.shipping[i]['id'] == shipping_address_id){
//                                 selected_shipping_address = 'selected';
//                             }

//                         //$('#sipping_add').append('<option value="" -- Select Shipping Address --</option>');
//                         $('#sipping_add').append('<option value="'+data.result.shipping[i]['id']+'" '+ selected_shipping_address + '>'+data.result.shipping[i]['information']+'</option>');
//                     }
//                 }
//                    // alert(distributor_rank);
//                     //distributor_rank=10;    
//                    //--------Get Customer-----------
//                    if(distributor_rank == 10){
//                        // alert(distributor_rank);
//                        $(this).after('<span class="loading"></span>');
//                        // alert(div_parent.val());

//                        var selected_value = $('#customer_id').has('option').length;
//                        if(selected_value) {
//                        }
//                        else {

//                           // $( ".loader" ).show();

//                           $('.customer-info').slideDown();
                          
//                           $('.extra_customer').attr('required', true);

//                         // $('.customer_id').empty();
//                         // $.get("/get/load-customer-brand-shop",
//                         // {customer_id: ''}
//                         // ,function(data,status){
//                         //     var data = $.parseJSON(data);
//                         //     if (data.result){
//                         //         var obj = data.result;
//                         //         for (var i = 0; i < obj.length; i++) {
                         
//                         //            var val = obj[i]['customer_id']
//                         //            var text = obj[i]['customer_name'];

//                         //            //var tax_number = obj[i]['tax_number'];
//                         //            //var text_name = text+'['+tax_number+']';
//                         //           // alert(text);
//                         //            $('.customer_id').append(new Option(text, val));
//                         //         }
//                         //     }
//                         //   $( ".loader" ).hide();
//                         // });
//                     }
                    
                    
                    
//                 }else{
//                     $('.customer-info').slideUp();
//                     $('.extra_customer').removeAttr('required');

//                     $('.customer_id').val('');
//                     $('.customer_name').val('');
//                     $('.customer_tax_number').val('');
//                     $('.customer_tax_address').val('');
//                         //$('#spc_discount').val(0);
//                     }

//                    //-------------------------------
//                } else {
//                 $('.distributor-info .retailer_name span').html('');
//                 $('.distributor-info .add textarea').html('');
//                 $('.distributor-info .credit_amount span').html('');
//                 $('.distributor-info .balance span').html('');
//                 $('.distributor-info .total_balance span').html('');
//                 $('.distributor-info .credit_type span').html('');
//                 $('.distributor-info .credit_status span').html(data.result);
//                 $('.distributor-info .spc_discount span').html('');
//                     //$('#spc_discount').val(0);
//                 }
//             }
//         });

// $('#salesman_catty').empty();
// var sales_admin_id = $('#salesman').val();
// var sales_catty_id = $('#sales_catty_id').val();
// var ids = $('.ids').val();
//         //alert(ids);
//         var select ='';
//         $('#salesman_catty').append('<option ref="1" value="">-- กรุณากำหนดชื่อเซล --</option>');
//         $.get("/get/load-sales-catty",
//             {distributor_id: id}
//             ,function(data,status){
//                 var data = $.parseJSON( data );
//                 if (data.result){
//                     var obj = data.result;
//                     for (var i = 0; i < obj.length; i++) 
//                     {
                      
//                       if(sales_catty_id==obj[i]['id']){
//                           select='selected'; 
//                       //alert(obj[i]['id']);
//                       $('#salesman_catty').append('<option ref="1" '+select+' value="'+obj[i]['id']+'">'+obj[i]['fullname']+'</option>');
//                       select ='';
//                   }else{
//                       select=''; 
//                       $('#salesman_catty').append('<option ref="1" value="'+obj[i]['id']+'">'+obj[i]['fullname']+'</option>');
//                   }
                  
//               }
              
//           }
//           if(sales_catty_id==0){
//               select='selected'; 
//           }
//           if(ids==''){
//               select=''; 
//           }
//             //alert(select);
//             $('#salesman_catty').append('<option ref="1" '+select+' value="0">-- ไม่กำหนดชื่อเซล --</option>');
//             _self.nextAll('.loading').remove();
//         });
        
//         $('.distributor-info').slideDown();
//         var chBtn = $('.view-more').text();
//         if(chBtn == '-'){
//             $('.view-more').trigger('click');
//         }

//         //Tanong
//         GetSalesOrder_Amount(id);
//         GetDelivery_Fee_All(id);
//         //alert(id);
//         Auto_Summary_TotalPrice();
//     }

//     calculate_fee();

//     //get_po_list(id, "#distributor_po");
// }

Array.prototype.contains = function (v) {
    return this.indexOf(v) > -1;
}

var array_ka = [ <?php echo KA_TGDD ?>, <?php echo KA_VTA ?> , <?php echo KA_FPT; ?> ];

function check_gift(elm) {

    if (!$('#form')[0].checkValidity()) {
        $('#form').find(':submit').click();
        return;
    }

    /*--------check Gifts R9s----------*/
    var warehouse_id = $('#warehouse_id').val();
    var distributor_id = $('#distributor_id').val();
    var rank_id = $('.rank').val();
    var sales_sn = $('#sn').val();
    var order_date = $('#order_date').val();
    
    var good_num_qty=0;
    var gift_num_qty=0;
    var good_id='';var good_color='';

    $('.num').each(function(){
      var div_parent = $(this).parent().parent().parent();
      good_id = div_parent.find('.good_id').val();
      good_color = div_parent.find('.good_color').val();
      var totals = parseFloat($(this).val().split(',').join(''));
      
      //alert(good_color);
      if(!isNaN(totals)){
        if(good_id==208)  //R9s
        {
          good_num_qty += totals;
      }

        if(good_id==209)  //Gift 05GB0003
        {
          gift_num_qty += totals;
      }

  }

  

});
/*
      if(warehouse_id==36 && rank_id==7 && good_num_qty >0){
        if(good_num_qty < 3 ){
          alert('ท่านกำหนดจำนวนไม่ถูกต้อง ! สินค้ารุ่น R9s ต้องสั่งซื้อขั้นต่ำ 3 เครื่องครับ.');
          return false;
        }
      }

      if(warehouse_id==36 && rank_id==7 && good_num_qty >0){
        var chk_qty = good_num_qty-gift_num_qty;
        var total_gift_num_qty = good_num_qty-2;
        if(chk_qty < 2){
         // alert('สินค้าของแถม (05GB0003) ต้องมีจำนวนน้อยกว่า R9s 2 ชิ้น !');
         alert('VIP Gift Box (05GB0003) ของ R9s ที่ต้องใส่จำนวน '+total_gift_num_qty+' ชิ้น');
          return false;
        }
    }*/

    
/*
    if(distributor_id==36){
      if(chk_good > 0 && chk_gifts_sdcard <=0){
        alert('กรุณาเลือกของแถมสำหรับ F1s ! (SD CARD 32GB)');
        return false;
      }
    }
    */    
//return false;
/*
    var good_num_qty=0;good_num_f1s_qty=0;good_color_num_f1s_qty=0;
    var gift_num_qty=0;var gift_sdcard_num_qty=0;var chk_good=0;var chk_gifts=0;
    $('.num').each(function(){
      var div_parent = $(this).parent().parent().parent();
      var good_id = div_parent.find('.good_id').val();
      var good_color = div_parent.find('.good_color').val();
      var totals = parseFloat($(this).val().split(',').join(''));
      
      //alert(good_color);
      if(!isNaN(totals)){
        if(good_id==142)  //F1s
        {
          good_num_qty += totals;
          good_num_f1s_qty += totals;
            if(good_color==24)  //F1s  Rose Gold/ชมพู
            {
                good_color_num_f1s_qty += totals;
            }
        }
        if(good_id==152)  //Gift 05GB0001
        {
          gift_num_qty += totals;
        }
        
        if(good_id==151)  //Gift SD CARD 32GB
        {
          gift_sdcard_num_qty += totals;
        }

      }
  });*/

  /*----------Chk No Sales-------------*/

  var salesman = $('#salesman').val();
  var warehouse_id = $('#warehouse_id').val();
  var group_id = $('#group_id').val();

  $('button, input, select').prop('disabled', true);
  $('#form').unbind('submit');

  good_list = [];
  $('[name="good_id[]"]:visible').each(function(index, elm) {
    good_list.push($(elm).val());
});

  $.ajax({
    url: '<?php echo HOST ?>get/check-gift',
    dataType: 'json',
    data: {good_list: good_list},
})
  .done(function(result) {
    $('button, input, select').prop('disabled', false);
    $('#form').bind('submit');

                //var distributor_id = $('#distributor_id').val();
                var order_type = $('#type').val();

                $.ajax({
                    type: 'get',
                    url : '/checkmoney/getbalance',
                    data: {'id':distributor_id,'type':order_type},
                    success: function(data){
                        if(data.status != 0){
                           // alert(JSON.stringify(data));
                           var credit_status = parseInt(data.result.credit_status);
                           var credit_amount = parseFloat(data.result.credit_amount.split(',').join(''));
                           var balance = parseFloat(data.result.balance.split(',').join(''));
                           var total_proce = $('.total_amount_all').val();
                            //alert(total_proce);
                           // alert(credit_status);alert(credit_amount);alert(balance);
                           if(credit_status==0 && credit_amount<=0){
                             //---------Submit Use Cash---------
                             if (typeof result.code != "undefined" && result.code != 1) {
                                $('#dialog').html(result.error);

                                $("#dialog").dialog({
                                    buttons : {
                                        "Choose Gifts" : function() {
                                            $(this).dialog("close");
                                            return false;
                                        },
                                        "Ignore" : function() {
                                                // $('#form').submit();
                                            }
                                        }
                                    });
                                $("#dialog").dialog("open");
                            } else {
                                    // $('#form').submit();
                                }
                              //-----------------------------------
                              
                          }else if(credit_status==1 && credit_amount > 0){
                            //alert(credit_amount);
                            //alert(balance);
                            //alert(total_proce);
                            var main_distributor_id = $('#main_distributor_id').val();
                            var total_bal = balance-total_proce;
                            if(main_distributor_id !='3332')
                            {
                                total_bal = 100000;
                            }
                            
                            if((total_bal) > 0){
                                //---------Submit Use Credit---------
                                if (typeof result.code != "undefined" && result.code != 1) {
                                    $('#dialog').html(result.error);

                                    $("#dialog").dialog({
                                        buttons : {
                                            "Choose Gifts" : function() {
                                                $(this).dialog("close");
                                                return false;
                                            },
                                            "Ignore" : function() {
                                                // $('#form').submit();
                                            }
                                        }
                                    });
                                    $("#dialog").dialog("open");
                                } else {
                                    // $('#form').submit();
                                }
                                //-----------------------------------
                            }else{
                                alert('ບໍ່ສາມາດສັ່ງຊື້ສິນຄ້ານີ້ໄດ້ ເນື່ອງຈາກເງິນເຄຍດິດຂອງທ່ານບໍ່ພຽງພໍ !('+total_bal+')');
                            }
                        }else{
                           alert('ບໍ່ສາມາດໃຊ້ວົງເງິນເຄຍດິດໄດ້ !');
                       }
                   } else {
                     alert('ບໍ່ສາມາດສັ່ງຊື້ສິນຄ້າໄດ້ !');
                 }
             }
         });

})
.fail(function(result) {
    console.log(result.error);
})
.always(function() {
    console.log("complete");
});

/*------------------------*/

}

function initGoBack(){
    $(document).off('click', '.go-back')
    .on('click', '.go-back', function(e) {
      var presales_sn = $('#presales_sn').val();
      if(presales_sn !=''){
        window.location.href = "/sales/pre-sales-order-list";
    }else{
        window.location.href = $('#back_url').val();
    }
    return false;
});
}

function initRemoveSales(){
    $(document).off('click', '.remove-sales')
    .on('click', '.remove-sales', function(e) {
        //console.log(1);
        $(this).parent().parent().parent().remove();
        calculate_fee();
        check_firm_focus($(this));
        Auto_Summary_TotalPrice();
        return false;
    });
}


function initAddSales(){
    $(document).off('click', '.add-sales')
    .on('click', '.add-sales', function(e) {

        var old_div = $('.div-add');

        old_div.find('.cat_id').select2("destroy");
        old_div.find('.good_id').select2("destroy");

        var new_div = old_div.clone();
        
        new_div.removeClass('div-add').find('select, input, textarea').removeAttr('disabled');
        
        var rank_id = $('.rank').val();
        if (rank_id == 1 || rank_id == 2 || rank_id ==5 || rank_id ==6 || rank_id ==7 || rank_id ==8 ) {
            new_div.find('.price').prop('disabled', true);
        }else if(rank_id == 3 || rank_id ==9 || rank_id == 10){
           new_div.find('.price').prop('disabled', false);

       }
       new_div.insertBefore($(this).parents('.row')).show();

       if($('.buy_return').is(":checked")==true){
          new_div.find('.cat_id').val('12');
          new_div.find('.cat_id option:not(:selected)').attr('disabled', true);
          new_div.find('.cat_id').change();
      }

        new_div.find('.cat_id').select2();
        new_div.find('.good_id').select2();


      $(document).off('change', '[class*="total"]').on('change', '[class*="total"]', calculate_fee);
      initSelectProduct();
      initSelectQuantity();
      initSelectPercent();
      initRemoveSales();
      initConfirmCampaign();
        // initResetRebate();

        return false;
    });
}

// function add bvg
function initAddBVG(){
    $('.add-bvg').click(function(e){
        var old_div = $('.div-bvg');
        var new_div = old_div.clone();
        var distributor_id = $('#distributor_id').val();
        new_div.removeClass('div-bvg').find('select, input, textarea').removeAttr('disabled');
        $('from .joint').each(function(i, obj) {
         if($('.joint').val())
         {
             joint_total++;
         }
     });
        $.get("/get/load-joint",
            {distributor_id : distributor_id , init_params : 1}
            ,function(data,status){
                var data = $.parseJSON( data );

                if (data){
                    var obj = data;


                    new_div.find('.joint').html('<option value="0">Please select</option>');
                    for (var i = 0; i < obj.length; i++) {

                        if(i <= joint_total)
                        {
                            new_div.find('.joint').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                        else
                            new_div.find('.joint').append('<option disabled value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                }

                else
                {
                    alert(data.error);
                }


                $('button[type=submit]').prop('disabled', false);
                $('form').unbind('submit');
            });

        new_div.insertBefore($(this).parent().parent().parent()).show();
        $(document).off('change', '[class*="total"]')
        .on('change', '[class*="total"]', calculate_fee);


        initSelectJoint();
        initSelectQuantityBVG();
        initRemoveSales();
        initSelectProductBVG();

        Auto_Summary_TotalPrice();
        return false;
    });
}

function initAddDiscount(){
    $('#btn-discount').click(function(e){
        var old_div = $('.div-discount');
        var new_div = old_div.clone();
        new_div.removeClass('div-discount').find('select, input, textarea').removeAttr('disabled');
        new_div.insertBefore($(this).parent().parent().parent()).show();

        var distributor_id = $('#distributor_id').val();

        if(!distributor_id)
        {
            alert('Please insert Distributor');
            return false;
        }

        $.get("/get/load-joint",
            {distributor_id : distributor_id , init_params : 2}
            ,function(data,status){
                var data = $.parseJSON( data );

                if (data){
                    var obj = data

                    console.log(obj);


                    new_div.find('.joint_discount').html('<option value="0">Please select</option>');
                    for (var i = 0; i < obj.length; i++) {
                        new_div.find('.joint_discount').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                }

                else
                {
                    alert(data.error);
                }


                $('button[type=submit]').prop('disabled', false);
                $('form').unbind('submit');
            });




        initSelectQuantityBVG();
        initRemoveSales();
        initSelectProductBVG();
        selectJointDiscount();

        Auto_Summary_TotalPrice();
        return false;
    });
}

var joint_total = 0;
var joint_discount_total = 0;


function resetJoint()
{
    if($('.joint').val())
       $('.joint').parent().parent().remove();
}

function selectJointDiscount()
{
    $(document).off('change', '.joint_discount')
    .on('change', '.joint_discount', function() {

        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit',function(e){e.preventDefault();});
        $('.loading').remove();
        $(this).after('<span class="loading"></span>');
        var distributor_id = $('#distributor_id').val();
        var joint = $(this).val();
        var _selft = $(this);
        var parent =  _selft.parent().parent();

        if(!distributor_id)
        {
            alert('Please select Joint Circular');
            return;
        }

        $.get("/get/load-jointprice",
            {joint: joint, d_id: distributor_id}
            ,function(data,status){
                var data = $.parseJSON( data );

                if (data.code == 1){
                    parent.find('.price_discount').val(data.price);
                    parent.find('.price_discount').attr('readonly', true);
                }

                if(data.code == -2)
                {
                    alert(data.error)
                }

                $('button[type=submit]').prop('disabled', false);
                $('form').unbind('submit');
                $('.loading').remove();
            });

    });
}

function initSelectJoint()
{
    var distributor_id = $('#distributor_id').val();
    $(document).off('change', '.joint')
    .on('change', '.joint', function() {
        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit',function(e){e.preventDefault();});
        $('.loading').remove();
        $(this).after('<span class="loading"></span>');
        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        var joint = div_parent.find('.joint').val();

        if (_self.hasClass('joint'))
            div_parent.find('.good_id').find('option:not(:first)').remove(); 

        var good_id = div_parent.find('.good_id').val();

        div_parent.find('.good_color').find('option:not(:first)').remove();

        div_parent.find('.num, .price, .total').val('');


        $.get("/get/load-joint",
            {joint: joint, good_id: good_id , distributor_id : distributor_id}
            ,function(data,status){
                var data = $.parseJSON( data );
                if (data.goods){
                    var obj = data.goods;
                    div_parent.find('.good_id_bvg').html('<option value="0">Please select</option>');
                    for (var i = 0; i < obj.length; i++) {
                        div_parent.find('.good_id_bvg').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }



                }



                $('button[type=submit]').prop('disabled', false);
                $('form').unbind('submit');
                _self.nextAll('.loading').remove();
            });
    });
}

function initSelectProduct(){
    $(document).off('change', '.cat_id, .good_id')
    .on('change', '.cat_id, .good_id', function(e) {
        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit',function(e){e.preventDefault();});

        $('.loading').remove();
        $(this).after('<span class="loading"></span>');

        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        var cat_id = div_parent.find('.cat_id option:selected').val();
        var distributor_id    = $('#distributor_id').val();
        var warehouse_id      = $('#warehouse_id').val();

        div_parent.find('.good_id').select2("destroy");

        
        var rank    = $('.rank').val();
        if (rank == 10 && distributor_id == 32160) {

        }else{
            if (rank == 10 && cat_id == 12) {
             div_parent.find('.price').prop('readonly', true);
             div_parent.find('.sale_off_percent').prop('disabled', true);
         }else if(rank == 10 && cat_id == 11){
             div_parent.find('.price').prop('readonly', false);
             div_parent.find('.sale_off_percent').prop('disabled', false);

         }
     }
     if (distributor_id == "" || distributor_id == null) {
          // alert('Please select Retailer name..');
          Swal.fire("Sorry"," Please select shop ກະລຸນາເລືອກຮ້ານຄ້າ","error")
          $('#distributor_id').focus();
      }

    if (_self.hasClass('cat_id'))
        div_parent.find('.good_id').find('option:not(:first)').remove();

    var good_id = div_parent.find('.good_id option:selected').val();
    var type = $('#type').val();

    div_parent.find('.good_color').find('option:not(:first)').remove();

    div_parent.find('.num, .price, .total').val('');

        // alert(cat_id); alert(good_id);

        $.get("/get/load2",
            {cat_id: cat_id, good_id: good_id, d_id:distributor_id, rank:rank, warehouse_id:warehouse_id, type:type}
            ,function(data,status){
                var data = $.parseJSON( data );
                if (data.status_block == 9) {
                  alert('This product is not available for sale. (สินค้าชิ้นนี้ปิดการจำหน่ายชั่วคราว)');
              }

              if (data.goods){
                var obj = data.goods;
                div_parent.find('.good_id').html('<option value="0">Please select</option>');
                for (var i = 0; i < obj.length; i++) {
                    div_parent.find('.good_id').append('<option value="'+obj[i]['id']+'">' +obj[i]['brand_name']+ ' '+obj[i]['name']+'</option>');
                }

            }
            if (data.colors){
                  // alert(data);
                  var obj = data.colors;
                  div_parent.find('.good_color').html('<option value="0">Please select</option>');
                  for (var i = 0; i < obj.length; i++) {
                    div_parent.find('.good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                }
            }

            if(data.discount){
               var obj = data.discount;
               div_parent.find('.sale_off_percent').html('<option value="">Please Choose</option>');
               for(var i = 0; i <obj.length; i++){
                div_parent.find('.sale_off_percent').append('<option value="'+obj[i]['discount']+'">'+obj[i]['name']+'</option>');
            } 
        }

        div_parent.find('.good_id').select2({
            allowClear: true
        });

        $('button[type=submit]').prop('disabled', false);
        $('form').unbind('submit');
        _self.nextAll('.loading').remove();
    });

    });
}

var xhr;

function initSelectProductBVG()
{
    $(document).off('change', '.good_id_bvg')
    .on('change', '.good_id_bvg', function(e) {
        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit',function(e){e.preventDefault();});
        var distributor_id    = $('#distributor_id').val();
        var _self = $(this);
        if(!distributor_id)
        {
            _self.val('');
            alert('Please select Warehouse/Retailer!');
        }


        $('.loading').remove();
        $(this).after('<span class="loading"></span>');

        var div_parent = $(this).parent().parent().parent();



        var good_id = div_parent.find('.good_id_bvg').val();
        var joint = div_parent.find('.joint').val();

        div_parent.find('.num_bvg, .price_bvg, .total_bvg').val('');


        $.get("/get/load-joint",
            {joint: joint, good_id: good_id , distributor_id : distributor_id}
            ,function(data,status){

                var data = $.parseJSON( data );

                var price = data.price;
                var num = data.total;
                var total = data.total_price;

                if (num > 0){
                    div_parent.find('.price_bvg').val(float_f(price));
                    div_parent.find('.num_bvg').val(float_f(num));
                    div_parent.find('.total_bvg').val(float_f(total));
                    selectBVGIMEI(div_parent);
                    joint_total++;
                }
                else
                {
                    alert('This distributor is don\'t have imei for this joint circular or discounts have been paid!');
                }

                $('button[type=submit]').prop('disabled', false);
                $('form').unbind('submit');
                _self.nextAll('.loading').remove();
            });
    });
}

function initSelectQuantityBVG()
{
    $(document).off('change', '.num_bvg')
    .on('change', '.num_bvg', function(e) {
        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit',function(e){e.preventDefault();});
        $('.loading').remove();
        var distributor_id    = $('#distributor_id').val();
        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        var num = _self.val();
        var price = floatval(div_parent.find('.price_bvg').val());

        if (distributor_id) {
            console.log(distributor_id);
            var total_price = 0;
            if (price && num)
                total_price = price * num;
            div_parent.find('.total_bvg').val(float_f(total_price)).change();
            selectBVGIMEI(div_parent);

        }
        else
        {
            _self.val('');
            alert('Please select Warehouse/Retailer!');
        }
    });
}

function selectBVGIMEI(div_parent)
{
    $('button, input, select').prop('disabled', true);
    distributor_id    = $('#distributor_id').val();
    joint  = div_parent.find('.joint').val();
    good_id_bvg = div_parent.find('.good_id_bvg').val();
    num =  div_parent.find('.num_bvg').val();
    var value = '';

    if(!joint && !good_id_bvg)
    {
        alert('Please Choose BVG');
        $('button, input, select').prop('disabled', false);
        return false;
    }

    $('.loading').remove();
    var targetUrl = '<?php echo HOST."bvg/get-imei" ?>';

        //get ajax content

        if (distributor_id && joint && good_id_bvg){
            div_parent.parents('.control-group').append("<span class=\'loading\'></span>");

            $.post(targetUrl, {
                d_id : distributor_id,
                joint_circular_id : joint,
                good_id : good_id_bvg,
                num : num
            }, function(data){
                $('button, input, select').prop('disabled', false);

                if (data){
                    if(data.result == 3)
                    {
                        alert('Number imei you insert is too large, Please contact Technolog Team');
                        $('.loading').remove();
                        div_parent.find('.num_bvg').val(0);
                        div_parent.find('.total_bvg').val(0).change();
                        div_parent.find('.bvg_imei').find('option').remove();
                    }
                    if(data.result == 4)
                    {
                        alert('This distributor don\'t have imei for discount');
                        $('.loading').remove();
                        div_parent.find('.num_bvg').val(0);
                        div_parent.find('.total_bvg').val(0).change();
                        div_parent.find('.bvg_imei').find('option').remove();
                    }

                    if(data.result == 1)
                    {

                      div_parent.find('.bvg_imei option').remove();
                      var obj = data.data;
                      for (var i = 0; i < obj.length; i++) {
                       div_parent.find('.bvg_imei').append('<option value="'+obj[i]['id']+'">'+obj[i]['imei_sn']+'</option>');
                       value += obj[i]['id'] + ',';
                   }
               }

           }
           $('.loading').remove();
           div_parent.find('.ids_imei').val(value.slice(0,-1));
           div_parent.find('.bvg_imei option').prop('selected', true);
       });
        }
    }

    function initSelectPercent(){
        $('.sale_off_percent').live('change',function(e) {
            var div_parent = $(this).parent().parent().parent();
            var _self = $(this);
            var sale_off_percent = _self.val();
            var price = parseFloat(div_parent.find('.price').val().split(',').join(''));
            var num = parseFloat(div_parent.find('.num').val().split(',').join(''));
        //alert(price);
        var total_price = 0;
        var type = $('.type').val();
        var rank = $('.rank').val();
        var for_partner = $("#for_partner").val();
        //alert(type);
        //alert(rank);
        var remark='';
        if (sale_off_percent > 0 && num > 0){

            total_price = price - Math.round((price*sale_off_percent/100)*100)/100;
            var tmp_total = Math.round(total_price*num,2);
            div_parent.find('.total').val(tmp_total.toLocaleString('en',{ minimumFractionDigits: 2 })).change();

            
            if(type==2 && rank==7 || rank==8 || rank==13){
              if(sale_off_percent==30){
                remark ="Live demo 30 %  จะรับคืนเมื่อสินค้าตกรุ่น ຂະຮັບ";
            }
        }else if(type==5 && rank==7 || rank==8  || rank==13){
          if(sale_off_percent==30){
            remark ="Live demo 30 %  จะรับคืนเมื่อสินค้าตกรุ่น";
        }
    }

/*
            if(type==2 && rank==1 || rank==2 || rank==5 || rank==6){
              if(sale_off_percent==50){
              remark ="Live demo 50% - ไม่เอาอุปกรณ์ จะรับคืนเมื่อสินค้าตกรุ่น - พร้อมอุปกรณ์ ซื้อขาดไม่รับคืนเมื่อสินค้าตกรุ่น";
              }
            }else if(type==5 && rank==1 || rank==2 || rank==5 || rank==6){
              if(sale_off_percent==50){
              remark ="Live demo 50% - ไม่เอาอุปกรณ์ จะรับคืนเมื่อสินค้าตกรุ่น - พร้อมอุปกรณ์ ซื้อขาดไม่รับคืนเมื่อสินค้าตกรุ่น";
              }
          }*/
      }
        //alert(remark);
        div_parent.find('.text').val(remark);
        
        phone_id = floatval( div_parent.find('.good_id').val() );
        
        if(for_partner === undefined){
            for_partner = 2;
        }

        if(type == <?php echo FOR_STAFFS ?> && for_partner == 2)
        {
            $.ajax({
              url: "/sales/check-sale-phone",
              type: "get",
              data: {'phone_id':phone_id,'sale_off_percent':sale_off_percent},
              success: function(result){
                if(result == 0)
                {
                    alert("ไม่มีส่วนลดใช้ในระดับนี้");
                    _self.val('0');
                    sale_off_percent = 0;

                    var price = parseFloat(div_parent.find('.price').val().split(',').join(''));
                    var num = parseFloat(div_parent.find('.num').val().split(',').join(''));
                    
                    var total_price = 0;
                    if (price > 0 && num > 0){
                        total_price = price - Math.round((price*sale_off_percent/100)*100)/100;
                        var tmp_total = Math.round(total_price*num,2);
                        div_parent.find('.total').val(tmp_total.toLocaleString('en',{ minimumFractionDigits: 2 })).change();

                    }
                }
                else{
                  
                    var price = parseFloat(div_parent.find('.price').val().split(',').join(''));
                    var num = parseFloat(div_parent.find('.num').val().split(',').join(''));
                    var total_price = 0;
                    if (price > 0 && num > 0){
                        total_price = price - Math.round((price*sale_off_percent/100)*100)/100;
                        var tmp_total = Math.round(total_price*num,2);
                        div_parent.find('.total').val(tmp_total.toLocaleString('en',{ minimumFractionDigits: 2 })).change();
                    }
                    
                }           
            },
            error:function(){
              alert("Error");
          }
      });
        }
        else{
            
            var price = parseFloat(div_parent.find('.price').val().split(',').join(''));
            var num = parseFloat(div_parent.find('.num').val().split(',').join(''));
            
            var total_price = 0;
            if (price > 0 && num > 0){
                total_price = price - Math.round((price*sale_off_percent/100)*100)/100;
                var tmp_total = Math.round(total_price*num,2);
                div_parent.find('.total').val(tmp_total.toLocaleString('en',{ minimumFractionDigits: 2 })).change();    
            }
        } 
        
    });
}

function initSelectQuantity(){
    $(document).off('change', '.num')
    .on('change', '.num', function(e) {

        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit',function(e){e.preventDefault();});

        $('.loading').remove();
        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        //var num = _self.val();
        var num = div_parent.find('.num').val();
        /*if($('.bs_campaign').is(":checked")==true){
          
          console.log(num);
          if(num==''){
            num=1;
            div_parent.find('.num').val(num);
          }
      }*/
      var good_id = div_parent.find('.good_id option:selected').val();
      var good_color = div_parent.find('.good_color').val();
      var cat_id = div_parent.find('.cat_id option:selected').val();
      var id = div_parent.find('.ids').val();
      var warehouse_id = $('#warehouse_id').val();
      var distributor_id = $('#distributor_id').val();
      var sales_sn = $('#sn').val();
      var type = $('#type').val();
      var order_date = $('#order_date').val();
      var rank =$ ('.rank').val();
      
        //NVMM LO MAY THANH LY
        var id_shipment = $('.shipment_id').val();
        var type_shipment = div_parent.find('.shipment_type').val();
        var type = $('.type').val();
        var rank = $('.rank').val();

        // var remark='';
        // if (type==2){ //for demo
        //     //set default sale off to 50%
        //     if(type==2 && rank==7 || rank==8 || rank==13){
        //       div_parent.find('.sale_off_percent').val('30');
        //       remark ="Live demo 30 %  จะรับคืนเมื่อสินค้าตกรุ่น";
        //     }else{
        //       div_parent.find('.sale_off_percent').val('50');
        //       remark ="Live APK";
        //     }

        //     //CPH1823/CPH1803(3G)/CPH1901/CPH1877
        //     if(good_id==345||good_id==339||good_id==363||good_id==353){
        //       div_parent.find('.sale_off_percent').val('50');
        //       remark ="Live demo ซื้อขาด 50% พร้อมอุปกรณ์ ไม่รับคืนเมื่อสินค้าตกรุ่น";
        //     }
        
        // }else if (type==3){ //for Staff
        //     //set default sale off to 50%
        //     if(type==5 && rank==7 || rank==8){
        //       // div_parent.find('.sale_off_percent').val('30');
        //       // remark ="For Staff 30 %";
        //     }else{
        //       // div_parent.find('.sale_off_percent').val('50');
        //       // remark ="For Staff 50% ";
        //     }
        // }else if (type==5){ //for APK
        //     //set default sale off to 50%
        //     if(type==5 && rank==7 || rank==8 || rank==13){
        //       div_parent.find('.sale_off_percent').val('30');
        //       remark ="Live demo 30 %  จะรับคืนเมื่อสินค้าตกรุ่น";
        //     }else{
        //       div_parent.find('.sale_off_percent').val('50');
        //       remark ="Live APK";
        //     }

        //     //by p'pui CPH1831 apk auto discount 50%
        //     if(good_id==321&&(rank==7||rank==8||rank==13)){
        //       div_parent.find('.sale_off_percent').val('50');
        //       remark ="Live APK";
        //     }

        //     //CPH1729(2G)/CPH1803(2G)/CPH1871/CPH1823/CPH1803(3G)/CPH1901/CPH1877
        //     if(good_id==323||good_id==338||good_id==340||good_id==345||good_id==339||good_id==363||good_id==353||good_id==371){
        //       div_parent.find('.sale_off_percent').val('50');
        //       remark ="Live demo ซื้อขาด 50% พร้อมอุปกรณ์ ไม่รับคืนเมื่อสินค้าตกรุ่น";
        //     }

        //     //CPH1923/CPH1969 6+128G/CPH1911/CPH1909/CPH1917/CPH1919/CPH1937
        //     if(good_id==393||good_id==392||good_id==395||good_id==374||good_id==399||good_id==403||good_id==453){
        //       div_parent.find('.sale_off_percent').val('50');
        //       remark ="Live APK";
        //     }

        // }

        // div_parent.find('.text').val(remark);
        var sale_off_percent = div_parent.find('.sale_off_percent').val();

        
        
        if (distributor_id && warehouse_id) {
            $(this).after('<span class="loading"></span>');
            if(xhr){
                xhr.abort();
            }
            // if($('.bs_campaign').is(":checked")==true){
            //   num = 1;
            // }
            xhr = $.get("/get/load-price",
                {num: num, good_id: good_id, is_sales_price: 1, distributor_id: distributor_id, good_color: good_color,
                    cat_id: cat_id, warehouse_id: warehouse_id, type: type, id: id, id_shipment: id_shipment,
                    type_shipment: type_shipment }
                    ,function(data,status){

                    //เช็คของในสต๊อก
                    if (data.indexOf("-3") !== -1){
                        var myarr = data.split("|");
                        // alert('ຈຳນວນເຄື່ອງທີ່ມີຢູ່ໃນສາງແມ່ນ: '+myarr[1]);
                        Swal.fire("Sorry!","Stock is not enough ຈຳນວນເຄື່ອງທີ່ມີຢູ່ໃນສາງແມ່ນ:"+myarr[1],"error")
                        div_parent.find('.num').val('');
                        div_parent.find('.sale_off_percent').val(0);
                        div_parent.find('.total').val(0);

		     } else if(data.indexOf("-5") !== -1) {

                        Swal.fire("Sorry","The product is locked by the warehouse. Cannot order.","error")
                        div_parent.find('.num').val('');
                        div_parent.find('.sale_off_percent').val(0);
                        div_parent.find('.total').val(0);

                    } else if(data.indexOf("-6") !== -1) {

                        Swal.fire("Sorry","The product is locked by the warehouse. Cannot order.","error")
                        div_parent.find('.num').val('');
                        div_parent.find('.sale_off_percent').val(0);
                        div_parent.find('.total').val(0);

                    } else {

                        var temp_discount_buy_return = parseInt(div_parent.find('.discount_buy_return').val());
                        var temp_discount_buy_return_true = parseInt(div_parent.find('.discount_buy_return_true').val());
                        var temp_num = parseInt(div_parent.find('.num').val());
                        
                        var price = 0;

                        if (data > 0 && num > 0) price = data/num;

                        var tmp_price = Math.round(price*100)/100;
                        div_parent.find('.price').val(tmp_price.toLocaleString('en',{ minimumFractionDigits: 2 }));

                        var total_price = data;

                        if (data > 0 && sale_off_percent > 0){

                          //alert(Math.round((data*sale_off_percent/100)*100)/100);
                          total_price = data - Math.round((data*sale_off_percent/100)*100)/100;
                      }

                      if(temp_discount_buy_return > 0 || temp_discount_buy_return_true > 0){
                        
                          total_price = total_price-((temp_discount_buy_return+temp_discount_buy_return_true)*temp_num);

                          // console.log('temp_discount_buy_return',temp_discount_buy_return);
                          // console.log('temp_discount_buy_return_true',temp_discount_buy_return_true);
                          // console.log('temp_num',temp_num);
                          // console.log('xxx',total_price-((temp_discount_buy_return+temp_discount_buy_return_true)*temp_num));
                      }

                      var tmp_total = Math.round(total_price*100)/100;
                        // alert(tmp_total);    

                        // alert(tmp_total.toLocaleString('en',{ minimumFractionDigits: 2 }));

                        if(isNaN(tmp_total)){
                          tmp_total = 0;
                      }

                      div_parent.find('.total').val(tmp_total.toLocaleString('en',{ minimumFractionDigits: 2 })).change();
                        // initSelectTotal();
                    }

                    $('button[type=submit]').prop('disabled', false);
                    $('form').unbind('submit');
                    // $('.loading').remove();
                });
        } else{
            _self.val('');
            alert('Please select Warehouse/Retailer!');
        }
        //pond check quota 
        if (distributor_id) {

          if($(this).val() == 0){
            $('.loading').remove();
            return false;
        }
          // alert(type)
          // alert(distributor_id)

          $('#submit_btn').attr('disabled','disabled');
          $('input[type="submit"]').attr('disabled','disabled');

          $.ajax({
            url: 'check-quota-oppo',
            type: 'POST',
            data: {distributor_id: distributor_id,good_id:good_id,good_color:good_color,num:num,rank:rank,warehouse_id:warehouse_id,cat_id:cat_id,sales_sn:sales_sn,type:type},
        })
          .done(function(data) {
             
           if (data == 1) {
              alert('Over Quota!');
              div_parent.find('.num').val(0).change();
              $('form').unbind('submit');
          }

          if (data == 2) {
              alert('ร้านนี้ยังไม่ได้กำหนดประเภทร้านค้า กรุณาอัพเดทข้อมูลร้านค้าด้วย!');
              div_parent.find('.num').val(0).change();
              $('form').unbind('submit');
          }

          console.log("success");
          $('.loading').remove();
          $('#submit_btn').removeAttr('disabled');
          $('input[type="submit"]').removeAttr('disabled');

      })
          .fail(function() {
            console.log("error");
            $('form').unbind('submit');
        })
          .always(function() {
            console.log("complete");
            $('form').unbind('submit');
        });
          
      }
      
      /*----------------------*/
      /*------------Check Limit Order---------*/
if(good_id==142){ // F1S
    $('#distributor_no_check_limit').val(0);
    $.get("/get/load-distributor-no-check-limit",{distributor_id : distributor_id,good_id : good_id}
        ,function(data,status){
            
            var data = $.parseJSON(data);
        //alert(data);
        if (data){   
            if(data==0){
                /*---------Get Good QTY------------*/
                GetProduct_Order(distributor_id,sales_sn,good_id,order_date);
                $('#distributor_no_check_limit').val(0).change();
            }else{
                $('#distributor_no_check_limit').val(1).change();
            }
        }else{
            $('#distributor_no_check_limit').val(0).change();
        }
    });    
}
});
}



function initSelectShipmentTypeQuantity(){
    $(document).off('change', '.shipment_type')
    .on('change', '.shipment_type', function(e) {
        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit',function(e){e.preventDefault();});

        $('.loading').remove();
        var div_parent     = $(this).parent().parent().parent();
        var _self          = $(this);
        var type_shipment  = _self.val();
        var good_id        = div_parent.find('.good_id').val();
        var good_color     = div_parent.find('.good_color').val();
        var cat_id         = div_parent.find('.cat_id').val();
        var id             = div_parent.find('.ids').val();
        var warehouse_id   = $('#warehouse_id').val();
        var distributor_id = $('#distributor_id').val();
        var type           = $('#type').val();
        //NVMM LO MAY THANH LY
        var id_shipment = $('.shipment_id').val();
        var num = div_parent.find('.num').val();
        
        if (type==2){ //for demo
            //set default sale off to 50%
            div_parent.find('.sale_off_percent').val('50');
        }
        var sale_off_percent = div_parent.find('.sale_off_percent').val();

        if (distributor_id && warehouse_id) {
            $(this).after('<span class="loading"></span>');
            if(xhr){
                xhr.abort();
            }
            xhr = $.get("/get/load-price",
                {num: num, good_id: good_id, is_sales_price: 1, distributor_id: distributor_id, good_color: good_color, cat_id: cat_id, warehouse_id: warehouse_id, type: type, id: id, id_shipment: id_shipment, type_shipment: type_shipment}
                ,function(data,status){
                    if (data.indexOf("-3") !== -1){
                        var myarr = data.split("|");
                        // alert('ຈຳນວນເຄື່ອງທີ່ມີຢູ່ໃນສາງແມ່ນ: '+myarr[1]);
                        Swal.fire("","ຈຳນວນເຄື່ອງທີ່ມີຢູ່ໃນສາງແມ່ນ:"+myarr[1],"error")
                        div_parent.find('.num').val('');
                        div_parent.find('.sale_off_percent').val(0);
                        div_parent.find('.total').val(0);
                    } else {
                        var price = 0;

                        if (data > 0 && num > 0) price = data/num;

                        div_parent.find('.price').val(Math.round(price*100)/100);

                        var total_price = data;

                        if (data > 0 && sale_off_percent > 0)
                            total_price = data - Math.round((data*sale_off_percent/100)*100)/100;

                        div_parent.find('.total').val(Math.round(total_price*100)/100).change();
                    }

                    $('button[type=submit]').prop('disabled', false);
                    $('form').unbind('submit');
                    $('.loading').remove();
                });
        } else{
            _self.val('');
            alert('Please select Warehouse/Retailer!');
        }
    });
}



function initSelectOrderType(){
    $(document).off('change', '#type')
    .on('change', '#type', function(e) {
        $('.num, .price, .total, .sale_off_percent').val('');
    });
}

function initReset(){
    $(document).off('click', 'button:reset')
    .on('click', 'button:reset', function(e) {
        e.preventDefault();
        $('select, input:text, input.num, input.price').val('');
        $('textarea').text('');

        $(form).find('select').each(function(i, v)
        {
            $(v).trigger('chosen:updated');
        });
    });
}

function initCheckGoodDemo(){//when submit

    var type        = $("#form #type").val(); //get current type
    var type_demo   = "<?php echo FOR_DEMO;?>";
    var good_id     = $('[name="good_id[]"]:visible');
    var num         = $('[name="num[]"]:visible');
    var arr_good    = [];
    var arr_num     = [];
    var d_id        = $("#distributor_id").val();

    $('#dialog').html('');//reset

    //check For order?
    if( type == type_demo ){

        good_id.each(function(index,elem){
            arr_good.push($(elem).val());
        });

        num.each(function(index,elem){
            arr_num.push($(elem).val());
        });

        $.ajax({
            type: 'post',
            url: '/get/check-good-demo',
            data: {'good_id':arr_good,'num':arr_num,'d_id':d_id},
            error: function(){
                alert('check demo error');
            },
            success: function(data){
                if(data.status == false)
                {
                    alert('get data check demo fail!');
                }else{
                    var $table = $('<table>',{class:'table'});
                    var tr = '';
                    var msg = '<div colspan=3 style="color: red">*This retailer has ordered above demo products, please confirm customer!</div>';
                    $table.append(
                        +'<thead>'
                        +'<tr>'
                        +'<td>Product</td>'
                        +'<td>Avaiable</td>'
                        +'<td>Over</td>'
                        +'</tr>'
                        +'</thead>'
                        );

                    if(data.result.length){

                        $.each(data.result,function(index){
                            tr += '<tr>'
                            +'<td>'+this.name+'</td>'
                            +'<td>'+this.avaiable+'</td>'
                            +'<td>'+this.over+'</td>'
                            +'</tr>';
                        });

                        $table.append(tr);
                        $('#dialog').append(msg);
                        $('#dialog').append($table[0]);

                        $('#dialog').dialog({
                            buttons:{
                                'Close':function(){
                                    $(this).dialog('close');
                                },
                                'Ignore': function(){
                                    check_gift();
                                    $(this).dialog('close');
                                }
                            }
                        });
                        $("#dialog").dialog("open");

                    }else{
                        check_gift();
                    }
                }
            }//End success
        });//End ajax
    }else{
        check_gift();
    }

}

function addRowNVMM(){
    $('.add_row_nvmm').live('click',function(){
        var _self = $(this);
        var d_id = $("#distributor_id").val();
        var nvmm =  '';
        if( d_id == <?php echo OPPO_STAFF;?> ){
            nvmm = $('.wrap_nvmm .info_nvmm');
        }else if(d_id == <?php echo OPPO_INGAME;?>) {
            nvmm = $('.wrap_nvmm .info_ingame');
        }

        var div_add_row = _self.parent().parent().parent();
        $(div_add_row).append(nvmm.clone());

    });
}

function removeRowNVMM(){
    $('#form .remove_nvmm').live('click',function(){
        console.log('cái nồi');
        $(this).parent().parent().remove();
    });
}

function add_product_color_key_nvmm(){
    $("#form .good_id").each(function(index,value){
        var row = $(this).closest('.row');
        var good_id = $(row).find('.good_id').val();
        var good_color = $(row).find('.good_color').val();
        var key = good_id+'_'+good_color;
        $(row).find('.product_color_key').val(key);
        console.log(key);
    });
}

//Khi chọn select area hoặc service center
function initSelectAreaService(){
    $('.addr_nvmm').each(function(i,v){
        var current = $(this).val();
        if(current != ''){
            $(".addr_nvmm").not(this).attr('required',false);
        }
    });

    $('.addr_nvmm').live('change',function(){
        $(".addr_nvmm").attr('required',true);
        var current = $(this).val();
        $(".addr_nvmm").not(this).val("");
        if(current == '' || current == 0){
            $(".addr_nvmm").attr('required',true);
        }else{
            $(".addr_nvmm").not(this).attr('required',false);
        }
    })
}



// tao remark tu dong cho nvmm
function autoRemarkForStaff(){
    $("#btn_auto_remark").live('click',function(){
        var d_id = $("#distributor_id").val();
        $("#form .good_id").each(function(index,value){
            var row = $(this).closest('.row');
            var shipment_id = $('.shipment_id').val();
            var good_id = $(row).find('.good_id').val();
            var good_color = $(row).find('.good_color').val();
            var cat_id = $(row).find('.cat_id').val();
            var type = $(row).find('.sale_off_percent option:selected').text();
            var all_staff = $(row).find('.id_staff');
            var all_num = $(row).find('.staff_num');
            var all_ingame = $(row).find('.name_staff_ingame');
            var all_ingame_cmndd = $(row).find('.cmnd_staff_ingame');
            var shipment_type = $(row).find('.shipment_type');
            var remark = '';

            remark = ''+type+''; //ຮ້ານນີ້ມີສ່ວນຫຼຸດ
            var str_cat = ' máy cho ';
            if(shipment_id === undefined){
                shipment_id = '';
            }

            if(shipment_id != ''){
                remark = 'Lô thanh lý ' + $('.shipment_id option:selected').html() + ': ';
            }

            if(cat_id == 12){
                str_cat = ' cái cho ';
            }

            if(d_id == <?php echo OPPO_STAFF;?>){
                $(all_staff).each(function(i,v){
                    var _num = $(all_num[i]).val();
                    var _name = $(v).attr('data-name');
                    var _type_name = '';
                    if(shipment_id != ''){
                        _type_name = ' loại ';
                        var _type = $(shipment_type[i]).val();
                        if(_type == 1){
                            _type_name += 'A ';
                        }else if(_type == 2){
                            _type_name += 'B ';
                        }else if(_type == 3){
                            _type_name += 'C ';
                        }else if(_type == 4){
                            _type_name += 'D ';
                        }else{
                            _type_name = '';
                        }
                    }
                    remark += _num + _type_name + str_cat+ _name + '; ';
                });
            }

            if(d_id == <?php echo OPPO_INGAME;?>){

                $(all_ingame).each(function(i,v){
                    var _num = $(all_num[i]).val();
                    var _name = $(v).val()+ ' (' + $(all_ingame_cmndd[i]).val()+ ')';
                    var _type_name = '';
                    if(shipment_id != ''){
                        _type_name = ' loại ';
                        var _type = $(shipment_type[i]).val();
                        if(_type == 1){
                            _type_name += 'A ';
                        }else if(_type == 2){
                            _type_name += 'B ';
                        }else if(_type == 3){
                            _type_name += 'C ';
                        }else if(_type == 4){
                            _type_name += 'D ';
                        }else{
                            _type_name = '';
                        }
                    }
                    remark += _num + _type_name + str_cat+ _name + '; ';
                });
            }

            $(row).find('.text').val(remark);

        });
    })
}

function ResetNvmm(){
    $('#form .wrap_list_staff').hide();
    $('.btn_add_row_nvmm').hide();

    $('#form .info_nvmm').remove();
    $('.info_nvmm').hide();

    $('#form .info_ingame').remove();
    $('.info_ingame').hide();

    $('#div-number-sales').remove();
}

function show_nvmm(option){
    if(option == 1){
        $('#form .wrap_list_staff').show();
        $('.btn_add_row_nvmm').show();

        $('#form .info_nvmm').remove();
        $('.info_nvmm').show();

        $('#form .info_ingame').remove();
        $('.info_ingame').hide();

        $('#div-number-sales').remove();
        var old_div = $('.div-number-sales');
        var new_div = old_div.clone();
        new_div.attr('id', 'div-number-sales');
        new_div.insertAfter($('#form .wrap_list_staff')).show();
    }else{
        $('#form .wrap_list_staff').hide();
        $('.btn_add_row_nvmm').show();

        $('#form .info_nvmm').remove();
        $('.info_nvmm').hide();

        $('#form .info_ingame').show();
        $('.info_ingame').show();

        $('#div-number-sales').remove();
        var old_div = $('.div-number-sales');
        var new_div = old_div.clone();
        new_div.attr('id', 'div-number-sales');
        new_div.insertAfter($('#form .wrap_list_staff')).show();

    }
}

function changePartner(){
    $("#for_partner").live('change',function(){
        var current = $(this).val();
        if(current == 2){
            var d_id = $('#distributor_id').val();
            if(d_id == <?php echo OPPO_STAFF?>){
                show_nvmm(1);
            }else{
                show_nvmm(2);
            }
        }else{
            ResetNvmm();
        }

    })
}

function  show_shipment_type(){
    //NHAN VIEN MUA MAY
    <?php if(!My_Staff_Group::create_for_partner($this->userStorage->id,$this->userStorage->group_id)):?>
        $('.wrap_shipment_type').hide();
    <?php endif?>
}

//Tanong

function DiscountDeposit(){
    var distributor_id = $('#distributor_id').val();
    var discount_deposit='';

    //alert(distributor_id);
    $.get("/get/load-deposit-sn",
        {distributor_id : distributor_id , init_params :discount_deposit.slice(0, -1)}
        ,function(data,status){
            //alert(data);
            var data = $.parseJSON(data);
            //alert(data);
            if (data){
                //alert(data);
                var obj = data
                
                console.log(obj);
                //alert(obj.length);
                $('#btn-deposit').removeAttr('disabled');
            }
            else
            {
                alert(data.error);
            }
        });
}

function initAddDiscountDeposit(){
    $('#btn-deposit').click(function(e){

        var distributor_id = $('#distributor_id').val();

        if(!distributor_id)
        {
            alert('Please insert Distributor');
            return false;
        }

        //alert('Add New');
        var old_div = $('.div-discount-deposit');
        var new_div = old_div.clone();
        new_div.removeClass('div-discount-deposit').find('select, input, textarea').removeAttr('disabled');
        new_div.insertBefore($(this).parent().parent().parent()).show();

        var discount_deposit='';
        $('.discount_deposit').each(function(){
            var deposit_sn = $(this).find('option:selected').text();
            if(deposit_sn!='Please select'){
                discount_deposit +="'"+$.trim(deposit_sn)+"',";
            }
        });

        
        //alert(distributor_id);alert(creditnote_sn_list);
        $.get("/get/load-deposit-sn",
            {distributor_id : distributor_id , init_params :discount_deposit.slice(0, -1)}
            ,function(data,status){
                //alert(data);
                var data = $.parseJSON( data );
                
                if (data){
                    var obj = data

                    //console.log(obj);
                    new_div.find('.discount_deposit').html('<option value="0">Please select</option>');
                    for (var i = 0; i < obj.length; i++) {
                        new_div.find('.discount_deposit').append('<option value="'+obj[i]['balance_total']+'">'+obj[i]['deposit_sn']+'</option>');
                    }
                }
                else
                {
                    new_div.find('.discount_deposit').html('<option value="0">Please select</option>');
                    //alert(data.error);
                }
            });

        Auto_Summary_TotalPrice();
        
        

        return false;
    });
}

//Tanong
function initSelectDiscountDeposit()
{
    $(document).off('change', '.discount_deposit')
    .on('change', '.discount_deposit', function(e) {
        var div_parent = $(this).parent().parent().parent();
        var deposit_sn = div_parent.find('.discount_deposit option:selected').text();
        var price_discount = div_parent.find('.discount_deposit option:selected').val();

        div_parent.find('.price_balance_discount_deposit').val(price_discount);
        div_parent.find('.price_use_discount_deposit').val(price_discount);
        div_parent.find('.ids_discount_deposit').val(deposit_sn);
        
        Auto_Summary_TotalPrice();
    });
}

//Tanong
function initChangeDiscountDeposit()
{
    $(document).off('change', '.price_use_discount_deposit')
    .on('change', '.price_use_discount_deposit', function(e) {

        var div_parent = $(this).parent().parent().parent();
        var use_discount = parseFloat($(this).val());
        var total_discount = div_parent.find('.price_balance_discount_deposit').val();
        var temp_total_discount = div_parent.find('.temp_price_use_discount_deposit').val();

        if(!use_discount){
          use_discount = '0';
      }

      if(!total_discount){
          total_discount = '0';
      }

      if(!temp_total_discount){
          temp_total_discount = '0';
      }

      use_discount = use_discount.replace(/,/g,'');
      total_discount = total_discount.replace(/,/g,'');
      temp_total_discount = temp_total_discount.replace(/,/g,'');

      if(total_discount<0){
        alert('ไม่สามารถใช้ส่วนลดได้');
        $(this).val(0);
        return;
    }

        // if(total_discount<use_discount){
            if(parseFloat(total_discount)+parseFloat(temp_total_discount) < use_discount){
                alert('ส่วนลดที่ใช้มากกว่าส่วนลดทั้งหมด');
                $(this).val(0);
                return;
            }
            Auto_Summary_TotalPrice();
        });
}

function initRemoveDeposit(){
    $(document).off('click', '.remove-deposit')
    .on('click', '.remove-deposit', function(e) {

        $(this).parent().parent().parent().remove();
        calculate_fee();
        Auto_Summary_TotalPrice();
        return false;
    });
}

//--------- CreditNote

function DiscountCreditNote(){
    var distributor_id = $('#distributor_id').val();
    var creditnote_sn_list='';

    //alert(distributor_id);
    $.get("/get/load-credit-note",
        {distributor_id : distributor_id , init_params :creditnote_sn_list.slice(0, -1)}
        ,function(data,status){
            //alert(data);
            var data = $.parseJSON(data);
            //alert(data);
            if (data){
                //alert(data);
                var obj = data
                
                console.log(obj);
                //alert(obj.length);
                $('#btn-discount-creditnote').removeAttr('disabled');
            }
            else
            {
                alert(data.error);
            }
        });
}

function initAddDiscountCreditNote(){
    $('#btn-discount-creditnote').click(function(e){

        var distributor_id = $('#distributor_id').val();
        var status_page = $('#status_page').val();
        console.log(status_page);
        if(!distributor_id)
        {
            alert('Please insert Distributor');
            return false;
        }

        //alert('Add New');
        var old_div = $('.div-discount-credit-note');
        var new_div = old_div.clone();
        new_div.removeClass('div-discount-credit-note').find('select, input, textarea').removeAttr('disabled');
        new_div.insertBefore($(this).parent().parent().parent()).show();

        var creditnote_sn_list='';
        $('.discount_creditnote').each(function(){
            var creditnote_sn = $(this).find('option:selected').text();
            if(creditnote_sn!='Please select'){
                creditnote_sn_list +="'"+$.trim(creditnote_sn)+"',";
            }
        });

        
        //alert(distributor_id);alert(creditnote_sn_list);
        $.get("/get/load-credit-note",
            {distributor_id : distributor_id , init_params :creditnote_sn_list.slice(0, -1)}
            ,function(data,status){
                //alert(data);
                var data = $.parseJSON( data );
                
                if (data){
                    var obj = data

                    //console.log(obj);
                    new_div.find('.discount_creditnote').html('<option value="0">Please select</option>');
                    for (var i = 0; i < obj.length; i++) {
                        if(status_page==1 && obj[i]['balance_total'] >0){
                            new_div.find('.discount_creditnote').append('<option value="'+obj[i]['balance_total']+'">'+obj[i]['creditnote_sn']+'</option>');
                        }else if(status_page==2){
                         new_div.find('.discount_creditnote').append('<option value="'+obj[i]['balance_total']+'">'+obj[i]['creditnote_sn']+'</option>');
                     }
                 }
             }
             else
             {
                new_div.find('.discount_creditnote').html('<option value="0">Please select</option>');
                    //alert(data.error);
                }
            });

        Auto_Summary_TotalPrice();
        
        

        return false;
    });
}

//Tanong
function initSelectDiscountCreditNote()
{
    $(document).off('change', '.discount_creditnote')
    .on('change', '.discount_creditnote', function(e) {
        var div_parent = $(this).parent().parent().parent();
        var creditnote_sn = div_parent.find('.discount_creditnote option:selected').text();
        var price_discount = div_parent.find('.discount_creditnote option:selected').val();

        div_parent.find('.price_balance_discount_creditnote').val(price_discount);
        div_parent.find('.price_use_discount_creditnote').val(price_discount);
        div_parent.find('.ids_discount_creditnote').val(creditnote_sn);
        
        Auto_Summary_TotalPrice();
    });
}

//Tanong
function initChangeDiscountCreditNote()
{
    $(document).off('change', '.price_use_discount_creditnote')
    .on('change', '.price_use_discount_creditnote', function(e) {
        //var div_parent = $(this).parent().parent().parent();
        //var use_discount = parseFloat($(this).val());
        //var total_discount = $('.price_balance_discount_creditnote').val();
        //alert(total_discount);

        var div_parent = $(this).parent().parent().parent();
        var use_discount = $(this).val();
        var total_discount = div_parent.find('.price_balance_discount_creditnote').val();
        var temp_total_discount = div_parent.find('.temp_price_use_discount_creditnote').val();

        if(!use_discount){
          use_discount = '0';
      }

      if(!total_discount){
          total_discount = '0';
      }

      if(!temp_total_discount){
          temp_total_discount = '0';
      }

      use_discount = use_discount.replace(/,/g,'');
      total_discount = total_discount.replace(/,/g,'');
      temp_total_discount = temp_total_discount.replace(/,/g,'');

      console.log(use_discount);
      console.log(total_discount);
      console.log(temp_total_discount);

      if(total_discount<0){
        alert('ບໍ່ສາມາດໃຊ້ສ່ວນຫຼຸດໄດ້');
        $(this).val(0);
        return;
    }

    console.log(parseFloat(total_discount)+parseFloat(temp_total_discount) + '<' + use_discount);
        //alert(total_discount);
        // if(total_discount<use_discount){
            if(parseFloat(total_discount)+parseFloat(temp_total_discount) < use_discount){
                alert('ສ່ວນຫຼຸດທີ່ໃຊ້ຫຼາຍກ່ວາສ່ວນຫຼຸດທັງໝົດ');
                $(this).val(0);
                return;
            }
            Auto_Summary_TotalPrice();
        });
}

function initRemoveCreditNote(){
    $(document).off('click', '.remove-credit-note')
    .on('click', '.remove-credit-note', function(e) {

        $(this).parent().parent().parent().remove();
        calculate_fee();
        Auto_Summary_TotalPrice();
        return false;
    });
}

function initChangeDiscount()
{
    $(document).off('change', '.price_discount')
    .on('change', '.price_discount', function(e) {
        var div_parent = $(this).parent().parent().parent();
        Auto_Summary_TotalPrice();
    });
}

//Tanong
function initChangeDeliveryFee()
{
    $(document).off('change', '.delivery_fee')
    .on('change', '.delivery_fee', function(e) {
        Auto_Summary_TotalPrice();
    });
}


//Tanong
function GetSalesOrder_Amount(d_id)
{  
    var total_amount_all=0;
    $.get("/get/load-sales-order-amount",{distributor_id : d_id}
        ,function(data,status){
            var data = $.parseJSON(data);
            if (data){                
                total_amount_all=data;
                $('#total_amount_all').val(total_amount_all);
                    //alert(total_amount_all);
                }
                else
                {
                    alert(data.error);
                    $('#total_amount_all').val(0);
                }
            });
    //Auto_Summary_TotalPrice();
    return parseFloat(total_amount_all);
}

//Tanong
function GetDelivery_Fee_All(d_id)
{  
    var delivery_fee_all=0;
    $.get("/get/load-delivery-fee-all",{distributor_id : d_id}
        ,function(data,status){
            var data = $.parseJSON(data);
            if (data){   
                //alert(data);                
                delivery_fee_all=data;
                $('#delivery_fee_all').val(delivery_fee_all);
                   // alert(delivery_fee_all);
               }
               else
               {
                alert(data.error);
                $('#delivery_fee_all').val(0);
            }
        });
    //Auto_Summary_TotalPrice();
    return parseFloat(delivery_fee_all);
}

//Tanong
function GetProduct_Order(d_id,sales_sn,good_id,order_date)
{  
    var product_total_qty=100;
    $('#product_total_qty').val(product_total_qty).change();
    $.get("/get/load-product-order",{distributor_id : d_id,sales_sn : sales_sn,good_id : good_id,order_date : order_date}
        ,function(data,status){
              //alert(data);
              var data = $.parseJSON(data);
              if (data){   
                  //  product_total_qty = parseFloat(data); 

                  product_total_qty = parseFloat(data.split(',').join(''));

                  
                  if(!isNaN(product_total_qty)){
                      $('#product_total_qty').val(product_total_qty).change();
                  //alert(product_total_qty);
              }else{
                $('#product_total_qty').val(100).change();
            }
              //alert($('#product_total_qty').val());
              
          }
          else
          {
            alert(data.error);
            $('#product_total_qty').val(product_total_qty).change();
        }

    });  
    
}

function GetDistributor_no_check_limit(distributor_id,sales_sn,good_id,order_date)
{  
    if(good_id==142){ // F1S
        $('#distributor_no_check_limit').val(0);
        $.get("/get/load-distributor-no-check-limit",{distributor_id : distributor_id,good_id : good_id}
            ,function(data,status){
                
                var data = $.parseJSON(data);
            //alert(data);
            if (data){   
                if(data==0){
                    /*---------Get Good QTY------------*/
                    GetProduct_Order(distributor_id,sales_sn,good_id,order_date);
                    $('#distributor_no_check_limit').val(0).change();
                }else{
                    $('#distributor_no_check_limit').val(1).change();
                }
            }else{
                $('#distributor_no_check_limit').val(0).change();
            }
        });    

    }
}

//Tanong
function Auto_Summary_TotalPrice()
{  
    
    var distributor_id = $('#distributor_id').val(); 
    var ext_vat_product_total_amount=0;   var ext_vat_delivery=0;
    var ext_vat_price_discount=0;   var ext_vat_total_amount=0;   var vat_amount=0;

    var in_vat_price_discount=0;
    var in_vat_total_amount=0;
    var price_qty_total=0;
    var  ext_vat_total =0;
    var total_amount=0;var vat_amount=0;var priceall=0;
    var price_discount=0;var price_total=0;var delivery_fee=0;
    var total_spc_discount=0;var price_deposit=0;
    
    var spc_discount = $('#spc_discount').val();
    var spc_discount_phone = $('#spc_discount_phone').val();
    var spc_discount_acc = $('#spc_discount_acc').val();
    var spc_discount_digital = $('#spc_discount_digital').val();

    var type = $('.type').val();
    //console.log(type);
    if(type==2 || type==5){
      spc_discount=0;
  }

    //Focus
    

/*    if(jQuery.inArray($(this).val(), arrFocus)) {
      alert($(this).val());
  }*/

  var chk_qty=0;
  $('.total').each(function(){
    var totals = parseFloat($(this).val().split(',').join(''));
    var div_parent = $(this).parent().parent().parent();
    var cat_id = div_parent.find('.cat_id').val();

    var price_qty = roundNumber(parseFloat(div_parent.find('.price').val().split(',').join('')),2).replace(",", "");
    var num_qty = parseFloat(div_parent.find('.num').val().split(',').join(''));
    var sale_off_percent = parseFloat(div_parent.find('.sale_off_percent').val().split(',').join(''));
    var discount_buy_return = div_parent.find('.discount_buy_return').val();
    var discount_buy_return_true = div_parent.find('.discount_buy_return_true').val();
    var total_price=0;
      //  var  ext_vat_total = roundNumber(ext_vat_product_total_amount,2).replace(",", "");

        //console.log(sale_off_percent);

        if(!isNaN(totals)){

            total_price = price_qty;

            if(sale_off_percent > 0){
              total_price = price_qty - roundNumber(Math.round((price_qty*sale_off_percent/100)*100)/100,2).replace(",", "");
          }

          if(discount_buy_return > 0){
              total_price = price_qty - discount_buy_return.replace(",", "") - discount_buy_return_true.replace(",", "");
          }

          if(discount_buy_return_true > 0){
              total_price = price_qty - discount_buy_return_true.replace(",", "") - discount_buy_return.replace(",", "");
          }

            //console.log(roundNumber((price_qty/1),2).replace(",", ""));
            price_qty_total = (roundNumber((total_price/1),2).replace(",", ""))*num_qty;
            price_total += price_qty_total;
            
            //console.log(price_qty_total);
            if(spc_discount >0){
              
              if(spc_discount_phone==1){
                if(cat_id==11){
                  total_spc_discount += price_qty_total;
              }else{
                  total_spc_discount += 0;
              }
          }

          if(spc_discount_acc==1){
            if(cat_id==12){
              total_spc_discount += price_qty_total;
          }else{
              total_spc_discount += 0;
          }
      }

      if(spc_discount_digital==1){
        if(cat_id==13){
          total_spc_discount += price_qty_total;
      }else{
          total_spc_discount += 0;
      }
  }
  
}else{
  total_spc_discount=0;
}          


var presales_sn = $('#presales_sn').val();
if(presales_sn !=''){
  div_parent.find('.cat_id option:not(:selected)').attr('disabled', true);
  div_parent.find('.good_id option:not(:selected)').attr('disabled', true);
  div_parent.find('.good_color option:not(:selected)').attr('disabled', true);
  div_parent.find('.price').attr('readonly', true);

  if(num_qty <=0){
    $('#submit_btn').prop('disabled', true);
    chk_qty +=1;
}


if(!isNaN(num_qty)){
    if(chk_qty <= 0){
      $('#submit_btn').prop('disabled', false);
  }
  
}
              //console.log(chk_qty);
          } 
      }

  });

  $('.price_discount').each(function(){
    var totals = parseFloat($(this).val().split(',').join(''));
    if(!isNaN(totals)){
        price_discount += totals;
    }
});

  $('.price_use_discount_creditnote').each(function(){
    var totals = parseFloat($(this).val().split(',').join(''));
    if(!isNaN(totals)){
        if(totals<0){
            alert('ບໍ່ສາມາດໃຊ້ສ່ວນຫຼຸດໄດ້');
            $(this).val(0);
            return;
        }else{
          price_discount += totals;
      }
  }
});

  $('.price_use_discount_deposit').each(function(){
    var totals = parseFloat($(this).val().split(',').join(''));
    if(!isNaN(totals)){
        price_deposit += totals;
    }
});

  $('.delivery_fee').each(function(){
    var totals = parseFloat($(this).val().split(',').join(''));
    if(!isNaN(totals)){
        delivery_fee += totals;
    }
});

//Exc VAT

    //Delivery Fee < 10000 all sales order per 1 day
    //delivery_fee_status = 1 : use delivery_fee
    GetSalesOrder_Amount(distributor_id);
    GetDelivery_Fee_All(distributor_id);

    var total_amount_all=0;var delivery_fee_all=0;var sales_order='';
    var chk_total_amount_all=0;var ext_total_total_after=0;var in_total_total_after =0;

    if(spc_discount >=0){
      var total_spc_discount_amount = (total_spc_discount *spc_discount/100);
      //console.log(total_spc_discount);
      //console.log(spc_discount);
      //console.log(total_spc_discount_amount);
      $('#total_spc_discount').val(total_spc_discount_amount);
      $('#total_spc_discount_view').text(roundNumber(total_spc_discount_amount*-1,2));
  } 

  // in_vat_total_amount = (price_total-total_spc_discount- price_discount - price_deposit)+delivery_fee;
  

  ext_total_total_after = (price_total- price_discount - price_deposit)+delivery_fee;

   //console.log(ext_total_total_after);
   //console.log(total_spc_discount_amount);

   in_vat_total_amount=ext_total_total_after-total_spc_discount_amount;

   total_amount_all = $('#total_amount_all').val();
   delivery_fee_all = $('#delivery_fee_all').val();
   sales_order = $('#sales_order').val();
   
   chk_total_amount_all = parseFloat(total_amount_all)+in_vat_total_amount;

   if(isNaN(chk_total_amount_all)){
    chk_total_amount_all = 0;
}

if(sales_order!=''){
 if(delivery_fee>0){
    
    $('.box_delivery_fee').show();
    $('#delivery_fee_status').val(1);
}
}else{
 if(delivery_fee_all<=0){
    
     if(sales_order==''){
        if(chk_total_amount_all<10000){

            var count_access_cat_id = 0;count_phone_cat_id = 0;
            $('.cat_id').each(function(){

                var div_parent = $(this).parent().parent().parent();
                var good_id = div_parent.find('.good_id option:selected').val();
                var cat_id = $(this).val();
                if(cat_id==12 && good_id != 127 && good_id != 141){
                  count_access_cat_id+=1;
              }
              if(cat_id==11){
                  count_phone_cat_id+=1;
              }
          });
                    if(count_access_cat_id >0 && count_phone_cat_id <=0){ // chk access only in order
                      if(chk_total_amount_all<2000){ // chk total amount access <2000 show fee delivery
                        $('.box_delivery_fee').show();
                        $('#delivery_fee_status').val(1);
                    }else{
                        $('.box_delivery_fee').hide();
                        delivery_fee=0;
                        $('#delivery_fee').val(0);
                        $('#delivery_fee_status').val(0);
                    }
                }else{
                  $('.box_delivery_fee').show();
                  $('#delivery_fee_status').val(1);
              }          
          }else{
            $('.box_delivery_fee').hide();
            delivery_fee=0;
            $('#delivery_fee').val(0);
            $('#delivery_fee_status').val(0);
        }
    }else{
        $('.box_delivery_fee').show();
        $('#delivery_fee_status').val(1);
    }
}else{
    if(sales_order==''){
        if(chk_total_amount_all<10000){
            $('.box_delivery_fee').show();
            $('#delivery_fee_status').val(1);
        }else{
            $('.box_delivery_fee').hide();
            delivery_fee=0;
            $('#delivery_fee').val(0);
            $('#delivery_fee_status').val(0);
        }
    }else{
        $('.box_delivery_fee').show();
        $('#delivery_fee_status').val(1);
    }
}
}

   // alert(total_spc_discount);

   if(isNaN(price_total)){
    price_total=0.00;
}

  //console.log(total_spc_discount_amount);
  //ext_vat_total_amount
  // ext_vat_total_amount = (delivery_fee+price_total);
  ext_vat_total_amount = (price_total);

  ext_vat_product_total_amount=ext_vat_total_amount;

  //ext_total_total_after
  ext_total_total_after =ext_vat_product_total_amount-total_spc_discount_amount+(delivery_fee/1);

  // Cal VAT
  //ext_vat_product_total_amount=roundNumber(ext_total_total_after/1,2).replace(",", "");
  vat_amount= (ext_total_total_after*1)-ext_total_total_after;


  if($('#rank').val() == '9'){
    ext_vat_product_total_amount=ext_total_total_after;
    vat_amount= ext_total_total_after - ext_vat_product_total_amount;
}

ext_vat_price_discount=(price_discount/1)*-1;
in_total_total_after = ext_total_total_after+vat_amount;

in_vat_total_amount = in_total_total_after-price_discount-price_deposit;


ext_vat_total = roundNumber(ext_vat_product_total_amount,2).replace(",", "");

if (ext_vat_total >= 10000.00 ) {
    $('.box_delivery_fee').hide();
    $('#delivery_fee').val(0);
    $('#delivery_fee_status').val(0);
}else{
    $('.box_delivery_fee').show();
    $('#delivery_fee_status').val(1);
}
$('#total_total').text(roundNumber(ext_vat_product_total_amount,2));
$('#ext_vat_delivery').text(roundNumber(ext_vat_delivery,2));

$('#total_total_after').text(roundNumber(ext_total_total_after,2));

$('#vat_amount').text(roundNumber(vat_amount,2));
$('#ext_sum_discount_price').text((roundNumber(ext_vat_price_discount,2)));
$('#total_amount').text(roundNumber(in_total_total_after,2));


//Inc VAT
$('#sum_discount_price').text(roundNumber((price_discount*-1),2));
$('#sum_deposit_price').text(roundNumber((price_deposit*-1),2));
$('#in_vat_delivery').text(roundNumber(delivery_fee,2));
$('#priceall').text(roundNumber(in_vat_total_amount,2));

}

//Tanong
function roundNumber(num, dec) {
 var result = Math.round(num*Math.pow(10,dec))/Math.pow(10,dec);
 return Number(result).toLocaleString('en',{ minimumFractionDigits: 2 });

   //tmp.toLocaleString('en',{ minimumFractionDigits: 4 });

}

function roundNumber2digi(num) {
 return Math.round(num).toFixed(3);
}

</script>