<script src="<?php echo HOST ?>js/jquery-ui.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>
<script src="<?php echo HOST ?>js/bootstrap-modal.js"></script>
<script src="<?php echo HOST ?>js/bootstrap-modalmanager.js"></script>
<script src="<?php echo HOST ?>js/jquery.blockUI.js"></script>

<script>
$(document).ready(function () {
    initChangeRetailer();
    initGoBack();
    initAddSales();
    initSelectPaid();
    initSelectTotal();
    initSearchObjectOption();
    initRemoveSales();
    initSelectProduct();
    initSelectQuantity();
    initSelectPercent();
    initSelectOrderType();
    initReset();
    initTag();
    initDialog();
    initTooltip();
    initGetSettedRetailer();
    initSearchOptionDistributor('distributor_id', 'SearchBox');
});

 $(document).on('focus',".payment_date", function(){
   $(this).datepicker({ dateFormat: "dd/mm/yy" });
});

//thay đổi số tiền thực tế thanh toán
function initSelectPaid(){
    $('.sotienthucte').live('change', function(e) {
        var _self = $(this);
        paid  = _self.val();

        total = $(this).closest('.row').find('.total').val().split('.').join('');
        var so_du = parseInt(paid) - parseInt(total);

        $(this).closest('.row').find('.sodu').val(float_f(so_du));
    });
}
//thay đổi giá máy không khớp với giá trên lô => hiện thông báo nếu có chọn lô máy
function initSelectTotal(){
    $(document).off('change', '.total')
    .on('change', '.total', function(e) {
        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        total  = _self.val().split('.').join('');
        var num = div_parent.find('.num').val();
        var price = div_parent.find('.price').val().split('.').join('');
        var good_id = div_parent.find('.good_id').val();
        var price_2 = total/num;
        var sum = 0;

        $('.total').each(function(){
            var totals = parseInt($(this).val().split('.').join(''));
            if(!isNaN(totals)){
                sum += totals;
            }
        });

        var paid = $('.paid').val();
        var so_du = parseInt(paid) - parseInt(sum);
        $('.so_du').val(float_f(so_du));

    });
}

function initResetRebate(){
    $(document).off('change', 'form .cat_id,form .good_id,form .good_color,form .num,form .price,form .sale_off_percent,form .total')
    .on('change', 'form .cat_id,form .good_id,form .good_color,form .num,form .price,form .sale_off_percent,form .total,form .id_for_staff', function(e) {
        $("#rebate_price").val('');
    });
}

function initRebate(){
    var timeout1;
    $("#btn-calculate").on("click", function () {
        window.clearTimeout(timeout1);
        timeout1 = window.setTimeout(function() {
            calculateRebatePrice();
        }, 500);

    });
}

function calculateRebatePrice(){
    var total_price = 0;
    var rebate_price = $("#rebate_price").val();

    if (rebate_price == '')
        return;

    $('button[type=submit]').prop('disabled', true);
    $('form').bind('submit',function(e){e.preventDefault();});

    $('form .total').each(function(){
        var div_parent = $(this).parent().parent().parent();
        if (div_parent.find('.cat_id').val() == '<?php echo PHONE_CAT_ID;?>') {
            if ($(this).val() == ''){
                alert('Please choose Total price');
                $("#rebate_price").val('');
                return;
            }
            total_price += Math.round( $(this).val() );
        }
    });

    if ( total_price > 0 ){
        var $rebate_percent = rebate_price/total_price;

        $('form .total').each(function(){
            var div_parent = $(this).parent().parent().parent();
            if (div_parent.find('.cat_id').val() == '<?php echo PHONE_CAT_ID;?>') {
                $v = $(this).val();
                if ($v > 0){
                    var $re = $v - Math.round($v * $rebate_percent);
                    $(this).val($re);
                }
            }
        });

    } else {
        alert('Please choose Total price');
        $("#rebate_price").val('');
    }

    $('button[type=submit]').prop('disabled', false);
    $('form').unbind('submit');
    return;
}

function initSearchOption(){
    var timeout;
    $("#SearchBox").on("keyup", function () {
        var userInput = $("#SearchBox").val();
        window.clearTimeout(timeout);
        timeout = window.setTimeout(function() {
            showOnlyOptionsSimilarToText($("#distributor_id"), userInput, true, 'initChangeRetailer');
        }, 500);

    });
}

function initSearchObjectOption(){
    var timeout;
    $("#SearchBoxObject").live("keyup", function () {
        var userInput = $("#SearchBoxObject").val();
        window.clearTimeout(timeout);
        timeout = window.setTimeout(function() {
            showOnlyOptionsSimilarToText($(".object_id"), userInput, true, '');
        }, 500);

    });
}

function initDialog(){
    $("#dialog").dialog({
        autoOpen: false,
        modal: true
    });
}

function initTooltip(){
    $('.tooltip-r').tooltip({
        placement: 'right',
        html: true,
        title: $('#tooltip_type').html()
    });
}

function initTag(){

    $('#myTags').tagit({
        allowSpaces: true,
        fieldName: 'tags[]',
        autocomplete: {
            delay: 0,
            minLength: 2,
            source: "<?php echo HOST;?>get/get-tags"
        }
    });

}

function initChangeRetailer(){//change retailer

    $('.distributor-info').hide();
    $(document).off('change', '#distributor_id')
    .on('change', '#distributor_id', function(e) {
    });

    initViewMore();
}

function initAddMethodPayment()
{
    var old_div = $('.div-payment');
    var new_div = old_div.clone();
    new_div.removeClass('.div-payment').find('select').removeAttr('disabled');
    new_div.attr('id', 'payment');
    new_div.insertAfter($('.distributor-info').parent().parent()).show();
}

function initGetSettedRetailer(){
    var d_id = $('#distributor_id').val();

    if(d_id){
    }
}

function initViewMore(){
    $(document).off('click', '.view-more')
    .on('click', '.view-more', function(e) {
        $('.distributor-info .info ').toggle();
        var text = $(this).text();
        if(text == '+'){
            $(this).text('-');
        }else{
            $(this).text('+');
        }
    });
}

Array.prototype.contains = function (v) {
    return this.indexOf(v) > -1;
}

var array_ka = [ <?php echo KA_TGDD ?>, <?php echo KA_VTA ?> , <?php echo KA_FPT; ?> ];

function check_gift(elm) {

    if (!$('#form')[0].checkValidity()) {
        $('#form').find(':submit').click();
        return;
    }

    $('button, input, select').prop('disabled', true);
    $('#form').unbind('submit');

    good_list = [];
    $('[name="good_id[]"]:visible').each(function(index, elm) {
        good_list.push($(elm).val());
    });

    $.ajax({
        url: '<?php echo HOST ?>get/check-gift',
        dataType: 'json',
        data: {good_list: good_list},
    })
    .done(function(result) {
        $('button, input, select').prop('disabled', false);
        $('#form').bind('submit');

        if (typeof result.code != "undefined" && result.code != 1) {
            $('#dialog').html(result.error);

            $("#dialog").dialog({
                buttons : {
                    "Choose Gifts" : function() {
                        $(this).dialog("close");
                        return false;
                    },
                    "Ignore" : function() {
                        $('#form').submit();
                    }
                }
            });

            $("#dialog").dialog("open");
        } else {
            $('#form').submit();
        }

    })
    .fail(function(result) {
        console.log(result.error);
    })
    .always(function() {
        console.log("complete");
    });

}

function initGoBack(){
    $(document).off('click', '.go-back')
    .on('click', '.go-back', function(e) {
        if (parent.history.length > 1)
            parent.history.back();
        else
            window.location.href = '<?php echo HOST ?>sales/stock';
        return false;
    });
}

function initRemoveSales(){
    $(document).off('click', '.remove-sales')
    .on('click', '.remove-sales', function(e) {
        $(this).parent().parent().parent().remove();
        return false;
    });
}

function initAddSales(){
    $(document).off('click', '.add-sales')
    .on('click', '.add-sales', function(e) {
        var old_div = $('.div-add');
        var new_div = old_div.clone();

        new_div.removeClass('div-add').find('select, input, textarea').removeAttr('disabled');

        new_div.insertBefore($(this).parents('.row')).show();

        initSelectProduct();
        initSelectQuantity();
        initSelectPercent();
        initRemoveSales();
        return false;
    });
}

function initSelectProduct(){
    $(document).off('change', '.cat_id, .good_id')
    .on('change', '.cat_id, .good_id', function(e) {
        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit',function(e){e.preventDefault();});

        $('.loading').remove();
        $(this).after('<span class="loading"></span>');
        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        var cat_id = div_parent.find('.cat_id').val();

        if (_self.hasClass('cat_id'))
            div_parent.find('.good_id').find('option:not(:first)').remove();

        var good_id = div_parent.find('.good_id').val();

        div_parent.find('.good_color').find('option:not(:first)').remove();

        div_parent.find('.num, .price, .total').val('');


        $.get("/get/load",
            {cat_id: cat_id, good_id: good_id}
            ,function(data,status){
                var data = $.parseJSON( data );
                if (data.goods){
                    var obj = data.goods;
                    div_parent.find('.good_id').html('<option value="0">Please select</option>');
                    for (var i = 0; i < obj.length; i++) {
                        div_parent.find('.good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                }
                if (data.colors){
                    var obj = data.colors;
                    div_parent.find('.good_color').html('<option value="0">Please select</option>');
                    for (var i = 0; i < obj.length; i++) {
                        div_parent.find('.good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                }

                $('button[type=submit]').prop('disabled', false);
                $('form').unbind('submit');
                _self.nextAll('.loading').remove();
            });
    });
}

var xhr;

    function initSelectProductBVG()
    {
        $(document).off('change', '.good_id_bvg')
        .on('change', '.good_id_bvg', function(e) {
            $('button[type=submit]').prop('disabled', true);
            $('form').bind('submit',function(e){e.preventDefault();});
            var distributor_id    = $('#distributor_id').val();
            var _self = $(this);
            if(!distributor_id)
            {
                _self.val('');
                alert('Please select Warehouse/Retailer!');
            }


            $('.loading').remove();
            $(this).after('<span class="loading"></span>');

            var div_parent = $(this).parent().parent().parent();



            var good_id = div_parent.find('.good_id_bvg').val();
            var joint = div_parent.find('.joint').val();

            div_parent.find('.num_bvg, .price_bvg, .total_bvg').val('');


            $.get("/get/load-joint",
                {joint: joint, good_id: good_id , distributor_id : distributor_id}
                ,function(data,status){

                    var data = $.parseJSON( data );

                    var price = data.price;
                    var num = data.total;
                    var total = data.total_price;

                    if (num > 0){
                        div_parent.find('.price_bvg').val(float_f(price));
                        div_parent.find('.num_bvg').val(float_f(num));
                        div_parent.find('.total_bvg').val(float_f(total));
                        selectBVGIMEI(div_parent);
                        joint_total++;
                    }
                    else
                    {
                        alert('This distributor is don\'t have imei for this joint circular or discounts have been paid!');
                    }

                    $('button[type=submit]').prop('disabled', false);
                    $('form').unbind('submit');
                    _self.nextAll('.loading').remove();
                });
        });
    }

    function initSelectQuantityBVG()
    {
        $(document).off('change', '.num_bvg')
        .on('change', '.num_bvg', function(e) {
            $('button[type=submit]').prop('disabled', true);
            $('form').bind('submit',function(e){e.preventDefault();});
            $('.loading').remove();
            var distributor_id    = $('#distributor_id').val();
            var div_parent = $(this).parent().parent().parent();
            var _self = $(this);
            var num = _self.val();
            var price = floatval(div_parent.find('.price_bvg').val());

            if (distributor_id) {
                console.log(distributor_id);
                var total_price = 0;
                if (price && num)
                    total_price = price * num;
                div_parent.find('.total_bvg').val(float_f(total_price)).change();
                selectBVGIMEI(div_parent);

            }
            else
            {
                _self.val('');
                alert('Please select Warehouse/Retailer!');
            }
        });
    }

    function selectBVGIMEI(div_parent)
    {
        $('button, input, select').prop('disabled', true);
        distributor_id    = $('#distributor_id').val();
        joint  = div_parent.find('.joint').val();
        good_id_bvg = div_parent.find('.good_id_bvg').val();
        num =  div_parent.find('.num_bvg').val();
        var value = '';

        if(!joint && !good_id_bvg)
        {
            alert('Please Choose BVG');
            $('button, input, select').prop('disabled', false);
            return false;
        }

        $('.loading').remove();
        var targetUrl = '<?php echo HOST."bvg/get-imei" ?>';

        //get ajax content

        if (distributor_id && joint && good_id_bvg){
            div_parent.parents('.control-group').append("<span class=\'loading\'></span>");

            $.post(targetUrl, {
                d_id : distributor_id,
                joint_circular_id : joint,
                good_id : good_id_bvg,
                num : num
            }, function(data){
                $('button, input, select').prop('disabled', false);

                if (data){
                    if(data.result == 3)
                    {
                        alert('Number imei you insert is too large, Please contact Technolog Team');
                        $('.loading').remove();
                        div_parent.find('.num_bvg').val(0);
                        div_parent.find('.total_bvg').val(0).change();
                        div_parent.find('.bvg_imei').find('option').remove();
                    }
                     if(data.result == 4)
                    {
                        alert('This distributor don\'t have imei for discount');
                        $('.loading').remove();
                        div_parent.find('.num_bvg').val(0);
                        div_parent.find('.total_bvg').val(0).change();
                        div_parent.find('.bvg_imei').find('option').remove();
                    }

                    if(data.result == 1)
                    {

                          div_parent.find('.bvg_imei option').remove();
                          var obj = data.data;
                          for (var i = 0; i < obj.length; i++) {
                             div_parent.find('.bvg_imei').append('<option value="'+obj[i]['id']+'">'+obj[i]['imei_sn']+'</option>');
                             value += obj[i]['id'] + ',';
                    }
                  }

                }
                $('.loading').remove();
                div_parent.find('.ids_imei').val(value.slice(0,-1));
                div_parent.find('.bvg_imei option').prop('selected', true);
            });
        }
    }

function initSelectQuantity(){
    $(document).off('change', '.num')
    .on('change', '.num', function(e) {
        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit',function(e){e.preventDefault();});
        
        $('.loading').remove();
        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        var num = _self.val();
        var good_id = div_parent.find('.good_id').val();
        var good_color = div_parent.find('.good_color').val();
        var cat_id = div_parent.find('.cat_id').val();
        var id = div_parent.find('.ids').val();
        var warehouse_id = $('#warehouse_id').val();
        var distributor_id = $('#distributor_id').val();
        var type = $('#type').val();
        var sale_off_percent = div_parent.find('.sale_off_percent').val();

        if (distributor_id && warehouse_id) {
            $(this).after('<span class="loading"></span>');
            if(xhr){
                xhr.abort();
            }
            
            xhr = $.get("/get/load-price-stock",
                {num: num, good_id: good_id, is_sales_price: 1, distributor_id: distributor_id, good_color: good_color,
                    cat_id: cat_id, warehouse_id: warehouse_id, type: type, id: id
                }
                ,function(data,status){
                    var price = 0;

                    if (data > 0 && num > 0) price = data/num;

                    div_parent.find('.price').val(float_f(price));

                    var total_price = data;

                    if(data != 'undefined' && type == 2)
                    {
                        div_parent.find('.sale_off_percent').val(0);
                    }

                    else if (data > 0 && sale_off_percent > 0)
                        total_price = data - Math.round(data*sale_off_percent/100);

                    // div_parent.find('.sale_off_percent').prop('disabled',true);
                   // div_parent.find('.total').prop('disabled',true);
                    div_parent.find('.total').val(float_f(total_price)).change();

                    $('button[type=submit]').prop('disabled', false);
                    $('form').unbind('submit');
                    $('.loading').remove();
                });
        } else{
            _self.val('');
            alert('Please select Warehouse/Retailer!');
        }
    });
}


function initSelectPercent(){
    $('.sale_off_percent').live('change',function(e) {
        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        var sale_off_percent = _self.val();
        var price = floatval( div_parent.find('.price').val() );
        var num = div_parent.find('.num').val();

        var total_price = 0;
        if (price > 0 && num > 0){
            total_price = price*num - Math.round(price*num*sale_off_percent/100);
            div_parent.find('.total').val(float_f(total_price)).change();
        }

        /* Nếu chọn nhân viên mua máy (OPPO)*/
        phone_id = floatval( div_parent.find('.good_id').val() );
        var type = $('.type').val();
        var for_partner = $("#for_partner").val();
        if(for_partner === undefined){
            for_partner = 2;
        }

        if(type == <?php echo FOR_STAFFS ?> && for_partner == 2)
        {
            /* kiểm tra giảm giá có hợ lệ ko */
            $.ajax({
    			  url: "/sales/check-sale-phone",
    		      type: "get",
    		      data: {'phone_id':phone_id,'sale_off_percent':sale_off_percent},
    		      success: function(result){
    					if(result == 0)
    					{
                            alert("Không áp dụng giảm giá ở mức này");
                            _self.val('0');
                            sale_off_percent = 0;

                            var price = floatval( div_parent.find('.price').val() );
                            var num = div_parent.find('.num').val();

                            var total_price = 0;
                            if (price > 0 && num > 0){
                                total_price = price*num - Math.round(price*num*sale_off_percent/100);
                                div_parent.find('.total').val(float_f(total_price)).change();
                            }
    					}
                        else{
                            var price = floatval( div_parent.find('.price').val() );
                            var num = div_parent.find('.num').val();

                            var total_price = 0;
                            if (price > 0 && num > 0){
                                total_price = price*num - Math.round(price*num*sale_off_percent/100);
                                div_parent.find('.total').val(float_f(total_price)).change();
                            }
                        }
    		      },
    		      error:function(){
    		    	  alert("Có lỗi 2!!");
    		      }
    		});
            /* end kiểm tra giảm giá có hợ lệ ko */
        }
        else{

            var price = floatval( div_parent.find('.price').val() );
            var num = div_parent.find('.num').val();

            var total_price = 0;
            if (price > 0 && num > 0){
                total_price = price*num - Math.round(price*num*sale_off_percent/100);
                div_parent.find('.total').val(float_f(total_price)).change();
            }
        }

    });
}

function initSelectOrderType(){
    $(document).off('change', '#type')
    .on('change', '#type', function(e) {
        $('.num, .price, .total, .sale_off_percent').val('');
    });
}

function initReset(){
    $(document).off('click', 'button:reset')
    .on('click', 'button:reset', function(e) {
        e.preventDefault();
        $('select, input:text, input.num, input.price').val('');
        $('textarea').text('');

        $(form).find('select').each(function(i, v) {
            $(v).trigger('chosen:updated');
        });
    });
}
</script>