
<script src="<?php echo HOST ?>js/jquery-ui.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>
<script src="<?php echo HOST ?>js/bootstrap-modal.js"></script>
<script src="<?php echo HOST ?>js/bootstrap-modalmanager.js"></script>
<script src="<?php echo HOST ?>js/jquery.blockUI.js"></script>
<script type="text/javascript" src="<?php echo HOST ?>js/sales.po.js"></script>

<script>

$(document).ready(function () {
    initChangeWarehouse();
    initChangeRetailer();
    initGoBack();
    initAddSales();
    //Add nvmm
    initAddNvmm();
    initSelectPaid();
    initSelectTotal();
    initSearchObjectOption();
    
    initAddBVG();
    initRemoveSales();
    initSelectProduct();
    initSelectQuantity();
    initSelectShipmentTypeQuantity();
    initSelectPercent();
    initSelectOrderType();
    initReset();
    initTag();
    initDialog();
    initCheckDemoBeforeSubmit();
    initTooltip();
    initGetSettedRetailer();
    initSearchOptionDistributor('distributor_id', 'SearchBox');
    initSelectJoint();
    initSelectQuantityBVG();
    initSelectProductBVG();
    initAddDiscount();
    initChangeInvoice();
    initConfirmCampaign();
    get_po_list("<?php isset($this->sales) and $this->sales and isset($this->sales[0]['sale']['po_id']) and printf($this->sales[0]['sale']['po_id']);?>", "#distributor_po");
    $('#add_po_btn').click(show_add_po_modal);

    $(document).off('change', '[class*="total"]').on('change', '[class*="total"]', calculate_fee);

    //NHAN VIEN MUA MAY
    addRowNVMM();
    removeRowNVMM();
    initSelectAreaService();
    autoRemarkForStaff();
    changePartner();
    show_shipment_type();

});

 $(document).on('focus',".payment_date", function(){ 
   $(this).datepicker({ dateFormat: "dd/mm/yy" });
});

//Add id nhân viên mua máy
function initAddNvmm(){
    $('.id_for_staff').live('click',function(e) {
        $id_staff = $('.object_id').val();
        var data_name = $('.object_id option:selected').attr('data-name');
        console.log(data_name);
        $name_staff = $( ".object_id option:selected" ).text().replace("Please select", "");
        if($id_staff == '' || $id_staff == 0){
            alert('Vui lòng chọn nhân viên');
        }else{
            var for_staff = $(this).closest('.span12').find('.name_staff');
            var id_staff = $(this).closest('.span12').find('.id_staff');
            for_staff.val($name_staff);
            id_staff.val($id_staff);
            id_staff.attr('data-name',data_name);
        }

    });
}

//thay đổi số tiền thực tế thanh toán 
function initSelectPaid(){
    $('.sotienthucte').live('change', function(e) {
        var _self = $(this);
        paid  = _self.val();
        
        total = $(this).closest('.row').find('.total').val().split('.').join('');
        var so_du = parseInt(paid) - parseInt(total);
        
        $(this).closest('.row').find('.sodu').val(float_f(so_du));
    });
}
//thay đổi giá máy không khớp với giá trên lô => hiện thông báo nếu có chọn lô máy 
function initSelectTotal(){
    $(document).off('change', '.total')
    .on('change', '.total', function(e) {
        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        total  = _self.val().split('.').join('');
        var num = div_parent.find('.num').val();
        var price = div_parent.find('.price').val().split('.').join('');
        var good_id = div_parent.find('.good_id').val();
        var shipment = $('.shipment_id').val();
        
        var price_2 = total/num;
        if(shipment){
            if(price != price_2){
                $(this).after('<span class="loading"></span>');
                $.get("/sales/check-price-shipment",
                {shipment:shipment, good_id:good_id, price: price_2}
                ,function(data){
                    if (data == "false"){
                        alert("Giá khác giá trong lô máy !");
                        $('.loading').remove();
                    }
                    else if(data == "true"){
                        alert("Giá đúng trong lô máy !");
                        $('.loading').remove();
                    }
                });
            }
        }
        
        var sum = 0;
        $('.total').each(function(){
            var totals = parseInt($(this).val().split('.').join(''));
            if(!isNaN(totals)){
                sum += totals;
            }
        });
        
        var paid = $('.paid').val();
        var so_du = parseInt(paid) - parseInt(sum);
        $('.so_du').val(float_f(so_du));
        
    });
}
//reset lại khi chọn lô máy
function initSelectShipment(){
    $(document).off('change', '.shipment_id').on('change', '.shipment_id', function(e) {
        $('.num, .price, .total, .paid, .so_du, .shipment_type').val('');
    });
}

function initSearchObjectOption(){
    var timeout;
    $("#SearchBoxObject").live("keyup", function () {
        var userInput = $("#SearchBoxObject").val();
        window.clearTimeout(timeout);
        timeout = window.setTimeout(function() {
            showOnlyOptionsSimilarToText($(".object_id"), userInput, true, '');
        }, 500);

    });
}

//end NVMM

function initResetRebate(){
    $(document).off('change', 'form .cat_id,form .good_id,form .good_color,form .num,form .price,form .sale_off_percent,form .total')
    .on('change', 'form .cat_id,form .good_id,form .good_color,form .num,form .price,form .sale_off_percent,form .total,form .id_for_staff', function(e) {
        $("#rebate_price").val('');
    });
}

function initConfirmCampaign(){
    $("#dialogcampaign").hide();
    $(".campaign_ck").click(function(e) {
        _self = $(this);
        if(!$(this).is(":checked"))
        {
            $("#dialogcampaign").html('Destroy campaign discount');
            var destroy = true;
        }
        e.preventDefault();
        var div_parent = _self.parent().parent().parent();

        var campaign_val = div_parent.find('.campaign_val');
        $("#dialogcampaign").dialog({
            buttons : {
                "Confirm" : function() {
                   if(!destroy)
                   {
                       var campaign = $('._campaign').val();
                       if(!campaign)
                       {
                           alert('please choose campaign');
                           return false;
                       }
                       _self.prop("checked", !_self.prop("checked"));
                       div_parent.find('.campaign_val').val(campaign);
                       div_parent.find('.total').val(0);

                   }

                    else
                   {
                       _self.prop("checked", false);
                       $('button[type=submit]').prop('disabled', true);
                       $('form').bind('submit',function(e){e.preventDefault();});
                       $.blockUI({ overlayCSS: { backgroundColor: '#009B72' } });
                       var num = div_parent.find('.num').val();
                       var good_id = div_parent.find('.good_id').val();
                       var good_color = div_parent.find('.good_color').val();
                       var cat_id = div_parent.find('.cat_id').val();
                       var id = div_parent.find('.ids').val();
                       var warehouse_id = $('#warehouse_id').val();
                       var distributor_id = $('#distributor_id').val();
                       var type = $('#type').val();
                       div_parent.find('.campaign_val').val('');
                       var sale_off_percent = div_parent.find('.sale_off_percent').val();
                       if (distributor_id && warehouse_id) {
                           if(xhr){
                               xhr.abort();
                           }
                           xhr = $.get("/get/load-price",
                               {
                                   num: num,
                                   good_id: good_id,
                                   is_sales_price: 1,
                                   distributor_id: distributor_id,
                                   good_color: good_color,
                                   cat_id: cat_id,
                                   warehouse_id: warehouse_id,
                                   type: type,
                                   id: id
                               }, function (data, status) {
                                   if (data.indexOf("-3") !== -1) {
                                        var myarr = data.split("|");
                                        alert('The available stock is only ' + myarr[1]);
                                        div_parent.find('.num').val('');
                                        div_parent.find('.sale_off_percent').val(0);
                                        div_parent.find('.total').val(0);
                                   } else {
                                       var price = 0;

                                       if (data > 0 && num > 0) price = data / num;

                                       div_parent.find('.price').val(float_f(price));

                                       var total_price = data;

                                       if (data > 0 && sale_off_percent > 0)
                                           total_price = data - Math.round(data * sale_off_percent / 100);

                                       div_parent.find('.total').val(float_f(total_price)).change();
                                   }

                                   $('button[type=submit]').prop('disabled', false);
                                   setTimeout($.unblockUI, 300);
                                   $('form').unbind('submit');
                                   $('.loading').remove();
                               });

                           _self.prop('checked', false);

                       }
                       else
                       {
                           alert('Please select Warehouse/Retailer!');
                           return;
                       }
                   }

                    $(this).dialog("close");
                    return true;
                },
                "Cancel" : function() {
                    $(this).dialog("close");
                }
            }
        });

        $("#dialogcampaign").dialog("open");
    });
}

function initRebate(){
    var timeout1;
    $("#btn-calculate").on("click", function () {
        window.clearTimeout(timeout1);
        timeout1 = window.setTimeout(function() {
            calculateRebatePrice();
        }, 500);

    });
}

function calculateRebatePrice(){
    var total_price = 0;
    var rebate_price = $("#rebate_price").val();

    if (rebate_price == '')
        return;

    $('button[type=submit]').prop('disabled', true);
    $('form').bind('submit',function(e){e.preventDefault();});

    $('form .total').each(function(){
        var div_parent = $(this).parent().parent().parent();
        if (div_parent.find('.cat_id').val() == '<?php echo PHONE_CAT_ID;?>') {
            if ($(this).val() == ''){
                alert('Please choose Total price');
                $("#rebate_price").val('');
                return;
            }
            total_price += Math.round( $(this).val() );
        }
    });

    if ( total_price > 0 ){
        var $rebate_percent = rebate_price/total_price;

        $('form .total').each(function(){
            var div_parent = $(this).parent().parent().parent();
            if (div_parent.find('.cat_id').val() == '<?php echo PHONE_CAT_ID;?>') {
                $v = $(this).val();
                if ($v > 0){
                    var $re = $v - Math.round($v * $rebate_percent);
                    $(this).val($re);
                }
            }
        });

    } else {
        alert('Please choose Total price');
        $("#rebate_price").val('');
    }

    $('button[type=submit]').prop('disabled', false);
    $('form').unbind('submit');
    return;
}

function initSearchOption(){
    var timeout;
    $("#SearchBox").on("keyup", function () {
        var userInput = $("#SearchBox").val();
        window.clearTimeout(timeout);
        timeout = window.setTimeout(function() {
            showOnlyOptionsSimilarToText($("#distributor_id"), userInput, true, 'initChangeRetailer');
        }, 500);

    });
}

function initDialog(){
    $("#dialog").dialog({
        autoOpen: false,
        modal: true
    });
}

function initCheckDemoBeforeSubmit(){
    $('#submit_btn').on('click',function(event){
        initCheckGoodDemo();
        add_product_color_key_nvmm();
    });
}

function initTooltip(){
    $('.tooltip-r').tooltip({
        placement: 'right',
        html: true,
        title: $('#tooltip_type').html()
    });
}

function initTag(){

    $('#myTags').tagit({
        allowSpaces: true,
        fieldName: 'tags[]',
        autocomplete: {
            delay: 0,
            minLength: 2,
            source: "<?php echo HOST;?>get/get-tags"
        }
    });

}

function initChangeRetailer(){//change retailer

    $('.distributor-info').hide();
    $(document).off('change', '#distributor_id')
    .on('change', '#distributor_id', function(e) {
        getRetailerInfo($(this));
    });

    initViewMore();
}

function initChangeWarehouse(){//change warehouse

    $('#warehouse_id').live('change', function(e) {
        $('#form .num,#form .sale_off_percent,#form .total,#form .price').val('');
    });

    $('#form .good_id, #form .good_color').live('change', function(e) {
        var div_parent = $(this).parent().parent().parent();
        div_parent.find('.price').val('');
        div_parent.find('.total').val('');
        div_parent.find('.num').val('');
        div_parent.find('.sale_off_percent').val('');
    });

}

function initAddMethodPayment()
{
    var old_div = $('.div-payment');
    var new_div = old_div.clone();
    new_div.removeClass('.div-payment').find('select').removeAttr('disabled');
    new_div.attr('id', 'payment');
    new_div.insertAfter($('.distributor-info').parent().parent()).show();
}

function initChangeInvoice()
{
    if($('#invoice_type').val() == 1)
    {
        $('.invoice_div').show();
        $('.invoice_div').find('select, input, textarea').removeAttr('disabled');
    }
    else
    {
        $('.invoice_div').hide();
        $('.invoice_div').find('select, input, textarea').prop('disabled', true);
    }

    $(document).off('change', '#invoice')
    .on('change', '#invoice', function(e) {
        initChangeInvoice();
    });
}

function initGetSettedRetailer(){
    var d_id = $('#distributor_id').val();

    if(d_id){
        getRetailerInfo($('#distributor_id'));
    }
}

function initViewMore(){
    $(document).off('click', '.view-more')
    .on('click', '.view-more', function(e) {
        $('.distributor-info .info ').toggle();
        var text = $(this).text();
        if(text == '+'){
            $(this).text('-');
        }else{
            $(this).text('+');
        }
    });
}

function getRetailerInfo(_this){
    var id = _this.val();

        if(id == <?php echo OPPO_SERVICE_CLUB ?>)
        {
            alert('Bạn đã chọn đơn hàng cho Service Club, bạn vui lòng chọn trung tâm bảo hành');

            var old_div = $('.div-service');

            var new_div = old_div.clone();

            new_div.removeClass('div-service').find('select, input, textarea').removeAttr('disabled');

            new_div.attr('id', 'service_id');

            new_div.insertAfter($('.distributor-info').parent().parent()).show();

            return false;
        }
        else
        {
            $('#service_id').remove();
        }
        ///// don hang cho nhan vien muon //////
        if(id == <?php echo OPPO_BORROW ?> )
        {
            alert('Bạn đã chọn đơn hàng mượn, Hệ thống sẽ ghi nhận trường hợp này');

            return false;
        }

        ///// don hang cho nhan vien mua may //////

        if(id == <?php echo OPPO_STAFF ?> || id == <?php echo OPPO_KVL ?>)
        {

            $('#invoice').remove();
            alert('Bạn đã chọn đơn hàng bán máy cho nhân viên , KVL , Vui lòng chọn chính xác có lấy hóa đơn hay không?');
            var old_div = $('.div-invoice');
            var new_div = old_div.clone();

            new_div.removeClass('div-invoice').find('select, input, textarea').removeAttr('disabled');
            new_div.attr('id', 'invoice');
            new_div.insertAfter($('.distributor-info').parent().parent()).show();

            initChangeInvoice();
            $(".object_id :selected").focus();

            if(id == <?php echo OPPO_STAFF ?>){
                var for_partner = "<?php  echo isset($this->for_partner) ? intval($this->for_partner) : 0;?>";
                $('.wrap_for_partner').show();
                $('#form .wrap_list_staff').show();
                $('.btn_add_row_nvmm').show();
                $('.info_nvmm').show();
                $('.info_ingame').hide();
                $('#div-number-sales').remove();
                var old_div = $('.div-number-sales');
                var new_div = old_div.clone();
                new_div.attr('id', 'div-number-sales');
                new_div.insertAfter($('#form .wrap_list_staff')).show();

            }else{
                $('.wrap_for_partner').hide();
                ResetNvmm();
            }
            return false;
        }
        
        ///// don hang cho nhan vien ingame //////
        if(id == <?php echo OPPO_INGAME ?>)
        {
            $('.wrap_for_partner').show();
            $('#invoice').remove();

            alert('Bạn đã chọn đơn hàng bán máy cho nhân viên , KVL , Vui lòng chọn chính xác có lấy hóa đơn hay không?');
            var old_div = $('.div-invoice');
            var new_div = old_div.clone();
            new_div.removeClass('div-invoice').find('select, input, textarea').removeAttr('disabled');
            new_div.attr('id', 'invoice');
            new_div.insertAfter($('.distributor-info').parent().parent()).show();
            initChangeInvoice();
            $(".object_id :selected").focus();


            $('#form .wrap_list_staff').hide();
            $('.btn_add_row_nvmm').show();
            $('.info_nvmm').hide();

            $('#form .info_ingame').show();
            $('.info_ingame').show();

            $('#div-number-sales').remove();
            var old_div = $('.div-number-sales');
            var new_div = old_div.clone();
            new_div.attr('id', 'div-number-sales');
            new_div.insertAfter($('#form .wrap_list_staff')).show();
            return false;
        }
        
        else
        {
            $('#invoice').remove();
            $('#div-number-sales').remove();
            $('#div-shipment').remove();
            $('#div-outsite').remove();
        }

        ///// don hang tặng cho nhân viên /////

        if(id == <?php echo OPPO_GIFT ?> || id == <?php echo OPPO_SUPER_DAY?>)
        {
            if(id == <?php echo OPPO_GIFT?>)
                   alert('Bạn đã chọn đơn hàng tặng cho nhân viên');
                   else
                    alert('Bạn đã chọn đơn hàng SUPER DAY , vui lòng chọn khu vực tương ứng');

            var old_div = $('.div-gift');

            var new_div = old_div.clone();

            new_div.removeClass('div-gift').find('select').removeAttr('disabled');

            new_div.attr('id', 'gift');

            new_div.insertAfter($('.distributor-info').parent().parent()).show();

            initChangeInvoice();

            return false;
        }
        else
        {
            $('#gift').remove();
        }

         if(id == <?php echo OPPO_DEMO ?> || id == <?php echo OPPO_EVENT ?>)
         {
            alert('Bạn đã chọn đơn hàng phụ kiện, vui lòng chọn khu vực');

            var old_div = $('.div-gift');

            var new_div = old_div.clone();

            new_div.removeClass('div-gift').find('select').removeAttr('disabled');

            new_div.attr('id', 'gift');

            new_div.insertAfter($('.distributor-info').parent().parent()).show();

            initChangeInvoice();

            return false;
        }
        else
        {
            $('#gift').remove();
        }


    if(id == ''){
        $('.distributor-info').slideUp();
    }else{
        $.ajax({
            type: 'get',
            url : '/checkmoney/getbalance',
            data: {'id':id},
            success: function(data){
                if(data.status != 0){
                    $('.distributor-info .add span').html(data.result.add);
                } else {
                    $('.distributor-info .add span').html('');
                }
            }
        });

        $.ajax({
            type: 'get',
            url : '/get/count-discount',
            data: {'id':id},
            success: function(data){
                if(data){
                    $('.discount span').html(parseInt(data).formatMoney(0,'.',','));
                } else {
                    $('.distributor-info .add span').html('');
                }
            }
        });

        $.ajax({
            type: 'get',
            url : '/get/count-good-demo',
            data: {'d_id':id},
            success: function(data){
                if(data.status != 0){
                    if (data.result){
                        //quantity dealer
                        $('.distributor-info .qty_dealer span').html(data.qty_dealer);
                        $('.distributor-info .product_demo table').html("");
                        var title = '<tr><td>Product name</td><td>Quantity</td></tr>';
                        $('.distributor-info .product_demo table').append(title);
                        $.each(data.result,function(index,value){
                            var td = '<td>'+this.name+'</td>';
                                td += '<td>'+this.total+'</td>';
                            var tr = $("<tr>").append(td);
                            $('.distributor-info .product_demo table').append(tr);
                        });
                    } else {
                        $('.distributor-info .qty_dealer span').html('');
                        $('.distributor-info .product_demo table').html("");
                    }

                    if (typeof data.incentive !== "undefined") {
                        $('.distributor-info .incentive span').text(data.incentive);
                    } else {
                        $('.distributor-info .incentive span').text('');
                    }


                    if (typeof (data.d_parent) !== "undefined" &&  data.d_parent) {
                        //$('.distributor-info .incentive span').text(data.d_parent);
                        alert('Vui lòng chọn loại thanh toán');
                        initAddMethodPayment();
                    } else {
                       // $('.distributor-info .incentive span').text('');
                    }
                }
            }
        });
        $('.distributor-info').slideDown();
        var chBtn = $('.view-more').text();
        if(chBtn == '-'){
            $('.view-more').trigger('click');
        }

    }



    calculate_fee();

    //get_po_list(id, "#distributor_po");
}

Array.prototype.contains = function (v) {
    return this.indexOf(v) > -1;
}

var array_ka = [ <?php echo KA_TGDD ?>, <?php echo KA_VTA ?> , <?php echo KA_FPT; ?> ];

function check_gift(elm) {

    if (!$('#form')[0].checkValidity()) {
        $('#form').find(':submit').click();
        return;
    }

    $('button, input, select').prop('disabled', true);
    $('#form').unbind('submit');

    good_list = [];
    $('[name="good_id[]"]:visible').each(function(index, elm) {
        good_list.push($(elm).val());
    });

    $.ajax({
        url: '<?php echo HOST ?>get/check-gift',
        dataType: 'json',
        data: {good_list: good_list},
    })
    .done(function(result) {
        $('button, input, select').prop('disabled', false);
        $('#form').bind('submit');

        if (typeof result.code != "undefined" && result.code != 1) {
            $('#dialog').html(result.error);

            $("#dialog").dialog({
                buttons : {
                    "Choose Gifts" : function() {
                        $(this).dialog("close");
                        return false;
                    },
                    "Ignore" : function() {
                        $('#form').submit();
                    }
                }
            });

            $("#dialog").dialog("open");
        } else {
            $('#form').submit();
        }

    })
    .fail(function(result) {
        console.log(result.error);
    })
    .always(function() {
        console.log("complete");
    });

}

function initGoBack(){
    $(document).off('click', '.go-back')
    .on('click', '.go-back', function(e) {
        window.location.href = $('#back_url').val();
        return false;
    });
}

function initRemoveSales(){
    $(document).off('click', '.remove-sales')
    .on('click', '.remove-sales', function(e) {
        $(this).parent().parent().parent().remove();
        calculate_fee();
        return false;
    });
}

function initAddSales(){
    $(document).off('click', '.add-sales')
    .on('click', '.add-sales', function(e) {
        var old_div = $('.div-add');
        var new_div = old_div.clone();

        new_div.removeClass('div-add').find('select, input, textarea').removeAttr('disabled');

        new_div.insertBefore($(this).parents('.row')).show();

        $(document).off('change', '[class*="total"]').on('change', '[class*="total"]', calculate_fee);
        initSelectProduct();
        initSelectQuantity();
        initSelectPercent();
        initRemoveSales();
        initConfirmCampaign();
        // initResetRebate();

        return false;
    });
}

// function add bvg
function initAddBVG(){
    $('.add-bvg').click(function(e){
        var old_div = $('.div-bvg');
        var new_div = old_div.clone();
        var distributor_id = $('#distributor_id').val();
        new_div.removeClass('div-bvg').find('select, input, textarea').removeAttr('disabled');
        $('from .joint').each(function(i, obj) {
           if($('.joint').val())
           {
               joint_total++;
           }
        });
        $.get("/get/load-joint",
            {distributor_id : distributor_id , init_params : 1}
            ,function(data,status){
                var data = $.parseJSON( data );

                if (data){
                    var obj = data;


                    new_div.find('.joint').html('<option value="0">Please select</option>');
                    for (var i = 0; i < obj.length; i++) {

                        if(i <= joint_total)
                        {
                            new_div.find('.joint').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                        else
                            new_div.find('.joint').append('<option disabled value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                }

                else
                {
                    alert(data.error);
                }


                $('button[type=submit]').prop('disabled', false);
                $('form').unbind('submit');
            });

        new_div.insertBefore($(this).parent().parent().parent()).show();
        $(document).off('change', '[class*="total"]')
            .on('change', '[class*="total"]', calculate_fee);


        initSelectJoint();
        initSelectQuantityBVG();
        initRemoveSales();
        initSelectProductBVG();
        return false;
    });
}

function initAddDiscount(){
    $('#btn-discount').click(function(e){
        var old_div = $('.div-discount');
        var new_div = old_div.clone();
        new_div.removeClass('div-discount').find('select, input, textarea').removeAttr('disabled');
        new_div.insertBefore($(this).parent().parent().parent()).show();

        var distributor_id = $('#distributor_id').val();

        if(!distributor_id)
        {
            alert('Please insert Distributor');
            return false;
        }

        $.get("/get/load-joint",
            {distributor_id : distributor_id , init_params : 2}
            ,function(data,status){
                var data = $.parseJSON( data );

                if (data){
                    var obj = data

                    console.log(obj);


                    new_div.find('.joint_discount').html('<option value="0">Please select</option>');
                    for (var i = 0; i < obj.length; i++) {
                            new_div.find('.joint_discount').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                }

                else
                {
                    alert(data.error);
                }


                $('button[type=submit]').prop('disabled', false);
                $('form').unbind('submit');
            });




        initSelectQuantityBVG();
        initRemoveSales();
        initSelectProductBVG();
        selectJointDiscount();
        return false;
    });
}

var joint_total = 0;
var joint_discount_total = 0;


function resetJoint()
{
    if($('.joint').val())
         $('.joint').parent().parent().remove();
}

function selectJointDiscount()
{
    $(document).off('change', '.joint_discount')
        .on('change', '.joint_discount', function() {

            $('button[type=submit]').prop('disabled', true);
            $('form').bind('submit',function(e){e.preventDefault();});
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var distributor_id = $('#distributor_id').val();
            var joint = $(this).val();
            var _selft = $(this);
            var parent =  _selft.parent().parent();

            if(!distributor_id)
            {
                alert('Please select Joint Circular');
                return;
            }

            $.get("/get/load-jointprice",
                {joint: joint, d_id: distributor_id}
                ,function(data,status){
                    var data = $.parseJSON( data );

                    if (data.code == 1){
                        parent.find('.price_discount').val(data.price);
                        parent.find('.price_discount').attr('readonly', true);
                    }

                    if(data.code == -2)
                    {
                        alert(data.error)
                    }

                    $('button[type=submit]').prop('disabled', false);
                    $('form').unbind('submit');
                    $('.loading').remove();
                });

        });
    }

function initSelectJoint()
{
    var distributor_id = $('#distributor_id').val();
     $(document).off('change', '.joint')
    .on('change', '.joint', function() {
        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit',function(e){e.preventDefault();});
        $('.loading').remove();
        $(this).after('<span class="loading"></span>');
        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        var joint = div_parent.find('.joint').val();

        if (_self.hasClass('joint'))
            div_parent.find('.good_id').find('option:not(:first)').remove();

        var good_id = div_parent.find('.good_id').val();

        div_parent.find('.good_color').find('option:not(:first)').remove();

        div_parent.find('.num, .price, .total').val('');


        $.get("/get/load-joint",
            {joint: joint, good_id: good_id , distributor_id : distributor_id}
            ,function(data,status){
                var data = $.parseJSON( data );
                if (data.goods){
                    var obj = data.goods;
                    div_parent.find('.good_id_bvg').html('<option value="0">Please select</option>');
                    for (var i = 0; i < obj.length; i++) {
                        div_parent.find('.good_id_bvg').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }



                }



                $('button[type=submit]').prop('disabled', false);
                $('form').unbind('submit');
                _self.nextAll('.loading').remove();
            });
    });
}

function initSelectProduct(){
    $(document).off('change', '.cat_id, .good_id')
    .on('change', '.cat_id, .good_id', function(e) {
        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit',function(e){e.preventDefault();});

        $('.loading').remove();
        $(this).after('<span class="loading"></span>');
        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        var cat_id = div_parent.find('.cat_id').val();

        if (_self.hasClass('cat_id'))
            div_parent.find('.good_id').find('option:not(:first)').remove();

        var good_id = div_parent.find('.good_id').val();

        div_parent.find('.good_color').find('option:not(:first)').remove();

        div_parent.find('.num, .price, .total').val('');


        $.get("/get/load",
            {cat_id: cat_id, good_id: good_id}
            ,function(data,status){
                var data = $.parseJSON( data );
                if (data.goods){
                    var obj = data.goods;
                    div_parent.find('.good_id').html('<option value="0">Please select</option>');
                    for (var i = 0; i < obj.length; i++) {
                        div_parent.find('.good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                }
                if (data.colors){
                    var obj = data.colors;
                    div_parent.find('.good_color').html('<option value="0">Please select</option>');
                    for (var i = 0; i < obj.length; i++) {
                        div_parent.find('.good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                }

                $('button[type=submit]').prop('disabled', false);
                $('form').unbind('submit');
                _self.nextAll('.loading').remove();
            });
    });
}

var xhr;

    function initSelectProductBVG()
    {
        $(document).off('change', '.good_id_bvg')
        .on('change', '.good_id_bvg', function(e) {
            $('button[type=submit]').prop('disabled', true);
            $('form').bind('submit',function(e){e.preventDefault();});
            var distributor_id    = $('#distributor_id').val();
            var _self = $(this);
            if(!distributor_id)
            {
                _self.val('');
                alert('Please select Warehouse/Retailer!');
            }


            $('.loading').remove();
            $(this).after('<span class="loading"></span>');

            var div_parent = $(this).parent().parent().parent();



            var good_id = div_parent.find('.good_id_bvg').val();
            var joint = div_parent.find('.joint').val();

            div_parent.find('.num_bvg, .price_bvg, .total_bvg').val('');


            $.get("/get/load-joint",
                {joint: joint, good_id: good_id , distributor_id : distributor_id}
                ,function(data,status){

                    var data = $.parseJSON( data );

                    var price = data.price;
                    var num = data.total;
                    var total = data.total_price;

                    if (num > 0){
                        div_parent.find('.price_bvg').val(float_f(price));
                        div_parent.find('.num_bvg').val(float_f(num));
                        div_parent.find('.total_bvg').val(float_f(total));
                        selectBVGIMEI(div_parent);
                        joint_total++;
                    }
                    else
                    {
                        alert('This distributor is don\'t have imei for this joint circular or discounts have been paid!');
                    }

                    $('button[type=submit]').prop('disabled', false);
                    $('form').unbind('submit');
                    _self.nextAll('.loading').remove();
                });
        });
    }

    function initSelectQuantityBVG()
    {
        $(document).off('change', '.num_bvg')
        .on('change', '.num_bvg', function(e) {
            $('button[type=submit]').prop('disabled', true);
            $('form').bind('submit',function(e){e.preventDefault();});
            $('.loading').remove();
            var distributor_id    = $('#distributor_id').val();
            var div_parent = $(this).parent().parent().parent();
            var _self = $(this);
            var num = _self.val();
            var price = floatval(div_parent.find('.price_bvg').val());

            if (distributor_id) {
                console.log(distributor_id);
                var total_price = 0;
                if (price && num)
                    total_price = price * num;
                div_parent.find('.total_bvg').val(float_f(total_price)).change();
                selectBVGIMEI(div_parent);

            }
            else
            {
                _self.val('');
                alert('Please select Warehouse/Retailer!');
            }
        });
    }

    function selectBVGIMEI(div_parent)
    {
        $('button, input, select').prop('disabled', true);
        distributor_id    = $('#distributor_id').val();
        joint  = div_parent.find('.joint').val();
        good_id_bvg = div_parent.find('.good_id_bvg').val();
        num =  div_parent.find('.num_bvg').val();
        var value = '';

        if(!joint && !good_id_bvg)
        {
            alert('Please Choose BVG');
            $('button, input, select').prop('disabled', false);
            return false;
        }

        $('.loading').remove();
        var targetUrl = '<?php echo HOST."bvg/get-imei" ?>';

        //get ajax content

        if (distributor_id && joint && good_id_bvg){
            div_parent.parents('.control-group').append("<span class=\'loading\'></span>");

            $.post(targetUrl, {
                d_id : distributor_id,
                joint_circular_id : joint,
                good_id : good_id_bvg,
                num : num
            }, function(data){
                $('button, input, select').prop('disabled', false);

                if (data){
                    if(data.result == 3)
                    {
                        alert('Number imei you insert is too large, Please contact Technolog Team');
                        $('.loading').remove();
                        div_parent.find('.num_bvg').val(0);
                        div_parent.find('.total_bvg').val(0).change();
                        div_parent.find('.bvg_imei').find('option').remove();
                    }
                     if(data.result == 4)
                    {
                        alert('This distributor don\'t have imei for discount');
                        $('.loading').remove();
                        div_parent.find('.num_bvg').val(0);
                        div_parent.find('.total_bvg').val(0).change();
                        div_parent.find('.bvg_imei').find('option').remove();
                    }

                    if(data.result == 1)
                    {

                          div_parent.find('.bvg_imei option').remove();
                          var obj = data.data;
                          for (var i = 0; i < obj.length; i++) {
                             div_parent.find('.bvg_imei').append('<option value="'+obj[i]['id']+'">'+obj[i]['imei_sn']+'</option>');
                             value += obj[i]['id'] + ',';
                    }
                  }

                }
                $('.loading').remove();
                div_parent.find('.ids_imei').val(value.slice(0,-1));
                div_parent.find('.bvg_imei option').prop('selected', true);
            });
        }
    }

function initSelectQuantity(){
    $(document).off('change', '.num')
    .on('change', '.num', function(e) {
        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit',function(e){e.preventDefault();});

        $('.loading').remove();
        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        var num = _self.val();
        var good_id = div_parent.find('.good_id').val();
        var good_color = div_parent.find('.good_color').val();
        var cat_id = div_parent.find('.cat_id').val();
        var id = div_parent.find('.ids').val();
        var warehouse_id = $('#warehouse_id').val();
        var distributor_id = $('#distributor_id').val();
        var type = $('#type').val();

        //NVMM LO MAY THANH LY
        var id_shipment = $('.shipment_id').val();
        var type_shipment = div_parent.find('.shipment_type').val();

        
        if (type==2){ //for demo
            //set default sale off to 50%
            div_parent.find('.sale_off_percent').val('50');
        }
        var sale_off_percent = div_parent.find('.sale_off_percent').val();

        if (distributor_id && warehouse_id) {
            $(this).after('<span class="loading"></span>');
            if(xhr){
                xhr.abort();
            }
            xhr = $.get("/get/load-price",
                {num: num, good_id: good_id, is_sales_price: 1, distributor_id: distributor_id, good_color: good_color,
                    cat_id: cat_id, warehouse_id: warehouse_id, type: type, id: id, id_shipment: id_shipment,
                    type_shipment: type_shipment}
                ,function(data,status){
                    if (data.indexOf("-3") !== -1){
                        var myarr = data.split("|");
                        alert('The available stock is only '+myarr[1]);
                        div_parent.find('.num').val('');
                        div_parent.find('.sale_off_percent').val(0);
                        div_parent.find('.total').val(0);
                    } else {
                        var price = 0;

                        if (data > 0 && num > 0) price = data/num;

                        div_parent.find('.price').val(Math.round(price*100)/100);

                        var total_price = data;

                        if (data > 0 && sale_off_percent > 0)
                            total_price = data - Math.round((data*sale_off_percent/100)*100)/100;

                        div_parent.find('.total').val(Math.round(total_price*100)/100).change();
                    }

                    $('button[type=submit]').prop('disabled', false);
                    $('form').unbind('submit');
                    $('.loading').remove();
                });
        } else{
            _self.val('');
            alert('Please select Warehouse/Retailer!');
        }
    });
}

function initSelectShipmentTypeQuantity(){
    $(document).off('change', '.shipment_type')
    .on('change', '.shipment_type', function(e) {
        $('button[type=submit]').prop('disabled', true);
        $('form').bind('submit',function(e){e.preventDefault();});

        $('.loading').remove();
        var div_parent     = $(this).parent().parent().parent();
        var _self          = $(this);
        var type_shipment  = _self.val();
        var good_id        = div_parent.find('.good_id').val();
        var good_color     = div_parent.find('.good_color').val();
        var cat_id         = div_parent.find('.cat_id').val();
        var id             = div_parent.find('.ids').val();
        var warehouse_id   = $('#warehouse_id').val();
        var distributor_id = $('#distributor_id').val();
        var type           = $('#type').val();
        //NVMM LO MAY THANH LY
        var id_shipment = $('.shipment_id').val();
        var num = div_parent.find('.num').val();
        
        if (type==2){ //for demo
            //set default sale off to 50%
            div_parent.find('.sale_off_percent').val('50');
        }
        var sale_off_percent = div_parent.find('.sale_off_percent').val();

        if (distributor_id && warehouse_id) {
            $(this).after('<span class="loading"></span>');
            if(xhr){
                xhr.abort();
            }
            xhr = $.get("/get/load-price",
                {num: num, good_id: good_id, is_sales_price: 1, distributor_id: distributor_id, good_color: good_color, cat_id: cat_id, warehouse_id: warehouse_id, type: type, id: id, id_shipment: id_shipment, type_shipment: type_shipment}
                ,function(data,status){
                    if (data.indexOf("-3") !== -1){
                        var myarr = data.split("|");
                        alert('The available stock is only '+myarr[1]);
                        div_parent.find('.num').val('');
                        div_parent.find('.sale_off_percent').val(0);
                        div_parent.find('.total').val(0);
                    } else {
                        var price = 0;

                        if (data > 0 && num > 0) price = data/num;

                        div_parent.find('.price').val(Math.round(price*100)/100);

                        var total_price = data;

                        if (data > 0 && sale_off_percent > 0)
                            total_price = data - Math.round((data*sale_off_percent/100)*100)/100;

                        div_parent.find('.total').val(Math.round(total_price*100)/100).change();
                    }

                    $('button[type=submit]').prop('disabled', false);
                    $('form').unbind('submit');
                    $('.loading').remove();
                });
        } else{
            _self.val('');
            alert('Please select Warehouse/Retailer!');
        }
    });
}

function initSelectPercent(){
    $('.sale_off_percent').live('change',function(e) {
        var div_parent = $(this).parent().parent().parent();
        var _self = $(this);
        var sale_off_percent = _self.val();
        var price = floatval( div_parent.find('.price').val() );
        var num = div_parent.find('.num').val();
        
        var total_price = 0;
        if (price > 0 && num > 0){
            total_price = price*num - Math.round(price*num*sale_off_percent/100);
            div_parent.find('.total').val(float_f(total_price)).change();
        }
        
        /* Nếu chọn nhân viên mua máy (OPPO)*/
        phone_id = floatval( div_parent.find('.good_id').val() );
        var type = $('.type').val();
        var for_partner = $("#for_partner").val();
        if(for_partner === undefined){
            for_partner = 2;
        }

        if(type == <?php echo FOR_STAFFS ?> && for_partner == 2)
        {
            /* kiểm tra giảm giá có hợ lệ ko */
            $.ajax({
    			  url: "/sales/check-sale-phone",
    		      type: "get",
    		      data: {'phone_id':phone_id,'sale_off_percent':sale_off_percent},
    		      success: function(result){
    					if(result == 0)
    					{
                            alert("Không áp dụng giảm giá ở mức này");
                            _self.val('0');
                            sale_off_percent = 0;
                            
                            var price = floatval( div_parent.find('.price').val() );
                            var num = div_parent.find('.num').val();
                    
                            var total_price = 0;
                            if (price > 0 && num > 0){
                                total_price = price*num - Math.round(price*num*sale_off_percent/100);
                                div_parent.find('.total').val(float_f(total_price)).change();
                            }
    					}
                        else{
                            var price = floatval( div_parent.find('.price').val() );
                            var num = div_parent.find('.num').val();
                    
                            var total_price = 0;
                            if (price > 0 && num > 0){
                                total_price = price*num - Math.round(price*num*sale_off_percent/100);
                                div_parent.find('.total').val(float_f(total_price)).change();
                            }
                        }			
    		      },
    		      error:function(){
    		    	  alert("Có lỗi 2!!");
    		      }
    		});
            /* end kiểm tra giảm giá có hợ lệ ko */
        }
        else{
            
            var price = floatval( div_parent.find('.price').val() );
            var num = div_parent.find('.num').val();
    
            var total_price = 0;
            if (price > 0 && num > 0){
                total_price = price*num - Math.round(price*num*sale_off_percent/100);
                div_parent.find('.total').val(float_f(total_price)).change();
            }
        } 
        
    });
}

function initSelectOrderType(){
    $(document).off('change', '#type')
    .on('change', '#type', function(e) {
        $('.num, .price, .total, .sale_off_percent').val('');
    });
}

function initReset(){
    $(document).off('click', 'button:reset')
    .on('click', 'button:reset', function(e) {
        e.preventDefault();
        $('select, input:text, input.num, input.price').val('');
        $('textarea').text('');

        $(form).find('select').each(function(i, v) {
            $(v).trigger('chosen:updated');
        });
    });
}

function initCheckGoodDemo(){//when submit

	var type 		= $("#form #type").val(); //get current type
	var type_demo 	= "<?php echo FOR_DEMO;?>";
	var good_id 	= $('[name="good_id[]"]:visible');
	var num 		= $('[name="num[]"]:visible');
	var arr_good 	= [];
	var arr_num 	= [];
	var d_id 		= $("#distributor_id").val();

	$('#dialog').html('');//reset

	//check For order?
	if( type == type_demo ){

		good_id.each(function(index,elem){
			arr_good.push($(elem).val());
		});

		num.each(function(index,elem){
			arr_num.push($(elem).val());
		});

		$.ajax({
			type: 'post',
			url: '/get/check-good-demo',
			data: {'good_id':arr_good,'num':arr_num,'d_id':d_id},
			error: function(){
				alert('check demo error');
			},
			success: function(data){
				if(data.status == false)
				{
					alert('get data check demo fail!');
				}else{
					var $table = $('<table>',{class:'table'});
					var tr = '';
					var msg = '<div colspan=3 style="color: red">*This retailer has ordered above demo products, please confirm customer!</div>';
					$table.append(
						+'<thead>'
							+'<tr>'
								+'<td>Product</td>'
								+'<td>Avaiable</td>'
								+'<td>Over</td>'
							+'</tr>'
						+'</thead>'
					);

					if(data.result.length){

						$.each(data.result,function(index){
							tr += '<tr>'
								+'<td>'+this.name+'</td>'
								+'<td>'+this.avaiable+'</td>'
								+'<td>'+this.over+'</td>'
								+'</tr>';
						});

						$table.append(tr);
						$('#dialog').append(msg);
						$('#dialog').append($table[0]);

						$('#dialog').dialog({
							buttons:{
								'Close':function(){
									$(this).dialog('close');
								},
								'Ignore': function(){
									check_gift();
									$(this).dialog('close');
								}
							}
						});
						$("#dialog").dialog("open");

					}else{
                        check_gift();
					}
				}
			}//End success
		});//End ajax
	}else{
		check_gift();
	}

}

function addRowNVMM(){
    $('.add_row_nvmm').live('click',function(){
        var _self = $(this);
        var d_id = $("#distributor_id").val();
        var nvmm =  '';
        if( d_id == <?php echo OPPO_STAFF;?> ){
            nvmm = $('.wrap_nvmm .info_nvmm');
        }else if(d_id == <?php echo OPPO_INGAME;?>) {
            nvmm = $('.wrap_nvmm .info_ingame');
        }

        var div_add_row = _self.parent().parent().parent();
        $(div_add_row).append(nvmm.clone());

    });
}

function removeRowNVMM(){
    $('#form .remove_nvmm').live('click',function(){
        console.log('cái nồi');
        $(this).parent().parent().remove();
    });
}

function add_product_color_key_nvmm(){
    $("#form .good_id").each(function(index,value){
        var row = $(this).closest('.row');
        var good_id = $(row).find('.good_id').val();
        var good_color = $(row).find('.good_color').val();
        var key = good_id+'_'+good_color;
        $(row).find('.product_color_key').val(key);
        console.log(key);
    });
}

//Khi chọn select area hoặc service center
function initSelectAreaService(){
    $('.addr_nvmm').each(function(i,v){
        var current = $(this).val();
        if(current != ''){
            $(".addr_nvmm").not(this).attr('required',false);
        }
    });

    $('.addr_nvmm').live('change',function(){
        $(".addr_nvmm").attr('required',true);
        var current = $(this).val();
        $(".addr_nvmm").not(this).val("");
        if(current == '' || current == 0){
            $(".addr_nvmm").attr('required',true);
        }else{
            $(".addr_nvmm").not(this).attr('required',false);
        }
    })
}

// tao remark tu dong cho nvmm
function autoRemarkForStaff(){
    $("#btn_auto_remark").live('click',function(){
        var d_id = $("#distributor_id").val();
        $("#form .good_id").each(function(index,value){
            var row = $(this).closest('.row');
            var shipment_id = $('.shipment_id').val();
            var good_id = $(row).find('.good_id').val();
            var good_color = $(row).find('.good_color').val();
            var cat_id = $(row).find('.cat_id').val();
            var type = $(row).find('.sale_off_percent option:selected').text();
            var all_staff = $(row).find('.id_staff');
            var all_num = $(row).find('.staff_num');
            var all_ingame = $(row).find('.name_staff_ingame');
            var all_ingame_cmndd = $(row).find('.cmnd_staff_ingame');
            var shipment_type = $(row).find('.shipment_type');
            var remark = '';

            remark = 'Lô máy giảm giá ' + type + ': ';
            var str_cat = ' máy cho ';
            if(shipment_id === undefined){
                shipment_id = '';
            }

            if(shipment_id != ''){
                remark = 'Lô thanh lý ' + $('.shipment_id option:selected').html() + ': ';
            }

            if(cat_id == 12){
                str_cat = ' cái cho ';
            }

            if(d_id == <?php echo OPPO_STAFF;?>){
                $(all_staff).each(function(i,v){
                    var _num = $(all_num[i]).val();
                    var _name = $(v).attr('data-name');
                    var _type_name = '';
                    if(shipment_id != ''){
                        _type_name = ' loại ';
                        var _type = $(shipment_type[i]).val();
                        if(_type == 1){
                            _type_name += 'A ';
                        }else if(_type == 2){
                            _type_name += 'B ';
                        }else if(_type == 3){
                            _type_name += 'C ';
                        }else if(_type == 4){
                            _type_name += 'D ';
                        }else{
                            _type_name = '';
                        }
                    }
                    remark += _num + _type_name + str_cat+ _name + '; ';
                });
            }

            if(d_id == <?php echo OPPO_INGAME;?>){

                $(all_ingame).each(function(i,v){
                    var _num = $(all_num[i]).val();
                    var _name = $(v).val()+ ' (' + $(all_ingame_cmndd[i]).val()+ ')';
                    var _type_name = '';
                    if(shipment_id != ''){
                        _type_name = ' loại ';
                        var _type = $(shipment_type[i]).val();
                        if(_type == 1){
                            _type_name += 'A ';
                        }else if(_type == 2){
                            _type_name += 'B ';
                        }else if(_type == 3){
                            _type_name += 'C ';
                        }else if(_type == 4){
                            _type_name += 'D ';
                        }else{
                            _type_name = '';
                        }
                    }
                    remark += _num + _type_name + str_cat+ _name + '; ';
                });
            }

            $(row).find('.text').val(remark);

        });
    })
}

function ResetNvmm(){
    $('#form .wrap_list_staff').hide();
    $('.btn_add_row_nvmm').hide();

    $('#form .info_nvmm').remove();
    $('.info_nvmm').hide();

    $('#form .info_ingame').remove();
    $('.info_ingame').hide();

    $('#div-number-sales').remove();
}

function show_nvmm(option){
    if(option == 1){
        $('#form .wrap_list_staff').show();
        $('.btn_add_row_nvmm').show();

        $('#form .info_nvmm').remove();
        $('.info_nvmm').show();

        $('#form .info_ingame').remove();
        $('.info_ingame').hide();

        $('#div-number-sales').remove();
        var old_div = $('.div-number-sales');
        var new_div = old_div.clone();
        new_div.attr('id', 'div-number-sales');
        new_div.insertAfter($('#form .wrap_list_staff')).show();
    }else{
        $('#form .wrap_list_staff').hide();
        $('.btn_add_row_nvmm').show();

        $('#form .info_nvmm').remove();
        $('.info_nvmm').hide();

        $('#form .info_ingame').show();
        $('.info_ingame').show();

        $('#div-number-sales').remove();
        var old_div = $('.div-number-sales');
        var new_div = old_div.clone();
        new_div.attr('id', 'div-number-sales');
        new_div.insertAfter($('#form .wrap_list_staff')).show();

    }
}

function changePartner(){
    $("#for_partner").live('change',function(){
        var current = $(this).val();
        if(current == 2){
            var d_id = $('#distributor_id').val();
            if(d_id == <?php echo OPPO_STAFF?>){
                show_nvmm(1);
            }else{
                show_nvmm(2);
            }
        }else{
            ResetNvmm();
        }

    })
}

function  show_shipment_type(){
    //NHAN VIEN MUA MAY
    <?php if(!My_Staff_Group::create_for_partner($this->userStorage->id,$this->userStorage->group_id)):?>
        $('.wrap_shipment_type').hide();
    <?php endif?>
}
</script>