<!-- mua may nhan vien -->
<?php if(My_Staff_Group::create_for_partner($this->userStorage->id,$this->userStorage->group_id)):?>
<div class="row div-number-sales" style="display: none;">
    <div class="span12">
        <div class="span6">
            <label class="span3 shipment_wrap">Lô máy <span style="color: red"></span>
                <select class="span3 shipment_id" name="shipment_id">
                    <option value="">Please select</option>
                    <?php foreach ($this->shipment as $key => $value):?>
                        <option value="<?php echo $value['id'];?>" <?php if (isset($this->shipment_id) and $value['id'] == $this->shipment_id):?> selected<?php endif;?>><?php echo $value['number'];?></option>
                    <?php endforeach;?>
                </select>
            </label>
        </div>
    </div>
</div>
<?php endif; ?>
<!-- END mua may nhan vien -->





<!-- invoice -->
<div  class="row div-invoice" style="display: none;">
    <div class="span12 wrap_for_partner" style="display: none">
        <?php if(My_Staff_Group::create_for_partner($this->userStorage->id,$this->userStorage->group_id)):?>
        <label class="span3">For partner or staff<span style="color: red">*</span>
            <select class="span3" name="for_partner" id='for_partner' required>
<!--                <option value>Please select</option>-->
                <?php foreach ($this->arr_for_partner as $k => $v):?>
                    <option value="<?php echo $k;?>" <?php if(isset($this->for_partner) AND $this->for_partner == $k) echo 'selected';?>>
                        <?php echo $v;?>
                    </option>
                <?php endforeach;?>

            </select>
        </label>
        <?php endif;?>
    </div>

    <div class="span12">
        <label class="span3">Invoice <span style="color: red">*</span>
            <select class="span3 invoice" id="invoice_type" name="invoice" required="required" disabled>
                <option value="">Please select Type</option>
                <option <?php if(isset($this->invoice_type) and $this->invoice_type and $this->invoice_type == 1 ) echo 'selected';  ?> value="1">Invoice</option>
                <option <?php if(isset($this->invoice_type) and $this->invoice_type and $this->invoice_type == 2 ) echo 'selected'; ?> value="2">Without Invoice</option>
            </select>
        </label>
    </div>

   
        
    <div class="span12  wrap_list_staff" style="display: none;">
        <label class="span3">For staff <span style="color: red">*</span>
            <input type='text' class="span3" name='SearchBox' id="SearchBoxObject" placeholder="Search" autocomplete="off"style="width: 430px;" />
            <select class="span3 object_id" name="for_staff" id='object_id' size="5" style="width: 440px; padding: 5px">
                <option value="">Please select</option>
                <?php if(isset($this->objects) AND $this->objects):?>
                <?php foreach ($this->objects as $k => $v):?>
                    <option value="<?php echo $v['staff_id'];?>" data-name="<?php echo $v['staff_name_2']?>"><?php echo $v['staff_name'];?></option>
                <?php endforeach;?>
                <?php endif;?>
            </select>
        </label>

    </div>

</div>
<!-- end invoice --->


<!-- HANG TANG NHAN VIEN -->
<div  class="row div-gift" style="display: none;">
    <div class="span12">
        <label class="span3">Area <span style="color: red">*</span>
            <select class="span3 gift_id" name="gift_id" required="required" disabled>
                <option value="">Please select</option>
                <?php foreach ($this->office as $k => $v):?>
                    <option value="<?php echo $k;?>" <?php if(isset($this->office_id) and $this->office_id and $this->office_id == $k ) echo "selected" ?> ><?php echo $v;?></option>
                <?php endforeach;?>
            </select>
        </label>
    </div>
</div>
<!-- end HANG TANG NHAN VIEN -->



<div style="display: none" class="row detail_good div-add" style="border-style: solid; padding: 20px; border-color: lavender;">
        <div class="span12">
            <label class="span2">Category <span style="color: red">*</span>
                <select class="span2 cat_id" name="cat_id[]" required="required" disabled>
                    <option value="">Please select</option>
                    <?php foreach ($this->good_categories as $good_category):?>
                        <option value="<?php echo $good_category->id;?>"><?php echo $good_category->name;?></option>
                    <?php endforeach;?>
                </select>
            </label>
    
            <label class="span2">Product <span style="color: red">*</span>
                <select class="span2 good_id" name="good_id[]" required="required" disabled>
                    <option value="">Please select</option>
                </select>
            </label>
    
            <label class="span2">Color <span style="color: red">*</span>
                <select class="span2 good_color" name="good_color[]" required="required" disabled>
                    <option value="">Please select</option>
                </select>
            </label>
    
            <label class="span1">Qty <span style="color: red">*</span>
                <input type="number" min="1" class="span1 num" name="num[]" required="required" maxlength="5" style="width: 50px" disabled />
            </label>
    
            <label class="span1">Price <span style="color: red">*</span>
                <input type="text" min="1" required="required"  class="span1 price" name="price[]" disabled />
            </label>
    
            <label class="span1 show_sale_off" style="color: orange">Sale off<span style="color: red">*</span>
                <select class="span1 sale_off_percent" name="sale_off_percent[]" required="required" disabled>
                    <option value="">sale off</option>
                    <!-- <option value="1">1%</option>
                    <option value="5">5%</option>
                    <option value="10">10%</option>
                    <option value="12">12%</option> -->
                    <!-- <option value="13">13%</option>
                    <option value="15">15% ສຳລັບເຄື່ອງໂຊ</option>
                    <option value="19.17525773195">A92 ສຳລັບພະນັກງານ</option>
                    <option value="24.94845360824">A92 ສຳລັບເຄື່ອງໂຊ</option>
                    <option value="12.5">Special Enco W31</option> -->
                    <!-- <option value="13">13%</option> 
                    <option value="15">15% For APK</option>
                    <option value="21.9123505976">20% A92 Staff</option>
                    <option value="24.1982507288">24% Reno4 APK</option>
                    <option value="18.36734693878">18% Reno4 Staff</option>
                    <option value="24.94845360824">25% A92 APK</option>
                    <option value="12.5">12.5% Enco W31</option> -->
                    <!-- <option value="13.5">13.5%</option> -->
                    <!-- <option value="16">16%</option>
                    <option value="18">18%</option>
                    <option value="20">20%</option>
                    <option value="22">22%</option>
                    <option value="23">23%</option>
                    <option value="24">24%</option>
                    <option value="25">25%</option>
                    <option value="27">27%</option>
                    <option value="29">29%</option>
                    <option value="30">30%</option>
                    <option value="31">31%</option>
                    <option value="40">40%</option>
                    <option value="50">50%</option>
                    <option value="70">70%</option>
                    <option value="90">90%</option>
                    <option value="99.9">99.9%</option> -->
                    <!-- <option value="100">100% Gift</option> -->
                </select>
            </label>

            <!-- <label class="span1">Sale Off by Unit<span style="color: red">*</span>
                <input type="text" min="0" step="any" required="required" readonly value="0"  class="span1 sale_off_price " id="sale_off_price" name="sale_off_price[]" />
            </label> -->
            
            <label class="span1">Total<span style="color: red">*</span>
                <input type="text" min="0" required="required" readonly="readonly" class="span1 total total_new" name="total[]" disabled />
            </label>
    
           <!--  <label class="span2" style="color: red">Click Auto Remark<span style="color: red">*</span>
                <textarea name="text[]" class="span2 text" readonly disabled></textarea>
            </label> -->
    
            <div class="no_show">
            <label class="span1 campaign">Campaign <span style="color: red">*</span>
                <input type="checkbox" class="span1 campaign_ck" name="campaign_ck[]"   disabled />
                <input type="hidden" class="campaign_val" name="campaign[]" value="" />
            </label>
            </div>
    
            <label class="span1" style="padding-top: 20px">&nbsp;<button type="button" class="btn-danger remove-sales"><i class="icon-minus"></i></button></label>
    
            <input type="hidden" name="ids[]" class="ids" disabled />
        </div>

        <!-- Button add nhan vien mua may -->
        <div class="span12 btn_add_row_nvmm" style="display: none">
            <label for="" class="span12">
                <button class="add_row_nvmm btn btn-small btn-success" type="button">+</button>
            </label>
        </div>

    </div>
</div>




<!-- discount Credit Note -->
<div class="row div-discount-credit-note" style="display: none;margin-left: 0px;">
<?php 
// print_r($this->credits_note[0]['creditnote_sn']); 
?>
    <div class="span12">
        <label class="span2">Credit Note No<span style="color: red">*</span>
   <select class="span2 discount_creditnote" name="discount_creditnote[]" required="required" >
        <option value="">Please select</option>

        <?php foreach ($this->credits_note as $k):?>
            <option value="<?php echo $k['creditnote_sn']; ?>"><?php echo $k['creditnote_sn']; ?></option>
        <?php endforeach;?>
    </select>
</label>

    <label class="span2">Balance Total <span style="color: red">*</span>
            <input type="text" readonly min="1"  class="span2 price_balance_discount_creditnote" name="price_balance_discount_creditnote[]" value="<?php printf(My_Number::f($sale['balance_total']));?>" />
    </label>

    <label class="span2">Use Price <span style="color: red">*</span>
            <input type="text" min="1" required="required" class="span2 price_use_discount_creditnote" name="price_use_discount_creditnote[]" value="<?php printf(My_Number::f($sale['use_total']));?>" />
    </label>


           <label class="span1">&nbsp;<button type="button" class="btn-danger remove-credit-note"><i class="icon-minus"></i></button></label>
           <input type="hidden" name="ids_discount_creditnote[]" class="ids_discount_creditnote"  value="" />
   </div>
</div> 
<!-- end discount Credit Note -->



<!-- discount Deposit-->
<div class="row div-discount-deposit" style="display: none;margin-left: 0px;">
<?php 
// print_r($this->credits_note[0]['creditnote_sn']); 
?>
    <div class="span12">
        <label class="span2">Deposit No<span style="color: red">*</span>
   <select class="span2 discount_deposit" name="discount_deposit[]" required="required" >
        <option value="">Please select</option>

        <?php foreach ($this->deposit_list as $k):?>
            <option value="<?php echo $k['deposit_sn']; ?>"><?php echo $k['deposit_sn']; ?></option>
        <?php endforeach;?>
    </select>
</label>

    <label class="span2">Balance Total <span style="color: red">*</span>
            <input type="text" readonly min="1"  class="span2 price_balance_discount_deposit" name="price_balance_discount_deposit[]" value="<?php printf(My_Number::f($sale['balance_total']));?>" />
    </label>

    <label class="span2">Use Price <span style="color: red">*</span>
            <input type="text" min="1" required="required" class="span2 price_use_discount_deposit" name="price_use_discount_deposit[]" value="<?php printf(My_Number::f($sale['use_total']));?>" />
    </label>


           <label class="span1">&nbsp;<button type="button" class="btn-danger remove-deposit"><i class="icon-minus"></i></button></label>
           <input type="hidden" name="ids_discount_deposit[]" class="ids_discount_deposit"  value="" />
   </div>
</div> 
<!-- end discount Deposit -->

