<style>

a{
    margin-right: 2.5px;
    margin-left: 2.5px;
}

.hilight
{
    background: #E8ADAA;
    /*color:white;*/
}
.hilight:hover
{
    /*color:black;*/
}
</style>
<table class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
					'from_deposit_no'  => 'Deposit No',
					'to_sales_no'  => 'To Sales Order No',
                    'use_total'  => 'Total Used',
                    'create_date' => 'Create Date',
                    'pay_type' => 'Log Type',
                    'remark' => 'Remark'
                ),
                $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php
        $statuses = unserialize(DISCOUNT_STATUS);
        if (isset($this->get_deposit_log) and $this->get_deposit_log) :
            foreach ($this->get_deposit_log as $k=>$m):
            ?>
            <tr>
                <td><?php if(isset($m['from_deposit_no']) && $m['from_deposit_no']){ echo $m['from_deposit_no']; }else{ echo '-';} ?></td>
                <td><?php if(isset($m['to_sales_no']) && $m['to_sales_no']){ echo $m['to_sales_no']; }else{ echo '-';} ?></td>
                <td><?php if(isset($m['use_total']) && $m['use_total']){ echo $m['use_total']; }else{ echo '-';} ?></td>
                <td><?php if(isset($m['update_date']) && $m['update_date']){ echo $m['update_date']; }else{ echo '-';} ?></td>
                <td><?php if(isset($m['remark']) && $m['remark']){ echo $m['remark']; }else{ echo '-';} ?>
            </tr>
        <?php endforeach;?>
		<?php endif; ?>
    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>
