<style>

a{
    margin-right: 2.5px;
    margin-left: 2.5px;
}
.status_enable{
    width: 70px;
    background: #99ff66;
    text-align: center;
}
.status_disable{
    width: 70px;
    background: #ff8c66;
    text-align: center;
}
.hilight
{
    background: #E8ADAA;
    /*color:white;*/
}
.hilight:hover
{
    /*color:black;*/
}
</style>
<div class="table-responsive">
    <span class="pull-left">
        <button class="btn btn-success" type="button" onclick="window.location='<?php echo HOST ?>sales/deposit-create'">
            Create Deposit
        </button>
    </span>
    <span class="pull-right" style="display: none;">
        <button class="btn btn-info btn-confirm-status" value="1" id="btn-confirm-enable" type="button">เปิดใช้งาน</button>&nbsp;

        <button class="btn btn-danger btn-confirm-status" value="0" id="btn-confirm-disable" type="button">ปิดใช้งาน</button>
    </span>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
                    '#',
					'title'  => 'Retailer Name',
                    'deposit_sn'  => 'Deposit No',
					'total_amount'  => 'Total Amount',
                    'use_total'  => 'Total Used',
                    'balance_total' => 'Total Balance',
                    'update_date' => 'Update Date',
                    'confirm_date' => 'Confirm Date',
                    'status' => 'Status'
                ),
                $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php
        $statuses = unserialize(DISCOUNT_STATUS);
        if (isset($this->get_resule) and $this->get_resule) :
            foreach ($this->get_resule as $k=>$m):

                $confirm_status = false;$WaitConfirm_status = false;
                $textConfirm_status = 'ไม่เปิดใช้งาน';

                if(isset($m['status']) && $m['status']&& $m['status']==1){
                    $confirm_status = true;
                    $textConfirm_status = 'เปิดใช้งาน';
                }

                if($m['confirm_date'] !=""){
                    $WaitConfirm_status = true;
                }
            ?>
            <tr>
                <td>#</td>
                <td><?php echo $m['title'] ?></td>
                <td><?php echo $m['deposit_sn'] ?></td>
                <td><?php echo $m['total_amount'] ?></td>
                <td><?php echo $m['use_total'] ?></td>
                <td><?php echo $m['balance_total'] ?></td>
                <td><?php echo $m['update_date'] ?></td>
                <td><?php if($WaitConfirm_status==false){echo "<input class='status_disable' type='text' value='รออนุมัติ'>";}else{echo $m['confirm_date'];} ?></td>
                <td><input class="<?php if($confirm_status){echo 'status_enable';}else{echo 'status_disable';}?>" id="confirmStatus-<?=$i;?>" type="text" value="<?=$textConfirm_status;?>"  ></td>
                <td style="text-align: center; display: none;">
                    <a title="Show Log Payment No" href="/sales/deposit-log?d_id=<?php echo $m['distributor_id'];?>&deposit_sn=<?php echo $m['deposit_sn'];?>"> <i class="icon-file-text-alt"></i></a>
                </td>

            </tr>
        <?php endforeach;?>
		<?php endif; ?>
    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<script type="text/javascript" src="/js/jets.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>

<script>
    

    $(document).ready(function () {
        
        alert(1);
        $('.btn-confirm-status').click(function(event)
        {
            
            var deposit_sn = [];
            $('.checkbox-confirm:checked').each(function(index, el) {
                deposit_sn.push($(el).val());
            });

            if(deposit_sn.length > 0){
                if (confirm('Are you sure?')) {

                    $.ajax({
                        url: '<?php echo HOST.'sales/deposit-status';?>',
                        type: 'POST',
                        data: {'d_id':<?=$this->distributor['id'];?>,'deposit_sn':deposit_sn},
                    })
                    .done(function(response) {

                    });

                }
            }else{
                alert('กรุณาเลือกรายการที่ต้องการ');
            }

        });    
    });

    /*$('#btn-confirm-enable').click(function(event) {
                
            deposit_sn = [];

            $('.checkbox-confirm:checked').each(function(index, el) {
                deposit_sn.push($(el).val());
            });

            if(deposit_sn.length > 0){

                if (confirm('Are you sure?')) {

                    $.ajax({
                        url: '<?php echo HOST.'sales/deposit-status';?>',
                        type: 'POST',
                        data: {'d_id':<?=$this->distributor['id'];?>,'deposit_sn':deposit_sn},
                    })
                    .done(function(response) {
                        var obj_response = jQuery.parseJSON(response);
                        console.log("success");

                        console.log(obj_response.status);

                         switch(obj_response.status){
                            case '400':
                                alert(obj_response.message);
                                console.log(obj_response.message);
                                break;
                            case '201':
                                window.location.href = obj_response.url;
                                break;
                            default:
                                console.log('ajax fail.');
                        }
                        
                    });

                }

            }else{
                alert('กรุณาเลือกรายการที่ต้องการ');
            }

        });*/
      

    



</script>