<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo HOST ?>css/jquery-ui-1.8.12.custom.css"/>
<link href="<?php echo HOST ?>css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="<?php echo HOST ?>css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">

<style type="text/css">
    #d_id {
        left: -20px !important;
    }
</style>

<form class="form-search form-horizontal" method="post" action="<?php echo HOST ?>sales/ep-privileges-check-staff-position">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="staff_code" class="control-label">Staff Code</label>
                <div class="controls">
                    <input type="text" class="form-control search-query" id="staff_code" name="staff_code" value="<?php isset($this->params['staff_code']) and printf($this->params['staff_code']);?>">
                </div>
            </div>

            

        </div>

        
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
</form>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<script type="text/javascript" src="<?php echo HOST ?>js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>


