<style>
.red
{
    background: #1B8324;color:red;
}
.show_item{
      background-color:#32CD32;
}
.show_item_select{
      background-color:#FFA500;
}

</style>

<table class="table table-bordered" style="margin-left: -70px;">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
          '#',
          'ID'            => 'Sale ID', 
          'sn'            => 'Sale Order Number',
          'd_id'          => 'Retailer Name',
          'good_id'       => 'Product Name',
          'good_color'    => 'Product Color',
          'num'           => 'Sales Quantity',
          'price'         => 'Sales Price',
          'total'         => 'Total',
          'total_discount' => 'Discount',
          'total_amount'  => 'Total Amount',
          'pay_time'      => 'Payment or Not',
          'shipping_yes_time'      => 'Shipping',
          'outmysql_time' => 'Out of Warehouse',
          'warehouse_id'  => 'Warehouse',
          'status'        => 'Status',
          'Discount Type',
          'p.id'          => 'Order Time',
          'Finance Confirm',
          'Action'
                ),
                $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
    <?php
        function cal_sale_off_percent($percent_sale_off,$price,$num,$price_total){
          
            if($percent_sale_off>0){
                $price_sale_off=$price_total/$num;
            }else{
                $price_sale_off = $price;
            }
            return $price_sale_off;
         }
          function ext_vat($num){
           return $num/1.07;
        }
        function format_number_4($num){
           return decimal_remove_comma(number_format($num, 4));
        }
         function format_number_2($num){
           return decimal_remove_comma(number_format($num, 2));
        }

         function decimal_remove_comma($priceFloat)
         {
            $price = str_replace(",","",$priceFloat);;
            return $price;
         }
        $percent_sale_off=0;
        $statuses = unserialize(DISCOUNT_STATUS);    


        if (isset($this->markets_sn) and $this->markets_sn) :

            foreach ($this->markets_sn as $k=>$m):
             $dt = DateTime::CreateFromFormat("Y-m-d H:i:s", isset($m['last_updated_at']) ? $m['last_updated_at'] : $m['add_time']);
             $h = $dt->format('H');
             $i = $dt->format('i');
             $d = $dt->format('d');
             $date = date('d');
             //print_r($m);
             $sn_ref = $m['sn_ref'];
             if($sn_ref==''){
                $sn_ref = $m['sn'];
             }
            $product_unit_price = $m['price'];//print_r($m);
            $product_qty        = $m['total_qty'];
            $price_total        = $m['total_price_amount'];
            $sale_off_percent   = isset($m['sale_off_percent'])?$m['sale_off_percent']:'0'; 
            $product_unit_price = cal_sale_off_percent($sale_off_percent,$product_unit_price,$product_qty,$price_total); 
            $total_price = ext_vat($product_unit_price); 
            $product_unit_price_4 = format_number_4($total_price);
            $product_amount_4 =format_number_2($product_unit_price_4) * $product_qty; 
            $total_amount = $product_amount_4*1.07;


            $total_amount = $m['total_price_amount'] - $m['total_discount'] + $m['delivery_fee'];
             if($m['delivery_fee']>0){
                $delivery_fee ="Delivery fee = ".$m['delivery_fee'];
             }else{
                $delivery_fee ="";
             }
             
            ?>
            <tr class="<?php
                    if(isset($h) and isset($i) and ($h >= 16))
                       {
                            if($date == $d)
                            {
                                if($h==16 and $i>=30){
                                    echo 'show_item';
                                }
                                else if($h > 16){
                                    echo 'show_item';
                                }
                            }                            
                       }
            ?>">
                
                    <td><a href="#id" rel="<?php echo $m['sn'] ?>" class="collapse_a btn btn-default btn-small" id="m_<?php echo $m['sn'] ?>"><span class="col-sign">+</span><img class="img-loading" src="<?php echo HOST?>img/ajax-loader.gif" style="display: none" /></a></td>
                <td><?php echo $m['id'] ?></td>
                <td><?php echo $sn_ref ?></td>
                <td><?php if (isset($this->distributors2) && $this->distributors2 && isset($this->distributors2[$m['d_id']])) echo $this->distributors2[$m['d_id']]['title']; ?></td>
                <td></td>
                <td></td>
                <td><?php echo $m['total_qty'] ?></td>
                <td></td>
                <td><?php echo My_Number::f($total_amount, 0, ',', '.'); ?></td><!-- TOTAL -->
                <td><?php echo My_Number::f($m['total_discount'], 0, ',', '.'); ?></td>
                <td title='<?=$delivery_fee?>'><?php echo My_Number::f($total_amount, 0, ',', '.'); ?></td><!-- TOTAL AMOUNT -->
                <td><?php if ($m['pay_time']):?><i class="icon-ok"></i><?php else:?><i class="icon-remove"></i><?php endif;?></td>
                <td><?php if ($m['shipping_yes_time']):?><i class="icon-ok"></i><?php else:?><i class="icon-remove"></i><?php endif;?></td>
                <td><?php if ($m['outmysql_time']):?><i class="icon-ok"></i><?php else:?><i class="icon-remove"></i><?php endif;?></td>
                <td><?php if (isset($this->warehouses_cached[$m['warehouse_id']])) echo $this->warehouses_cached[$m['warehouse_id']] ?></td>
                <td><?php if ($m['status']==1):?>Active<?php else:?>Expired<?php endif;?></td>
                <td><?php echo ( isset($statuses[ $m['discount'] ]) ? $statuses[ $m['discount'] ] : '' ); ?></td>
                <td><?php echo $m['add_time'] ?></td>
                <td><?php echo $m['pay_time'] ?></td>
                <td>
                    <a title="View" href="/sales/view?sn=<?php echo $m['sn'];?>"> <i class="icon-eye-open"></i></a>

                    <?php if ($m['status']==1): ?>
                        <?php if (!$m['pay_time'] and !$m['outmysql_time']): ?>
                            <?php if ($m['confirm_so'] != 1): ?>
                               <a title="Edit" href="/sales/create?sn=<?php echo $m['sn'];?>&sn_ref=<?php echo $m['sn_ref'];?>"> <i class="icon-edit"></i></a>
                           <?php endif;?>
                            
                            <a title="Delete" class="confirmLink" href="/sales/del?sn=<?php echo $m['sn'];?>"> <i class="icon-trash"></i></a>

                        <?php else:?>
                            <a class="lock" title="Lock" href="javascript:void(0);"> <i class="icon-lock"></i></a>

                            <?php if (!$m['canceled']):?>
                                <!-- <a class="cancel" title="Mark Canceled" rel="<?php echo $m['sn'];?>" href="javascript:void(0);"> <i class="icon-eraser"></i></a> -->
                                <!-- <a title="Mark Canceled" data-toggle="modal" data-sn="55566645466"> <i class="icon-eraser"></i></a> -->
                                <a data-toggle="modal" data-sn="'<?php echo $m['sn'];?>'" title="Mark Canceled" class="open-cancel" href="#cancelSO"><i class="icon-eraser"></i></a>


                            <?php else:?>
                                 <a data-toggle="modal" data-sn="'<?php echo $m['sn'];?>'"  class="open-remark" href="#canceRemark"><span style="color: red">Canceled</span></a>
                            <?php endif;?>
                        <?php endif;?>
                        <a title="Print" target="_blank" href="/sales/print-sale?sn=<?php echo $m['sn'];?>"> <i class="icon-print"></i></a>
                        <?php //print_r($this->view_accessories); ?>
                        <?php if ($m['confirm_so'] == 0 && $m['confirm_access_status'] == 1){ ?>
                            <a title="Confirming Order" href="/sales/sales-confirm-order?sn=<?php echo  $m['sn'];?>"> 
                            <i class="icon-shopping-cart"></i></a>

                         <?php }else if ($m['confirm_so'] == 0 && $m['confirm_access_status'] == null && $this->view_accessories=='wait'){ ?>  
                            <a title="Approve" href="/sales/sales-confirm-accessories-order?sn=<?php echo  $m['sn'];?>"> 
                            <i class="icon-ok"></i></a>
                        <?php }?>

                        


                    <?php endif;?>
                </td>
                </tr>

            <?php endforeach;?>
    <?php endif; ?>
    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

