<style>

a{
    margin-right: 2.5px;
    margin-left: 2.5px;
}
.status_enable{
    width: 70px;
    background: #99ff66;
    text-align: center;
}
.status_disable{
    width: 70px;
    background: #ff8c66;
    text-align: center;
}
.hilight
{
    background: #E8ADAA;
    /*color:white;*/
}
.hilight:hover
{
    /*color:black;*/
}
</style>
<div class="table-responsive">
    <?php
        $userStorage = Zend_Auth::getInstance()->getStorage()->read();
        if (My_Staff_Group::inGroup($userStorage->group_id, array(ADMINISTRATOR_ID, 63)) or ($exception_case and in_array
        ($userStorage->id, $exception_case))){
            $view_import="";    //Open Market Campaign = 63
        }else{
            $view_import='style="display: none;"';
        }
    ?>
    <span <?php echo $view_import; ?> class="pull-left">
        <button class="btn btn-success" type="button" onclick="window.location='<?php echo HOST ?>sales/import-confirm-rebate-open-market'">
            Import Confirm Payment Rebate True Campaign File
        </button>
    </span>
</br></br>
</div>
<table class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
                    '#',
                    'distributor_id'  => 'Distributor ID',
                    'store_code'  => 'Store Code',
                    'partner_code' => 'Partner Code',
					'distributor_name'  => 'Distributor Name',
					'total_imei'  => 'Total Imei',
                    'total_amount'  => 'Total Amount'
                ),
                $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php
        $statuses = unserialize(DISCOUNT_STATUS);
        if (isset($this->get_resule) and $this->get_resule) :
            foreach ($this->get_resule as $k=>$m):
            ?>
            <tr>
                <td>#</td>
                <td><?php echo $m['distributor_id'] ?></td>
                <td><?php echo $m['store_code'] ?></td>
                <td><?php echo $m['partner_code'] ?></td>
                <td><?php echo $m['distributor_name'] ?></td>
                <td><?php echo $m['total_imei'] ?></td>
                <td><?php echo My_Number::f($m['total_amount'], 0, ',', '.') ?></td>
               

            </tr>
        <?php endforeach;?>
		<?php endif; ?>
    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<script type="text/javascript" src="/js/jets.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>

<script>
    

    $(document).ready(function () {
        
        //alert(1);
        $('.btn-confirm-status').click(function(event)
        {
            
            var deposit_sn = [];
            $('.checkbox-confirm:checked').each(function(index, el) {
                deposit_sn.push($(el).val());
            });

            if(deposit_sn.length > 0){
                if (confirm('Are you sure?')) {

                    $.ajax({
                        url: '<?php echo HOST.'sales/deposit-status';?>',
                        type: 'POST',
                        data: {'d_id':<?=$this->distributor['id'];?>,'deposit_sn':deposit_sn},
                    })
                    .done(function(response) {

                    });

                }
            }else{
                alert('กรุณาเลือกรายการที่ต้องการ');
            }

        });    
    });

    
      

    



</script>