<form class="form-search form-horizontal" method="get" action="<?php echo HOST ?>sales/pre-sales-order-list">
    <div class="row">
        <div class="span6">

            
            <div class="control-group">
            <label for="presales_no" class="span2">รหัสการจองสินค้า</label>
            <input id="presales_no" name="presales_no" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['presales_no']) and printf($this->params['presales_no']);?>">
            </div>

            <div class="control-group" style="display: none;">
            <label for="distributor_name" class="span2">ร้านค้า</label>
            <input id="distributor_name" name="distributor_name" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['distributor_name']) and printf($this->params['distributor_name']);?>">
            </div>

            <div class="control-group">
            <label for="sell_name" class="span2">ผู้จองสินค้า/Email</label>
            <input id="sell_name" name="sell_name" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['sell_name']) and printf($this->params['sell_name']);?>">
            </div>

            <div class="control-group">
            <label for="distributor_name" class="span2">ร้านค้า</label>
            <input id="distributor_name" name="distributor_name" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['distributor_name']) and printf($this->params['distributor_name']);?>">
            </div>

            <div class="control-group">
            <label for="start_date" class="span2">วันที่รับจองสินค้า</label>
                <input type="text" class="span1 start_date" name="start_date" id="start_date" value="<?php isset($this->params['start_date']) and printf($this->params['start_date']);?>" /> - <input type="text" class="span1 end_date" name="end_date" id="end_date" value="<?php isset($this->params['end_date']) and printf($this->params['end_date']);?>" />
            </div>

            
            <div class="control-group" ">
            <label for="status" class="span2">สถานะ</label>
                <select id="status" name="status" >
                    <option value="1" <?php if (isset($this->params['status']) and $this->params['status']==1):?> selected<?php endif;?>>รอดำเนินการ</option>
                    <option value="2" <?php if (isset($this->params['status']) and $this->params['status']==2):?> selected<?php endif;?>>บันทึกรายการ</option>
                    <option value="3" <?php if (isset($this->params['status']) and $this->params['status']==3):?> selected<?php endif;?>>ยกเลิก</option>
                    <option value="0" <?php if (isset($this->params['status']) and $this->params['status']==0):?> selected<?php endif;?>>-ทั้งหมด-</option>
                </select>
            </div>
        </div>
        <div class="span5">

        </div>
    </div>

    
    <input type="hidden" name="counter" value="<?=$this->counter;?>">
    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
    <button type="submit" name="export" value="1" class="btn btn-success">Export</button>
</form>

<script async="async">

    <?php if(isset($this->params['finance_group']) && $this->params['finance_group']){?>
        $('#finance_group').val('<?php echo $this->params['finance_group'];?>');
    <?php } ?>
    
        <?php if(isset($this->rank)) { ?>
            $('#rank').val(<?= $this->rank ?>);
            get_distributor_cached_for_search(<?= $this->rank ?>);
        <?php }?>

        $('.rank').change(function(event) {
            get_distributor_cached_for_search($(this).val());
          });

        $(document).on('focus',".start_date", function(){ 
         $(this).datepicker({ dateFormat: "yy-mm-dd" });
        });

        $(document).on('focus',".end_date", function(){ 
         $(this).datepicker({ dateFormat: "yy-mm-dd" });
        });

        function get_distributor_cached_for_search(rank_id){

            var rank_id = rank_id;
                  $.ajax({
                      url: '<?php echo HOST ?>get/distributor-cached-for-search',
                      type: 'POST',
                      dataType: 'html',
                      data: {rank_id: rank_id},
                  })
                  .done(function(data) {
                      $('.retailer_name_list').empty();
                      $('.retailer_name_list').append(data);
                        var jets = new Jets({
                        searchTag: '#SearchBox',
                        contentTag: '#d_id'
                    });
                        <?php if(isset($this->d_id)){ ?>
                            $('#d_id').val(<?= $this->d_id ?>);
                        <?php }?>
                      console.log("success");
                  })
                  .fail(function() {
                      console.log("error");
                  })
                  .always(function() {
                      console.log("complete");
                  });

        }

    function getDistributor(currentDistributorID) {

        $.ajax({
            url: '<?php echo HOST ?>get/distributor-cached',
            type: 'post',
            dataType: 'json'
        })
            .done(function(data) {
                if (!data || data.no_data) return false;
                $('#d_id option').not(':first').remove();

                $.each(data, function(key, value) {
                    var selected = currentDistributorID == key ? 'selected' :'';
                    var op = '<option value="'+key+'" ' + selected + '>'+value.store_code+' - '+value.title+'</option>';
                    $('#d_id').append(op);
                });

                var jets = new Jets({
                    searchTag: '#SearchBox',
                    contentTag: '#d_id'
                });
            })
            .fail(function() {
                console.log("error");
            })
            .always(function() {
                /*console.log("complete");*/
            });

    }
</script>