<link href="../css/select2.css" rel="stylesheet"/>
<script src="../js/select2.js"></script>
<form class="form-search form-horizontal" method="get" action="<?php echo HOST ?>sales/return-list">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="sn" class="span2">Return Order Number</label>
                <input id="sn" name="sn" type="text" placeholder="Search by RO" class="input-medium search-query form-control" value="<?php isset($this->params['sn']) and printf($this->params['sn']);?>">
            </div>

            <div class="control-group">
                <label for="creditnote_sn" class="span2">Credit Note Number</label>
                <input id="creditnote_sn" name="creditnote_sn" type="text" placeholder="Search by CN" class="input-medium search-query form-control" value="<?php isset($this->params['creditnote_sn']) and printf($this->params['creditnote_sn']);?>">
            </div>

            <div class="control-group">
                <label for="create_cn" class="span2">ສ້າງລະຫັດ CN</label>
                <select id="create_cn" class="span3" name="create_cn">
                    <option value="">Choose</option>
                    <option value="0" <?php if (isset($this->params['create_cn']) and 0==$this->params['create_cn']):?> selected<?php endif;?> >-- ທັງໝົດ --</option>
                    <option value="1" <?php if (isset($this->params['create_cn']) and 1==$this->params['create_cn']):?> selected<?php endif;?>>-- ສ້າງລະຫັດ CN --</option>
                    <option value="2" <?php if (isset($this->params['create_cn']) and 2==$this->params['create_cn']):?> selected<?php endif;?>>-- ບໍ່ສ້າງລະຫັດ CN --</option>
                </select>
            </div>

        </div>
        <div class="span5">
        
            <div class="control-group">
             <label class="span2" for="rank" style="color: blue;">Retailer name ຮ້ານຄ້າ<span style="color: red">*</span></label>
                
                    <select id="rank" name="rank" class="rank span3">
                        <option value="">---</option>
                        <!-- <option value="1" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==1 ) { ?> selected<?php }?>>1. ORG-WDS(1)</option>
                        <option value="2" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==2 ) { ?> selected<?php }?>>2. ORG(2)</option>
                        <option value="5" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==5 ) { ?> selected<?php }?>>3. ORG-Dtac/Advice(5)</option>
                        <option value="6" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==6 ) { ?> selected<?php }?>>4. ORG-Lotus/Power by(6)</option>
                        <option value="7" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==7 ) { ?> selected<?php }?>>5. Dealer(7)</option>
                        <option value="8" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==8 ) { ?> selected<?php }?>>6. HUB(8)</option> -->
                        <option value="9" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==9 ) { ?> selected<?php }?>>7. Laos(9)</option>
                        <!-- <option value="3" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==3 ) { ?> selected<?php }?>>8. Online and Staff(3)</option>
                        <option value="10" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==10 ) { ?> selected<?php }?>>9. Brand Shop/Service(10)</option>
                        <option value="11" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==11 ) { ?> selected<?php }?>>10. King Power(11)</option>
                        <option value="12" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==12 ) { ?> selected<?php }?>>11. Jaymart(12)</option>  
                        <option value="13" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==13 ) { ?> selected<?php }?>>12. Brand Shop By Dealer(13)</option>
                        <option value="14" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==14 ) { ?> selected<?php }?>>13. KR Dealer(14)</option>
                        <option value="15" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==15 ) { ?> selected<?php }?>>14. TRUE(15)</option> -->
                    </select>
                
             </div>       
                
        <div class="retailer_name_list"></div>
        </div>
    </div>

   <!--edit selector warehouse -->
     <div class="control-group">
<label class="control-label" for="name" style="color: blue;">Warehouse <span style="color: red">*</span></label>
<div class="controls">
    <select name="warehouse[]" id="warehouse" class="warehouse span3" multiple="multiple">
                 <?php 
                    if (isset($this->params['warehouse'])){
                        if ($this->warehouses): 
                           $i=0;
                           foreach ($this->warehouses as $id=>$name):?>
                                <?php 
                                    $selected='';
                                    try{
                                        $key = array_search($id, $this->params['warehouse']);
                                        $warehouse_id = $this->params['warehouse'][$key];
                                        if($warehouse_id==$id){
                                            $selected='selected';
                                        }else{
                                            $selected='';
                                        }  
                                    } catch (Exception $e) {
                                        $selected='';
                                    }
      
                                ?>
                                <option value="<?php echo $id;?>" <?php echo $selected;?>   >
                                    <?php echo $name;?>
                                </option>

                        <?php endforeach; endif;?>
                    <?php }else{ ?>
                        <?php if ($this->warehouses): 
                            foreach ($this->warehouses as $id=>$name):?>
                            <option value="<?php echo $id;?>">
                                <?php echo $name;?>
                            </option>
                        <?php endforeach; endif;?>
                        <?php } ?>

        <!-- <option value>---</option>
        <?php if (isset( $this->warehouses ) && $this->warehouses): ?>
        <?php foreach ($this->warehouses as $key => $warehouses): ?>
        <?php if($key != '1'){?>
        <option value="<?php echo $key ?>" <?php if( isset($this->params['warehouse']) && isset($this->params['warehouse']) && $this->params['warehouse'] == $key ) echo "selected='selected'" ?>><?php echo $warehouses ?></option>
        <?php } ?>
        <?php endforeach ?>
        <?php endif ?> -->
    </select>
<p class="help-block"></p >
</div>
</div>

    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="cat_id" class="span2">Product Category</label>
                <select id="cat_id" class="span3" name="cat_id">
                    <option value="">Choose</option>
                    <?php if ($this->good_categories): foreach ($this->good_categories as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['cat_id']) and $id==$this->params['cat_id']):?> selected<?php endif;?>><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">
                <label for="good_id" class="span2">Product</label>
                <select id="good_id" class="span3" name="good_id">
                    <option value="">Choose</option>
                    <?php if ($this->goods): foreach ($this->goods as $key=> $item):?>
                        <option value="<?php echo $key;?>" <?php if (isset($this->params['good_id']) and $key==$this->params['good_id']):?> selected<?php endif;?>><?php echo $item;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">
                <label for="good_color" class="span2">Color</label>
                <select id="good_color" class="span3" name="good_color">
                    <option value="">Choose</option>
                    <?php if ($this->goodColors): foreach ($this->goodColors as $key=>$item):?>
                        <option value="<?php echo $key;?>" <?php if (isset($this->params['good_color']) and $key==$this->params['good_color']):?> selected<?php endif;?>><?php echo $item;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            
            
        </div>
        <div class="span5">
            <div class="control-group">
                <label for="payment" class="span2">PAYMENT</label>
                <input id="payment" name="payment" type="checkbox" class="input-large search-query form-control" value="1" <?php if (isset($this->params['payment']) and $this->params['payment']):?>checked="checked" <?php endif;?>>
            </div>
            <div class="control-group">
                <label for="outmysql_time" class="span2">OUT OF THE WAREHOUSE</label>
                <input id="outmysql_time" name="outmysql_time" type="checkbox" class="input-large search-query form-control" value="1" <?php if (isset($this->params['outmysql_time']) and $this->params['outmysql_time']):?>checked="checked" <?php endif;?>>
            </div>
            <div class="control-group">
                <label for="created_at_from" class="span2">Order Time From</label>
                <input type="text" class="form-control search-query date" id="created_at_from" name="created_at_from" value="<?php isset($this->params['created_at_from']) and printf($this->params['created_at_from']);?>">
            </div>
            <div class="control-group">
                <label for="created_at_to" class="span2">Order Time To</label>
                <input type="text" class="form-control search-query date" id="created_at_to" name="created_at_to" value="<?php isset($this->params['created_at_to']) and printf($this->params['created_at_to']);?>">
            </div>

    <!--  Add Receive date  -->
    
            <div class="control-group">
                <label for="receive_at_from" class="span2" style="color: blue;">Receive From</label>
                <input type="text" class="form-control search-query date" id="receive_at_from" name="receive_at_from" value="<?php isset($this->params['receive_at_from']) and printf($this->params['receive_at_from']);?>">
            </div>
            <div class="control-group">
                <label for="receive_at_to" class="span2" style="color: blue;">Receive To</label>
                <input type="text" class="form-control search-query date" id="receive_at_to" name="receive_at_to" value="<?php isset($this->params['receive_at_to']) and printf($this->params['receive_at_to']);?>">
            </div>

            

        </div>
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
    <!-- <button type="submit" name="export" value="1" class="btn btn-success">Export No IMEI</button> -->
    <button type="submit" name="export" value="3" class="btn btn-success">Export No IMEI</button>
    <button type="submit" name="export" value="2" class="btn btn-success">Export IMEI</button>
    <button type="submit" name="export" value="4" class="btn btn-success">Export For Finance</button>

</form>
<script type="text/javascript" src="<?php echo HOST ?>js/jets.js"></script>
<script>
    $(document).ready(function () {

        $('.warehouse').select2();

        <?php if(isset($this->warehouse)) { ?>
            $('#warehouse').val(<?= $this->warehouse ?>);
            get_warehouse(<?= $this->warehouse ?>);
        <?php } ?>

        $('.warehouse').change(function(event){
            get_warehouse($(this).val());
        });

        <?php if(isset($this->rank)) { ?>
            $('#rank').val(<?= $this->rank ?>);
            get_distributor_cached_for_search(<?= $this->rank ?>);
        <?php }?>

        $('.rank').change(function(event) {
            get_distributor_cached_for_search($(this).val());
          });

        function get_distributor_cached_for_search(rank_id){

            var rank_id = rank_id;
                  $.ajax({
                      url: '<?php echo HOST ?>get/distributor-cached-for-search',
                      type: 'POST',
                      dataType: 'html',
                      data: {rank_id: rank_id},
                  })
                  .done(function(data) {
                      $('.retailer_name_list').empty();
                      $('.retailer_name_list').append(data);
                        var jets = new Jets({
                        searchTag: '#SearchBox',
                        contentTag: '#d_id'
                    });
                        <?php if(isset($this->d_id)){ ?>
                            $('#d_id').val(<?= $this->d_id ?>);
                        <?php }?>
                      console.log("success");
                  })
                  .fail(function() {
                      console.log("error");
                  })
                  .always(function() {
                      console.log("complete");
                  });

        }
        
        initSearchOptionDistributor('d_id', 'SearchBox');
        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('#cat_id, #good_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var cat_id = $('#cat_id').val();

            if (_self.attr('id')=='cat_id')
                $('#good_id').find('option:not(:first)').remove();

            var good_id = $('#good_id').val();

            $('#good_color').find('option:not(:first)').remove();

            $('#num, #price').val('');

            $.get("/get/load",
                {cat_id: cat_id, good_id: good_id}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    if (data.goods){
                        var obj = data.goods;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    if (data.colors){
                        var obj = data.colors;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    _self.nextAll('.loading').remove();
                });
        });
    });
</script>
<script>
       // $(document).ready(function() { $("#d_id").select2(); });
</script>