<script type="text/javascript" src="<?php echo HOST ?>js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo HOST ?>css/jquery-ui-1.8.12.custom.css"/>

<link href="<?php echo HOST ?>css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="<?php echo HOST ?>css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">

<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>

<link href="../css/select2.css" rel="stylesheet"/>
<script src="../js/select2.js"></script>

<form class="form-search form-horizontal" method="get" action="<?php echo HOST ?>sales/client-management">
	<div class="row">
		<div class="span6">
			<div class="control-group">
				<label class="control-label">Certificate Name : </label>
				<div class="controls">
					<input type="text" name="client_name" class="span3" placeholder="Enter" value="<?php isset($this->params['client_name']) and printf($this->params['client_name']);?>">
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">Client Name ( in Short ) : </label>
				<div class="controls">
					<input type="text" name="short_name" class="span3" placeholder="Enter" value="<?php isset($this->params['short_name']) and printf($this->params['short_name']);?>">
				</div>
			</div>
		</div>

		<div class="span6">
			<div class="control-group">
				<label class="control-label">Client Level : </label>
				<div class="controls">
					<select class="span3" name="level">
						<option value=""> Selected Client Level </option>
						<option value="A" <?php if (isset($this->params['level']) and $this->params['level']== 'A' ):?> selected <?php endif;?> >A</option>
						<option value="B" <?php if (isset($this->params['level']) and $this->params['level']== 'B' ):?> selected <?php endif;?> >B</option>
						<option value="C" <?php if (isset($this->params['level']) and $this->params['level']== 'C' ):?> selected <?php endif;?> >C</option>
						<option value="D" <?php if (isset($this->params['level']) and $this->params['level']== 'D' ):?> selected <?php endif;?> >D</option>
						<option value="Other" <?php if (isset($this->params['level']) and $this->params['level']== 'Other' ):?> selected <?php endif;?> >Other</option>
					</select>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">Actual Cooperate Date Form : </label>
				<div class="controls">
					<input type="text" class="span3 form-control date" name="cooperate_date_form" placeholder="DD / MM / YYYY" value="<?php isset($this->params['date_form']) and printf($this->params['date_form']);?>">
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">Actual Cooperate Date To : </label>
				<div class="controls">
					<input type="text" class="span3 form-control date" name="cooperate_date_to" placeholder="DD / MM / YYYY" value="<?php isset($this->params['date_to']) and printf($this->params['date_to']);?>">
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">Client Status</label>
				<div class="controls">
					<select class="span3" name="status">
						<option value=""> Selected Status </option>
						<option value="1" <?php if (isset($this->params['status']) and $this->params['status']== 1 ):?> selected <?php endif;?> >Official</option>
						<option value="2" <?php if (isset($this->params['status']) and $this->params['status']== 2 ):?> selected <?php endif;?> >Freeze</option>
						<option value="3" <?php if (isset($this->params['status']) and $this->params['status']== 3 ):?> selected <?php endif;?> >Close</option>
					</select>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="span8">
				<div class="controls">
					<button type="submit" class="btn btn-primary">Search</button>
					<button type="submit" class="btn btn-success" name="export" value="1"> Export </button>
				</div>
			</div>
		</div>

	</div>
</form>



<script type="text/javascript" src="<?php echo HOST ?>js/jets.js"></script>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap.min.js"></script>

<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>

<script type="text/javascript">
	$(window).ready(function() {
		$( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });
	});
</script>