<style>

a{
    margin-right: 2.5px;
    margin-left: 2.5px;
}
.status_confirm{
    width: 70px;
    background: #99ff66;
    text-align: center;
}
.status_wait{
    width: 70px;
    background: #fff966;
    text-align: center;
}
.status_cancel{
    width: 70px;
    background: #ff8c66;
    text-align: center;
}
.hilight
{
    background: #E8ADAA;
    /*color:white;*/
}
.hilight:hover
{
    /*color:black;*/
}
</style>

<table class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
                '#',
                'privileges_sn'  => 'Privileges No',
                'company_name'  => 'Company Name',
                'sales_order_no'  => 'Sales Order No',
                'staff_code'  => 'Staff Code',
                'staff_name'  => 'Staff Name',
                'province_name'  => 'เขต',
                'cat_name'  => 'ประเภทสินค้า',
                'discount_type'  => 'ส่วนลด',
                'sum_qty'  => 'QUANTITY',
                'total_amount'  => 'Total Amount',
                'create_date'  => 'Request Date',
                'status'  => 'Status',
                'hr_confirm_date'  => 'HR Confirm Date',
                'hr_name' => 'HR Name',
                'remark'  => 'หมายเหตุ',      
                'Action'
            ),
            $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php
        $statuses = unserialize(DISCOUNT_STATUS);
        if (isset($this->get_resule) and $this->get_resule) :
            $row=1;
            foreach ($this->get_resule as $k=>$m):

/*
1 รอแนบใบเปย์
2 รอ HR อนุมัติ
3 เปิดบิลแล้ว รอจัดสินค้า
4 สินค้ารอการจัดส่ง
5 ได้รับสินค้าแล้ว
6 ยกเลิก
*/
        
                $pre_status = "";
                $textpre_status = '-';
                $action_frm="";
                if(isset($m['status_order']) && $m['status_order']&& $m['status_order']==1){
                    $pre_status=1;
                    $textpre_status = 'รอแนบใบเปย์';
                    $action_frm="confirm";
                }else if(isset($m['status_order']) && $m['status_order']&& $m['status_order']==2){
                    $pre_status=2;
                    $textpre_status = 'รออนุมัติ';
                    $action_frm="confirm";
                }else if(isset($m['status_order']) && $m['status_order']&& $m['status_order']==3){
                    $pre_status=3;
                    $textpre_status = 'เปิดบิลแล้ว';
                    $action_frm="view";
                }else if(isset($m['status_order']) && $m['status_order']&& $m['status_order']==4){
                    $pre_status=4;
                    $textpre_status = 'สินค้ารอการจัดส่ง';
                    $action_frm="view";   
                }else if(isset($m['status_order']) && $m['status_order']&& $m['status_order']==5){
                    $pre_status=5;
                    $textpre_status = 'ได้รับสินค้าแล้ว';
                    $action_frm="view";      
                }else if(isset($m['status_order']) && $m['status_order']&& $m['status_order']==6){
                    $pre_status=6;
                    $textpre_status = 'ยกเลิก';
                    $action_frm="view";
                }

                if($m['cat_id']=="11"){
                    $cat_name="Phone";
                }else{
                    $cat_name="Acc";
                }

                if($m['discount_type']=="0"){
                    $discount_type="EOL";
                }else{
                    $discount_type=$m['discount_type']."%";
                }
                ?>


                <tr>
                    <td><?php echo $row; ?></td>
                    <td><?php echo $m['privileges_no'] ?></td>
                    <td><?php echo $m['company_name'] ?></td>
                    <td><?php echo $m['sales_order_no'] ?></td>
                    <td><?php echo $m['staff_code'] ?></td>
                    <td><?php echo $m['staff_name'] ?></td>
                    <td><?php echo $m['provice_name'] ?></td>
                    <td style="text-align: center;"><?php echo $cat_name ?></td>
                    <td style="text-align: center;"><?php echo $discount_type ?></td>
                    <td style="text-align: center;" ><?php echo $m['sum_qty'] ?></td>
                    <td style="text-align: right;" ><?php echo number_format($m['total_amount'],2) ?></td>
                    <td><?php echo $m['create_date'] ?></td>
                    <td><input class="<?php 
                    if($pre_status==2){echo 'status_wait';
                    }else if($pre_status==3){echo 'status_confirm';
                    }else if($pre_status==4){echo 'status_confirm';
                    }else if($pre_status==5){echo 'status_confirm';
                    }else if($pre_status==6){echo 'status_cancel';
                    }else{echo 'status_wait';}
                    ?>" 
                    id="status-<?=$i;?>" 
                    type="text" value="<?=$textpre_status;?>"></td>
                    <td><?php echo $m['hr_confirm_date'] ?></td>
                    <td><?php echo $m['hr_name'] ?></td>
                    <td><?php echo $m['remark'] ?></td>
                    
                    <td style="text-align: center;" >
                        <a title="View Order"  href="/sales/staff-sales-order-list-view?action_frm=<?php echo $action_frm;?>&privileges_sn=<?php echo $m['privileges_sn'];?>&company_id=<?php echo $m['company_id'];?>"> <i class="icon-qrcode" style="color: red;"></i></a>

                        <!-- <a class="show-payment-slip getImgPaymentOne" data-toggle="modal" data-sn="'<?php echo $m['privileges_sn'];?>'" data-payment_no="<?php echo $m['privileges_no'];?>" href="#" title="Show Image Payslip"> <i class="icon-book"></i></a> -->
                    </td>

                </tr>
                <?php 
                $row +=1;
            endforeach;
            ?>
        <?php endif; ?>
    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<script type="text/javascript" src="/js/jets.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>

<script>
    

    $(document).ready(function () {
        
        //alert(1);
        $('.btn-confirm-status').click(function(event)
        {
            
            var creditnote_sn = [];
            $('.checkbox-confirm:checked').each(function(index, el) {
                creditnote_sn.push($(el).val());
            });

            if(creditnote_sn.length > 0){
                if (confirm('Are you sure?')) {

                    $.ajax({
                        url: '<?php echo HOST.'finance/creditnote-status';?>',
                        type: 'POST',
                        data: {'d_id':<?=$this->distributor['id'];?>,'creditnote_sn':creditnote_sn},
                    })
                    .done(function(response) {

                    });

                }
            }else{
                alert('กรุณาเลือกรายการที่ต้องการ');
            }

        });    
    });


    



</script>