<form action="<?php echo HOST ?>sales/target-view" class="form-horizontal form-search">
    <div class="control-group">
        <label class="control-label" for="area_id">Area</label>
        <div class="controls">
            <select name="area_id" id="area_id">
                <option value>---</option>
                <?php if (isset($this->areas) && $this->areas): ?>
                    <?php foreach ($this->areas as $key => $value): ?>
                        <option value="<?php echo $key ?>" <?php if (isset($this->params['area_id']) && $this->params['area_id']== $key)  
                                            echo "selected" ?>><?php echo $value ?></option>
                    <?php endforeach ?>
                <?php endif ?>
            </select>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="name">Distributor</label>
        <div class="controls">
            <input type="text" id="name" name="name" placeholder="Distributor name" value="<?php if (isset($this->params['name']) && $this->params['name']) echo $this->params['name'] ?>">
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button class="btn btn-primary">Search</button>
            <button class="btn btn-success" name="export" value="1">Export</button>
            <button class="btn btn-warning" type="reset">Reset</button>
        </div>
    </div>
</form>