<style>

a{
    margin-right: 2.5px;
    margin-left: 2.5px;
}
.status_enable{
    width: 70px;
    background: #99ff66;
    text-align: center;
}
.status_disable{
    width: 70px;
    background: #ff8c66;
    text-align: center;
}
.hilight
{
    background: #E8ADAA;
    /*color:white;*/
}
.hilight:hover
{
    /*color:black;*/
}
</style>
<div class="table-responsive">
    <?php
        $userStorage = Zend_Auth::getInstance()->getStorage()->read();
        if (My_Staff_Group::inGroup($userStorage->group_id, array(ADMINISTRATOR_ID, CHECK_MONEY)) or ($exception_case and in_array
        ($userStorage->id, $exception_case))){
            $view_import="";
        }else{
            $view_import='style="display: none;"';
        }
    ?>
    <span <?php echo $view_import; ?> class="pull-left">
        <button class="btn btn-success" type="button" onclick="window.location='<?php echo HOST ?>sales/wht-manual-upload-list'">
            Import Withholding Tax File
        </button>
    </span>
</br></br>
    <span class="pull-right" style="display: none;">
        <button class="btn btn-info btn-confirm-status" value="1" id="btn-confirm-enable" type="button">เปิดใช้งาน</button>&nbsp;

        <button class="btn btn-danger btn-confirm-status" value="0" id="btn-confirm-disable" type="button">ปิดใช้งาน</button>
    </span>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
                    '#',
                    'running_no'  => 'Running No',
                    'import_name'  => 'ชื่อหัวข้อการนำเข้าข้อมูล',
                    'distributor_id'  => 'Distributor ID',
					'distributor_name'  => 'Distributor Name',
                    'payment_name_01'  => '01 ชื่อค่าใช้จ่าย',
                    'payment_price_01'  => '01 ยอดเงิน',
                    'payment_wht_vat_01'  => '01 ภาษี ณ ที่จ่าย',
                    'payment_name_02'  => '02 ชื่อค่าใช้จ่าย',
                    'payment_price_02'  => '02 ยอดเงิน',
                    'payment_wht_vat_02'  => '02 ภาษี ณ ที่จ่าย',    

                    'payment_price_total'  => 'รวมยอดเงิน',
                    'payment_wht_vat_total'  => 'รวมภาษี ณ ที่จ่าย',    

                    'create_by' => 'Import By',
                    'create_date' => 'Import Date',
                     'Action'
                ),
                $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php
        $statuses = unserialize(DISCOUNT_STATUS);
        if (isset($this->get_resule) and $this->get_resule) :
            foreach ($this->get_resule as $k=>$m):

                $payment_price_01= $m['payment_price_01'];
                $payment_wht_vat_01= $m['payment_wht_vat_01'];

                $payment_price_02= $m['payment_price_02'];
                $payment_wht_vat_02= $m['payment_wht_vat_02'];
                
                $payment_price_total = ($payment_price_01 + $payment_price_02);
                $payment_wht_vat_total = ($payment_wht_vat_01 + $payment_wht_vat_02);

                if($m['distributor_id']=='0'){
                    $distributor_id='';
                }else{
                    $distributor_id=$m['distributor_id'];
                }
            ?>

            <tr>
                <td>#</td>
                <td><?php echo $m['wht_running_no'] ?></td>
                <td><?php echo $m['import_name'] ?></td>
                <td><?php echo $distributor_id ?></td>
                <td><?php echo $m['distributor_name'] ?></td>
                <td><?php echo $m['payment_name_01'] ?></td>
                <td><?php echo number_format($m['payment_price_01'],2) ?></td>
                <td><?php echo number_format($m['payment_wht_vat_01'],2) ?></td>
                <td><?php echo $m['payment_name_02'] ?></td>
                <td><?php echo number_format($m['payment_price_02'],2) ?></td>
                <td><?php echo number_format($m['payment_wht_vat_02'],2) ?></td>

                <td><?php echo number_format($payment_price_total,2) ?></td>
                <td><?php echo number_format($payment_wht_vat_total,2) ?></td>

                <td><?php echo $m['staff_name'] ?></td>
                <td><?php echo $m['create_date'] ?></td>               
                <td><a title="Print" target="_blank" href="/sales/print-withholding-tax?wht_sn=<?php echo $m['wht_sn'];?>"> <i class="icon-print" style="color: red"></i></a></td>
                
            </tr>
        <?php endforeach;?>
		<?php endif; ?>
    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<script type="text/javascript" src="/js/jets.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>

<script>
    

$(document).ready(function () {
    
     
});


</script>