<style>

a{
    margin-right: 2.5px;
    margin-left: 2.5px;
}
.status_enable{
    width: 70px;
    background: #99ff66;
    text-align: center;
}
.status_disable{
    width: 70px;
    background: #ff8c66;
    text-align: center;
}
.hilight
{
    background: #E8ADAA;
    /*color:white;*/
}
.hilight:hover
{
    /*color:black;*/
}
</style>


<table class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
                    '#',
					'title'  => 'Retailer Name',
                    'deposit_sn'  => 'Deposit No',
					'total_amount'  => 'Total Amount',
                    'use_total'  => 'Total Used',
                    'balance_total' => 'Total Balance',
                    'status' => 'Status',
                    'update_date' => 'Update Date',
                    'confirm_date' => 'Confirm Date',
                    'action' => 'ACTION'
                    
                ),
                $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php
        $statuses = unserialize(DISCOUNT_STATUS);
        if (isset($this->get_resule) and $this->get_resule) :
            foreach ($this->get_resule as $k=>$m):

                $confirm_status = false;
                $textConfirm_status = 'ไม่เปิดใช้งาน';

                if(isset($m['status']) && $m['status']&& $m['status']==1){
                    $confirm_status = true;
                    $textConfirm_status = 'เปิดใช้งาน';
                }
                if($m['confirm_date'] ==""){
                    $confirm_status = false;
                    $textConfirm_status = 'รออนุมัติ';
                }
            ?>
            <tr>
                <td>#</td>
                <td><?php echo $m['title'] ?></td>
                <td><?php echo $m['deposit_sn'] ?></td>
                <td><?php echo $m['total_amount'] ?></td>
                <td><?php echo $m['use_total'] ?></td>
                <td><?php echo $m['balance_total'] ?></td>
                 <td><input class="<?php if($confirm_status){echo 'status_enable';}else{echo 'status_disable';}?>" id="confirmStatus-<?=$i;?>" type="text" value="<?=$textConfirm_status;?>"  ></td>
                <td><?php echo $m['update_date'] ?></td>
                <td><?php echo $m['confirm_date'] ?></td>
                <td><a title="Edit" href="/finance/deposit-confirm?deposit_sn=<?php echo $m['deposit_sn'];?>&view_status=<?=$this->params['view_status']?>"> <i class="icon-edit"></i></a></td>
                

            </tr>
        <?php endforeach;?>
		<?php endif; ?>
    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<script type="text/javascript" src="/js/jets.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>

<script>
    

    $(document).ready(function () {
        
        alert(1);
        $('.btn-confirm-status').click(function(event)
        {
            
            var deposit_sn = [];
            $('.checkbox-confirm:checked').each(function(index, el) {
                deposit_sn.push($(el).val());
            });

            if(deposit_sn.length > 0){
                if (confirm('Are you sure?')) {

                    $.ajax({
                        url: '<?php echo HOST.'sales/deposit-status';?>',
                        type: 'POST',
                        data: {'d_id':<?=$this->distributor['id'];?>,'deposit_sn':deposit_sn},
                    })
                    .done(function(response) {

                    });

                }
            }else{
                alert('กรุณาเลือกรายการที่ต้องการ');
            }

        });    
    });

    /*$('#btn-confirm-enable').click(function(event) {
                
            deposit_sn = [];

            $('.checkbox-confirm:checked').each(function(index, el) {
                deposit_sn.push($(el).val());
            });

            if(deposit_sn.length > 0){

                if (confirm('Are you sure?')) {

                    $.ajax({
                        url: '<?php echo HOST.'sales/deposit-status';?>',
                        type: 'POST',
                        data: {'d_id':<?=$this->distributor['id'];?>,'deposit_sn':deposit_sn},
                    })
                    .done(function(response) {
                        var obj_response = jQuery.parseJSON(response);
                        console.log("success");

                        console.log(obj_response.status);

                         switch(obj_response.status){
                            case '400':
                                alert(obj_response.message);
                                console.log(obj_response.message);
                                break;
                            case '201':
                                window.location.href = obj_response.url;
                                break;
                            default:
                                console.log('ajax fail.');
                        }
                        
                    });

                }

            }else{
                alert('กรุณาเลือกรายการที่ต้องการ');
            }

        });*/
      

    



</script>