<table class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
                    '#',
                    'SO',
                    'Distributor',
                    'Finance Confirm Date',
                    'Due Payment Date',
                    'Credit Day',
                    'total'
                    
                ),
                $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php
        if (isset($this->due) and $this->due)
            foreach ($this->due as $k=>$item): 

        $sn_ref = $PO['sn_ref'];
         if($sn_ref==''){
            $sn_ref = $PO['sn'];
         }
            ?>
        <tr>
            <td><?php
                    $inc = $this->offset + $k + 1;
                    echo $inc;
                ?></td>
            <td><?php echo $item['sn_ref'];?></td>
            <td><?php echo $item['title'];?></td>
            <td><?php echo $item['finance_confirm_date'];?></td>
            <td><?php echo $item['pay_date'];?></td>
            <td><?php echo $item['credit']. ' day';?></td>
            <td><?php echo number_format($item['total'],2);?></td>
           
        </tr>
        <?php endforeach;?>

    </tbody>
</table>
<div class="paging">
    <!-- <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?> -->
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
