<form class="form-search form-horizontal" method="POST" action="/finance/due-payment-order">

    <div class="row">
        <div class="span5">
           
            <div class="control-group">
                <label for="pay_date" class="span2">Due Payment From</label>
                <input type="text" class="form-control search-query date" id="due_from" name="due_from" value="<?php isset($this->params['due_from']) and printf($this->params['due_from']);?>">
            </div>
        </div>
        <div class="span5">
            <div class="control-group">
                <label for="pay_date" class="span2">Due Payment To</label>
                <input type="text" class="form-control search-query date" id="due_to" name="due_to" value="<?php isset($this->params['due_to']) and printf($this->params['due_to']);?>">
            </div>
        </div>
        <div class="span5">

            <div class="control-group">
                <label for="pay_date" class="span2">Due Payment To</label>
                <select name="d_id">
                    <option></option>
                    <?PHP foreach ($this->distributor as $key => $value) {?>
                        <option value="<?=$key?>"<?=$this->params['d_id']==$key?'selected':''?>><?=$value?></option>
                    <?PHP } ?>
                    <option></option>
                </select>
            </div>
      
          <!--   <div class="control-group">
                <label for="warehouse_id" class="span2">Warehouse</label>
                <select name="warehouse_id" id="warehouse_id" class="span3">
                    <option value="">Choose</option>
                    <?php if ($this->warehouses): foreach ($this->warehouses as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['warehouse_id']) and $id==$this->params['warehouse_id']):?> selected<?php endif;?>><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select> -->
            </div>
            
           
        </div>
    

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
</form>
<script>
    $(document).ready(function () {
        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

    });
</script>