<style>
    iframe {
        width: 100%;
        height: 300px;
    }

    .bar {
        line-height: 18px;
    }
    .modal-scrollable
    {
        position: absolute;
        z-index: 9999;
    }
</style>
<div class="page-header">
    <h1>Upload OPPO All Green Reward</h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="well">
    <div class="row-fluid">

        <div class="span4">
            List of uploaded files <a class="btn btn-success btn-mini" href="<?php echo HOST ?>file-log/oppo-all-green">View Logs</a></p>
            Accessories Protection Price Template <a class="btn btn-success btn-mini" href="<?php echo HOST ?>upload/file_template/oppo_all_grren_template.xlsx">Download File</a></p>


        </div>

    </div>
</div>

<form action="<?php echo HOST ?>finance/oppo-all-green-save" id="form" target="iframe" class="form-inline" method="post" enctype="multipart/form-data">

    <div class="row">
        <div class="span6">
            <div class="form-group">
                <label for="" class="span4">
                    <input type="checkbox" id="generateCN" name="generateCN" value="1" checked> Auto Generate CN
                    <span id="active"><input type="checkbox" id="activeCN" name="activeCN" value="1" checked> Active CN </span>
                </label><br>
                <label for="" class="span4">File <span style="color: red">*</span>
                    <input type="file" class="span4" name="file" id="file" required />
                </label>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="form-group">
        <button type="submit" class="form-control btn btn-primary" id="submit">Save</button>
        <a href="/finance/oppo-all-green" class="btn btn-danger">Go back</a>
    </div>
</form>
<a href="/finance/oppo-all-green-upload" class="btn btn-primary upload" >Upload</a>
<a href="/finance/oppo-all-green" class="btn btn-danger upload" >Go back</a>
<br><br>


<div class="row">
    <div class="span12">
        <div class="progress progress-striped active">
            <div class="bar" style="width: 0%;"></div>
        </div>
    </div>
</div>

<iframe src="" frameborder="0" name="iframe" id="iframe"></iframe>

<script src="<?php echo HOST ?>js/jquery-ui.js"></script>
<script src="<?php echo HOST ?>js/bootstrap-modal.js"></script>
<script src="<?php echo HOST ?>js/bootstrap-modalmanager.js"></script>
<script type="text/javascript" src="<?php echo HOST ?>js/sales.po.js"></script>

<script>
function set_progress(percent) {
        $('.bar').css('width', percent+'%');
        $('.bar').html(percent+'%');
    }
    $(document).ready(function () {
$(".upload").hide();
$("#submit").click(function(){
    if( $('#file').val() != ""){
       $( ".form-inline" ).hide();
       $(".upload").show();
   }
});

        $( "#generateCN" ).click(function() {
          $( "#active" ).toggle();
        });

        $('form').bind('submit',function(e){
            $('.bar').css('width', '0%');
            $('.bar').html('');
            $('#iframe').get(0).contentWindow.clear_content();
            $('form button, form input, form select').prop('readonly', true);
            $('.loading').remove();
            $(this).after('<span class="pre_loading">Processing <span><span class="loading"></span>');
            window.onbeforeunload = confirmExit;
        });
        $('#add_po_btn').click(show_add_joint_modal);
    });

</script>