<link href="../css/select2.css" rel="stylesheet"/>
<script src="../js/select2.js"></script>
<form class="form-search form-horizontal" method="get" action="<?php echo HOST ?>finance/oppo-all-green">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="year" class="span2">Year</label>
                <input id="year" name="year" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['year']) and printf($this->params['year']);?>">
            </div>

        </div>
        <div class="span5">
            <div class="control-group">
                <label for="air_number" class="span2">Air Number</label>
                <input id="air_number" name="air_number" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['air_number']) and printf($this->params['air_number']);?>">
            </div>

        </div>
    </div>
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="cn" class="span2">Creditnote SN</label>
                <input id="cn" name="cn" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['cn']) and printf($this->params['cn']);?>">
            </div>
            <div class="control-group">
                <label for="created_at_from" class="span2">Create Time From</label>
                <input type="text" class="form-control search-query date" id="created_at_from" name="created_at_from" value="<?php isset($this->params['created_at_from']) and printf($this->params['created_at_from']);?>">
            </div>
            <div class="control-group">
                <label for="created_at_to" class="span2">Create Time To</label>
                <input type="text" class="form-control search-query date" id="created_at_to" name="created_at_to" value="<?php isset($this->params['created_at_to']) and printf($this->params['created_at_to']);?>">
            </div>
        </div>
        <div class="span5">
            <div class="control-group">
                <label for="d_id" class="span2"> Distributor Name
					<input type='text' class="span4" name='SearchBox' id="SearchBox" placeholder="Search" autocomplete="off" />
					<select name="d_id" id="d_id" class="span3" size='5'>
						<option value="">Choose</option>
						<?php if (isset($this->distributors) && $this->distributors): foreach ($this->distributors as $id=>$name):?>
							<option value="<?php echo $id;?>" <?php if (isset($this->params['d_id']) and $id==$this->params['d_id']):?> selected="selected"<?php endif;?>><?php echo $name;?></option>
						<?php endforeach; endif;?>
					</select>
				</label>
            </div>

        </div>
    </div>
    

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
    <button type="submit"  name="export" value="1" class="btn btn-success">Export</button>
</form>
<style>
	#d_id {
	left: 0px !important;
	width: 360px;
	margin: 20px 0px 0px;
}
</style>
<script>
    $(document).ready(function () {
        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });
        initSearchOptionDistributor('d_id', 'SearchBox');

        $('#cat_id, #good_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var cat_id = $('#cat_id').val();

            if (_self.attr('id')=='cat_id')
                $('#good_id').find('option:not(:first)').remove();

            var good_id = $('#good_id').val();

            $('#good_color').find('option:not(:first)').remove();

            $('#num, #price').val('');

            $.get("/get/load",
                {cat_id: cat_id, good_id: good_id}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    if (data.goods){
                        var obj = data.goods;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    if (data.colors){
                        var obj = data.colors;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    _self.nextAll('.loading').remove();
                });
        });
    });
</script>
<script>
        //$(document).ready(function() { $("#d_id").select2(); });
    </script>