<style>

</style>
<div class="page-header">
    <h1>Force Sale</h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="row">
    <div class="span12">
        <span class="pull-right">
            <?php if ($this->access('bvg', 'mass')) {?>
                <button class="btn btn-info" type="button" onclick="window.location='<?php echo HOST ?>force-sale/create'">
                    Create Force Sale
                </button>
            <?php } ?>

        </span>
    </div>
</div>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('force-sale/partials/search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>
<div class="table-responsive">
    <?php
        echo $this->render('force-sale/partials/list.phtml');
    ?>
</div>

<script>
    $(document).ready(function () {     
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
        initSearchOptionDistributor('distributor_id', 'SearchBox');
    });
</script>