<style>
.red
{
    background: #1B8324;
    color:white;
}
.red:hover
{
    color:black;
}
</style>
<!-- BANK -->
<table class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
                    '#',
                    'p.id'            => 'Sale ID',
                    'p.sn_ref'            => 'Sale Order Number',
                    'title'          => 'Retailer Name',
                     'Product Name',
                     'Product Color',
                    'sum'           => 'Sales Quantity',
                    'total_price'         => 'Sales Price',
                    'total_amount'         => 'Total Amount',
                    'name'  => 'Warehouse',
                    /*'outmysql_time' => 'Out of Warehouse',*/
                    'date_canceled'          => 'Cancel Time',
                     'Cancel By',
                     'Remark',
                     'Cancel Confirm By',
                     'cancel_delivery_date'          => 'Cancel Confirm TIME',
                    'Action'
                ),
                $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php

        $statuses = unserialize(DISCOUNT_STATUS);
        if (isset($this->markets_sn) and $this->markets_sn) :
            foreach ($this->markets_sn as $k=>$m):
             $dt = DateTime::CreateFromFormat("Y-m-d H:i:s", isset($m['last_updated_at']) ? $m['last_updated_at'] : $m['add_time']);
             $h = $dt->format('H');
             $i = $dt->format('i');
             $d = $dt->format('d');
             $date = date('d');

             $sn_ref = $m['sn_ref'];
             if($sn_ref==''){
                $sn_ref = $m['sn'];
             }

             $total_amount = $m['total_price_amount'] - $m['total_discount'] + $m['delivery_fee'];
             if($m['delivery_fee']>0){
                $delivery_fee ="Delivery fee = ".$m['delivery_fee'];
             }else{
                $delivery_fee ="";
             }

             //print_r($m);
            ?>
            <tr class="<?php
                    if(isset($h) and isset($i) and ($h >= 16))
                       {
                            if($date == $d)
                            {
                                if($h==16 and $i>=30)
                                    echo 'red';
                                else if($h > 16)
                                    echo 'red';
                            }                            
                       }
            ?>">
                <td><a href="#id" rel="<?php echo $m['sn'] ?>" class="collapse_a btn btn-default btn-small" id="m_<?php echo $m['sn'] ?>"><span class="col-sign">+</span><img class="img-loading" src="<?php echo HOST?>img/ajax-loader.gif" style="display: none" /></a></td>
                 <td><?php echo $m['id'] ?></td>
                <td><?php echo $sn_ref ?></td>
                <td><?php echo $m['title']?></td>
                <td></td>
                <td></td>
                <td><?php echo $m['sum'] ?></td>
                <td></td>
                <td><?php echo My_Number::f($m['total_price']) ?></td>
                <td><?php echo $m['name'] ?></td>
                <td><?php echo $m['date_canceled'];?></td>
                <td><?php echo $m['name_cancel'] ?></td>
                <td> <?php echo $m['canceled_remark']?></td>
                <td><?php echo $m['name_cancel_kerry'] ?></td>
                <td><?php echo $m['cancel_delivery_date'] ?></td>
                <td>
                <?php if( $m['cancel_delivery_status'])
                    {
                        echo "<center><button class='btn-default'>Confirmed</button></center>";
                    }
                    else { ?>
                        <center><a data-toggle="modal" data-sn="'<?php echo $m['sn'];?>'" title="Mark Canceled" class="open-cancel" href="#cancelSO"><button class='btn-info'>View</button></a></center>
                   <?php }
                ?>
                </td>
            </tr>

        <?php endforeach;?>
        <?php endif; ?>
    </tbody>
</table>
<div class="paging">
<?php 
// print_r($this->total. $this->limit.$this->offset. $this->url) ;?>
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<?php echo $this->load();?>
<?php echo $this->confirm();?>
