<style type="text/css">
    #distributor_id,
    #SearchBox {
        display: block;
    }

    #distributor_id {
        margin-bottom: 0;
    }
</style>

<div class="page-header">
    <h1>Distributor Code Mapping <small>For Mass Order Upload</small></h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="row">
    <div class="span12">
        <span class="pull-right">
            <button class="btn-success" type="button" onclick="window.location='<?php echo HOST ?>mapping/fpt-store-create'">
                <i class="icon-plus"></i>
            </button>
        </span>
    </div>
</div>


<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <div class="row">
                    <div class="span12">
                        <form action="<?php echo HOST ?>mapping/fpt-store" action="get" class="form-horizontal form-search">
                            <div class="control-group">
                                <label class="control-label" >Distributor name</label>
                                <div class="controls">
                                    <input type='text' class="" name='SearchBox' id="SearchBox" placeholder="Search" autocomplete="off" />
                                    <select name="distributor_id" class="" id="distributor_id" size="5">
                                        <option value="">Please select</option>
                                        <?php
                                            foreach($this->distributors as $_id => $distributor):
                                                $selected = '';
                                                if(isset($this->params['distributor_id']) and $_id == $this->params['distributor_id']){
                                                    $selected = 'selected';
                                                }
                                                echo '<option '.$selected.' value="'.$_id.'" title="'.$distributor.'">'.$distributor.'</option>';
                                            endforeach;
                                        ?>
                                    </select>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Code</label>
                                <div class="controls">
                                    <input type="text" class="" placeholder="Code" name="code"
                                        value="<?php if(isset($this->params['code'])) echo trim($this->params['code']) ?>">
                                </div>
                            </div>
                            <div class="control-group">
                                <div class="controls">
                                    <button class="btn btn-info">Search</button>
                                    <button class="btn btn-danger reset" type="reset">Reset</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="span12">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <?php echo $this->sorting(array(
                        '#',
                        'code' => 'Code',
                        'distributor_name' => 'Distributor Name',
                        'Address',
                        'Action'
                    ),
                    $this->url, $this->sort, $this->desc); ?>
                </tr>
            </thead>
            <tbody>
                <?php if (isset($this->mapping) && $this->mapping): ?>
                    <?php foreach ($this->mapping as $key => $value): ?>
                        <tr>
                            <td><?php
                                    $inc = $this->offset + $key + 1;
                                    echo $inc;
                                ?>
                            </td>
                            <td><?php echo $value['code'] ?></td>
                            <td><?php echo $value['title'] ?></td>
                            <td><?php echo $value['add'] ?></td>
                            <td>
                                <a title="Edit" href="<?php echo HOST ?>mapping/fpt-store-edit?distributor_id=<?php echo $value['distributor_id'];?>"> <i class="icon-edit"></i></a>
                                <a title="Delete" class="confirmLink" href="<?php echo HOST ?>mapping/fpt-store-delete?distributor_id=<?php echo $value['distributor_id'];?>"> <i class="icon-trash"></i></a>
                            </td>
                        </tr>
                    <?php endforeach ?>
                <?php endif ?>
            </tbody>
        </table>
        <div class="paging">
            <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
        </div>
    </div>
</div>

<script type="text/javascript" src="<?php echo HOST ?>js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo HOST ?>css/jquery-ui-1.8.12.custom.css"/>
<?php echo $this->confirm();?>
<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        initSearchOptionDistributor("distributor_id", "SearchBox");
    });
</script>