<form id="form" name="form" class="form-search form-horizontal" action="<?php echo HOST ?>product/hold-product">
	<div class="row">
		<div class="span5"> 
			<div class="control-group">
				<label class="control-label" for="name">Name</label>
				<div class="controls">
					<input type="text" id="name" name="name" placeholder="Name" <?php if( isset($this->params['name']) && $this->params['name'] ) echo 'value="'.$this->params['name'].'"' ?> />
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="details">Details</label>

				<div class="controls">
					<input type="text" id="details" name="details" placeholder="Details" <?php if( isset($this->params['details']) && $this->params['details'] ) echo 'value="'.$this->params['details'].'"' ?> />
				</div>
			</div>
		</div>
        <div class="span5">
            <div class="control-group">
                <label for="cat_id" class="span2">Product Category</label>
                <select id="cat_id" class="span3" name="cat_id">
                    <option value="">Choose</option>
                    <?php if ($this->good_categories): foreach ($this->good_categories as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['cat_id']) and $id==$this->params['cat_id']):?> selected<?php endif;?>><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">
                <label for="good_id" class="span2">Product</label>
                <select id="good_id" class="span3" name="good_id">
                    <option value="">Choose</option>
                    <?php if ($this->goods): foreach ($this->goods as $item):?>
                        <option value="<?php echo $item->id;?>" <?php if (isset($this->params['good_id']) and $item->id==$this->params['good_id']):?> selected<?php endif;?>><?php echo $item->name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">
                <label for="good_color" class="span2">Color</label>
                <select id="good_color" class="span3" name="good_color">
                    <option value="">Choose</option>
                    <?php if ($this->colors): foreach ($this->colors as $item):?>
                        <option value="<?php echo $item->id;?>" <?php if (isset($this->params['good_color']) and $item->id==$this->params['good_color']):?> selected<?php endif;?>><?php echo $item->name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>
            <div class="control-group">
                <label for="good_color" class="span2">Hold</label>
               <input type="checkbox"  name="hold" value="1" <?php if (isset($this->params['hold']) && $this->params['hold']) echo "checked" ?>> 
            </div>
      
        </div>


	</div>

	<div class="row">
        <div class="span10">
            <div class="controls">
				<button type="submit" class="btn btn-primary">Search</button>
			    <button type="reset" class="btn btn-warning">Reset</button>
			    <button type="submit" name="export" value="1" class="btn btn-success">Export</button>
			</div>
		</div>
	</div>
</form>

<script type="text/javascript" src="<?php echo HOST ?>js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" type="text/css" href="<?php echo HOST ?>css/jquery-ui-1.8.12.custom.css"/>
<link href="<?php echo HOST ?>css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="<?php echo HOST ?>css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">
<script>
    $(document).ready(function () {
        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('#cat_id, #good_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var cat_id = $('#cat_id').val();

            if (_self.attr('id')=='cat_id')
                $('#good_id').find('option:not(:first)').remove();

            var good_id = $('#good_id').val();

            $('#good_color').find('option:not(:first)').remove();

            $('#num, #price').val('');

            $.get("/get/load",
                {cat_id: cat_id, good_id: good_id}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    if (data.goods){
                        var obj = data.goods;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    if (data.colors){
                        var obj = data.colors;
                        for (var i = 0; i < obj.length; i++) {
                            $('#good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }
                    _self.nextAll('.loading').remove();
                });
        });

    	$('#area').change(function(){
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();

            $.get("<?php echo HOST ?>get/region",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#region').find('option:not(:first)').remove();
                    $('#district').find('option:not(:first)').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#region').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('.loading').remove();
                });
        });

        $('#region').change(function(){

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var region = _self.val();

            $('#district').find('option:not(:first)').remove();

            $.get("/get/district",
                {region: region}
                ,function(data,status){
                    var data = $.parseJSON( data );

                    for (var i = 0; i < data.length; i++) {
                        $('#district').append('<option value="'+data[i]['id']+'">'+data[i]['name']+'</option>');
                    }

                    _self.nextAll('.loading').remove();
                });
        });

        initTag();
        initSearchOptionDistributor('d_id', 'SearchBox');
	});

    function initTag(){

        $('#myTags').tagit({
            allowSpaces: true,
            fieldName: 'tags[]',
            autocomplete: {
                delay: 0,
                minLength: 2,
                source: "<?php echo HOST;?>get/get-tags"
            }
        });

    }
</script>
