<table class="table table-bordered">
	<thead>
		<tr>
			<th>Distributor Code</th>
			<th>Distributor</th>
			<th>Superior Distributor</th>
			<th>Affiliated Clients</th>
			<th>Distributor Type</th>
			<th>Total Store Quantity</th>
			<th>Cooperative Stores Quantity</th>
			<th>Price System</th>
			<th>Office</th>
			<th>External Serial Number</th>
			<th>Statusr</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>

		<?php if (isset($this->distriubtor) and $this->distriubtor) : ?>
			<?php foreach ($this->distriubtor as $k => $d) : ?>

				<?php

				if ($d['distributor_type'] == 1) {
					$d_type = 'Regional Distributor';
				}elseif ($d['distributor_type'] == 2) {
					$d_type = 'Affiliate';
				}elseif ($d['distributor_type'] == 3) {
					$d_type = 'Retailer';
				}else {
					$d_type = 'Exclusive Distributor';
				}

				if ($d['status'] == 1) {
					$status_type = '<span style="color: green">In Cooperation</span>';
				}elseif ($d['status'] == 2) {
					$status_type = '<span style="color: orange">Suspend Cooperation</span>';
				}else{
					$status_type = '<span style="color: red">Close</span>';
				}

				?>

				<tr>
					<td><?php echo $d['distributor_code'] ?></td>
					<td><?php echo $d['distributor_name'] ?></td>
					<td><?php echo $this->distributor_cache[$d['superior_distributor']] ?></td>
					<td><?php echo $this->client_cache[$d['client_code']] ?></td>
					<td><?php echo $d_type ?></td>
					<td></td>
					<td></td>
					<td><?php echo $d['rank_price'] ?></td>
					<td><?php echo $this->regional[$d['provience_id']] ?></td>
					<td><?php echo $d['external_serial'] ?></td>
					<td><?php echo $status_type ?></td>
					<td>
						<a href="<?php echo HOST ?>sales/distributor-detail?id=<?php echo $d['id'] ?>">Detail</a> |

						<?php if($d['status'] == 1) { ?>
							<a href="<?php echo HOST ?>sales/add-distributor?id=<?php echo $d['id'] ?>">Edit</a> |

						<?php } ?>

						<?php if(in_array($d['status'], array(1,2))) { ?>
						<a href="#myModal" 
							data-id="<?php echo $d['id'] ?>" 
							data-name="<?php echo $d['distributor_name'] ?>" 
							data-event ="close" 
							data-title ="Close Distributor"
							style="color: red;" data-toggle="modal" role="button" class="modal-function" >Close Distributor</a> |

						<?php } ?>

						<?php if(in_array($d['status'], array(1))) { ?>
						<a href="#myModal"
							data-id="<?php echo $d['id'] ?>"
							data-name="<?php echo $d['distributor_name'] ?>"
							data-event="puss"
							data-title="Suspend Distributor"
							style="color: orange;" data-toggle="modal" role="button" class="modal-function" >Suspend Cooperation</a> |

						<?php } ?>

						<?php if(in_array($d['status'], array(3,2))) { ?>

						<a href="#myModal"
						    data-id="<?php echo $d['id'] ?>"
						    data-name="<?php echo $d['distributor_name'] ?>"
						    data-event="restart"
						    data-title="Restart cooperation"
							data-toggle="modal" role="button" class="modal-function" >Restart Cooperation</a>

						<?php } ?>
					</td>
				</tr>

			<?php endforeach ?>
		<?php endif ?>

	</tbody>
</table>

 <div class="paging">
  <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>


<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="ModalLabel"></h3>
	</div>
	<form action="<?php echo HOST.'sales/distributor-event';?>" method="post">
		<div class="modal-body">
			<div class="span5">
				<div class="control-group">
					<label class="control-label span2">Distributor :  </label>
					<div class="controls">
						<input type="text" name="d_name" id="d_name" value="" readonly />
					</div>
				</div>

				<div class="control-group">
					<label class="control-label span2">Reason : </label>
					<div class="controls">
						<textarea cols="2" rows="2" name="remark"></textarea>
					</div>
				</div>
				<p style="color: orange;">Close Distributor is irrevocable. Please enable it with</p>
			</div>

		</div>
		<div class="modal-footer">
			<input type="hidden" name="id" id="d_id">
			<input type="hidden" name="event" id="event">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			<button class="btn btn-success">Save changes</button>
		</div>
	</form>

</div>

<script type="text/javascript">
	$(document).on("click", ".modal-function", function () {
		var Id = $(this).data('id');
		var Name = $(this).data('name');
		var Event = $(this).data('event');
		var Title = $(this).data('title');

		$(".modal-body #d_name").val(Name);
		$("#d_id").val(Id);
		$("#event").val(Event);
		$("#ModalLabel").text(Title);

	});
</script>