<form class="form-horizontal" onsubmit="return false;" id="create_po_form">
    <!-- 
    <div class="control-group">
        <label class="control-label">Retailer name</label>
        <div class="controls">
            <input type='text' name='SearchBox_modal' id="SearchBox_modal" placeholder="Search" autocomplete="off" />
            <select name="distributor_id_modal" id="distributor_id_modal" required size="5">
                <option value="">Please select</option>
                <?php
                /*
                    foreach($this->distributors as $distributor):
                        $selected = '';
                        if(isset($this->distributor_id) and $distributor['id'] == $this->distributor_id){
                            $selected = 'selected';
                        }
                        echo '<option '.$selected.' value="'.$distributor['id'].'">'.$distributor['title'].'</option>';
                    endforeach;
                */    
                ?>
            </select>
        </div>
    </div>
    -->    
    <div class="control-group">
        <label class="control-label">PO Number</label>
        <div class="controls">
            <input type='text' name='po_name_modal' id="po_name_modal" placeholder="PO Name" required />
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">Note</label>
        <div class="controls">
            <textarea id="note_modal"></textarea>
        </div>
    </div>

    <div class="control-group">
        <p id="info_modal" class="text-error" style='color: red;text-align: center;'></p>
    </div>
</form>