<div class="page-header">
    <h1>Brand List</h1>
</div>
<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="row">
    <div class="span12">
        <span class="pull-right">
            <button class="btn-success" type="button" onclick="window.location='<?php echo HOST ?>product/brand-create'">
                <i class="icon-plus"></i>
            </button>
        </span>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
	    <thead>
	        <tr>
	            <th>#</th>
	            <th>Name</th>
	            <th>Action</th>
	        </tr>
	    </thead>
	    <tbody>
	        <?php
	        if (isset($this->brands) and $this->brands) :
	        	$i = 1;
	            foreach ($this->brands as $k => $brand): ?>
	        <tr>
	            <td>
	                <?php
	                    echo $i++;
	                ?>
	            </td>
	            <td><?php echo $brand['name'] ?></td>
	            <td class="">
	                <a title="Edit" href="/product/brand-create?id=<?php echo $brand['id'];?>"> <i class="icon-edit"></i></a>
	                <a title="Delete" class="confirmLink" href="/product/brand-delete?id=<?php echo $brand['id'];?>"> <i class="icon-trash"></i></a>
	            </td>
	        </tr>
	        <?php endforeach;?>
			<?php endif; ?>
	    </tbody>
	</table>
	
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<?php echo $this->confirm();?>