<div class="table-responsive" style="padding-top: 20px;">

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Lock Type</th>
                <th>Warehouse Name</th>
                <th>Product Model</th>
                <th>Product Color</th>
                <th>Qulity</th>
                <th>Remark</th>
                <th>Creator</th>
                <th>Creator Time</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>

            <?php if(isset($this->data) && $this->data) : ?>
                <?php foreach ($this->data as $value) : ?>
                    <tr>
                        <td></td>
                        <td><?php if($value['lock_type'] == 1) { echo "Lock By Model"; }else{ echo "Lock By Model Color" ; } ?></td>
                        <td><?php echo $value['warehouse_name'] ?></td>
                        <td><?php echo $value['product_name'] ?></td>
                        <td><?php if($value['color_name']) { echo $value['color_name']; }else{ echo "-"; } ?></td>
                        <td><?php if($value['qulity'] > 0) { echo $value['qulity']; }else{ echo "-"; } ?></td>
                        <td><?php echo $value['remark'] ?></td>
                        <td><?php echo $this->staff[$value['created_by']] ?></td>
                        <td><?php echo $value['created_at'] ?></td>
                        <td>
                            <a href="<?php echo HOST ?>product/add-product-lock-stock?id=<?php echo $value['id'] ?>">Edit</a>
                            | <a href="<?php echo HOST ?>product/delete-product-lock-stock?id=<?php echo $value['id'] ?>" style="color: red;" onclick="return confirm('Are You Sure?')" >Delete</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>

        </tbody>
    </table>

    <div class="paging">
        <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
    </div>

</div>