<script type="text/javascript" src="<?php echo HOST ?>js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo HOST ?>css/jquery-ui-1.8.12.custom.css"/>

<link href="<?php echo HOST ?>css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="<?php echo HOST ?>css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">

<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>

<link href="../css/select2.css" rel="stylesheet"/>
<script src="../js/select2.js"></script>

<form id="form" name="form" class="form-search form-horizontal" action="<?php echo HOST ?>product/product-lock-stock">
    <div class="row">
        <div class="span6">
            <div class="control-group">
                <label class="control-label" for="warehouse_id">Warehouse Name : </label>
                <div class="controls">
                    <select id="warehouse_id" name="warehouse_id" class="span3">
                        <option value=""> Please Selected </option>
                        <?php if(isset($this->warehouse) && $this->warehouse) : ?>
                            <?php foreach ($this->warehouse as $value) : ?>
                                <option value="<?php echo $value['id'] ?>" <?php if(isset($this->params['warehouse_id']) && $this->params['warehouse_id'] == $value['id']) : ?> selected <?php endif; ?> ><?php echo $value['name'] ?></option>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="product_model">Product Model : </label>
                <div class="controls">
                    <select id="product_model" name="product_model" class="span3">
                        <option value=""> Please Selected </option>
                        <?php if(isset($this->goods) && $this->goods) :?>
                            <?php foreach($this->goods as $value) : ?>
                                <option value="<?php echo $value['good_id'] ?>" <?php if(isset($this->params['product_model']) && $this->params['product_model'] == $value['good_id']): ?> selected <?php endif; ?> ><?php echo $value['brand_name'] ?> <?php echo $value['good_name'] ?></option>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </select>
                </div>
            </div>
        </div>

        <div class="span6">
            <div class="control-group">
                <label for="lock_type" class="control-label">Lock Type : </label>
                <div class="controls">
                    <select id="lock_type" name="lock_type" class="span3">
                        <option value="">Choose</option>
                        <option value="1" <?php if(isset($this->params['lock_type']) && $this->params['lock_type'] == 1) : ?> selected <?php endif; ?> >By Model ( All Color )</option>
                        <option value="2" <?php if(isset($this->params['lock_type']) && $this->params['lock_type'] == 2) : ?> selected <?php endif; ?> >By Model Color ( Select Color )</option>
                    </select>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="span12">
            <div class="controls">
                <button type="submit" class="btn btn-primary">Search</button>
                <button type="reset" class="btn btn-warning">Reset</button>
            </div>
        </div>
    </div>
</form>


<script type="text/javascript" src="<?php echo HOST ?>js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="<?php echo HOST ?>js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" type="text/css" href="<?php echo HOST ?>css/jquery-ui-1.8.12.custom.css"/>
<link href="<?php echo HOST ?>css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="<?php echo HOST ?>css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">
<script>

    $(document).ready(function () {
        $("#warehouse_id, #product_model, #lock_type").select2();
    });

</script>
