    <!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> -->



 <script type="text/javascript" src="<?php echo HOST ?>js/jquery-1.7.2.min.js"></script> 
<script type="text/javascript" src="<?php echo HOST ?>js/jquery-ui-1.8.12.custom.min.js"></script>
  <link rel="stylesheet" type="text/css" href="<?php echo HOST ?>css/jquery-ui-1.8.12.custom.css"/>  
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
    <link href="<?=HOST?>public/css/bootstrap.modi.min.css" rel="stylesheet">
     <style type="text/css">
       .container
       {
          max-width: 1400px !important;
       }
        .list-group{
            height: 200px;
            overflow: hidden;
            overflow-y: scroll;
        }

        .so {
            width: 50px !important;
            padding-left: 15px;
            display: -webkit-inline-box;
            display: inline-block;
        }
        .qty {
          width: 70px;
          display: -webkit-inline-box;
          display: inline-block;
          text-align: left;
        }
        .price_ori {
            width: 310px;
            display: -webkit-inline-box;
            display: inline-block;
            text-align: left;
        }
        .so-title {
            padding-left: 5px;
            width: 100px;
            display: -webkit-inline-box;
            display: inline-block;
        }
        .price_text{
            margin-top: 0px;
        }
        .list-left-warehouses li, .list-right-warehouses li{
            cursor: pointer;
        }
        .activeW, .activeD, .activeP, .activePG, .list-group-item{
            cursor: pointer;
        }
        input[type=checkbox] {
          transform: scale(1.2);
        }
        .list-group-item{
            padding: 4px !important;
        }

        .list-group-item.activeW, .list-group-item.activeW:hover, .list-group-item.activeW:focus,
        .list-group-item.activeD, .list-group-item.activeD:hover, .list-group-item.activeD:focus,
        .list-group-item.activeP, .list-group-item.activeP:hover, .list-group-item.activeP:focus,
        .list-group-item.activePG, .list-group-item.activePG:hover, .list-group-item.activePG:focus {
        z-index: 2;
        color: #fff;
        background-color: #69e0b6;
        border-color: #69e0b6;
        }
    </style> 

    <div class="page-header">
        <h1>Add Quota</h1>
    </div>
    <div class="container">
    <form role="form" id="form" enctype="multipart/form-data" action="<?php echo HOST.'tool/save-quota-distributor';?>" method="post"  > <!-- savequotadistributor -->
    <?PHP if ($_GET['sn']) { ?>
      <div class="well" style="    min-height: 150px;">
        <div class="col-md-6"> 
       
            <div class="control-group">
            <label class="span3" for="rank">Warehouse<span style="color: red">*</span></label>
                <div class="controls">
                   <p><?=$this->quota[0]['w_name']?></p>
                   <input type="hidden" name="warehouses" value="<?=$this->quota[0]['warehouse']?>">
                </div>
           
            </div>  
           <div class="control-group">
            <label class="span3" for="rank">Product Category<span style="color: red">*</span></label>
                <div class="controls">
                   <p><?=$this->quota[0]['gt_name']?></p>
                   
                   <input type="hidden" name="cat_id" value="<?=$this->quota[0]['cat_id']?>">

                </div>
           
            </div>
            <div class="control-group">
                <label class="span3" for="rank">Product<span style="color: red">*</span></label>
                    <div class="controls">
                   <p><?=$this->quota[0]['p_code'].' '.$this->quota[0]['p_name']?></p>
                   <input type="hidden" name="good_id" value="<?=$this->quota[0]['good_id']?>">

                    </div>
               
            </div>
            <div class="control-group">
                <label class="span3" for="rank">Color<span style="color: red">*</span></label>
                    <div class="controls">
                   <p><?=$this->quota[0]['gc_name']?></p>
                   <input type="hidden" name="good_color" value="<?=$this->quota[0]['good_color']?>">

                    </div>
                
            </div>
            <div class="control-group">
                <label class="span3" for="rank">Quota Date<span style="color: red">*</span></label>
                    <p style="font-size: 20px;"><?=$this->quota[0]['quota_date']?></p>
                   <input type="hidden" name="quota_date" value="<?=$this->quota[0]['quota_date']?>">

                
            </div>
        </div>
      </div>
      <input type="hidden" name="sn" value="<?=$this->quota[0]['sn']?>">
      <input type="hidden" name="type" value="<?=$this->quota[0]['type']?>">
    <?PHP }else{ ?>
       <div class="well">
          <div class="control-group">
            <label class="span3" for="rank">Order Type<span style="color: red">*</span></label>
                <div class="controls">
                    <select id="type" class="span3" name="type" required>
                        <option value="">Choose</option>
                        <option value="1" <?php if (isset($this->params['type']) and $this->params['type']==1):?> selected <?php endif;?>>For Retailer</option>
                        <option value="2" <?php if (isset($this->params['type']) and $this->params['type']==2):?> selected <?php endif;?>>For Demo</option>
                        <option value="3" <?php if (isset($this->params['type']) and $this->params['type']==3):?> selected <?php endif;?>>For Staffs</option>
                        <option value="4" <?php if (isset($this->params['type']) and $this->params['type']==4):?> selected <?php endif;?>>For Lending</option>
                    </select>
                </div>
           
            </div>
            <div class="control-group">
            <label class="span3" for="rank">Warehouse<span style="color: red">*</span></label>
                <div class="controls">
                    <select class="warehouses span3"  name="warehouses" required>
                    <option value="">Choose</option>
                    <?php if ($this->warehouses): foreach ($this->warehouses as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php echo (isset($list['warehouses']) and $id==$list['warehouses'])? 'selected':''?> ><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select>
                </div>
           
            </div>
            <div class="control-group">
            <label class="span3" for="rank">Product Category<span style="color: red">*</span></label>
                <div class="controls">
                    <select class="cat_id span3"  name="cat_id" required>
                    <option value="">Choose</option>
                    <?php if ($this->good_categories): foreach ($this->good_categories as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php echo (isset($list['cat_id']) and $id==$list['cat_id'])? 'selected':''?> ><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select>
                </div>
           
            </div>
            <div class="control-group">
                <label class="span3" for="rank">Product<span style="color: red">*</span></label>
                    <div class="controls">
                       <select class="good_id span3" class="" name="good_id" required>
                        <option value="">Choose</option>
                     
                            <?php foreach ($goods as $good):?>
                                <option value="<?php echo $good->id;?>" <?php echo ($good->id == $list->good_id)?'selected':''?>><?php echo $good->name;?></option>
                            <?php endforeach;?>
                       
                    </select>
                    </div>
               
            </div>
            <div class="control-group">
                <label class="span3" for="rank">Color<span style="color: red">*</span></label>
                    <div class="controls">
                        <select class="good_color span3" class="" name="good_color" required>
                        <option value="">Choose</option>
                        <?php foreach ($colors as $color):?>
                                <option value="<?php echo $color->id;?>" <?php echo ($color->id == $list->good_color)? 'selected':''?>><?php echo $color->name;?></option>
                            <?php endforeach;?>
                    </select>
                    </div>
                
            </div>
            <div class="control-group">
                <label class="span3" for="rank">Quota Date<span style="color: red">*</span></label>
                    <div class="controls">
                        <input type="text" class="date" name="quota_date" style="width: 260px;" required>
                    </div>
                
            </div>

      </div>
    <?PHP } ?>  
      <div class="well"> 
    <div class="col-md-12"> 

       <h2>Distributor</h2>
        <div class="control-group">
            <div class="controls">ประเภทร้านค้า<span style="color: red">*</span> 
                <select id="rank" name="rank" class="rank">
                    <option value="">---</option>
                    <option value="1" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==1 ) { ?> selected<?php }?>>1. ORG-WDS(1)</option>
                    <option value="2" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==2 ) { ?> selected<?php }?>>2. ORG(2)</option>
                    <option value="5" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==5 ) { ?> selected<?php }?>>3. ORG-Dtac/Advice(5)</option>
                    <option value="6" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==6 ) { ?> selected<?php }?>>4. ORG-Lotus/Power by(6)</option>
                    <option value="7" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==7 ) { ?> selected<?php }?>>5. Dealer(7)</option>
                    <option value="8" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==8 ) { ?> selected<?php }?>>6. HUB(8)</option>
                    <option value="9" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==9 ) { ?> selected<?php }?>>7. Laos(9)</option>
                    <option value="3" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==3 ) { ?> selected<?php }?>>8. Online and Staff(3)</option>
                    <option value="10" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==10 ) { ?> selected<?php }?>>9. Brand Shop/Service(10)</option>
                    <option value="11" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==11 ) { ?> selected<?php }?>>10. King Power(11)</option>
                    <option value="12" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==12 ) { ?> selected<?php }?>>11. Jaymart(12)</option>
                    <option value="13" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==13 ) { ?> selected<?php }?>>12. Brand Shop By Dealer(13)</option>
                    <option value="14" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==14 ) { ?> selected<?php }?>>13. KR Dealer(14)</option>
                    <option value="15" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==15 ) { ?> selected<?php }?>>14. TRUE(15)</option>
                </select>
                &nbsp;&nbsp;&nbsp; ร้านค้าทั้งหมด &nbsp;&nbsp; <input type="checkbox" name="distributor_all" value="1" <?php echo($this->forceSaleSelect[0]['distributor_all']==1?'checked':'')?>> 
                <p class="help-block"></p>
            </div>
        </div> 
         <div class="list_distributor">    
            <?php
                echo $this->render('tool/list-distributor-force-sale-first.phtml');
            ?>   
       </div>
   
        
        <div class="row">
                <div class="span6">
                    <div class="control-group">
                        
                        <div class="span4">

                            <button type="submit" class="btn btn-primary" id="submit_btn">Confirm</button>
                            <a href="<?PHP echo isset($_GET['sn'])?'view-quota-distributor?sn='.$_GET['sn']:'quota-manage-distributor' ?>" class="btn btn-danger go-back">Go back</a>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
        </div>
    </form>
</div>
 
    <!--  -->
     
<!-- <script type="text/javascript" src="http://code.jquery.com/jquery.js"></script> -->
<!-- <script src="<?php echo HOST?>js/jquery.datetimepicker.js"></script>
<link rel="stylesheet" href="<?php echo HOST?>css/jquery.datetimepicker.css" /> -->
<script type="text/javascript" src="<?php echo HOST ?>js/jets.js"></script>

    <script type="text/javascript">
     
    // function initDatepicker(){
    //     $( ".date" ).datepicker({
    //         format:'Y-m-d H:i:s'
    //     });
    // }
    
    $(document).ready(function () {
      initSelectProduct();
      $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        initSearchOptionDistributor('d_id', 'SearchBox');
        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });
            // initDatepicker();
          
            $("*").keypress(function(event){  
                 if(event.keyCode==13){  
                    return false;  
                 }  
            });

            // $('body').on('click', '.list-group .list-group-item', function () {
            //     $(this).toggleClass('active');
            // });
          

            $('body').on('change', '.rank', function () {
               var list =  $(this).val();
               
               $.ajax({
                   url: 'list-distributor-for-quota',
                   type: 'POST',
                   data: {rank: list},
               })
               .done(function(data) {
                    $('.list-left-distributor').empty();
                    $('.list-left-distributor').append(data);
                   console.log("success");
               })
               .fail(function() {
                   console.log("error");
               })
               .always(function() {
                   console.log("complete");
               });
               
            });

            $('body').on('change', '.category', function () {
               var list =  $(this).val();
               
               $.ajax({
                   url: '/tool/list-product',
                   type: 'GET',
                   data: {cat_id: list},
               })
               .done(function(data) {
                    $('.list-left-product').empty();
                    $('.list-left-product').append(data);
                   console.log("success");
               })
               .fail(function() {
                   console.log("error");
               })
               .always(function() {
                   console.log("complete");
               });
               
            });

            $('body').on('change', '.category-gift', function () {
               var list =  $(this).val();
               
               $.ajax({
                   url: '/tool/list-product-gift',
                   type: 'GET',
                   data: {cat_id: list},
               })
               .done(function(data) {
                    $('.list-left-product-gift').empty();
                    $('.list-left-product-gift').append(data);
                   console.log("success");
               })
               .fail(function() {
                   console.log("error");
               })
               .always(function() {
                   console.log("complete");
               });
               
            });

          
            // $('.list-arrows a').click(function () {
            //     var $button = $(this), actives = '';
            //     if ($button.hasClass('move-left')) {
            //         actives = $('.list-right ul li.active');
            //        acc = actives.clone().appendTo('.list-left ul').find('span.price_text').addClass('none_price').find('input,textarea,select,hidden,number').attr('disabled','disabled').val('');
            //         acc.parent().parent().find('.pay_ment').removeClass('pay_money_total');
            //         actives.remove();
                    
                  
            //     } else if ($button.hasClass('move-right')) {
            //         actives = $('.list-left ul li.active');
            //         acc  =  actives.clone().appendTo('.list-right ul').find('span').removeClass('none_price').find('input,textarea,select,hidden,number').removeAttr('disabled');
            //         acc.parent().find('.pay_ment').addClass('pay_money_total');
            //         actives.remove();
                   
                    
                    
            //     }
            // });

            // $('.dual-list .selector').click(function () {
            //     var $checkBox = $(this);
            //     if (!$checkBox.hasClass('selected')) {
            //         $checkBox.addClass('selected').closest('.well').find('ul li:not(.active)').addClass('active');
            //         $checkBox.children('i').removeClass('icon icon-circle-blank').addClass('icon icon-ok');
            //     } else {
            //         $checkBox.removeClass('selected').closest('.well').find('ul li.active').removeClass('active');
            //         $checkBox.children('i').removeClass('icon icon-ok').addClass('icon icon-circle-blank');
            //     }
            // });
            // $('[name="SearchDualList"]').keyup(function (e) {
            //     var code = e.keyCode || e.which;
            //     if (code == '9') return;
            //     if (code == '27') $(this).val(null);
            //     var $rows = $(this).closest('.dual-list').find('.list-group li');
            //     var val = $.trim($(this).val()).replace(/ +/g, ' ').toLowerCase();
            //     $rows.show().filter(function () {
            //         var text = $(this).text().replace(/\s+/g, ' ').toLowerCase();
            //         return !~text.indexOf(val);
            //     }).hide();
            // });

            

            // $(document).on("submit", "form", function(e)
            // {
            //      $('#form').submit();
            // });
            
        });

        function initSelectProduct(){
            $(document).off('change', '.cat_id, .good_id')
            .on('change', '.cat_id, .good_id', function(e) {
                $('button[type=submit]').prop('disabled', true);
                $('form').bind('submit',function(e){e.preventDefault();});

                $('.loading').remove();
                $(this).after('<span class="loading"></span>');
                var div_parent = $(this).parent().parent().parent();
                var _self = $(this);
                var cat_id = div_parent.find('.cat_id').val();
                var distributor_id    = $('#d_id').val();
                var rank    = $('.rank').val();

                // if (distributor_id == "" || distributor_id == null) {
                //   alert('Please select Retailer name..');
                //   $('#d_id').focus();
                // $('.good_id').find('option:not(:first)').remove();
                // $('.good_color').find('option:not(:first)').remove();
                // $('.quantity').val('');
                // }
                if (_self.hasClass('cat_id'))
                    div_parent.find('.good_id').find('option:not(:first)').remove();

                var good_id = div_parent.find('.good_id').val();

                div_parent.find('.good_color').find('option:not(:first)').remove();

                div_parent.find('.quantity').val('');

                //alert(cat_id);alert(good_id);
                $.get("/get/load",
                    {cat_id: cat_id, good_id: good_id}
                    ,function(data,status){
                        var data = $.parseJSON( data );
                        if (data.goods){
                            var obj = data.goods;
                            for (var i = 0; i < obj.length; i++) {
                                 div_parent.find('.good_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            }
                        }
                        if (data.colors){
                            var obj = data.colors;
                            for (var i = 0; i < obj.length; i++) {
                                 div_parent.find('.good_color').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            }
                        }
                        $('button[type=submit]').prop('disabled', false);
                        $('form').unbind('submit');
                        _self.nextAll('.loading').remove();
                    });

            });
        }
        function roundNumber(num, dec) {
            var result = Math.round(num*Math.pow(10,dec))/Math.pow(10,dec);
            return Number(result).toLocaleString('en',{ minimumFractionDigits: 2 });
        }
    </script>
