<div class="page-header">
    <h1>ADD Imei Lot</h1>
</div>
<style>
    textarea {
        resize: none;
    }
    

</style>

 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 

<form role="form" id="form" method="post" enctype="multipart/form-data" class="form-inline" action="<?php echo HOST.'tool/add-imei-lot';?>">
<?php
if (isset($this->messages_success) and $this->messages_success)
    foreach ($this->messages_success as $message):
        echo '<div class="alert alert-success">'.$message.'</div>';
    endforeach;

if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>
    <div class="row-fluid">
        <div class="span3">
            <label for="" class="">Lot No: <span><input  required="required" type="text" name="lot_name" class="lot_name" id="lot_name" value="<?php echo$this->params['lot_name'] ?>" maxlength="30"></span></label>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span3">
            <label for="" class="">IMEI Code: <span><strong id="num_imei">0</strong> IMEI(s)</span></label>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span3">
            <div class="control-group">
                <textarea name="imei" id="imei" cols="20" rows="20" required="required"><?php echo$this->params['imei'] ?></textarea>
            </div>
            <div class="clearfix"></div>
             <div class="control-group">
                <button name="btn_save" value="1" id="valid_btn" type="submit" class="btn btn-primary ">Save</button>
                <a href="/tool/imei-lot" class="btn btn-danger go-back">Go back</a>
                <span></span>
            </div>
        </div>
        <div class="span5">
            <div id="check_res"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</form>
<div class="row-fluid">
    <div class="span12">
        <div class="ajax-load">
            
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
     
        $('#valid_btn').click(function(){
            _self = $(this);
            _self.nextAll('span').addClass('loading');
            imei = $('#imei').val();
            $.post(
                "<?php echo HOST . 'tool/add-imei-lot'?>",
                {
                    value : imei,
                    is_check : 1
                },
                function(data){
                    $('.ajax-load').html(data);
                    _self.nextAll('span').removeClass('loading');
            });
        });

        initShowIMEINum();
        checkIMEI();

    });
 



    function initShowIMEINum(){
        $('#imei').keyup(function (e){

            var inputnum = 0;

            if ($(this).val() != '')
                inputnum = ($(this).val().split("\n").length).toString();


            $('#num_imei').html(inputnum);

        });
    }


</script>