
<div class="page-header">
    <h1>Function Edit</h1>
</div>
<?php
if (isset($this->messages_success) and $this->messages_success)
    foreach ($this->messages_success as $message):
        echo '<div class="alert alert-success">'.$message.'</div>';
    endforeach;

if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;

?>

<div class="table-responsive">
<h3>แก้ชื่อลูกค้าเเบร์นช๊อป</h3>
   <form method="post" action="function-edit" enctype="multipart/form-data" >
       <div class="control-group">
                <label for="invoice_number" class="span1">SO<span style="color: red">*</span></label>
                <input id="" name="so" type="text" required class="input-medium form-control" ">
        </div>
        <div class="control-group">
                <label for="invoice_number" class="span1">ชื่อลูกค้า</label>
                <input id="" name="customer_name" type="text" class="input-medium form-control" ">
        </div>
        <div class="control-group">
                <label for="invoice_number" class="span1">เลขผู้เสียภาษี</label>
                <input id="" name="tax" type="text" class="input-medium form-control" ">
        </div>
        <div class="control-group">
                <label for="invoice_number" class="span1">ที่อยู่</label>
                <textarea name="add"></textarea>    
        </div>

        <div class="row">
                <div class="span6">
                    <div class="control-group">
                        
                        <div class="span4">

                            <button type="submit" value="1" name="customer" class="btn btn-primary" >submit</button>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
        </div>
   </form>
</div>
<script>

   
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });
</script>