
<div class="page-header">
    <h1>IMEI LOT</h1>
</div>
<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('tool/partials/imei-lot-search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>
<div style="margin-bottom: 15px;"><a href="/tool/add-imei-lot" class="btn btn-success">Add Imei Lot</a></div>
<div class="table-responsive">
    <?php
        echo $this->render('tool/partials/lish-imei-lot.phtml');
    ?>
</div>

<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });
</script>
<?php echo $this->load('combobox');?>