
                <div class="well-D">
                    <div class="row tabLeft">
                        <div class="col-md-7">
                            <div class="input-prepend">
                                <span class="add-on"><i class="icon icon-search"></i></span>
                                <input type="text" name="SearchDualListDistributor" class="form-control" placeholder="Search" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="btn-group">
                                <a class="btn btn-default selectorDD" title="select all"><i class="icon icon-circle-blank"></i></a>
                            </div>
                        </div>
                    </div>
                    <div>
                         <span class="so-title">Distributor ID</span>
                         <span class="price_ori">Distributor Name</span>
                         
                    </div>
                    <ul class="list-group">
                    <?PHP 
                        $i = 1;
                        foreach ($this->blacklist as $list) :
                         
                            ?>
                        <li class="list-group-item item-distributor">
                            <span class="so"><?=$list['id']?></span>
                            <span class="price_ori "><?=$list['title']?>

                            <input type="hidden" class="sn" name="d_id[]" disabled value="<?=$list['id']?>">
                            </span>
                            
                        </li>
                            
                            
                      <?PHP $i+=1; 
                       
                      endforeach; ?>  
                        
                    </ul>
                </div>
    

    <script type="text/javascript">
        $(document).ready(function () {
              $('[name="SearchDualListDistributor"]').keyup(function (e) {
                    var code = e.keyCode || e.which;
                    if (code == '9') return;
                    if (code == '27') $(this).val(null);
                    var $rows = $(this).closest('.dual-list').find('.list-group .item-distributor');
                    var val = $.trim($(this).val()).replace(/ +/g, ' ').toLowerCase();
                    $rows.show().filter(function () {
                        var text = $(this).text().replace(/\s+/g, ' ').toLowerCase();
                        return !~text.indexOf(val);
                    }).hide();
                });

             $('.selectorDD').click(function () {
                var $checkBox = $(this);
                if (!$checkBox.hasClass('selected')) {
                    $checkBox.addClass('selected').closest('.well-D').find('ul li:not(.activeD)').addClass('activeD');
                    $checkBox.children('i').removeClass('icon icon-circle-blank').addClass('icon icon-ok');
                } else {
                    $checkBox.removeClass('selected').closest('.well-D').find('ul li.activeD').removeClass('activeD');
                    $checkBox.children('i').removeClass('icon icon-ok').addClass('icon icon-circle-blank');
                }
            });

             });
    </script>
    