<link href="../css/select2.css" rel="stylesheet"/>
<script src="../js/select2.js"></script>
<div class="page-header">
    <h1>New Quota Distributor</h1>
</div>
<style type="text/css">
.label {
    padding: 3px 6px 4px;
    font-size: 12px;
    }
	.label-default  {
  background-color: #aaa  !important;
}

.badge-primary,
.label-primary {
  background-color: #428bca !important;
}

.label-success, 
.badge-success {
  background-color: #3cc051;
  background-image: none !important;
}

.label-warning, 
.badge-warning {
  background-color: #fcb322;
  background-image: none !important;
}

.label-danger, 
.badge-danger {
  background-color: #fb0000;
  background-image: none !important;
}

.label-info, 
.badge-info {
  background-color: #57b5e3;
  background-image: none !important;
}
</style>

<?php
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('tool/partials/new-quota-manage-distributor-search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>
<div class="pull-right" style="margin-bottom: 15px;"><a href="new-add-quota-distributor" class="btn btn-success">Add Quota</a></div>
<div class="pull-right" style="margin-bottom: 15px;margin-right: 15px;"><a href="new-import-quota-distributor" class="btn btn-warning">Import Quota</a></div>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <?php 

                $array_field = array('#',
                        'Quota Data',
                        'Distributor Type',
                        'Distributor Name',
                        'Order Type',
                        'Warehouse',
                        );

                foreach ($this->good_product_color as $key => $value) {
                    array_push($array_field, 'Product<br/>[' . $value['name'] . '] ' . $value['desc'] . ' (' . $value['color_name'] . ')');
                }

                $array_field = array_merge($array_field,['Status','Action']); 

                echo $this->sorting($array_field,
                    $this->url, $this->sort, $this->desc); 
                    
                ?>
            </tr>
        </thead>
        <tbody>
            <?php 
                if( $this->quota ):
                    $intSTT = 1;
                foreach($this->quota as $item):

                if ($item['status'] == 1) {
                	$toDay = date('Y-m-d');
                	$quota_d = $item['quota_date'];

                	if ($quota_d < $toDay) {
                		$status = '<span class="label label-default">Expired</span>';
                	}elseif ($quota_d > $toDay) {
                		$status = '<span class="label label-primary">Quota Next</span>';
                	}elseif ($quota_d = $toDay) {
                		$status = '<span class="label label-success">Now</span>';
                	}
                }else{
                	$status = '<span class="label label-danger">Disabled</span>';
                }

                $good_type = '';

                switch ($item['good_type']) {
                    case '1':
                        $good_type = 'Normal';
                        break;
                    
                    case '2':
                        $good_type = 'Demo';
                        break;

                    case '5':
                        $good_type = 'APK';
                        break;
                }
            ?>
                    <tr>
                        <td><?php echo $intSTT++;?></td>
                        <td><?php echo date('d/m/Y',strtotime($item['quota_date']));?></td>
                        <td><?php echo $item['group_name']?></td>
                        <td><?php echo '[ '.$item['store_code'].' ] ' . $item['d_name']?></td>
                        <td><?php echo $good_type;?></td>
                        <td><?php echo $this->warehouses[$item['warehouse_id']];?></td>
                        
                        <?php 

                        foreach ($this->good_product_color as $key => $value) {
                                
                                $quota_num = 0;
                                $quota_current = 0;
                                if(isset($this->quota_color[$item['id']][$value['color_id']])){

                                    $quota_num = $this->quota_color[$item['id']][$value['color_id']]['num'];
                                }

                                if(isset($this->quota_current[$item['id']][$value['color_id']])){

                                    $quota_current = $this->quota_current[$item['id']][$value['color_id']]['current_quota'];
                                }

                                $text_show_quota = '';


                                switch ($this->quota_color[$item['id']][$value['color_id']]['status']) {

                                    case '':
                                        $text_show_quota = 'Quota Unlimited';
                                        break;
                                    
                                    case '1':

                                        if($this->quota_color[$item['id']][$value['color_id']]['num'] == 0){
                                            $text_show_quota = 'Quota Unlimited';
                                        }else{
                                            $text_show_quota = 'Quota : ' . $quota_num . ' | Order : ' . $quota_current .' | Current : ' . ($quota_num-$quota_current);
                                        }
                                        
                                        break;

                                    case '2':
                                        $text_show_quota = 'Over Quota';
                                        break;
                                }

                        ?>

                        <td><center><?=$text_show_quota?></center></td>
                        <?php } ?>

                        <td><center><?php echo $status?></center></td>
                        
                        <td>
                        <center>
                            <a class="btn btn-warning" title="view" href="new-view-quota-distributor?id=<?=$item['id']?>" >
                                <i class="icon-eye-open "></i>
                            </a>
                        </center>
                        </td>
                    </tr>
            <?php 
                endforeach;
                endif;
            ?>
        </tbody>
    </table>
    <div class="paging">
        <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
    </div>
</div>
<script>

    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });
</script>