<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Report : Weekly Turn Over Stock</title>
</head>
<style type="text/css">
body {
  font-family: "Times New Roman", Times, serif;
  background: white; 
  font-size:12px;
  margin: 0px;
}
page {
  background: white;
  display: block;
  margin: 0 auto;
  /*margin-bottom: 0.5cm;*/
  /*box-shadow: 0 0 0.5cm rgba(0,0,0,0.5);*/
  padding-left:0.5cm;
  padding-right:0.5cm;
}
page[size="A4"] {  
  width: 21cm;
  height: 29.7cm;
}
#sales-info{
  text-align: center;
  height:2cm;
}
table {
    border-collapse: collapse;
    width:100%;
}

table, th, td {
    border: 1px solid black;
}
table.nb, table.nb th, table.nb td{
  border: none;
}
.txthead{
    text-align: center;
    background-color: #b1a7a7;
    height: 20px;
    font-weight: bold;
}
.txtleft{
    text-align: left;
    background-color: #ddd;
    height: 30px
}
.bgrey{
    background-color: #ddd;
    height: 60px;
    text-align: left;
    vertical-align: top;
}
.zc-ref {
  display: none;
}
</style>

<body>
<page size="A4">
    <div class="details-head-page-none" style="display: none;">
      <div align="right" style="margin-right: 30px;padding-top: 160px;"><?php echo "$current_page/$total_page";?></div>
    </div>

    <div class="details-head-page">
      <img style="width: 100%" src='<?php echo HOST.'img/oppo_header.png'?>'>
    </div>
      <table id="sales-info" style="margin-top:0.2cm;">
        <?php
            $createdate = "";
            foreach ($this->imeilot as $key => $imei){
                $data_date = $imei['data_date'];
            }
         ?>
         <tr>
          <th width="100%" colspan="12" style="padding: 5px;" class='txtleft'>Print : Weekly Turn Over Stock</th>
         </tr>
         <tr>
          <th width="100%" colspan="12" style="padding: 5px;" class='txtleft'>Data Date : <?=$data_date?></th>
         </tr>
        
      </table>
      <table id="sales-info" style="margin-top:-0.2cm;">
         <tr>
          <td width="100%" class="txthead">
            <div id="myChart"></div>
          </td>
         </tr>
      </table>
      <br>
</page>
</body>
</html>

<?php



$inventory_num_total = [];
$stock_month_name = [];

foreach ($this->get_resule1 as $id=>$item)
{
    $inventory_num=$item['inventory_num_total']/$item['so_num_total_all'];
    array_push($inventory_num_total, number_format($inventory_num,0));
    array_push($stock_month_name, $item['stock_month_name']);
}

$inventory_num_total = json_encode($inventory_num_total,JSON_NUMERIC_CHECK);
$stock_month_name = json_encode($stock_month_name,JSON_NUMERIC_CHECK);
?>


<script src= "https://cdn.zingchart.com/zingchart.min.js"></script>
<script> zingchart.MODULESDIR = "https://cdn.zingchart.com/modules/";
    ZC.LICENSE = ["569d52cefae586f634c54f86dc99e6a9","ee6b7db5b51705a13dc2339db3edaf6d"];</script>  
<script src='//code.jquery.com/jquery-2.1.4.min.js'></script>

<script>
 
var inventory_num_total = '<?php echo $inventory_num_total; ?>';
var stock_month_name = '<?php echo $stock_month_name; ?>';


var myConfig = {
"graphset":[
    {
        "type":"mixed",
        "title":{
            "text":"Weekly Turn Over Stock",
            "align":"left",
            "font-size":14,
            "background-color":"#BDBDBD",
            "height":"5%"
        },
        "scale-x":{
            "values": JSON.parse(stock_month_name),
            "zooming":true,
            "guide":{
                "line-style":"solid",
                "line-color":"#BDBDBD"
            }
        },
        "scale-y":{
            "zooming":true,
            "guide":{
                "visible":false
            },
        },
         "scale-y-2":{
            "zooming":true,
            "guide":{
                "line-style":"solid"
            },
            "label":{
                "text":"Turn Over Stock"
            },
            "minor-ticks":5,
            "minor-tick":{
                "placement":"cross",
                "size":6
            },
            "minor-guide":{
                "line-width":"1px",
                "line-style":"dashed",
                "line-segement-size":"1px",
                "line-gap-size":"6px",
                "alpha":0.7
            },
            "markers": [
            {
              "type": "line",
              "range": [14],
              "line-width": 2,
              "line-color": "red",
              "text": "14",
              "placement": "bottom",
              "label-placement": "normal",
              "label-alignment": "normal"
            },{
              "type": "line",
              "range": [18],
              "line-width": 2,
              "line-color": "red",
              "text": "18",
              "placement": "bottom",
              "label-placement": "normal",
              "label-alignment": "normal"
            }
          ]
        },
        "series":[
            
            {
                "type":"line",
                "values": JSON.parse(inventory_num_total),
                "scales":"scale-x,scale-y-2",
                "line-color":"#0D47A1",
                "thousands-separator":"," , 
                "tooltip-text":"Weekly Turn Over Stock %v",
                "legend-marker":{
                  "type":"circle"
                },
                "marker":{
                  "background-color":"#B71C1C"
                },
                "value-box":{
                    "thousands-separator":"," , 
                    "offset-y":5,
                    "font-color":"black",
                    "text":"%v",
                    "decimals":0,
                    "font-angle":0
                }

            }
        ]
    }
],
"background-color":"white"
};

zingchart.render({ 
  id : 'myChart', 
  data : myConfig
});


</script>
