<link href="../css/select2.css" rel="stylesheet"/>
<script src="../js/select2.js"></script>
<div class="page-header">
    <h1>Quota Distributor</h1>
</div>
<style type="text/css">
.label {
    padding: 3px 6px 4px;
    font-size: 12px;
    }
	.label-default  {
  background-color: #aaa  !important;
}

.badge-primary,
.label-primary {
  background-color: #428bca !important;
}

.label-success, 
.badge-success {
  background-color: #3cc051;
  background-image: none !important;
}

.label-warning, 
.badge-warning {
  background-color: #fcb322;
  background-image: none !important;
}

.label-danger, 
.badge-danger {
  background-color: #fb0000;
  background-image: none !important;
}

.label-info, 
.badge-info {
  background-color: #57b5e3;
  background-image: none !important;
}
</style>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('tool/partials/distributor-black-list-search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>
<div style="margin-bottom: 15px;"><a href="add-quota-distributor" class="btn btn-success">Add Quota</a></div>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <?php echo $this->sorting(array(
                        '#',
                        'Quota Data',
                        'Distributor Type',
                        'Product',
                        'Color',
                        'Status',
                        'Action'
                    ),
                    $this->url, $this->sort, $this->desc); ?>
            </tr>
        </thead>
        <tbody>
            <?php 
                if( $this->quota ):
                    $intSTT = 1;
                foreach($this->quota as $item):
                	switch ($item['dis_type']) {
                		case '1':
                			$type = 'ORG';
                			break;
                		case '7':
                			$type = 'Dealer / Hub';
                			break;
                		case '10':
                			$type = 'Brand Shop';
                			break;
                		
                		default:
                			$type = '-';
                			break;
                	}

                if ($item['status'] == 1) {
                	$toDay = date('Y-m-d');
                	$quota_d = $item['quota_date'];

                	if ($quota_d < $toDay) {
                		$status = '<span class="label label-default">Expired</span>';
                	}elseif ($quota_d > $toDay) {
                		$status = '<span class="label label-primary">Quota Next</span>';
                	}elseif ($quota_d = $toDay) {
                		$status = '<span class="label label-success">Now</span>';
                	}
                }else{
                	$status = '<span class="label label-danger">Disabled</span>';
                }
            ?>
                    <tr>
                        <td><?php echo $intSTT++;?></td>
                        <td><?php echo date('d/m/Y',strtotime($item['quota_date']));?></td>
                        <td><?php echo $type?></td>
                        <td><?php echo '[ '.$item['good'].' ]  '.$item['desc']?></td>
                        <td><center><?php echo $item['color']?></center></td>
                        <td><center><?php echo $status?></center></td>
                        
                        <td>
                        <center>
                            <a class="btn btn-warning" title="view" href="view-quota-distributor?sn=<?=$item['sn']?>" >
                                <i class="icon-eye-open "></i>
                            </a>
                        </center>
                        </td>
                    </tr>
            <?php 
                endforeach;
                endif;
            ?>
        </tbody>
    </table>
    <div class="paging">
        <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
    </div>
</div>
<script>

    function unblock(id,title){

        if (confirm("Press Confirm Unblock : "+title) == true) {
                window.location.assign("/tool/un-black-list?d_id="+id);
            }
       
    }

    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });
</script>