<div class="page-header">
    <h1>Check Saturday</h1>
</div>
<div class="row-fluid">
    <form role="form" method="post" class="row-fluid">
        <div class="span3">
            <p><?php if (isset($this->result))
                        if ($this->result)
                            echo 'YES';
                        else
                            echo 'NO';
            ?></p>
        	<label for="" class="">Date</label>
        	<input type="date" id="date" name="date" value="<?php if (isset($this->date) and $this->date) echo $this->date;?>" />
        	<div class="clearfix"></div>
        	<button id="valid_btn" type="submit" class="btn btn-primary">Get Info</button>
        	<span></span>
        </div>
        <div class="clearfix"></div>
        
    </form>
</div>
