<link href="<?php echo HOST ?>css/bootstrap.min.css" rel="stylesheet" />
<link href="<?php echo HOST ?>css/default.css" rel="stylesheet" />

<style>
    body {
        background: #f9f6f1;
        padding: 10px;
    }

    .info {
        margin-bottom: 20px;
    }
</style>
<div id="content_wrapper">
    
    <?php if (isset($this->error) && $this->error): ?>
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>ERROR!</strong> <?php echo $this->error ?>
        </div>
    <?php elseif(isset($this->number_of_order)): ?>
        <div class="row info">
            <div class="span3">
                <strong>Number of orders</strong>: <span class="badge"><?php echo $this->number_of_order ?></span>
            </div>
            <div class="span3">
                <strong>Success</strong>: <span class="badge badge-success"><?php echo $this->number_of_order - count($this->error_list) ?></span>
            </div>
            <div class="span3">
                <strong>Failed</strong>: <span class="badge badge-warning"><?php echo count($this->error_list) ?></span>
            </div>

        </div>
        <div class="row">
            <?php if (isset($this->error_file) && $this->error_file): ?>
                <div class="span12">
                    <p>
                        You can download and modify <strong>ERROR</strong> orders file:
                        <strong><a href="<?php echo $this->error_file ?>">Click here to download</a></strong>
                    </p>
                </div>
            <?php endif ?>

            <?php if (isset($this->success_file) && $this->success_file): ?>
                <div class="span12">
                    <p>
                        You can download and view <strong>SUCCESSFUL</strong> orders file:
                        <strong><a href="<?php echo $this->success_file ?>">Click here to download</a></strong>
                    </p>
                </div>
            <?php endif ?>
        </div>

        <div class="row">
            <div class="span12">
                <?php if (isset($this->error_list) && $this->error_list): ?>
                <legend>List of failed</legend>
                <table class="table table-bordered">
                    <thead>

                        <tr>
                            <th>good_code</th>
                            <th>good_model</th>
                            <th>good_name_chinese</th>
                            <th>good_name_eng</th>
                            <th>import_price_usd</th>
                            <th>import_price_bath</th>
                            <th>retail_price_bath</th>
                            <th>Message</th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php foreach ($this->error_list as $key => $row): ?>
                            <tr>
                                <td><?php echo $row['good_code']?></td>
                                <td><?php echo $row['good_model_name']?></td>
                                <td><?php echo $row['good_name_chinese']?></td>
                                <td><?php echo $row['good_name_eng']?></td>
                                <td><?php echo $row['import_price_usd']?></td>
                                <td><?php echo $row['import_price_bath']?></td>
                                <td><?php echo $row['retail_price_bath']?></td>
                                <td><?php echo $row['message']?></td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
                <?php endif ?>
            </div>
        </div>
    <?php else: ?>

    <?php endif ?>
</div>
<script>
    parent.$('.loading, .pre_loading').remove();
    parent.$('form button, form input, form select').prop('readonly', false);
    parent.$('form input').val('');
    parent.clear_interval();
    parent.window.onbeforeunload = null;

    function clear_content() {
        document.getElementById('content_wrapper').innerHTML = '';
    }
</script>