<link href="/css/bootstrap.min.css" rel="stylesheet">
<style type="text/css">
    body {
        background: #f9f6f1;
    }
</style>
<?php if (isset($this->result) && $this->result == "success"): ?>
    <div class="alert alert-success"><?php echo $this->message ?></div>
<?php endif ?>

<?php if (isset($this->error) && $this->error): ?>
    <div class="alert alert-error"><?php echo $this->error ?></div>
<?php endif ?>