<form class="form-search form-horizontal" method="get" action="<?php echo HOST ?>kerry/report">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="sn" class="span2">Sales Order Number</label>
                <input id="sn" name="sn" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['sn']) and printf($this->params['sn']);?>">
            </div>

        </div>
        <div class="span5">
        
            <div class="control-group">
             <label class="span2" for="rank">ประเภทร้านค้า<span style="color: red">*</span></label>

                    <select id="rank" name="rank" class="rank span3">
                        <option value="">---</option>
                        <option value="1" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==1 ) { ?> selected<?php }?>>1. ORG-WDS(1)</option>
                        <option value="2" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==2 ) { ?> selected<?php }?>>2. ORG(2)</option>
                        <option value="5" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==5 ) { ?> selected<?php }?>>3. ORG-Dtac/Advice(5)</option>
                        <option value="6" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==6 ) { ?> selected<?php }?>>4. ORG-Lotus/Power by(6)</option>
                        <option value="7" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==7 ) { ?> selected<?php }?>>5. Dealer(7)</option>
                        <option value="8" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==8 ) { ?> selected<?php }?>>6. HUB(8)</option>
                        <option value="9" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==9 ) { ?> selected<?php }?>>7. Laos(9)</option>
                        <option value="3" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==3 ) { ?> selected<?php }?>>8. Online and Staff(3)</option>
                        <option value="10" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==10 ) { ?> selected<?php }?>>9. Brand Shop/Service(10)</option>
                        <option value="11" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==11 ) { ?> selected<?php }?>>10. King Power(11)</option>
                        <option value="12" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==12 ) { ?> selected<?php }?>>11. Jaymart(12)</option>
                        <option value="13" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==13 ) { ?> selected<?php }?>>12. Brand Shop By Dealer(13)</option>
                        <option value="14" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==14 ) { ?> selected<?php }?>>13. KR Dealer(14)</option>
                        <option value="15" <?php if( isset($this->distributor['rank']) and $this->distributor['rank']==15 ) { ?> selected<?php }?>>14. TRUE(15)</option>
                    </select>

             </div>

        <div class="retailer_name_list"></div>
        </div>
    </div>
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="warehouse_id" class="span2">Warehouse</label>
                <select id="warehouse_id" class="span3" name="warehouse_id">
                    <option value="">Choose</option>
                    <?php if ($this->warehouses_cached): foreach ($this->warehouses_cached as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['warehouse_id']) and $id==$this->params['warehouse_id']):?> selected<?php endif;?>><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">
                <label for="cat_id" class="span2">Product Category</label>
                <select id="cat_id" class="span3" name="cat_id">
                    <option value="">Choose</option>
                    <?php if ($this->good_categories): foreach ($this->good_categories as $id=>$name):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['cat_id']) and $id==$this->params['cat_id']):?> selected<?php endif;?>><?php echo $name;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">
                <label for="good_id" class="span2">Product</label>
                <select id="good_id" class="span3" name="good_id">
                    <option value="">Choose</option>
                    <?php if ($this->goods): foreach ($this->goods as $key=> $item):?>
                        <option value="<?php echo $key;?>" <?php if (isset($this->params['good_id']) and $key==$this->params['good_id']):?> selected<?php endif;?>><?php echo $item;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">
                <label for="good_color" class="span2">Color</label>
                <select id="good_color" class="span3" name="good_color">
                    <option value="">Choose</option>
                    <?php if ($this->goodColors): foreach ($this->goodColors as $key=>$item):?>
                        <option value="<?php echo $key;?>" <?php if (isset($this->params['good_color']) and $key==$this->params['good_color']):?> selected<?php endif;?>><?php echo $item;?></option>
                    <?php endforeach; endif;?>
                </select>
            </div>

            <div class="control-group">
                <label for="created_at_from" class="span2">Order Time From</label>
                <input type="text" class="form-control search-query date" id="created_at_from" name="created_at_from" value="<?php isset($this->params['created_at_from']) and printf($this->params['created_at_from']);?>">
            </div>

            <div class="control-group">
                <label for="created_at_to" class="span2">Order Time To</label>
                <input type="text" class="form-control search-query date" id="created_at_to" name="created_at_to" value="<?php isset($this->params['created_at_to']) and printf($this->params['created_at_to']);?>">
            </div>

            <div class="control-group">
                <label for="send_at_from" class="span2">Send Time From</label>
                <input type="text" class="form-control search-query date" id="send_at_from" name="send_at_from" value="<?php isset($this->params['send_at_from']) and printf($this->params['send_at_from']);?>">
            </div>

            <div class="control-group">
                <label for="send_at_to" class="span2">Send Time To</label>
                <input type="text" class="form-control search-query date" id="send_at_to" name="send_at_to" value="<?php isset($this->params['send_at_to']) and printf($this->params['send_at_to']);?>">
            </div>

        </div>
        <div class="span5">
            
            <div class="control-group">
                <label for="myTags" class="span2">Tags</label>
                <ul class="form-control span3" id="myTags"><?php
                    if (isset($this->params['tags']) and $this->params['tags']):
                        foreach ($this->params['tags'] as $ta)
                            echo '<li>'.$ta.'</li>';
                    endif;
                    ?></ul>
            </div>

            <div class="control-group">
                <label for="tracking_no" class="span2">Tracking No</label>
                <input type="text" class="form-control search-query input-medium" id="tracking_no" name="tracking_no" value="<?php isset($this->params['tracking_no']) and printf($this->params['tracking_no']);?>">
            </div>

            <div class="control-group">
                <label for="cat_id" class="span2">Company Logistics</label>
                <select id="company_logistics" class="span3" name="company_logistics">
                        <option value="1">Kerry</option>
                        <option value="3">Genious</option>
                        <option value="5">NKC</option>
                        <option value="6">YAS</option>
                        <option value="9">J&T</option>
                </select>
            </div>

            <div class="control-group">
                <label for="cat_id" class="span2">Logistics Status</label>
                <select id="logistics_status" class="span3" name="logistics_status">
                        <option value="1">On The Way</option>
                        <option value="2">Completed</option>
                        <option value="3">Kerry EDI Error</option>
                </select>
            </div>

            <div class="control-group">
                <label for="no_show_brandshop" class="span2">ไม่แสดงข้อมูล Brandshop/Service/Lazada</label>
                <input id="no_show_brandshop" name="no_show_brandshop" type="checkbox" class="input-large search-query form-control" value="1" <?php if (isset($this->params['no_show_brandshop']) and $this->params['no_show_brandshop']):?>checked="checked" <?php endif;?>>
            </div>

            <!-- <div class="control-group">
                <label for="show_kerry" class="span2">เเสดงเฉพาะ Kerry</label>
                <input id="show_kerry" name="show_kerry" type="checkbox" class="input-large search-query form-control" value="1" <?php if (isset($this->params['show_kerry']) and $this->params['show_kerry']):?>checked="checked" <?php endif;?>>
            </div>

            <div class="control-group">

                <label for="show_kerry_pending" class="span3">เเสดงเฉพาะรายการที่ส่งสำเร็จเเล้ว</label>
                <input id="show_kerry_pending" name="show_kerry_status" type="radio" class="input-large search-query form-control" value="1" <?php if (isset($this->params['show_kerry_status']) and $this->params['show_kerry_status'] == 1):?>checked="checked" <?php endif;?>>

                <br/>
                <br/>

                <label for="show_kerry_pending" class="span3">เเสดงเฉพาะรายการที่กำลังส่ง</label>
                <input id="show_kerry_pending" name="show_kerry_status" type="radio" class="input-large search-query form-control" value="2" <?php if (isset($this->params['show_kerry_status']) and $this->params['show_kerry_status'] == 2):?>checked="checked" <?php endif;?>>

                <br/>
                <br/>

                <label for="show_kerry_fail" class="span3">เเสดงเฉพาะรายการที่ส่งล้มเหลว</label>
                <input id="show_kerry_fail" name="show_kerry_status" type="radio" class="input-large search-query form-control" value="3" <?php if (isset($this->params['show_kerry_status']) and $this->params['show_kerry_status'] == 3):?>checked="checked" <?php endif;?>>
            </div> -->

        </div>
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
    <button type="submit" name="export" value="1" class="btn btn-success">Export</button>
</form>
<script async="async">
    //getDistributor(<?php echo ((isset($this->params['d_id']) and $this->params['d_id']) ? $this->params['d_id'] : '');?>);

    <?php if(isset($this->rank)) { ?>
        $('#rank').val(<?= $this->rank ?>);
        get_distributor_cached_for_search(<?= $this->rank ?>);
    <?php }?>

    <?php if(isset($this->params['company_logistics'])) { ?>
        $('#company_logistics').val(<?= $this->params['company_logistics']; ?>);
    <?php }?>

    <?php if(isset($this->params['logistics_status'])) { ?>
        $('#logistics_status').val(<?= $this->params['logistics_status']; ?>);
    <?php }?>

    $('.rank').change(function(event) {
        get_distributor_cached_for_search($(this).val());
      });

    function get_distributor_cached_for_search(rank_id){

        var rank_id = rank_id;
              $.ajax({
                  url: '<?php echo HOST ?>get/distributor-cached-for-search',
                  type: 'POST',
                  dataType: 'html',
                  data: {rank_id: rank_id},
              })
              .done(function(data) {
                  $('.retailer_name_list').empty();
                  $('.retailer_name_list').append(data);
                    var jets = new Jets({
                    searchTag: '#SearchBox',
                    contentTag: '#d_id'
                });
                    <?php if(isset($this->d_id)){ ?>
                        $('#d_id').val(<?= $this->d_id ?>);
                    <?php }?>
                  console.log("success");
              })
              .fail(function() {
                  console.log("error");
              })
              .always(function() {
                  console.log("complete");
              });

    }

    function getDistributor(currentDistributorID) {

        $.ajax({
            url: '<?php echo HOST ?>get/distributor-cached',
            type: 'post',
            dataType: 'json'
        })
            .done(function(data) {
                if (!data || data.no_data) return false;
                $('#d_id option').not(':first').remove();

                $.each(data, function(key, value) {
                    var selected = currentDistributorID == key ? 'selected' :'';
                    var op = '<option value="'+key+'" ' + selected + '>'+value.store_code+' - '+value.title+'</option>';
                    $('#d_id').append(op);
                });

                var jets = new Jets({
                    searchTag: '#SearchBox',
                    contentTag: '#d_id'
                });
            })
            .fail(function() {
                console.log("error");
            })
            .always(function() {
                /*console.log("complete");*/
            });

    }
</script>